In [1]:
import pandas as pd
import numpy as np
from os import listdir

In [2]:
import sklearn

In [3]:
# Ignore warnings
import warnings; warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline



from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
from sklearn import svm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

#from skbold.preproc.confounds import ConfoundRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn import preprocessing
    
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.impute import SimpleImputer



# Import libraries
import os
import numpy as np
import pandas as pd


from sklearn.feature_selection import RFE
from sklearn.metrics import balanced_accuracy_score

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn.model_selection import cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import make_scorer
from sklearn.metrics import \
    confusion_matrix, \
    accuracy_score, \
    matthews_corrcoef, \
    precision_score, \
    recall_score, \
    f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import LeaveOneOut


import pymrmr

# Set the random generator seed
seed = 42

# Matplotlib settings
plt.style.use("classic")

# Seaborn settings
sns.set()
sns.set(font_scale=1.0)
sns.set_style({"font.family":"serif", "font.serif":["Times New Roman"]})

# Show seaborn settings
sns.axes_style()

{'axes.facecolor': '#EAEAF2',
 'axes.edgecolor': 'white',
 'axes.grid': True,
 'axes.axisbelow': True,
 'axes.labelcolor': '.15',
 'figure.facecolor': 'white',
 'grid.color': 'white',
 'grid.linestyle': '-',
 'text.color': '.15',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'lines.solid_capstyle': <CapStyle.round: 'round'>,
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'font.family': ['serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'xtick.bottom': False,
 'xtick.top': False,
 'ytick.left': False,
 'ytick.right': False,
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True}

In [4]:
# ------------------------------
# Define the classifier settings
# ------------------------------

model_params = {
    
    # General parameters
    "booster": "gbtree", 
    "silent": True, 
    "n_jobs": -1, 
    
    # Learning task parameters
    "objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "eval_metric": "error", 
    "seed": seed, 
    
    # Tree Booster parameters
    "n_estimators": 500, 
    "learning_rate": 0.20, 
    "gamma": 1.0, 
    "max_depth": 10, 
    "subsample": 1.0, 
    "colsample_bylevel": 1, 
    "colsample_bytree": 1.0, 
    "min_child_weight": 5
}

# ------------------------------------------
# Define the hyper-parameter tuning settings
# ------------------------------------------

param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [1, 3, 5, 6, 7, 9]  # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
#scale_pos_weight = total_negative_examples / total_positive_examples
}

search_settings = {
    "param_distributions": param_grid, 
    "scoring": "balanced_accuracy",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
}

In [5]:
# ---------------------------------
# Define the classification metrics
# ---------------------------------

def sensitivity_score(y_true, y_pred):
    return recall_score(y_true, y_pred)

def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)

In [6]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import os

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

# For models
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# For evaluation
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score
from sklearn.preprocessing import OneHotEncoder

In [7]:
dataset = pd.read_csv('AU_features.csv')

In [8]:
del dataset['Unnamed: 0']
del dataset['index']

In [9]:
dataset

,patient,record,diagnosis,timestamp_start,timestamp_end,AU01_mid_Absolute energy,AU01_mid_Area under the curve,AU01_mid_Autocorrelation,AU01_mid_Average power,AU01_mid_Centroid,...,AU04_eve_rsd,AU06_eve_rsd,AU07_eve_rsd,AU10_eve_rsd,AU12_eve_rsd,AU14_eve_rsd,AU15_eve_rsd,AU17_eve_rsd,AU23_eve_rsd,AU24_eve_rsd
0,P08,0,0,1.658354e+09,1.659996e+09,9.678860,0.135414,1.0,17.923815,0.321564,...,640.933848,138.122806,67.855963,196.857019,66.814940,115.890566,113.386691,50.928506,148.995611,245.019331
1,P08,1,0,1.659996e+09,1.661206e+09,346.605312,4.324380,3.0,32.698614,5.773005,...,259.048799,105.779751,44.732121,216.912520,76.445191,129.562811,152.426847,60.490611,132.494496,313.892010
2,P10,2,1,1.658354e+09,1.659996e+09,11.415247,0.220840,2.0,2.875377,1.133316,...,265.374413,121.008673,67.176427,179.301774,89.136093,96.213302,138.309344,69.726973,135.622399,202.271039
3,P10,3,0,1.659996e+09,1.662070e+09,94.056685,1.252902,28.0,14.788787,1.454312,...,337.776724,132.427033,49.625233,199.063960,105.206820,88.204114,150.012813,61.994076,175.510401,187.385402
4,P12,4,1,1.658441e+09,1.659996e+09,21.142705,0.263578,1.0,35.237842,0.239713,...,116.988466,134.024675,46.498004,202.483565,118.604478,92.273881,106.845779,70.164313,109.443031,191.562723
5,P12,5,1,1.659996e+09,1.661206e+09,20.994168,0.265975,4.0,29.991668,0.394627,...,291.131247,162.944912,71.969314,400.045107,112.831481,55.994326,136.362200,128.327725,247.829012,716.936198
6,P13,6,0,1.658700e+09,1.659996e+09,181.566144,2.958368,8.0,6.742152,11.983574,...,117.830345,53.715064,51.059604,207.427112,120.569142,72.696209,51.834430,21.960962,99.607412,262.799857
7,P13,7,0,1.659996e+09,1.661206e+09,11.106465,0.244671,2.0,5.165798,0.664407,...,113.367852,14.180311,3.167624,248.513328,78.299349,11.102685,54.539460,12.858752,52.764130,96.930184
8,P14,8,0,1.658700e+09,1.659910e+09,22.525144,0.321874,3.0,17.597769,0.885024,...,226.534759,121.200776,71.706519,233.281849,134.745633,141.773571,135.110341,53.541805,136.021599,292.753501
9,P15,9,0,1.658786e+09,1.660082e+09,NaN,NaN,NaN,NaN,NaN,...,149.356222,127.167824,47.665138,252.503638,157.825090,103.602792,142.036647,91.645749,128.844890,245.636518
10,P15,10,1,1.660082e+09,1.661206e+09,9.122883,0.145782,2.0,6.291643,1.045863,...,176.010829,205.710660,80.940490,334.540653,255.280704,232.573141,224.974399,111.707370,315.072176,756.285165
11,P16,11,0,1.658873e+09,1.659996e+09,1095.311385,14.134593,106.0,31.628974,20.757402,...,143.109325,102.441982,81.791770,264.078243,185.463949,184.215295,180.057549,93.819228,167.026598,583.883302
12,P16,12,0,1.659996e+09,1.661206e+09,681.964975,8.429412,75.0,25.192648,14.629460,...,123.366342,119.985935,96.157310,287.292748,330.117073,184.979622,238.650168,123.327143,242.287104,825.161342
13,P17,13,1,1.658786e+09,1.659996e+09,103.357981,1.222127,17.0,51.421881,0.816389,...,233.828141,133.229961,74.018833,382.003612,112.218930,111.523354,170.431072,96.982193,148.565087,201.637073
14,P18,14,1,1.658873e+09,1.659996e+09,143.395653,2.238986,3.0,12.121357,6.133693,...,199.171956,147.300449,70.534243,299.204224,151.707252,110.115983,127.825284,53.339761,159.486032,570.492425
15,P18,15,1,1.659996e+09,1.661206e+09,165.125454,2.305494,3.0,16.815219,3.968694,...,251.089074,151.898807,83.133014,289.405013,155.340625,99.134680,124.391735,58.558246,137.297885,433.001841
16,P19,16,1,1.658873e+09,1.660255e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,P19,17,1,1.660255e+09,1.661897e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,P20,18,0,1.658786e+09,1.660082e+09,93.122488,1.471653,15.0,16.900633,3.072395,...,223.227290,74.228437,35.484323,104.256564,81.664274,100.630279,204.572232,55.673490,105.513047,152.960011
19,P20,19,0,1.660082e+09,1.661810e+09,21.993645,0.418841,2.0,4.909296,1.752230,...,175.725185,101.650089,40.142880,135.156750,108.208542,90.361813,221.499680,64.376641,213.354004,304.211543
20,P21,20,0,1.658959e+09,1.660169e+09,85.657739,1.176673,2.0,12.765684,3.359070,...,170.149930,96.077160,24.357688,116.258776,116.609282,73.131860,85.603287,41.694647,108.089455,660.011791
21,P21,21,1,1.660169e+09,1.661810e+09,42.924443,0.610312,4.0,19.780849,0.913781,...,144.766483,62.805806,39.511453,88.369386,84.034607,90.932349,125.965679,54.331211,102.688696,681.279367
22,P23,22,0,1.659046e+09,1.660255e+09,155.213290,2.267547,9.0,21.088762,4.216136,...,198.896271,107.861649,54.578204,392.919226,137.959790,160.581798,171.616260,72.355338,162.307410,243.233741
23,P23,23,0,1.660255e+09,1.661810e+09,534.085917,6.975295,5.0,36.960963,7.644916,...,226.408986,129.136013,37.601563,268.066415,157.243745,79.333382,249.226501,84.421874,129.308944,224.228218
24,P24,24,1,1.659046e+09,1.660428e+09,138.596402,2.612807,26.0,6.764100,7.212719,...,59.130596,180.889244,31.778058,284.477056,170.252081,54.163010,40.953834,18.677663,61.513525,586.987408
25,P24,25,1,1.660428e+09,1.661810e+09,115.728873,2.464224,3.0,9.676327,6.559235,...,75.472210,188.103775,59.787927,370.667139,356.622469,96.086324,63.146310,18.664397,98.009214,1022.233854
26,P25,26,0,1.660774e+09,1.661983e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,P27,27,0,1.660514e+09,1.661724e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,P28,28,0,1.660514e+09,1.663279e+09,84.142252,1.221990,45.0,17.136915,1.279490,...,122.896545,82.315730,70.340876,203.538189,95.435663,119.512615,151.076418,79.773905,110.466292,594.009512
29,P29,29,0,1.659305e+09,1.660255e+09,820.571764,10.937797,52.0,17.095245,25.144625,...,326.163080,268.213295,189.061852,563.043404,413.715468,126.146560,281.737914,119.292613,270.373123,567.577611
30,P29,30,0,1.660255e+09,1.661810e+09,393.173109,6.846644,3.0,8.010862,23.477188,...,254.229115,221.596918,122.201653,414.903052,243.616697,125.401348,153.842572,80.639075,214.196939,624.834400
31,P30,31,1,1.659305e+09,1.660255e+09,1416.620799,16.535962,4.0,41.288860,17.975948,...,105.946971,93.830646,68.416012,191.139851,176.419904,235.518350,269.925095,96.137536,179.087188,1306.713779
32,P30,32,1,1.660255e+09,1.661810e+09,1160.854156,14.431542,4.0,33.726152,16.810768,...,114.778733,116.556963,86.600239,200.048984,161.740007,192.335126,199.418447,88.729381,199.037527,881.704162
33,P31,33,0,1.659391e+09,1.660601e+09,343.600896,3.752019,117.0,39.631015,5.387888,...,124.572221,159.961657,68.138527,162.203306,118.985189,29.275468,77.136295,20.850092,65.509279,109.147858
34,P31,34,0,1.660601e+09,1.661810e+09,88.795518,1.229210,9.0,9.088589,3.840574,...,78.754119,358.531784,42.900599,365.140726,148.064797,46.024062,204.973953,20.673249,277.241052,618.160373
35,P33,35,0,1.659478e+09,1.660601e+09,683.500080,8.385086,37.0,44.556720,8.053174,...,257.053051,63.041628,52.408926,93.484244,51.776076,232.714717,198.571807,96.446632,232.715141,740.728669
36,P33,36,0,1.660601e+09,1.662070e+09,739.117689,9.181307,49.0,47.167689,6.100510,...,237.285428,39.959283,46.353555,86.272375,48.590646,244.347590,161.575625,86.046657,312.787140,1277.881742
37,P34,37,0,1.659564e+09,1.660774e+09,49.064325,0.831729,5.0,5.385766,2.508201,...,132.593169,118.091150,44.411083,188.987689,130.145547,56.344655,104.679489,35.006988,92.109378,291.145953
38,P35,38,0,1.659564e+09,1.660774e+09,175.417481,2.792106,9.0,14.753363,6.889522,...,77.207277,70.274420,40.971311,111.910188,112.752043,84.181463,165.161023,76.876100,85.326094,483.397770
39,P35,39,0,1.660774e+09,1.662070e+09,360.949977,4.917896,11.0,23.622381,7.632751,...,82.736228,61.950241,37.731644,114.156391,119.057369,123.036794,166.337261,115.358173,81.844017,753.624206
40,P36,40,0,1.660860e+09,1.662070e+09,536.410087,7.089358,4.0,20.631157,13.233442,...,262.206323,78.567966,32.285163,273.577360,83.810995,152.070219,131.615641,38.341760,90.493755,585.309642
41,P38,41,0,1.659564e+09,1.661206e+09,36.118396,0.548272,3.0,3.583174,3.998362,...,114.902903,116.098638,49.560351,173.450666,154.911011,112.229959,208.413822,63.154765,195.126945,450.001606
42,P38,42,0,1.661206e+09,1.661983e+09,96.558084,1.334526,28.0,19.546171,1.933390,...,180.460393,96.917000,62.957496,141.880115,174.594280,159.757598,218.710025,86.989420,224.118844,838.483503

In [10]:
subdata = pd.read_csv('.\dataset\AU_cross\AU_0_.csv')
subdata2 =pd.read_csv('.\dataset\AU_cross\AU_1_.csv')

In [11]:
subdata_all = pd.concat([subdata, subdata2])
flag = 0 
for i in range(0, 43):
    subdata = pd.read_csv('.\dataset\AU_cross\AU_'+str(i)+'_.csv')
    if len(subdata)>1:
        if flag==0:
            subdata_all = subdata.loc[1:].copy()
            flag = 1
        else:
            subdata_all = pd.concat([subdata_all, subdata.loc[1:]])

In [12]:
del subdata_all['Unnamed: 0']
del subdata_all['type_data']
del subdata_all['subrecord']

In [13]:
dataset = pd.concat([dataset, subdata_all])

In [14]:
group = dataset['patient']

In [15]:
group = dataset['patient']
patients_pandas_encoded = pd.get_dummies(group, columns=['patient'], drop_first=False)

In [16]:
dataset

,patient,record,diagnosis,timestamp_start,timestamp_end,AU01_mid_Absolute energy,AU01_mid_Area under the curve,AU01_mid_Autocorrelation,AU01_mid_Average power,AU01_mid_Centroid,...,AU04_eve_rsd,AU06_eve_rsd,AU07_eve_rsd,AU10_eve_rsd,AU12_eve_rsd,AU14_eve_rsd,AU15_eve_rsd,AU17_eve_rsd,AU23_eve_rsd,AU24_eve_rsd
0,P08,0,0,1.658354e+09,1.659996e+09,9.678860,0.135414,1.0,17.923815,0.321564,...,640.933848,138.122806,67.855963,196.857019,66.814940,115.890566,113.386691,50.928506,148.995611,245.019331
1,P08,1,0,1.659996e+09,1.661206e+09,346.605312,4.324380,3.0,32.698614,5.773005,...,259.048799,105.779751,44.732121,216.912520,76.445191,129.562811,152.426847,60.490611,132.494496,313.892010
2,P10,2,1,1.658354e+09,1.659996e+09,11.415247,0.220840,2.0,2.875377,1.133316,...,265.374413,121.008673,67.176427,179.301774,89.136093,96.213302,138.309344,69.726973,135.622399,202.271039
3,P10,3,0,1.659996e+09,1.662070e+09,94.056685,1.252902,28.0,14.788787,1.454312,...,337.776724,132.427033,49.625233,199.063960,105.206820,88.204114,150.012813,61.994076,175.510401,187.385402
4,P12,4,1,1.658441e+09,1.659996e+09,21.142705,0.263578,1.0,35.237842,0.239713,...,116.988466,134.024675,46.498004,202.483565,118.604478,92.273881,106.845779,70.164313,109.443031,191.562723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,P38,42,0,1.661206e+09,1.661983e+09,0.007025,0.001534,1.0,0.058544,0.075068,...,93.962994,44.232045,23.287695,100.956276,153.669661,364.945349,170.557186,77.355825,249.974605,717.779970
3,P38,42,0,1.661206e+09,1.661983e+09,3.421030,0.065943,1.0,6.578904,0.190530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P38,42,0,1.661206e+09,1.661983e+09,0.007025,0.001534,1.0,0.058544,0.075068,...,147.693531,72.144864,50.081831,142.670287,144.493719,123.185280,229.903774,73.830597,191.421844,728.627052
5,P38,42,0,1.661206e+09,1.661983e+09,92.478118,1.231389,1.0,36.843872,1.316727,...,360.597135,193.707711,92.211677,140.468116,350.797958,761.769275,197.531326,120.434505,439.279089,1251.428276
6,P38,42,0,1.661206e+09,1.661983e+09,3.525935,0.069530,1.0,5.342326,0.329465,...,147.693531,72.144864,50.081831,142.670287,144.493719,123.185280,229.903774,73.830597,191.421844,728.627052

In [17]:
del dataset['patient']

In [18]:
dataset = dataset.fillna(dataset.mean())

In [19]:
y = dataset['diagnosis']

In [20]:
records  = dataset['record']

In [21]:
del dataset['record']

In [22]:
X = dataset.copy()

In [23]:
dataset

,diagnosis,timestamp_start,timestamp_end,AU01_mid_Absolute energy,AU01_mid_Area under the curve,AU01_mid_Autocorrelation,AU01_mid_Average power,AU01_mid_Centroid,AU01_mid_ECDF Percentile Count_0,AU01_mid_ECDF Percentile Count_1,...,AU04_eve_rsd,AU06_eve_rsd,AU07_eve_rsd,AU10_eve_rsd,AU12_eve_rsd,AU14_eve_rsd,AU15_eve_rsd,AU17_eve_rsd,AU23_eve_rsd,AU24_eve_rsd
0,0,1.658354e+09,1.659996e+09,9.678860,0.135414,1.0,17.923815,0.321564,11.0,44.0,...,640.933848,138.122806,67.855963,196.857019,66.814940,115.890566,113.386691,50.928506,148.995611,245.019331
1,0,1.659996e+09,1.661206e+09,346.605312,4.324380,3.0,32.698614,5.773005,212.0,848.0,...,259.048799,105.779751,44.732121,216.912520,76.445191,129.562811,152.426847,60.490611,132.494496,313.892010
2,1,1.658354e+09,1.659996e+09,11.415247,0.220840,2.0,2.875377,1.133316,79.0,318.0,...,265.374413,121.008673,67.176427,179.301774,89.136093,96.213302,138.309344,69.726973,135.622399,202.271039
3,0,1.659996e+09,1.662070e+09,94.056685,1.252902,28.0,14.788787,1.454312,127.0,509.0,...,337.776724,132.427033,49.625233,199.063960,105.206820,88.204114,150.012813,61.994076,175.510401,187.385402
4,1,1.658441e+09,1.659996e+09,21.142705,0.263578,1.0,35.237842,0.239713,12.0,48.0,...,116.988466,134.024675,46.498004,202.483565,118.604478,92.273881,106.845779,70.164313,109.443031,191.562723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,0,1.661206e+09,1.661983e+09,0.007025,0.001534,1.0,0.058544,0.075068,2.0,10.0,...,93.962994,44.232045,23.287695,100.956276,153.669661,364.945349,170.557186,77.355825,249.974605,717.779970
3,0,1.661206e+09,1.661983e+09,3.421030,0.065943,1.0,6.578904,0.190530,10.0,42.0,...,192.416214,130.803588,66.038233,244.116235,169.529760,143.514414,170.195290,72.539274,165.617451,448.000881
4,0,1.661206e+09,1.661983e+09,0.007025,0.001534,1.0,0.058544,0.075068,2.0,10.0,...,147.693531,72.144864,50.081831,142.670287,144.493719,123.185280,229.903774,73.830597,191.421844,728.627052
5,0,1.661206e+09,1.661983e+09,92.478118,1.231389,1.0,36.843872,1.316727,50.0,201.0,...,360.597135,193.707711,92.211677,140.468116,350.797958,761.769275,197.531326,120.434505,439.279089,1251.428276
6,0,1.661206e+09,1.661983e+09,3.525935,0.069530,1.0,5.342326,0.329465,13.0,53.0,...,147.693531,72.144864,50.081831,142.670287,144.493719,123.185280,229.903774,73.830597,191.421844,728.627052

# Feature selection 2

In [24]:
from pyHSICLasso import HSICLasso

In [25]:
del X['diagnosis']

In [26]:
del X['timestamp_start']
del X['timestamp_end']

In [27]:
X

,AU01_mid_Absolute energy,AU01_mid_Area under the curve,AU01_mid_Autocorrelation,AU01_mid_Average power,AU01_mid_Centroid,AU01_mid_ECDF Percentile Count_0,AU01_mid_ECDF Percentile Count_1,AU01_mid_ECDF Percentile_0,AU01_mid_ECDF Percentile_1,AU01_mid_ECDF_0,...,AU04_eve_rsd,AU06_eve_rsd,AU07_eve_rsd,AU10_eve_rsd,AU12_eve_rsd,AU14_eve_rsd,AU15_eve_rsd,AU17_eve_rsd,AU23_eve_rsd,AU24_eve_rsd
0,9.678860,0.135414,1.0,17.923815,0.321564,11.0,44.0,0.000857,0.504417,0.018182,...,640.933848,138.122806,67.855963,196.857019,66.814940,115.890566,113.386691,50.928506,148.995611,245.019331
1,346.605312,4.324380,3.0,32.698614,5.773005,212.0,848.0,0.001880,0.912324,0.000943,...,259.048799,105.779751,44.732121,216.912520,76.445191,129.562811,152.426847,60.490611,132.494496,313.892010
2,11.415247,0.220840,2.0,2.875377,1.133316,79.0,318.0,0.000820,0.050790,0.002513,...,265.374413,121.008673,67.176427,179.301774,89.136093,96.213302,138.309344,69.726973,135.622399,202.271039
3,94.056685,1.252902,28.0,14.788787,1.454312,127.0,509.0,0.000006,0.490617,0.001570,...,337.776724,132.427033,49.625233,199.063960,105.206820,88.204114,150.012813,61.994076,175.510401,187.385402
4,21.142705,0.263578,1.0,35.237842,0.239713,12.0,48.0,0.016091,0.882381,0.016393,...,116.988466,134.024675,46.498004,202.483565,118.604478,92.273881,106.845779,70.164313,109.443031,191.562723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,0.007025,0.001534,1.0,0.058544,0.075068,2.0,10.0,0.000088,0.008235,0.076923,...,93.962994,44.232045,23.287695,100.956276,153.669661,364.945349,170.557186,77.355825,249.974605,717.779970
3,3.421030,0.065943,1.0,6.578904,0.190530,10.0,42.0,0.002941,0.208080,0.018868,...,192.416214,130.803588,66.038233,244.116235,169.529760,143.514414,170.195290,72.539274,165.617451,448.000881
4,0.007025,0.001534,1.0,0.058544,0.075068,2.0,10.0,0.000088,0.008235,0.076923,...,147.693531,72.144864,50.081831,142.670287,144.493719,123.185280,229.903774,73.830597,191.421844,728.627052
5,92.478118,1.231389,1.0,36.843872,1.316727,50.0,201.0,0.086478,0.906153,0.003968,...,360.597135,193.707711,92.211677,140.468116,350.797958,761.769275,197.531326,120.434505,439.279089,1251.428276
6,3.525935,0.069530,1.0,5.342326,0.329465,13.0,53.0,0.001958,0.104410,0.014925,...,147.693531,72.144864,50.081831,142.670287,144.493719,123.185280,229.903774,73.830597,191.421844,728.627052

In [28]:
#Initialize HSICLasso
hsic_lasso = HSICLasso()

# Load data
hsic_lasso.input(np.array(X), np.array(y), featname=X.columns)

True

In [33]:
hsic_lasso.classification(50)

Block HSIC Lasso B = 20.
M set to 3.
Using Gaussian kernel for the features, Delta kernel for the outcomes.

True

In [34]:
valuable_features_list = hsic_lasso.get_features()

In [35]:
col =  valuable_features_list

In [37]:
col = ['AU06_eve_LPCC_3',
 'AU06_aft_LPCC_8',
 'AU12_aft_ECDF Percentile_0',
 'AU06_eve_SB_TransitionMatrix_3ac_sumdiagcov',
 'AU04_eve_Wavelet variance_25.0Hz',
 'AU04_aft_ECDF Percentile_1',
 'AU17_mor_Mean absolute diff',
 'AU24_eve_FC_LocalSimple_mean1_tauresrat',
 'AU04_aft_Spectral kurtosis',
 'AU23_mor_MFCC_2',
 'AU24_eve_Spectral centroid',
 'AU23_aft_Absolute energy',
 'AU15_mid_PD_PeriodicityWang_th0_01',
 'AU07_eve_Wavelet variance_25.0Hz',
 'AU14_mid_Mean diff',
 'AU06_eve_SP_Summaries_welch_rect_centroid',
 'AU02_mor_Variance',
 'AU15_mid_Wavelet variance_6.25Hz',
 'AU17_mid_Wavelet variance_3.57Hz',
 'AU06_mid_MFCC_9',
 'AU02_mid_Median absolute diff',
 'AU14_aft_Spectral spread',
 'AU12_aft_MFCC_9',
 'AU06_eve_LPCC_11',
 'AU07_aft_Wavelet variance_3.57Hz',
 'AU01_mid_SP_Summaries_welch_rect_area_5_1',
 'AU12_eve_LPCC_11',
 'AU07_mid_Wavelet variance_6.25Hz',
 'AU07_eve_Wavelet variance_8.33Hz',
 'AU07_aft_MFCC_3',
 'AU06_eve_LPCC_10',
 'AU06_aft_Wavelet standard deviation_2.78Hz',
 'AU07_mid_Wavelet variance_25.0Hz',
 'AU24_eve_SP_Summaries_welch_rect_centroid',
 'AU15_mid_Wavelet variance_25.0Hz',
 'AU06_mid_SP_Summaries_welch_rect_area_5_1',
 'AU06_eve_LPCC_7',
 'AU07_eve_Wavelet variance_12.5Hz',
 'AU10_aft_DN_OutlierInclude_n_001_mdrmd',
 'AU10_aft_Spectral decrease',
 'AU10_aft_Interquartile range',
 'AU04_aft_Wavelet variance_6.25Hz',
 'AU10_aft_ECDF Percentile_0',
 'AU14_aft_MFCC_9',
 'AU04_aft_Skewness',
 'AU14_aft_Histogram mode',
 'AU06_aft_ECDF Percentile_0',
 'AU06_aft_LPCC_4',
 'AU06_eve_LPCC_9']

# Read the data again to import data with NaN values

In [38]:
dataset = pd.read_csv('AU_features.csv')
del dataset['Unnamed: 0']
del dataset['index']
group = dataset['patient']
groups = group
del dataset['patient']
y = dataset['diagnosis']
del dataset['diagnosis']
records  = dataset['record']
del dataset['record']
X = dataset.copy()

In [39]:
patients_pandas_encoded = pd.get_dummies(group, columns=['patient'], drop_first=False)
patients_pandas_encoded

,P08,P10,P12,P13,P14,P15,P16,P17,P18,P19,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [40]:
X_new = X[col]

In [41]:
patients_pandas_encoded

,P08,P10,P12,P13,P14,P15,P16,P17,P18,P19,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [42]:
X_new2 = pd.concat([X_new, patients_pandas_encoded], axis=1)

In [43]:
X_new2

,AU06_eve_LPCC_3,AU06_aft_LPCC_8,AU12_aft_ECDF Percentile_0,AU06_eve_SB_TransitionMatrix_3ac_sumdiagcov,AU04_eve_Wavelet variance_25.0Hz,AU04_aft_ECDF Percentile_1,AU17_mor_Mean absolute diff,AU24_eve_FC_LocalSimple_mean1_tauresrat,AU04_aft_Spectral kurtosis,AU23_mor_MFCC_2,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,0.467778,0.357625,1.983699e-02,0.005208,0.003817,0.013362,0.198662,0.023810,1.776869,-11.974438,...,False,False,False,False,False,False,False,False,False,False
1,0.321457,0.336955,2.427905e-04,0.003750,0.038149,0.099797,0.182858,0.071429,1.909916,-8.599952,...,False,False,False,False,False,False,False,False,False,False
2,0.278050,0.370153,6.893801e-03,0.083333,0.018921,0.108932,NaN,0.013514,1.969486,NaN,...,False,False,False,False,False,False,False,False,False,False
3,0.421375,0.272728,2.658271e-02,0.018229,0.014970,0.005352,NaN,0.005556,1.687982,NaN,...,False,False,False,False,False,False,False,False,False,False
4,0.141733,0.239838,4.017546e-04,0.004115,0.081924,0.210585,0.254536,0.166667,1.922836,21.008126,...,False,False,False,False,False,False,False,False,False,False
5,0.051007,0.387076,2.304023e-03,0.004229,0.029223,0.764549,0.249805,0.250000,1.957194,-23.105807,...,False,False,False,False,False,False,False,False,False,False
6,0.718189,0.614106,4.006230e-04,0.005144,0.027012,0.880638,NaN,0.004184,1.749286,NaN,...,False,False,False,False,False,False,False,False,False,False
7,0.739083,NaN,NaN,0.001096,0.025814,NaN,NaN,0.071429,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
8,0.328526,0.436134,1.839091e-03,0.006122,0.034237,0.096452,0.224734,0.052632,1.786420,-7.368590,...,False,False,False,False,False,False,False,False,False,False
9,0.412759,0.440480,9.339379e-07,0.012004,0.045485,0.181113,0.221224,0.009009,1.754423,-24.650082,...,False,False,False,False,False,False,False,False,False,False
10,0.340810,0.364233,1.309960e-07,0.004626,0.051604,0.038582,0.282392,0.055556,1.795595,9.444248,...,False,False,False,False,False,False,False,False,False,False
11,0.547097,0.467183,1.863898e-05,0.010417,0.026322,0.967467,NaN,0.008333,1.973267,NaN,...,False,False,False,False,False,False,False,False,False,False
12,0.453088,0.508546,8.688172e-05,0.003781,0.034704,0.873045,0.113750,0.037037,2.004380,-7.828294,...,False,False,False,False,False,False,False,False,False,False
13,0.409288,0.251336,3.264027e-05,0.005208,0.021319,0.004485,0.069961,0.008130,1.817114,25.338472,...,False,False,False,False,False,False,False,False,False,False
14,0.300718,0.163448,3.490537e-05,0.002126,0.030927,0.013781,0.280941,0.031250,1.882789,-1.843740,...,False,False,False,False,False,False,False,False,False,False
15,0.277389,0.264632,7.443115e-04,0.017751,0.029759,0.092756,0.226903,0.047619,2.372177,20.436963,...,False,False,False,False,False,False,False,False,False,False
16,NaN,0.350818,7.486734e-05,NaN,NaN,0.774506,0.324222,NaN,1.840394,45.964661,...,False,False,False,False,False,False,False,False,False,False
17,NaN,NaN,NaN,NaN,NaN,NaN,0.240845,NaN,NaN,-21.498953,...,False,False,False,False,False,False,False,False,False,False
18,0.465950,0.520925,7.826469e-04,0.111111,0.008729,0.031799,0.093837,0.032258,1.814424,-20.221025,...,False,False,False,False,False,False,False,False,False,False
19,0.426381,0.382152,1.249885e-03,0.067708,0.019444,0.045720,0.195632,0.043478,1.853546,-44.016027,...,False,False,False,False,False,False,False,False,False,False
20,0.491876,0.524447,4.473744e-01,0.001972,0.034117,0.393643,NaN,0.009259,1.866082,NaN,...,False,False,False,False,False,False,False,False,False,False
21,0.579768,0.679636,3.389058e-02,0.022039,0.048585,0.790420,NaN,0.250000,1.802460,NaN,...,False,False,False,False,False,False,False,False,False,False
22,0.463179,0.523395,8.289118e-05,0.020741,0.011532,0.357489,0.150207,0.020408,1.906231,15.494868,...,False,False,False,False,False,False,False,False,False,False
23,0.356379,0.240342,8.676713e-02,0.030303,0.018543,0.108001,0.158352,0.005348,1.855580,-1.373738,...,False,False,False,False,False,False,False,False,False,False
24,0.351897,0.570098,1.213355e-04,0.023333,0.041827,0.999617,NaN,0.111111,2.352300,NaN,...,False,False,False,False,False,False,False,False,False,False
25,0.519034,0.127531,2.770259e-05,0.062500,0.060183,0.999993,0.207798,0.500000,4.473827,-86.549170,...,False,False,False,False,False,False,False,False,False,False
26,NaN,0.416525,3.344721e-07,NaN,NaN,0.990531,0.106145,NaN,1.915915,17.174414,...,False,False,False,False,False,False,False,False,False,False
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
28,0.509581,0.451214,1.248080e-03,0.010204,0.056803,0.878123,0.131743,0.020408,2.001412,-27.423784,...,False,True,False,False,False,False,False,False,False,False
29,0.307272,0.165860,3.877229e-09,0.005810,0.010916,0.027889,0.099686,0.005000,1.807204,-61.270395,...,False,False,True,False,False,False,False,False,False,False
30,0.447347,0.450749,1.927895e-09,0.011834,0.012337,0.014049,0.081412,0.008333,1.820906,3.267319,...,False,False,True,False,False,False,False,False,False,False
31,0.456945,0.404091,6.434294e-06,0.018519,0.079230,0.967373,0.250738,0.166667,1.798897,-56.903248,...,False,False,False,True,False,False,False,False,False,False
32,0.371689,0.453760,7.365178e-06,0.004630,0.081412,0.954934,0.260324,0.055556,1.867737,-29.814491,...,False,False,False,True,False,False,False,False,False,False
33,0.267713,0.103998,6.245684e-08,0.027778,0.015542,0.340447,0.142851,0.007299,1.566717,-8.433733,...,False,False,False,False,True,False,False,False,False,False
34,0.464787,NaN,NaN,0.005510,0.046999,NaN,0.199885,0.052632,NaN,202.676380,...,False,False,False,False,True,False,False,False,False,False
35,0.628633,0.613909,7.880423e-01,0.006803,0.021390,0.039820,NaN,0.047619,1.856263,NaN,...,False,False,False,False,False,True,False,False,False,False
36,0.814570,0.607213,4.403683e-02,0.002604,0.021969,0.068404,NaN,0.043478,1.734034,NaN,...,False,False,False,False,False,True,False,False,False,False
37,0.452381,0.438092,2.440177e-02,0.020267,0.033650,0.491360,0.394448,0.058824,1.836681,-16.871159,...,False,False,False,False,False,False,True,False,False,False
38,0.539259,0.581705,2.632838e-03,0.062500,0.062143,0.942420,NaN,0.018182,1.882411,NaN,...,False,False,False,False,False,False,False,True,False,False
39,0.566554,0.552275,4.455710e-04,0.005859,0.058133,0.967125,NaN,0.027027,1.857773,NaN,...,False,False,False,False,False,False,False,True,False,False
40,0.486781,0.521069,7.894196e-03,0.008889,0.031430,0.033914,0.187240,0.025000,1.792005,-26.708219,...,False,False,False,False,False,False,False,False,True,False
41,0.483606,0.508105,3.092360e-03,0.040000,0.031293,0.381744,NaN,0.023810,1.987287,NaN,...,False,False,False,False,False,False,False,False,False,True
42,0.565784,0.444620,3.483567e-03,0.166667,0.021053,0.056275,0.075692,0.035714,1.610046,-8.927264,...,False,False,False,False,False,False,False,False,False,True

# Cross-validation

In [44]:
# configure the cross-validation procedure
#create loocv procedure
cv = LeaveOneOut()
cv_outer = cv.split(X_new2)

In [45]:
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV

# Logistic regression

In [46]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [47]:
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

# For Leave-One-Day-Out Cross-Validation

In [48]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0



            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)
    
    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.701666783880723, Precision: 0.4608695652173913, Recall: 0.8983050847457628, F1-score: 0.6091954022988506, Accuracy: 0.6211699164345403, Balanced Accuracy: 0.6918911315844997

# Nested Cross-Validation LR + SMOTE

In [49]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [50]:
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [51]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7398023771010619, Precision: 0.4807692307692308, Recall: 0.847457627118644, F1-score: 0.6134969325153374, Accuracy: 0.649025069637883, Balanced Accuracy: 0.6996624235178283

# Nested Cross-Validation k-NN

In [52]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier

In [53]:
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [54]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0



            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7066776847879599, Precision: 0.6739130434782609, Recall: 0.2627118644067797, F1-score: 0.3780487804878049, Accuracy: 0.7158774373259053, Balanced Accuracy: 0.6002356002531823

# Nested Cross-Validation k-NN + SMOTE

In [55]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier

In [56]:
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')




# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [57]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0



            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)
    
    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7690062592306068, Precision: 0.4217391304347826, Recall: 0.8220338983050848, F1-score: 0.5574712643678161, Accuracy: 0.5710306406685237, Balanced Accuracy: 0.6350833391940361

# Nested Cross-Validation SVM

In [58]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np




# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step,
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

In [59]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)
    
    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7838103945425136, Precision: 0.5, Recall: 0.6440677966101694, F1-score: 0.5629629629629629, Accuracy: 0.6713091922005571, Balanced Accuracy: 0.6643575497573668

# Nested Cross-Validation SVM + SMOTE

In [60]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step,
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

In [61]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    if len(extra_AU)>1:
 
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(1, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7121633026232506, Precision: 0.46601941747572817, Recall: 0.8135593220338984, F1-score: 0.5925925925925927, Accuracy: 0.6323119777158774, Balanced Accuracy: 0.6785638933820943

# Nested Cross-Validation XGBoost

In [62]:
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)

In [63]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [64]:
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from xgboost import XGBClassifier

In [65]:
from xgboost import XGBClassifier

In [66]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [67]:
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE

param_grid = {
    "xgbsclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbsclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbsclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbsclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbsclassifier__scale_pos_weight": [1, ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
model_params = {
    
    # General parameters
    "xgbclassifier__booster": "gbtree", 
    "xgbclassifier__silent": True, 
    "xgbclassifier__n_jobs": -1, 
    
    # Learning task parameters
    "xgbclassifier__objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "xgbclassifier__eval_metric": "error", 
    "xgbclassifier__seed": seed, 
    
    # Tree Booster parameters
    "xgbclassifier__n_estimators": 500, 
    "xgbclassifier__learning_rate": 0.20, 
    "xgbclassifier__gamma": 1.0, 
    "xgbclassifier__max_depth": 10, 
    "xgbclassifier__subsample": 1.0, 
    "xgbclassifier__colsample_bylevel": 1, 
    "xgbclassifier__colsample_bytree": 1.0, 
    "xgbclassifier__min_child_weight": 5
}
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }


param_grid = {
    "xgbclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbclassifier__scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier#
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, xgb.XGBClassifier(**model_params))
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [68]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0



            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices

            search = RandomizedSearchCV(pipe, cv=cv_inner.split(X_train, y_train), random_state=seed, **search_settings, error_score='raise')

            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
0
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
1
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
2
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
3
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
4
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
5
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
6
7
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
8
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
9
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
10
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
11
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
12
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
13
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
14
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
15
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
16
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
17
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
18
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
19
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
20
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
21
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
22
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
23
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
24
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
25
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
26
27
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
28
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
29
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
30
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
31
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
32
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
33
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
34
35
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
36

# Nested Cross-Validation with XGBoost and SMOTE

In [69]:
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE

param_grid = {
    "xgbsclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbsclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbsclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbsclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbsclassifier__scale_pos_weight": [1, ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
model_params = {
    
    # General parameters
    "xgbclassifier__booster": "gbtree", 
    "xgbclassifier__silent": True, 
    "xgbclassifier__n_jobs": -1, 
    
    # Learning task parameters
    "xgbclassifier__objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "xgbclassifier__eval_metric": "error", 
    "xgbclassifier__seed": seed, 
    
    # Tree Booster parameters
    "xgbclassifier__n_estimators": 500, 
    "xgbclassifier__learning_rate": 0.20, 
    "xgbclassifier__gamma": 1.0, 
    "xgbclassifier__max_depth": 10, 
    "xgbclassifier__subsample": 1.0, 
    "xgbclassifier__colsample_bylevel": 1, 
    "xgbclassifier__colsample_bytree": 1.0, 
    "xgbclassifier__min_child_weight": 5
}
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }


param_grid = {
    "xgbclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbclassifier__scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, xgb.XGBClassifier(**model_params))
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [70]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices

            search = RandomizedSearchCV(pipe, cv=cv_inner.split(X_train, y_train), random_state=seed, **search_settings, error_score='raise')

            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
0
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
1
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
2
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
3
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
4
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
5
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
6
7
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
8
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
9
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
10
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
11
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
12
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
13
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
14
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
15
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
16
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
17
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
18
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
19
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
20
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
21
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
22
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
23
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
24
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
25
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
26
27
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
28
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
29
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
30
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
31
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
32
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
33
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
34
35
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
36

In [71]:
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.6654476404810464, Precision: 0.3900414937759336, Recall: 0.7966101694915254, F1-score: 0.5236768802228412, Accuracy: 0.5236768802228412, Balanced Accuracy: 0.5933258316337295

# Nested Cross-Validation with Random Forest

In [72]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [73]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

pipe = Pipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('scale', StandardScaler()),
    ('model', model)])

In [74]:
param_grid = {
    "model__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "model__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "model__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "model__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "model__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "model__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [75]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices
            search = RandomizedSearchCV(pipe, param_distributions = param_grid, cv=cv_inner.split(X_train, y_train), random_state=seed, scoring='roc_auc', n_jobs=-1)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.6392502988958437, Precision: 0.5, Recall: 0.4067796610169492, F1-score: 0.4485981308411215, Accuracy: 0.6713091922005571, Balanced Accuracy: 0.6038047682678107

# Random Forest with SMOTE

In [76]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
from imblearn.pipeline import make_pipeline

In [77]:
model_params = {
    
    "n_estimators": 1,
    "max_depth": 32,  
    "min_samples_split": 0.1,
    "min_samples_leaf": 0.1,
    "max_features": 1,
    "class_weight": 'balanced'
}

param_grid = {
    "randomforestclassifier__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "randomforestclassifier__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "randomforestclassifier__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "randomforestclassifier__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "randomforestclassifier__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "randomforestclassifier__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [78]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])


# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, RandomForestClassifier(**model_params))

In [79]:
model_params = {
    
    "n_estimators": 1,
    "max_depth": 32,  
    "min_samples_split": 0.1,
    "min_samples_leaf": 0.1,
    "max_features": 1,
    "class_weight": 'balanced'
}

param_grid = {
    "randomforestclassifier__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "randomforestclassifier__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "randomforestclassifier__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "randomforestclassifier__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "randomforestclassifier__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "randomforestclassifier__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [80]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])


# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, RandomForestClassifier(**model_params))

In [81]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/AU_cross/AU_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices
            search = RandomizedSearchCV(pipe, param_distributions = param_grid, cv=cv_inner.split(X_train, y_train), random_state=seed, scoring='roc_auc', n_jobs=-1)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.6426084816091147, Precision: 0.461038961038961, Recall: 0.6016949152542372, F1-score: 0.5220588235294118, Accuracy: 0.637883008356546, Balanced Accuracy: 0.6286482875026373