In [42]:
import pandas as pd
import numpy as np
from os import listdir

In [43]:
import sklearn

In [101]:
# Ignore warnings
import warnings; warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
from imblearn.pipeline import Pipeline as ImbPipeline

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import ParameterGrid



from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
from sklearn import svm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

#from skbold.preproc.confounds import ConfoundRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn import preprocessing
    
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.impute import SimpleImputer



# Import libraries
import os
import numpy as np
import pandas as pd


from sklearn.feature_selection import RFE
from sklearn.metrics import balanced_accuracy_score

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn.model_selection import cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import make_scorer
from sklearn.metrics import \
    confusion_matrix, \
    accuracy_score, \
    matthews_corrcoef, \
    precision_score, \
    recall_score, \
    f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

import pymrmr

# Set the random generator seed
seed = 42

# Matplotlib settings
plt.style.use("classic")

# Seaborn settings
sns.set()
sns.set(font_scale=1.0)
sns.set_style({"font.family":"serif", "font.serif":["Times New Roman"]})

# Show seaborn settings
sns.axes_style()

{'axes.facecolor': '#EAEAF2',
 'axes.edgecolor': 'white',
 'axes.grid': True,
 'axes.axisbelow': True,
 'axes.labelcolor': '.15',
 'figure.facecolor': 'white',
 'grid.color': 'white',
 'grid.linestyle': '-',
 'text.color': '.15',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'lines.solid_capstyle': <CapStyle.round: 'round'>,
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'font.family': ['serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'xtick.bottom': False,
 'xtick.top': False,
 'ytick.left': False,
 'ytick.right': False,
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True}

In [102]:
# ------------------------------
# Define the classifier settings
# ------------------------------

model_params = {
    
    # General parameters
    "booster": "gbtree", 
    "silent": True, 
    "n_jobs": -1, 
    
    # Learning task parameters
    "objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "eval_metric": "error", 
    "seed": seed, 
    
    # Tree Booster parameters
    "n_estimators": 500, 
    "learning_rate": 0.20, 
    "gamma": 1.0, 
    "max_depth": 10, 
    "subsample": 1.0, 
    "colsample_bylevel": 1, 
    "colsample_bytree": 1.0, 
    "min_child_weight": 5
}

# ------------------------------------------
# Define the hyper-parameter tuning settings
# ------------------------------------------

param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [1, 3, 5, 6, 7, 9]  # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
#scale_pos_weight = total_negative_examples / total_positive_examples
}

search_settings = {
    "param_distributions": param_grid, 
    "scoring": "balanced_accuracy",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
}

In [46]:
# ---------------------------------
# Define the classification metrics
# ---------------------------------

def sensitivity_score(y_true, y_pred):
    return recall_score(y_true, y_pred)

def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)

In [47]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import os

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

# For models
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# For evaluation
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score

In [48]:
dataset = pd.read_csv('euler_features.csv')

In [49]:
dataset

,Unnamed: 0,level_0,index,patient,record,diagnosis,timestamp_start,timestamp_end,X_mid_Absolute energy,X_mid_Area under the curve,...,Z_eve_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1,Z_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1,Z_eve_SP_Summaries_welch_rect_centroid,Z_eve_FC_LocalSimple_mean3_stderr,X_eve_app_ent,Y_eve_app_ent,Z_eve_app_ent,X_eve_rsd,Y_eve_rsd,Z_eve_rsd
0,0,0,0,P08,0,0,1.658354e+09,1.659996e+09,2.385522e+04,17.340800,...,0.183673,0.877551,0.038350,0.556470,1.240145,1.414059,1.101619,-137.406912,247.810229,-84.170855
1,1,1,0,P08,1,0,1.659996e+09,1.661206e+09,2.328345e+05,239.885354,...,0.437500,0.875000,0.104311,0.664134,1.110772,1.153594,1.206691,-246.703278,-917.852063,-147.429543
2,2,2,0,P10,2,1,1.658354e+09,1.659996e+09,4.725678e+04,54.145724,...,0.125000,0.854167,0.193282,0.768328,0.829204,1.076619,1.013430,114.967050,-107.494007,-224.427014
3,3,3,0,P10,3,0,1.659996e+09,1.662070e+09,1.807770e+05,129.773994,...,0.224490,0.122449,0.138058,0.682936,0.659745,0.789076,0.931019,65.528455,-348.921557,-328.457878
4,4,4,0,P12,4,1,1.658441e+09,1.659996e+09,4.557987e+04,24.120677,...,0.860465,0.139535,0.613592,0.924430,0.938069,0.806088,0.934574,72.352631,177.627123,159.713801
5,5,5,0,P12,5,1,1.659996e+09,1.661206e+09,2.937881e+04,14.343478,...,0.619048,0.738095,0.269981,0.758146,0.529294,0.502848,0.595768,44.882796,-1732.345347,174.352004
6,6,6,0,P13,6,0,1.658700e+09,1.659996e+09,1.425495e+05,166.412023,...,0.755102,0.510204,0.036816,0.527443,0.646985,0.687472,0.806980,172.224880,46.271562,73.328927
7,7,7,0,P13,7,0,1.659996e+09,1.661206e+09,1.526638e+04,15.338700,...,0.780488,0.731707,0.220893,0.714463,0.864127,0.889067,0.751850,-108.350642,22.814158,63.237315
8,8,8,0,P14,8,0,1.658700e+09,1.659910e+09,2.917384e+04,22.015482,...,0.448980,0.530612,0.085903,0.636002,1.382823,1.206934,1.187669,318.194246,-125.681839,133.769104
9,9,9,0,P15,9,0,1.658786e+09,1.660082e+09,NaN,NaN,...,0.122449,0.448980,0.171806,0.654882,0.913396,0.750667,0.753536,42.929179,1791.647415,1154.407059
10,10,10,0,P15,10,1,1.660082e+09,1.661206e+09,1.737008e+05,103.388069,...,0.204082,0.877551,0.233165,0.722889,0.745131,0.752576,0.874068,62.402568,12200.127526,283.902945
11,11,11,0,P16,11,0,1.658873e+09,1.659996e+09,2.302304e+06,1236.346278,...,0.220000,0.140000,0.095490,0.630106,0.716455,0.694768,0.883786,81.659767,-520.957701,73.706644
12,12,12,0,P16,12,0,1.659996e+09,1.661206e+09,1.302403e+06,728.651101,...,0.240000,0.820000,0.161068,0.712716,0.749267,0.881995,1.036046,90.985271,-879.392994,67.290676
13,13,13,0,P17,13,1,1.658786e+09,1.659996e+09,3.208747e+04,36.392223,...,0.270833,0.812500,0.291456,0.822146,1.004644,1.144014,1.295719,81.538374,686.473191,156.711907
14,14,14,0,P18,14,1,1.658873e+09,1.659996e+09,4.090342e+05,269.571245,...,0.163265,0.122449,0.116583,0.683514,1.348638,1.196337,1.133462,47.327685,-772.470353,258.826406
15,15,15,0,P18,15,1,1.659996e+09,1.661206e+09,4.377093e+05,257.597133,...,0.367347,0.714286,0.148796,0.712698,1.257952,0.979177,1.103751,63.622003,-341.175758,-1184.535555
16,16,16,0,P19,16,1,1.658873e+09,1.660255e+09,1.946176e+04,37.826394,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
17,17,17,0,P19,17,1,1.660255e+09,1.661897e+09,1.271333e+04,26.636822,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
18,18,18,0,P20,18,0,1.658786e+09,1.660082e+09,1.774296e+05,102.492349,...,0.375000,0.875000,0.092039,0.651827,0.808821,0.759898,0.924682,77.662710,-521.668527,-500.317074
19,19,19,0,P20,19,0,1.660082e+09,1.661810e+09,1.428093e+05,79.795842,...,0.765957,0.765957,0.306796,0.831599,0.883499,0.802121,0.904028,43.516442,-152.723374,-609.727436
20,20,20,0,P21,20,0,1.658959e+09,1.660169e+09,8.525104e+04,96.856466,...,0.857143,0.734694,0.033748,0.483177,0.823738,0.732468,0.599353,236.903653,-731.602823,-236.548434
21,21,21,0,P21,21,1,1.660169e+09,1.661810e+09,2.998148e+04,38.033857,...,0.142857,0.122449,0.018408,0.423411,0.976725,0.927626,0.592826,166.822358,-272.059310,378.801917
22,22,22,0,P23,22,0,1.659046e+09,1.660255e+09,2.071118e+05,124.147355,...,0.142857,0.122449,0.165670,0.779446,0.684134,0.684993,0.721743,91.361271,227.860434,137.081212
23,23,23,0,P23,23,0,1.660255e+09,1.661810e+09,4.935869e+05,261.020003,...,0.142857,0.224490,0.154932,0.638348,0.839413,0.611069,0.759300,68.424529,414.442518,178.512029
24,24,24,0,P24,24,1,1.659046e+09,1.660428e+09,2.794095e+05,329.216794,...,0.360000,0.620000,0.074398,0.574362,1.254626,1.188718,1.165499,160.889891,215.793478,1356.962550
25,25,25,0,P24,25,1,1.660428e+09,1.661810e+09,6.920620e+04,104.340501,...,0.244898,0.183673,0.090505,0.584386,1.299245,1.307400,1.107756,157.945336,126.015444,246.620638
26,26,26,0,P25,26,0,1.660774e+09,1.661983e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
27,27,27,0,P27,27,0,1.660514e+09,1.661724e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
28,28,28,0,P28,28,0,1.660514e+09,1.663279e+09,4.192882e+04,52.765973,...,0.326531,0.795918,0.078233,0.525366,0.796606,0.828557,0.822693,118.516619,-826.924369,135.896976
29,29,29,0,P29,29,0,1.659305e+09,1.660255e+09,6.656350e+05,522.587999,...,0.387755,0.530612,0.073631,0.566284,1.024214,0.609471,0.911550,30.481007,739.618210,151.253866
30,30,30,0,P29,30,0,1.660255e+09,1.661810e+09,8.155723e+05,618.118330,...,0.142857,0.836735,0.044485,0.591347,0.862309,0.730197,0.857840,33.571947,-1370.466385,-2691.185081
31,31,31,0,P30,31,1,1.659305e+09,1.660255e+09,1.648135e+06,799.078291,...,0.306122,0.714286,0.134223,0.706227,1.012830,1.181778,1.192320,101.949414,-387.438819,-359.940743
32,32,32,0,P30,32,1,1.660255e+09,1.661810e+09,1.416431e+06,673.771219,...,0.346939,0.510204,0.125019,0.675214,1.089338,1.128268,1.274522,92.760183,-520.650958,-291.697824
33,33,33,0,P31,33,0,1.659391e+09,1.660601e+09,8.374565e+05,341.777817,...,0.142857,0.877551,0.016874,0.386287,0.786770,0.543841,0.297664,23.406838,384.541061,705.739276
34,34,34,0,P31,34,0,1.660601e+09,1.661810e+09,5.963323e+05,245.186974,...,0.872340,0.851064,0.067495,0.456107,0.752665,0.656863,0.457564,27.380116,-810.587563,-62.962912
35,35,35,0,P33,35,0,1.659478e+09,1.660601e+09,1.240011e+05,138.264214,...,0.673469,0.714286,0.014573,0.363809,0.788975,0.760841,0.556171,-257.206934,-104.646432,11214.786426
36,36,36,0,P33,36,0,1.660601e+09,1.662070e+09,8.216622e+04,120.025222,...,0.673469,0.632653,0.030680,0.402100,0.870246,0.754503,0.500728,-302.284049,-69.070960,328.900087
37,37,37,0,P34,37,0,1.659564e+09,1.660774e+09,2.167278e+05,144.547551,...,0.125000,0.750000,0.193282,0.733465,0.970049,0.605108,0.908089,35.684895,6700.653138,276.467772
38,38,38,0,P35,38,0,1.659564e+09,1.660774e+09,1.303872e+05,112.606316,...,0.775510,0.591837,0.225495,0.771283,1.028943,0.941293,1.140582,79.495705,122.183045,499.331583
39,39,39,0,P35,39,0,1.660774e+09,1.662070e+09,3.243721e+05,220.622951,...,0.244898,0.653061,0.156466,0.673304,0.944400,0.977701,1.023298,75.766267,115.203053,227.014058
40,40,40,0,P36,40,0,1.660860e+09,1.662070e+09,2.573372e+05,220.269186,...,0.163265,0.142857,0.202485,0.763000,1.164823,1.035039,1.242862,124.295620,-135.939454,-185.267916
41,41,41,0,P38,41,0,1.659564e+09,1.661206e+09,4.329576e+05,247.863471,...,0.326531,0.775510,0.029146,0.410367,0.598555,0.821194,0.736928,75.920045,-189.245762,-1504.488006
42,42,42,0,P38,42,0,1.661206e+09,1.661983e+09,1.642575e+05,102.116400,...,0.250000,0.125000,0.009204,0.419243,0.689716,0.521414,0.552463,44.144951,-127.073653,-97.309417

In [50]:
del dataset['Unnamed: 0']
del dataset['index']
del dataset['level_0']

In [51]:
group = dataset['patient']

In [52]:
del dataset['patient']

In [53]:
dataset

,record,diagnosis,timestamp_start,timestamp_end,X_mid_Absolute energy,X_mid_Area under the curve,X_mid_Autocorrelation,X_mid_Average power,X_mid_Centroid,X_mid_ECDF Percentile Count_0,...,Z_eve_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1,Z_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1,Z_eve_SP_Summaries_welch_rect_centroid,Z_eve_FC_LocalSimple_mean3_stderr,X_eve_app_ent,Y_eve_app_ent,Z_eve_app_ent,X_eve_rsd,Y_eve_rsd,Z_eve_rsd
0,0,0,1.658354e+09,1.659996e+09,2.385522e+04,17.340800,16.0,11580.203963,0.936651,41.0,...,0.183673,0.877551,0.038350,0.556470,1.240145,1.414059,1.101619,-137.406912,247.810229,-84.170855
1,1,0,1.659996e+09,1.661206e+09,2.328345e+05,239.885354,42.0,6007.081693,21.592224,775.0,...,0.437500,0.875000,0.104311,0.664134,1.110772,1.153594,1.206691,-246.703278,-917.852063,-147.429543
2,2,1,1.658354e+09,1.659996e+09,4.725678e+04,54.145724,63.0,4535.199168,6.523586,208.0,...,0.125000,0.854167,0.193282,0.768328,0.829204,1.076619,1.013430,114.967050,-107.494007,-224.427014
3,3,0,1.659996e+09,1.662070e+09,1.807770e+05,129.773994,65.0,14002.863964,7.335980,258.0,...,0.224490,0.122449,0.138058,0.682936,0.659745,0.789076,0.931019,65.528455,-348.921557,-328.457878
4,4,1,1.658441e+09,1.659996e+09,4.557987e+04,24.120677,8.0,30386.579672,0.962864,30.0,...,0.860465,0.139535,0.613592,0.924430,0.938069,0.806088,0.934574,72.352631,177.627123,159.713801
5,5,1,1.659996e+09,1.661206e+09,2.937881e+04,14.343478,2.0,34974.776061,0.392917,17.0,...,0.619048,0.738095,0.269981,0.758146,0.529294,0.502848,0.595768,44.882796,-1732.345347,174.352004
6,6,0,1.658700e+09,1.659996e+09,1.425495e+05,166.412023,56.0,4206.240544,18.322024,678.0,...,0.755102,0.510204,0.036816,0.527443,0.646985,0.687472,0.806980,172.224880,46.271562,73.328927
7,7,0,1.659996e+09,1.661206e+09,1.526638e+04,15.338700,11.0,6131.074397,0.533629,50.0,...,0.780488,0.731707,0.220893,0.714463,0.864127,0.889067,0.751850,-108.350642,22.814158,63.237315
8,8,0,1.658700e+09,1.659910e+09,2.917384e+04,22.015482,8.0,15354.652608,1.082417,38.0,...,0.448980,0.530612,0.085903,0.636002,1.382823,1.206934,1.187669,318.194246,-125.681839,133.769104
9,9,0,1.658786e+09,1.660082e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,0.122449,0.448980,0.171806,0.654882,0.913396,0.750667,0.753536,42.929179,1791.647415,1154.407059
10,10,1,1.660082e+09,1.661206e+09,1.737008e+05,103.388069,11.0,25657.434938,3.140234,135.0,...,0.204082,0.877551,0.233165,0.722889,0.745131,0.752576,0.874068,62.402568,12200.127526,283.902945
11,11,0,1.658873e+09,1.659996e+09,2.302304e+06,1236.346278,51.0,27516.483424,45.273118,1673.0,...,0.220000,0.140000,0.095490,0.630106,0.716455,0.694768,0.883786,81.659767,-520.957701,73.706644
12,12,0,1.659996e+09,1.661206e+09,1.302403e+06,728.651101,38.0,17002.649361,35.965444,1532.0,...,0.240000,0.820000,0.161068,0.712716,0.749267,0.881995,1.036046,90.985271,-879.392994,67.290676
13,13,1,1.658786e+09,1.659996e+09,3.208747e+04,36.392223,34.0,4782.037941,3.885111,134.0,...,0.270833,0.812500,0.291456,0.822146,1.004644,1.144014,1.295719,81.538374,686.473191,156.711907
14,14,1,1.658873e+09,1.659996e+09,4.090342e+05,269.571245,10.0,17768.642943,11.898989,460.0,...,0.163265,0.122449,0.116583,0.683514,1.348638,1.196337,1.133462,47.327685,-772.470353,258.826406
15,15,1,1.659996e+09,1.661206e+09,4.377093e+05,257.597133,28.0,22608.949559,10.502108,387.0,...,0.367347,0.714286,0.148796,0.712698,1.257952,0.979177,1.103751,63.622003,-341.175758,-1184.535555
16,16,1,1.658873e+09,1.660255e+09,1.946176e+04,37.826394,46.0,1291.424058,5.671386,301.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
17,17,1,1.660255e+09,1.661897e+09,1.271333e+04,26.636822,42.0,1361.170554,3.956658,187.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
18,18,0,1.658786e+09,1.660082e+09,1.774296e+05,102.492349,39.0,20800.662151,3.095727,170.0,...,0.375000,0.875000,0.092039,0.651827,0.808821,0.759898,0.924682,77.662710,-521.668527,-500.317074
19,19,0,1.660082e+09,1.661810e+09,1.428093e+05,79.795842,18.0,19616.668229,3.687198,145.0,...,0.765957,0.765957,0.306796,0.831599,0.883499,0.802121,0.904028,43.516442,-152.723374,-609.727436
20,20,0,1.658959e+09,1.660169e+09,8.525104e+04,96.856466,26.0,4239.236206,8.281299,402.0,...,0.857143,0.734694,0.033748,0.483177,0.823738,0.732468,0.599353,236.903653,-731.602823,-236.548434
21,21,1,1.660169e+09,1.661810e+09,2.998148e+04,38.033857,17.0,3490.277533,3.654378,172.0,...,0.142857,0.122449,0.018408,0.423411,0.976725,0.927626,0.592826,166.822358,-272.059310,378.801917
22,22,0,1.659046e+09,1.660255e+09,2.071118e+05,124.147355,41.0,11957.954140,13.895433,346.0,...,0.142857,0.122449,0.165670,0.779446,0.684134,0.684993,0.721743,91.361271,227.860434,137.081212
23,23,0,1.660255e+09,1.661810e+09,4.935869e+05,261.020003,43.0,21937.196088,14.115106,450.0,...,0.142857,0.224490,0.154932,0.638348,0.839413,0.611069,0.759300,68.424529,414.442518,178.512029
24,24,1,1.659046e+09,1.660428e+09,2.794095e+05,329.216794,65.0,3640.514209,35.806481,1535.0,...,0.360000,0.620000,0.074398,0.574362,1.254626,1.188718,1.165499,160.889891,215.793478,1356.962550
25,25,1,1.660428e+09,1.661810e+09,6.920620e+04,104.340501,19.0,2275.023136,14.626497,608.0,...,0.244898,0.183673,0.090505,0.584386,1.299245,1.307400,1.107756,157.945336,126.015444,246.620638
26,26,0,1.660774e+09,1.661983e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
27,27,0,1.660514e+09,1.661724e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
28,28,0,1.660514e+09,1.663279e+09,4.192882e+04,52.765973,48.0,3565.375641,5.577221,235.0,...,0.326531,0.795918,0.078233,0.525366,0.796606,0.828557,0.822693,118.516619,-826.924369,135.896976
29,29,0,1.659305e+09,1.660255e+09,6.656350e+05,522.587999,44.0,13254.381399,22.455095,1004.0,...,0.387755,0.530612,0.073631,0.566284,1.024214,0.609471,0.911550,30.481007,739.618210,151.253866
30,30,0,1.660255e+09,1.661810e+09,8.155723e+05,618.118330,138.0,16370.379979,23.657539,996.0,...,0.142857,0.836735,0.044485,0.591347,0.862309,0.730197,0.857840,33.571947,-1370.466385,-2691.185081
31,31,1,1.659305e+09,1.660255e+09,1.648135e+06,799.078291,31.0,26833.845857,31.267339,1228.0,...,0.306122,0.714286,0.134223,0.706227,1.012830,1.181778,1.192320,101.949414,-387.438819,-359.940743
32,32,1,1.660255e+09,1.661810e+09,1.416431e+06,673.771219,33.0,29301.436202,23.672326,967.0,...,0.346939,0.510204,0.125019,0.675214,1.089338,1.128268,1.274522,92.760183,-520.650958,-291.697824
33,33,0,1.659391e+09,1.660601e+09,8.374565e+05,341.777817,7.0,59100.670379,6.933817,283.0,...,0.142857,0.877551,0.016874,0.386287,0.786770,0.543841,0.297664,23.406838,384.541061,705.739276
34,34,0,1.660601e+09,1.661810e+09,5.963323e+05,245.186974,30.0,57229.588036,4.771805,208.0,...,0.872340,0.851064,0.067495,0.456107,0.752665,0.656863,0.457564,27.380116,-810.587563,-62.962912
35,35,0,1.659478e+09,1.660601e+09,1.240011e+05,138.264214,59.0,4975.968115,11.862588,498.0,...,0.673469,0.714286,0.014573,0.363809,0.788975,0.760841,0.556171,-257.206934,-104.646432,11214.786426
36,36,0,1.660601e+09,1.662070e+09,8.216622e+04,120.025222,19.0,3341.448433,12.320009,492.0,...,0.673469,0.632653,0.030680,0.402100,0.870246,0.754503,0.500728,-302.284049,-69.070960,328.900087
37,37,0,1.659564e+09,1.660774e+09,2.167278e+05,144.547551,31.0,19350.694698,5.309470,224.0,...,0.125000,0.750000,0.193282,0.733465,0.970049,0.605108,0.908089,35.684895,6700.653138,276.467772
38,38,0,1.659564e+09,1.660774e+09,1.303872e+05,112.606316,23.0,6208.912115,11.166546,420.0,...,0.775510,0.591837,0.225495,0.771283,1.028943,0.941293,1.140582,79.495705,122.183045,499.331583
39,39,0,1.660774e+09,1.662070e+09,3.243721e+05,220.622951,18.0,12499.886626,12.452717,519.0,...,0.244898,0.653061,0.156466,0.673304,0.944400,0.977701,1.023298,75.766267,115.203053,227.014058
40,40,0,1.660860e+09,1.662070e+09,2.573372e+05,220.269186,17.0,7627.067261,21.104571,675.0,...,0.163265,0.142857,0.202485,0.763000,1.164823,1.035039,1.242862,124.295620,-135.939454,-185.267916
41,41,0,1.659564e+09,1.661206e+09,4.329576e+05,247.863471,61.0,21529.469314,11.592990,402.0,...,0.326531,0.775510,0.029146,0.410367,0.598555,0.821194,0.736928,75.920045,-189.245762,-1504.488006
42,42,0,1.661206e+09,1.661983e+09,1.642575e+05,102.116400,18.0,23736.638028,3.387446,138.0,...,0.250000,0.125000,0.009204,0.419243,0.689716,0.521414,0.552463,44.144951,-127.073653,-97.309417

In [40]:
#dataset = dataset.fillna(dataset.mean())

In [54]:
y = dataset['diagnosis']

In [55]:
del dataset['diagnosis']

In [56]:
records  = dataset['record']

In [57]:
del dataset['record']

In [58]:
del dataset['timestamp_start']
del dataset['timestamp_end']

# Binary classification

# Splitting and training

# Feature selection

In [20]:
import pymrmr

In [59]:
X = dataset.copy()

In [22]:
type_classification = 'binary'



#X = X.replace([np.nan, -np.inf, np.inf], 0)
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
#y = y.reshape((len(y), ))
X.insert(loc=0, column='class', value=y)
X_to_choose = X.copy()
#Discritize data
_, nr_col = np.shape(X)
for i in range(1, nr_col):
    discretizer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='kmeans')
    X.iloc[:, i] = discretizer.fit_transform(X.iloc[:, i].values.reshape(-1,1))
    
col = pymrmr.mRMR(X, 'MIQ', 50)

# Read the data again to import data with NaN values

In [ ]:
dataset = pd.read_csv('euler_features.csv')
del dataset['Unnamed: 0']
del dataset['index']
group = dataset['patient']
groups = group
del dataset['patient']
y = dataset['diagnosis']
del dataset['diagnosis']
records  = dataset['record']
del dataset['record']
del dataset['timestamp_start']
del dataset['timestamp_end']
X = dataset.copy()

In [23]:
col

['X_mor_Median absolute diff',
 'X_mor_CO_FirstMin_ac',
 'Y_eve_Spectral skewness',
 'Z_aft_MFCC_9',
 'Z_eve_LPCC_10',
 'Y_aft_DN_OutlierInclude_n_001_mdrmd',
 'Y_aft_Kurtosis',
 'Y_mid_SB_MotifThree_quantile_hh',
 'X_mid_CO_HistogramAMI_even_2_5',
 'X_mid_Median absolute diff',
 'X_mor_rsd',
 'Y_eve_Wavelet energy_5.0Hz',
 'Z_mor_Histogram mode',
 'X_mid_Spectral distance',
 'X_mid_Wavelet absolute mean_12.5Hz',
 'Z_mor_Human range energy',
 'Z_aft_Human range energy',
 'Z_mid_Wavelet entropy',
 'X_mor_SB_TransitionMatrix_3ac_sumdiagcov',
 'Y_eve_MFCC_0',
 'X_eve_CO_f1ecac',
 'Y_eve_FC_LocalSimple_mean1_tauresrat',
 'X_mid_MFCC_7',
 'Z_eve_LPCC_6',
 'Y_eve_Mean',
 'Z_aft_aft',
 'Y_mor_Median absolute diff',
 'X_aft_Wavelet variance_6.25Hz',
 'Y_aft_Skewness',
 'Y_eve_Standard deviation',
 'Z_aft_app_ent',
 'Z_eve_Histogram mode',
 'Z_mor_Spectral kurtosis',
 'Z_mor_LPCC_10',
 'Z_mid_MFCC_0',
 'Z_mid_DN_OutlierInclude_n_001_mdrmd',
 'X_mid_FC_LocalSimple_mean3_stderr',
 'Z_mor_Spectral roll-on',
 'Y_eve_Wavelet standard deviation_5.0Hz',
 'Z_eve_LPCC_9',
 'Y_mid_Wavelet entropy',
 'X_mor_MFCC_1',
 'Y_aft_Median diff',
 'Y_mor_Interquartile range',
 'X_eve_MFCC_2',
 'Z_aft_ECDF Percentile_0',
 'Y_aft_Interquartile range',
 'Y_eve_SB_MotifThree_quantile_hh',
 'Y_aft_MFCC_11',
 'Z_aft_Median absolute deviation']

In [60]:
col = ['X_mor_Median absolute diff',
 'X_mor_CO_FirstMin_ac',
 'Y_eve_Spectral skewness',
 'Z_aft_MFCC_9',
 'Z_eve_LPCC_10',
 'Y_aft_DN_OutlierInclude_n_001_mdrmd',
 'Y_aft_Kurtosis',
 'Y_mid_SB_MotifThree_quantile_hh',
 'X_mid_CO_HistogramAMI_even_2_5',
 'X_mid_Median absolute diff',
 'X_mor_rsd',
 'Y_eve_Wavelet energy_5.0Hz',
 'Z_mor_Histogram mode',
 'X_mid_Spectral distance',
 'X_mid_Wavelet absolute mean_12.5Hz',
 'Z_mor_Human range energy',
 'Z_aft_Human range energy',
 'Z_mid_Wavelet entropy',
 'X_mor_SB_TransitionMatrix_3ac_sumdiagcov',
 'Y_eve_MFCC_0',
 'X_eve_CO_f1ecac',
 'Y_eve_FC_LocalSimple_mean1_tauresrat',
 'X_mid_MFCC_7',
 'Z_eve_LPCC_6',
 'Y_eve_Mean',
 'Z_aft_aft',
 'Y_mor_Median absolute diff',
 'X_aft_Wavelet variance_6.25Hz',
 'Y_aft_Skewness',
 'Y_eve_Standard deviation',
 'Z_aft_app_ent',
 'Z_eve_Histogram mode',
 'Z_mor_Spectral kurtosis',
 'Z_mor_LPCC_10',
 'Z_mid_MFCC_0',
 'Z_mid_DN_OutlierInclude_n_001_mdrmd',
 'X_mid_FC_LocalSimple_mean3_stderr',
 'Z_mor_Spectral roll-on',
 'Y_eve_Wavelet standard deviation_5.0Hz',
 'Z_eve_LPCC_9',
 'Y_mid_Wavelet entropy',
 'X_mor_MFCC_1',
 'Y_aft_Median diff',
 'Y_mor_Interquartile range',
 'X_eve_MFCC_2',
 'Z_aft_ECDF Percentile_0',
 'Y_aft_Interquartile range',
 'Y_eve_SB_MotifThree_quantile_hh',
 'Y_aft_MFCC_11',
 'Z_aft_Median absolute deviation']

In [61]:
X_new = X[col]

In [62]:
X_new = X_new.astype(float)

In [63]:
X_new

,X_mor_Median absolute diff,X_mor_CO_FirstMin_ac,Y_eve_Spectral skewness,Z_aft_MFCC_9,Z_eve_LPCC_10,Y_aft_DN_OutlierInclude_n_001_mdrmd,Y_aft_Kurtosis,Y_mid_SB_MotifThree_quantile_hh,X_mid_CO_HistogramAMI_even_2_5,X_mid_Median absolute diff,...,Y_mid_Wavelet entropy,X_mor_MFCC_1,Y_aft_Median diff,Y_mor_Interquartile range,X_eve_MFCC_2,Z_aft_ECDF Percentile_0,Y_aft_Interquartile range,Y_eve_SB_MotifThree_quantile_hh,Y_aft_MFCC_11,Z_aft_Median absolute deviation
0,1.111253,74.0,0.517216,-63.982947,0.675936,-1.100402e-01,25.992625,1.978107,0.516409,1.528561,...,2.152985,-3.072370,0.013744,5.240502,-22.456701,-10.962842,4.394781,1.864898,59.704709,4.151739
1,1.308431,32.0,0.680874,112.264414,0.612926,5.357020e-01,22.832775,1.854084,0.337028,1.317124,...,2.138340,-0.401723,-0.010733,4.968046,3.395688,-11.699333,4.687869,1.952109,74.004968,3.668667
2,NaN,NaN,0.592283,2.675322,0.438377,3.435115e-02,143.664869,1.894561,0.383104,0.773181,...,2.150831,NaN,-0.082027,NaN,-34.447004,-2.302551,2.267029,1.780803,105.640193,1.006021
3,NaN,NaN,0.955738,54.407397,0.450985,-6.993355e-01,6.156512,1.884529,0.463371,0.931493,...,2.134726,NaN,-0.036780,NaN,-47.229599,-2.616420,2.358197,1.811812,115.953813,1.473273
4,1.596026,43.0,0.393953,52.227544,0.281112,7.246377e-03,15.418383,1.989329,0.223958,1.925686,...,2.152917,-21.617130,-0.150450,4.929372,-12.635634,-1.889871,6.230423,2.003690,-2.610520,4.293780
5,1.466992,8.0,0.584826,56.037895,0.345149,2.788104e-02,6.170825,1.946959,0.130506,3.131657,...,2.116769,-28.497878,-0.077307,8.400432,-26.351001,0.355439,8.168228,1.983756,61.651174,3.508968
6,NaN,0.0,0.925695,26.963204,0.710825,4.886914e-01,25.544060,1.745747,0.500287,0.551627,...,2.115506,NaN,0.009768,NaN,-18.467790,3.242870,4.385272,1.602744,27.342037,1.877807
7,NaN,NaN,1.498715,NaN,0.432193,NaN,NaN,1.885628,0.472960,0.630010,...,2.081751,NaN,NaN,NaN,3.665892,NaN,NaN,1.816719,NaN,NaN
8,1.438103,78.0,0.730327,91.267617,0.583473,3.044569e-01,22.191378,1.912865,0.446269,0.991263,...,2.109643,-39.446570,-0.015004,5.123199,17.178118,1.734700,5.746389,1.986252,16.018730,2.482197
9,0.615900,65.0,0.737098,19.692294,0.368518,7.337990e-01,22.126425,NaN,NaN,NaN,...,NaN,-39.327540,0.000000,3.868259,-16.853711,-0.684947,2.940107,1.784682,27.795198,2.026146
10,1.038286,38.0,0.817353,-106.931391,0.382868,-3.526502e-01,17.516283,1.853436,0.283253,0.941719,...,2.134208,-4.193180,0.000000,3.052002,-20.425282,-0.848230,4.910234,1.704214,63.588291,3.349189
11,NaN,3.0,0.847186,-70.067874,0.619001,4.874326e-02,23.396487,1.724375,0.436389,0.731863,...,2.131955,NaN,0.000000,NaN,-19.515672,3.733087,3.955010,1.720068,-10.669185,1.834128
12,0.448883,49.0,0.808764,64.944846,0.650510,-1.122221e-01,19.285454,1.788548,0.552395,0.824285,...,2.100066,-35.181177,0.000000,3.248620,-18.242893,3.814629,4.106638,1.764715,13.045705,1.510285
13,1.637819,14.0,0.450551,60.874769,0.402966,-5.722121e-01,7.000005,1.938482,0.347183,1.362998,...,2.151092,-2.598269,-0.031402,3.108677,-8.310724,-1.856744,3.827209,1.966050,118.394924,2.384671
14,1.321345,9.0,0.476536,66.231207,0.371433,1.835260e-01,6.523740,1.905054,0.227555,1.654872,...,2.134211,-18.590897,0.000000,8.339779,12.235696,-3.034599,14.367436,1.841763,49.987589,2.218539
15,1.479718,20.0,0.659623,35.787966,0.360944,-2.797007e-01,3.627778,1.892406,0.397275,1.744752,...,2.124604,-3.385302,0.000000,4.656797,5.246099,-4.859943,7.896904,1.809754,70.122815,4.085826
16,1.086963,12.0,NaN,4.408386,NaN,-7.192719e-01,0.951592,1.903324,0.193070,0.943032,...,2.147038,-20.807324,0.000000,5.041651,NaN,-1.170173,6.277124,NaN,-9.881476,1.218377
17,0.966860,6.0,NaN,15.686907,NaN,-4.422283e-01,7.562745,1.862871,0.307026,0.851114,...,2.137967,-23.620446,0.000000,4.099857,NaN,-2.041435,8.909347,NaN,83.784428,1.268542
18,1.206118,8.0,0.486776,56.888360,0.407310,4.868270e-02,7.306668,1.717159,0.535797,1.244235,...,2.127153,-27.154971,0.000000,4.157889,-17.686048,-4.106281,6.163193,1.571979,22.549502,2.865926
19,0.893174,99.0,0.447340,138.575448,0.331049,-1.871019e-01,14.743259,1.746401,0.363373,1.250019,...,2.122076,-5.889597,-0.024491,13.016761,25.588765,-5.061770,5.773919,1.736361,86.978766,2.443794
20,0.750226,3.0,0.548314,40.125264,0.594565,-4.645722e-01,46.596975,1.696524,0.373741,1.053736,...,2.143544,-50.517869,0.000000,2.018994,-46.282413,-8.347845,6.107253,1.663914,66.019012,6.086764
21,1.807127,8.0,0.681030,-33.281877,0.516805,-2.068345e-01,2.383401,1.924890,0.189339,1.575512,...,2.141609,-25.975366,0.002576,5.594112,-13.052011,-3.132679,3.549302,1.727994,2.118721,3.402856
22,0.536682,13.0,0.696914,-6.424896,0.433016,2.901941e-01,32.954414,1.834062,0.314347,0.561548,...,2.143465,-11.033751,0.000000,3.550989,1.076126,0.000000,4.594831,1.641053,-15.077872,2.217061
23,0.728699,6.0,0.672893,8.711157,0.390232,5.695364e-01,6.581130,1.861804,0.441856,1.146022,...,2.134000,-34.579958,0.000000,6.173963,0.160713,0.000000,3.935947,1.607141,121.225019,1.764034
24,NaN,NaN,0.596384,-40.561028,0.454478,9.516044e-02,14.833107,1.750434,0.387203,0.677467,...,2.121724,NaN,0.000000,NaN,-18.512153,-3.949457,3.506641,1.889734,-4.935831,2.696076
25,1.600874,13.0,0.565484,-3.911360,0.522524,8.820547e-02,18.169195,1.727562,0.336077,0.548032,...,2.107494,-19.654209,0.000000,5.394820,-14.372742,-2.712456,3.004355,1.925500,118.654509,2.879263
26,1.073469,43.0,NaN,188.559776,NaN,2.942431e-01,-0.037500,NaN,NaN,NaN,...,NaN,-3.915514,-0.007298,4.325374,NaN,-1.794570,23.561896,NaN,-39.993649,2.033478
27,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1.073238,4.0,0.746395,30.226218,0.546876,2.926454e-02,39.366018,1.870610,0.361587,0.869337,...,2.115205,-36.622388,-0.031303,1.248004,17.799423,-0.554675,2.866319,1.804502,96.358848,3.401126
29,0.377140,2.0,0.930641,85.805745,0.494515,2.598210e-02,50.456104,1.600954,0.410879,0.526183,...,2.085806,-23.060833,0.006468,1.825335,8.753988,-0.196570,3.329284,1.660378,59.092030,2.294688
30,0.692001,4.0,0.633616,-40.889321,0.343416,3.724844e-01,47.933842,1.539176,0.364176,0.425434,...,2.087394,-11.427632,0.005015,2.495442,-42.582852,-0.837587,2.369761,1.616308,87.043032,1.868708
31,0.996188,12.0,0.750036,20.847412,0.407810,7.510373e-02,15.054817,1.885899,0.384304,1.613190,...,2.140710,-3.561522,0.000000,6.609087,-24.629256,-4.966409,5.659095,1.859660,102.815809,3.163371
32,1.886517,16.0,0.811673,-0.631917,0.389133,-4.841670e-02,9.778527,1.888543,0.393705,1.793191,...,2.141740,-22.063881,0.000000,5.602948,-15.898975,-5.648980,6.642947,1.833809,93.001009,3.389426
33,0.989116,10.0,0.944241,91.021027,0.678898,-6.470588e-01,-1.287972,1.660440,0.174817,0.790281,...,2.116286,-43.549008,-0.031206,11.436524,-11.521579,-8.522572,2.032622,1.464199,-33.770083,1.144690
34,1.165693,14.0,0.775394,NaN,0.787172,NaN,NaN,1.775330,0.218588,1.109812,...,2.120087,-37.127717,NaN,4.570741,12.205924,NaN,NaN,1.849550,NaN,NaN
35,NaN,NaN,0.770107,71.251214,0.620800,-3.169277e-01,40.989244,1.805300,0.367572,1.198754,...,2.124524,NaN,-0.022092,NaN,6.753406,-7.466444,3.162169,1.741058,72.434361,5.387588
36,NaN,NaN,0.652905,70.136828,0.603601,-3.797949e-01,79.999198,1.772278,0.253257,1.041236,...,2.095759,NaN,-0.025278,NaN,-20.375921,-5.582903,2.827058,1.779270,19.308598,5.237796
37,1.585906,3.0,0.732584,41.710544,0.453645,6.540698e-01,22.134586,1.903310,0.306781,1.178527,...,2.135848,-33.305169,-0.006729,1.589636,21.799145,-0.323051,2.126114,1.861879,59.265805,1.365304
38,NaN,2.0,0.537867,134.121287,0.309930,5.793980e-01,20.601140,1.874326,0.328845,0.850876,...,2.111035,NaN,0.001732,NaN,0.577950,-1.010658,4.877649,1.784582,35.433410,1.898511
39,NaN,NaN,0.591624,154.160828,0.359757,-2.160289e-01,32.343618,1.823821,0.410944,0.919447,...,2.112386,NaN,0.000000,NaN,33.094618,0.356156,4.493054,1.788140,60.054939,1.884466
40,1.128918,9.0,0.538607,104.880130,0.409385,2.459598e-01,38.393322,1.886529,0.262298,1.254875,...,2.121034,12.482932,-0.011648,3.292935,11.437699,-4.494592,3.477370,1.933807,37.459221,1.985527
41,NaN,NaN,0.794318,50.952279,0.600105,5.551115e-17,12.314867,1.666544,0.541686,0.939454,...,2.133573,NaN,0.014595,NaN,0.990027,-2.998859,10.741115,1.732128,-56.098826,2.409841
42,0.524316,7.0,0.838034,92.787908,0.728768,-9.247059e-01,21.405046,1.747295,0.263795,0.827353,...,2.145677,-8.744205,-0.001365,1.264163,-42.958969,-7.123243,2.510394,1.668844,57.927983,2.384202

# Training and validation

# Test

In [64]:
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
ratio_scaler

2.0714285714285716

In [65]:
from sklearn.model_selection import LeaveOneGroupOut

logo = LeaveOneGroupOut()
logo.get_n_splits(X_new, y, group)

25

# Decision Tree

In [66]:
from sklearn.model_selection import RandomizedSearchCV, LeaveOneGroupOut
from xgboost import XGBClassifier
from scipy.stats import randint, uniform
import numpy as np

In [67]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
distributions_dt = dict(max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced', None])

In [68]:
param_dist = distributions_dt
model = dt

In [69]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'max_depth': np.random.choice(distributions_dt['max_depth']),
            'min_samples_split': np.random.choice(distributions_dt['min_samples_split']),
            'min_samples_leaf': np.random.choice(distributions_dt['min_samples_leaf']),
            'max_features': np.random.choice(distributions_dt['max_features']),
            'class_weight': np.random.choice(distributions_dt['class_weight']),
        }
        print(f"Testing parameters: {params}")
        model = DecisionTreeClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(dt, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 38, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 38, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 74, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': None}

Parameters: {'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 71, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 71, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.5960591133004927, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 27, 'class_weight': None}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}

Parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 26, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 78, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 78, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}

Parameters: {'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': None}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': None}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': None}
AUC: 0.5923645320197044, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': None}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}

Parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': None}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': None}
AUC: 0.6995073891625616, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}

Parameters: {'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 23, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 23, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': None}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 93, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 93, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}

Parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': None}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': None}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 63, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 63, 'class_weight': None}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.645320197044335, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': None}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}

Parameters: {'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': None}
AUC: 0.6810344827586207, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 50, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 50, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.645320197044335, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}

Parameters: {'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': None}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': None}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': None}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.7167487684729063, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Best AUC: 0.7167487684729063
Best parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}

In [70]:
model.set_params(**best_params)

DecisionTreeClassifier(class_weight='balanced', max_depth=12, max_features=98,
                       min_samples_leaf=0.2, min_samples_split=1.0)

In [71]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    model.fit(X_train, y_train)

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.541871921182266, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333, Accuracy: 0.6744186046511628, Balanced Accuracy: 0.6477832512315271

# Decision Tree + SMOTE

In [72]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'max_depth': np.random.choice(distributions_dt['max_depth']),
            'min_samples_split': np.random.choice(distributions_dt['min_samples_split']),
            'min_samples_leaf': np.random.choice(distributions_dt['min_samples_leaf']),
            'max_features': np.random.choice(distributions_dt['max_features']),
            'class_weight': np.random.choice(distributions_dt['class_weight']),
        }
        print(f"Testing parameters: {params}")
        model = DecisionTreeClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(dt, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': None}
AUC: 0.4753694581280788, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': None}
AUC: 0.520935960591133, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.3928571428571428, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.5492610837438423, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
AUC: 0.48768472906403937, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 95, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 95, 'class_weight': None}
AUC: 0.4088669950738916, Precision: 0.3181818181818182, Recall: 0.5, F1-score: 0.3888888888888889
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': None}
AUC: 0.39408866995073893, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': None}
AUC: 0.5455665024630543, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.5197044334975369, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.39778325123152714, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.3842364532019704, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': None}
AUC: 0.4100985221674877, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': None}
AUC: 0.39039408866995073, Precision: 0.23529411764705882, Recall: 0.2857142857142857, F1-score: 0.2580645161290323
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6108374384236452, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.480295566502463, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4076354679802956, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
AUC: 0.34113300492610843, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.3448275862068965, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.3916256157635468, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': None}
AUC: 0.29064039408866993, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': None}
AUC: 0.46182266009852213, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}

Parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.3866995073891626, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.3830049261083744, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.4433497536945813, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': None}
AUC: 0.33004926108374383, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': None}
AUC: 0.5628078817733991, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 55, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 55, 'class_weight': None}
AUC: 0.48152709359605916, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': None}
AUC: 0.39778325123152714, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.40394088669950734, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 43, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 43, 'class_weight': None}
AUC: 0.5689655172413792, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.49137931034482757, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': None}
AUC: 0.42241379310344823, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': None}
AUC: 0.4753694581280788, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4470443349753694, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5036945812807881, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.39408866995073893, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.375615763546798, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': None}
AUC: 0.43226600985221675, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.3719211822660099, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': None}
AUC: 0.4322660098522168, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.4445812807881773, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': None}

Parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': None}
AUC: 0.5036945812807883, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.47167487684729065, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
AUC: 0.5332512315270936, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': None}
AUC: 0.40394088669950734, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4248768472906404, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.4088669950738916, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.37192118226600984, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4371921182266009, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.291871921182266, Precision: 0.2, Recall: 0.21428571428571427, F1-score: 0.20689655172413796
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': None}
AUC: 0.4704433497536946, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.3977832512315271, Precision: 0.1875, Recall: 0.21428571428571427, F1-score: 0.19999999999999998
Testing parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.4532019704433497, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': None}
AUC: 0.35344827586206895, Precision: 0.2857142857142857, Recall: 0.42857142857142855, F1-score: 0.34285714285714286
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 71, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 71, 'class_weight': None}
AUC: 0.38916256157635465, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.4211822660098522, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.5098522167487685, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.45443349753694584, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
AUC: 0.4236453201970443, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.5825123152709359, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.5110837438423645, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.36699507389162567, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.38300492610837444, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 8, 'class_weight': None}

Parameters: {'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 8, 'class_weight': None}
AUC: 0.4433497536945813, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.3189655172413793, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': None}
AUC: 0.42980295566502463, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': None}
AUC: 0.4667487684729063, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4433497536945813, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.38300492610837433, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': None}
AUC: 0.4273399014778325, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4421182266009852, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
AUC: 0.4076354679802956, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.38916256157635465, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': None}
AUC: 0.4224137931034483, Precision: 0.23529411764705882, Recall: 0.2857142857142857, F1-score: 0.2580645161290323
Testing parameters: {'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': None}
AUC: 0.3571428571428571, Precision: 0.23076923076923078, Recall: 0.21428571428571427, F1-score: 0.22222222222222224
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.29802955665024633, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': None}
AUC: 0.4224137931034483, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.3879310344827586, Precision: 0.2857142857142857, Recall: 0.42857142857142855, F1-score: 0.34285714285714286
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': None}
AUC: 0.36206896551724144, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': None}
AUC: 0.6059113300492611, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': None}
AUC: 0.46798029556650245, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': None}
AUC: 0.5184729064039408, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.5307881773399015, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': None}

Parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': None}
AUC: 0.3128078817733991, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.4938423645320197, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': None}
AUC: 0.3903940886699508, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.4285714285714285, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.5320197044334976, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': None}
AUC: 0.44581280788177335, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.3041871921182266, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.5147783251231528, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.5874384236453201, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': None}
AUC: 0.5812807881773399, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.37068965517241376, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.3583743842364532, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': None}
AUC: 0.45935960591133007, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': None}
AUC: 0.4273399014778325, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5123152709359606, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.41256157635467977, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': None}
AUC: 0.4938423645320197, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': None}
AUC: 0.396551724137931, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.47290640394088673, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
AUC: 0.32881773399014774, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': None}
AUC: 0.47906403940886705, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': None}

Parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': None}
AUC: 0.4014778325123153, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.5024630541871922, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4667487684729065, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4088669950738917, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': None}
AUC: 0.44704433497536944, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': None}
AUC: 0.29433497536945813, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.5467980295566502, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': None}
AUC: 0.42610837438423643, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.4458128078817734, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': None}
AUC: 0.44581280788177335, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': None}
AUC: 0.3583743842364531, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.44211822660098526, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.43349753694581283, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.5874384236453202, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': None}
AUC: 0.3854679802955665, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': None}
AUC: 0.38793103448275856, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.47167487684729065, Precision: 0.3181818181818182, Recall: 0.5, F1-score: 0.3888888888888889
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4532019704433498, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': None}
AUC: 0.4876847290640394, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4864532019704433, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.41256157635467977, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
AUC: 0.3830049261083744, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': None}

Parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': None}
AUC: 0.29926108374384236, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
AUC: 0.5344827586206897, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.5135467980295567, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.5049261083743843, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.45935960591133007, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': None}
AUC: 0.43226600985221675, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 73, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 73, 'class_weight': None}
AUC: 0.35714285714285715, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.46798029556650245, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.3990147783251231, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.6096059113300494, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.40763546798029554, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4482758620689655, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.4445812807881774, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.3842364532019705, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': None}
AUC: 0.4174876847290641, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.4285714285714285, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': None}
AUC: 0.4433497536945813, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
AUC: 0.45935960591133007, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.5160098522167489, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': None}
AUC: 0.4064039408866995, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}

Parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.43842364532019706, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': None}
AUC: 0.4975369458128079, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.45689655172413796, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5147783251231527, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.3181818181818182, Recall: 0.5, F1-score: 0.3888888888888889
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.5775862068965518, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.49137931034482757, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5123152709359605, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': None}
AUC: 0.45566502463054187, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': None}
AUC: 0.46059113300492605, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4839901477832512, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': None}
AUC: 0.3793103448275862, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.46182266009852213, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': None}
AUC: 0.5049261083743842, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.3657635467980296, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.3448275862068966, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
AUC: 0.5283251231527095, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': None}
AUC: 0.35221674876847286, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': None}
AUC: 0.3362068965517241, Precision: 0.2857142857142857, Recall: 0.42857142857142855, F1-score: 0.34285714285714286
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': None}
AUC: 0.2881773399014778, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.3866995073891626, Precision: 0.23529411764705882, Recall: 0.2857142857142857, F1-score: 0.2580645161290323
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}

Parameters: {'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.4285714285714286, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': None}
AUC: 0.4051724137931034, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.4187192118226601, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': None}
AUC: 0.5049261083743842, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.37068965517241376, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.4839901477832513, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': None}
AUC: 0.395320197044335, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': None}
AUC: 0.5714285714285715, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.3719211822660098, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.5344827586206896, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': None}
AUC: 0.3238916256157635, Precision: 0.2857142857142857, Recall: 0.42857142857142855, F1-score: 0.34285714285714286
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': None}
AUC: 0.3300492610837439, Precision: 0.23529411764705882, Recall: 0.2857142857142857, F1-score: 0.2580645161290323
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4778325123152709, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.479064039408867, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': None}
AUC: 0.458128078817734, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.5480295566502463, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': None}
AUC: 0.35960591133004927, Precision: 0.21052631578947367, Recall: 0.2857142857142857, F1-score: 0.24242424242424243
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.3842364532019704, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': None}
AUC: 0.35714285714285715, Precision: 0.3181818181818182, Recall: 0.5, F1-score: 0.3888888888888889
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.44211822660098526, Precision: 0.2857142857142857, Recall: 0.42857142857142855, F1-score: 0.34285714285714286
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}

Parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4334975369458128, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': None}
AUC: 0.5098522167487685, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Best AUC: 0.6108374384236452
Best parameters: {'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}

In [73]:
model = dt.set_params(**best_params)

In [74]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.5972906403940887, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855, Accuracy: 0.627906976744186, Balanced Accuracy: 0.5763546798029556

# Random Forest

In [75]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param_grid = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])

In [77]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'n_estimators': np.random.choice(param_grid['n_estimators']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'min_samples_split': np.random.choice(param_grid['min_samples_split']),
            'min_samples_leaf': np.random.choice(param_grid['min_samples_leaf']),
            'max_features': np.random.choice(param_grid['max_features']),
            'class_weight': np.random.choice(param_grid['class_weight']),

        }
        print(f"Testing parameters: {params}")
        pipeline = RandomForestClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

rf = RandomForestClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(rf, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5160098522167487, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6330049261083743, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.7684729064039408, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.5307881773399015, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.41009852216748766, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.5652709359605912, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5652709359605912, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.437192118226601, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.41748768472906406, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.5652709359605912, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.7364532019704434, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6798029556650247, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.7216748768472907, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.5886699507389163, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6330049261083744, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.7339901477832512, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.7315270935960592, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.5455665024630542, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.49630541871921174, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.5258620689655173, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5160098522167487, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.5086206896551724, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.5344827586206897, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.7881773399014779, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.6502463054187193, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.7758620689655173, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.5738916256157635, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4125615763546798, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 2, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.7758620689655173, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6674876847290641, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.7167487684729064, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.7857142857142857, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.7684729064039408, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.7881773399014779, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.5911330049261084, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.6699507389162562, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 4, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.5431034482758621, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.539408866995074, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.5738916256157635, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.7733990147783252, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.6330049261083743, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.7857142857142858, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.5283251231527094, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.603448275862069, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.6576354679802956, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.7044334975369458, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6379310344827587, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.7807881773399015, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 64, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.5258620689655173, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.731527093596059, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.5825123152709359, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.7635467980295567, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.5726600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.6059113300492611, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.5825123152709359, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5566502463054187, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Testing parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.7364532019704433, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.7610837438423645, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.5726600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.7980295566502462, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.8201970443349754, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.5110837438423645, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.5504926108374384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.7684729064039408, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.58128078817734, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.729064039408867, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.7660098522167488, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.7315270935960592, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.7044334975369458, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.6699507389162562, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.5825123152709359, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6428571428571429, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.6133004926108374, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.7758620689655172, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.7660098522167488, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6970443349753694, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.729064039408867, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.6428571428571429, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.7906403940886699, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Best AUC: 0.8201970443349754
Best parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}

In [78]:
model = RandomForestClassifier(**best_params, random_state = 42)

In [79]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train, y_train)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8201970443349754, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56, Accuracy: 0.7441860465116279, Balanced Accuracy: 0.6810344827586207

# Random Forest + SMOTE

In [80]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param_grid = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])

In [81]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'n_estimators': np.random.choice(param_grid['n_estimators']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'min_samples_split': np.random.choice(param_grid['min_samples_split']),
            'min_samples_leaf': np.random.choice(param_grid['min_samples_leaf']),
            'max_features': np.random.choice(param_grid['max_features']),
            'class_weight': np.random.choice(param_grid['class_weight']),

        }
        print(f"Testing parameters: {params}")
        pipeline = RandomForestClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

rf = RandomForestClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(rf, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.6527093596059114, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.7118226600985222, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.6724137931034483, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.665024630541872, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5714285714285714, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.6083743842364533, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.5960591133004927, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.5677339901477833, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.5443349753694582, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.7364532019704433, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.4482758620689655, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5640394088669951, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.689655172413793, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.5578817733990147, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.7561576354679803, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.729064039408867, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.7623152709359605, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.5886699507389161, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.6391625615763548, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.7068965517241378, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.7019704433497537, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.6945812807881773, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.7167487684729065, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.6280788177339902, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.6379310344827587, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.625615763546798, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.3793103448275862, Precision: 0.18181818181818182, Recall: 0.14285714285714285, F1-score: 0.16
Testing parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.6268472906403941, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.5738916256157636, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.623152709359606, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.5960591133004927, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.7487684729064039, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.5172413793103449, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6280788177339902, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.7364532019704433, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.6416256157635468, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.47044334975369456, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.6798029556650247, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5357142857142856, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.7216748768472907, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.5935960591133006, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.7413793103448275, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 2, 'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6083743842364533, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.5517241379310345, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6502463054187192, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.5197044334975369, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 73, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.8066502463054187, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.6219211822660099, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.8275862068965517, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.5640394088669951, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.7266009852216749, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.602216748768473, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6896551724137931, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.6847290640394088, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 16, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.6379310344827587, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.7167487684729064, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.6157635467980296, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.7266009852216748, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.605911330049261, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.5665024630541872, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.70935960591133, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.603448275862069, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 2, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.8300492610837438, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.6798029556650246, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.6354679802955665, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.7807881773399015, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Best AUC: 0.853448275862069
Best parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}

In [82]:
model = RandomForestClassifier(**best_params, random_state = 42)

In [83]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)
    


            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6, Accuracy: 0.813953488372093, Balanced Accuracy: 0.7142857142857143

# XGBoost

In [84]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [85]:
param_grid

{'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.3],
 'gamma': [0, 0.1, 0.15, 0.25, 0.5],
 'max_depth': [6, 8, 10, 12, 15],
 'subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'colsample_bylevel': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'colsample_bytree': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'min_child_weight': [0.5, 1.0, 3.0, 5.0, 7.0, 10.0],
 'estimators': [50, 100, 200],
 'scale_pos_weight': [2.0714285714285716]}

In [86]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'learning_rate': np.random.choice(param_grid['learning_rate']),
            'gamma': np.random.choice(param_grid['gamma']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'subsample': np.random.choice(param_grid['subsample']),
            'colsample_bylevel': np.random.choice(param_grid['colsample_bylevel']),
            'colsample_bytree': np.random.choice(param_grid['colsample_bytree']),
            'min_child_weight': np.random.choice(param_grid['min_child_weight']),
            'estimators': np.random.choice(param_grid['estimators']),
            'scale_pos_weight': np.random.choice(param_grid['scale_pos_weight'])
        }
        print(f"Testing parameters: {params}")
        pipeline = XGBClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

xgb = XGBClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(xgb, X_new, y, group, param_grid, n_iter = 500)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783251, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497538, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05172413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4285714285714286, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374385, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11576354679802957, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08866995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965518, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08620689655172414, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8571428571428572, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137934, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807883, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270935, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09359605911330053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07635467980295566, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1108374384236453, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266014, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497537, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10714285714285715, Precision: 0.09375, Recall: 0.21428571428571427, F1-score: 0.13043478260869562
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6834975369458128, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.049261083743842374, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06157635467980298, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325123, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6416256157635468, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6145320197044335, Precision: 0.16666666666666666, Recall: 0.07142857142857142, F1-score: 0.1
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08866995073891627, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5467980295566502, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0788177339901478, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08004926108374387, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.025862068965517244, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08374384236453203, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.874384236453202, Precision: 0.6666666666666666, Recall: 0.8571428571428571, F1-score: 0.75
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.059113300492610835, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10960591133004931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5431034482758621, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.25, Recall: 0.5714285714285714, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.689655172413793, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17364532019704432, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.013546798029556653, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2943349753694581, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699508, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11576354679802955, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3830049261083744, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.810344827586207, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.056650246305418726, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.018472906403940885, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655173, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8497536945812807, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369457, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266014, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8719211822660099, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990147, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05418719211822662, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04679802955665025, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.025862068965517244, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04556650246305415, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11083743842364534, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.25, Recall: 0.5714285714285714, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497537, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7032019704433498, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142856, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605911, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07142857142857145, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06403940886699509, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546797, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.061576354679802964, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.083743842364532, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1059113300492611, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23522167487684728, Precision: 0.14285714285714285, Recall: 0.14285714285714285, F1-score: 0.14285714285714285
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05172413793103449, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157636, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.14901477832512322, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8497536945812809, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.036945812807881784, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.24876847290640394, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.793103448275862, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197045, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08004926108374387, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965518, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07389162561576355, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325123, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.024630541871921173, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8916256157635468, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11822660098522168, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.665024630541872, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.748768472906404, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11083743842364532, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20689655172413796, Precision: 0.16666666666666666, Recall: 0.07142857142857142, F1-score: 0.1
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.731527093596059, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11330049261083744, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.025862068965517244, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1231527093596059, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8793103448275862, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07389162561576357, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.665024630541872, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09482758620689655, Precision: 0.1, Recall: 0.21428571428571427, F1-score: 0.13636363636363638
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009851, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09482758620689655, Precision: 0.1, Recall: 0.21428571428571427, F1-score: 0.13636363636363638
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029557, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1539408866995074, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.710591133004926, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940886, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093595, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.013546798029556653, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990147, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04926108374384237, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9088669950738917, Precision: 0.7058823529411765, Recall: 0.8571428571428571, F1-score: 0.7741935483870968
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.768472906403941, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.025862068965517244, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502463, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5443349753694582, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11330049261083745, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08743842364532022, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438404, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807883, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.810344827586207, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3633004926108374, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08374384236453203, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655173, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137932, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10591133004926107, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2795566502463054, Precision: 0.22580645161290322, Recall: 0.5, F1-score: 0.3111111111111111
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04064039408866996, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172414, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172413, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.025862068965517244, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0665024630541872, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783251, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.7058823529411765, Recall: 0.8571428571428571, F1-score: 0.7741935483870968
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.046798029556650245, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12438423645320196, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17733990147783252, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2795566502463054, Precision: 0.22580645161290322, Recall: 0.5, F1-score: 0.3111111111111111
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.044334975369458136, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09852216748768475, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.038177339901477834, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06403940886699509, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5480295566502463, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.79064039408867, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08004926108374387, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5320197044334976, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10344827586206898, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.187192118226601, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.768472906403941, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8017241379310345, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605911, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06157635467980296, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625615, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11576354679802955, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11083743842364532, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5689655172413793, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3879310344827586, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10098522167487683, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.874384236453202, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04926108374384237, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12438423645320196, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13054187192118227, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04926108374384237, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.28940886699507384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23522167487684728, Precision: 0.14285714285714285, Recall: 0.14285714285714285, F1-score: 0.14285714285714285
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08990147783251233, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093595, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014778, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03448275862068967, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940886, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8497536945812808, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502464, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.24507389162561574, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965518, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13054187192118227, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Best AUC: 0.9088669950738917
Best parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

In [87]:
model = XGBClassifier(**best_params, random_state = 42)

In [88]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train, y_train)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9088669950738917, Precision: 0.7058823529411765, Recall: 0.8571428571428571, F1-score: 0.7741935483870968, Accuracy: 0.8372093023255814, Balanced Accuracy: 0.8423645320197044

# XGBoost + SMOTE

In [89]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler, 1]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [90]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'learning_rate': np.random.choice(param_grid['learning_rate']),
            'gamma': np.random.choice(param_grid['gamma']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'subsample': np.random.choice(param_grid['subsample']),
            'colsample_bylevel': np.random.choice(param_grid['colsample_bylevel']),
            'colsample_bytree': np.random.choice(param_grid['colsample_bytree']),
            'min_child_weight': np.random.choice(param_grid['min_child_weight']),
            'estimators': np.random.choice(param_grid['estimators']),
            'scale_pos_weight': np.random.choice(param_grid['scale_pos_weight'])
        }
        print(f"Testing parameters: {params}")
        pipeline = XGBClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

xgb = XGBClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(xgb, X_new, y, group, param_grid, n_iter = 1000)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497537, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7660098522167488, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5615763546798029, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5467980295566502, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369457, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7142857142857143, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6539408866995073, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4642857142857143, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753694, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5689655172413792, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.41379310344827586, Recall: 0.8571428571428571, F1-score: 0.5581395348837208
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349754, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394088, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965518, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162562, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.795566502463054, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4963054187192118, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6551724137931034, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6490147783251231, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.770935960591133, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5455665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083743, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5665024630541872, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6711822660098522, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.42241379310344823, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5591133004926109, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.770935960591133, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5615763546798029, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679802, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167487, Precision: 0.5, Recall: 0.8571428571428571, F1-score: 0.631578947368421
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6366995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.541871921182266, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.20073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216749, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630543, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7931034482758621, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502462, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7142857142857143, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325122, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.687192118226601, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216749, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650246, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5899014778325122, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5665024630541873, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216749, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7204433497536946, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4938423645320197, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630542, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.28201970443349755, Precision: 0.125, Recall: 0.14285714285714285, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6366995073891626, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837438, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.22906403940886697, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8054187192118226, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783251, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8177339901477834, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221676, Precision: 0.6, Recall: 0.8571428571428571, F1-score: 0.7058823529411764
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246304, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162561, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.28201970443349755, Precision: 0.125, Recall: 0.14285714285714285, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.70935960591133, Precision: 0.5454545454545454, Recall: 0.8571428571428571, F1-score: 0.6666666666666665
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546797, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014778, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5554187192118227, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.41009852216748766, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142858, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5135467980295566, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.28201970443349755, Precision: 0.125, Recall: 0.14285714285714285, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7536945812807883, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477831, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.42857142857142855, Recall: 0.8571428571428571, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187193, Precision: 0.39285714285714285, Recall: 0.7857142857142857, F1-score: 0.5238095238095237
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5862068965517242, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832511, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.39285714285714285, Recall: 0.7857142857142857, F1-score: 0.5238095238095237
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7118226600985221, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852216, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059114, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5738916256157636, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7290640394088671, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679802, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7019704433497537, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8275862068965517, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965518, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.665024630541872, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.4444444444444444, Recall: 0.8571428571428571, F1-score: 0.5853658536585367
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527094, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246304, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6650246305418719, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5517241379310345, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.44581280788177347, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6650246305418719, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.539408866995074, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502463, Precision: 0.5454545454545454, Recall: 0.8571428571428571, F1-score: 0.6666666666666665
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5307881773399015, Precision: 0.4, Recall: 0.8571428571428571, F1-score: 0.5454545454545455
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.30434782608695654, Recall: 0.5, F1-score: 0.3783783783783784
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7660098522167488, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453201, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6379310344827587, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369457, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.3870967741935484, Recall: 0.8571428571428571, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5295566502463054, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374385, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423645, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6305418719211823, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5455665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246304, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5862068965517242, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4002463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.4444444444444444, Recall: 0.8571428571428571, F1-score: 0.5853658536585367
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.564039408866995, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7931034482758621, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7339901477832512, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.79064039408867, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906405, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7339901477832512, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5862068965517242, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7931034482758621, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.43333333333333335, Recall: 0.9285714285714286, F1-score: 0.5909090909090909
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.41935483870967744, Recall: 0.9285714285714286, F1-score: 0.5777777777777778
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6083743842364532, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679802, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472906, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.770935960591133, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211822, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630543, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.42610837438423643, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4913793103448276, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674878, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5, Recall: 0.9285714285714286, F1-score: 0.65
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655171, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7931034482758621, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320198, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192119, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423645, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270935, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172414, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7660098522167488, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6551724137931034, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783251, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.772167487684729, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.689655172413793, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6317733990147784, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7894088669950738, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5972906403940887, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162562, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.6, Recall: 0.8571428571428571, F1-score: 0.7058823529411764
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5972906403940887, Precision: 0.3333333333333333, Recall: 0.6428571428571429, F1-score: 0.43902439024390244
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502462, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.708128078817734, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8177339901477833, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753696, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6773399014778325, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5899014778325122, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935962, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6034482758620691, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502462, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5738916256157636, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246304, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.79064039408867, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.24753694581280788, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704434, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753693, Precision: 0.3870967741935484, Recall: 0.8571428571428571, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502462, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6416256157635468, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.41256157635467977, Precision: 0.25806451612903225, Recall: 0.5714285714285714, F1-score: 0.35555555555555557
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.768472906403941, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6921182266009852, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753694, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7118226600985221, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.79064039408867, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.731527093596059, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093595, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5517241379310345, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325122, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689656, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5886699507389163, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034484, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5541871921182266, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.45073891625615764, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.32389162561576357, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704433, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.770935960591133, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349754, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5899014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7376847290640395, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7118226600985222, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.39408866995073893, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.623152709359606, Precision: 0.3333333333333333, Recall: 0.5714285714285714, F1-score: 0.4210526315789474
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5098522167487685, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832513, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6921182266009852, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7746305418719213, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5960591133004927, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679802, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497537, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674878, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349754, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7352216748768473, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.706896551724138, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.4642857142857143, Recall: 0.9285714285714286, F1-score: 0.6190476190476191
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5270935960591133, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059113, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.520935960591133, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477831, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6403940886699507, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.748768472906404, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133005, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.646551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.604679802955665, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5911330049261084, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192117, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7536945812807883, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25985221674876846, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679802, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7894088669950738, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453203, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.45320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.8571428571428571, F1-score: 0.631578947368421
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.41009852216748766, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.31157635467980294, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325123, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4074074074074074, Recall: 0.7857142857142857, F1-score: 0.5365853658536585
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8719211822660099, Precision: 0.5714285714285714, Recall: 0.8571428571428571, F1-score: 0.6857142857142857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6083743842364532, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349754, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5640394088669951, Precision: 0.3333333333333333, Recall: 0.5714285714285714, F1-score: 0.4210526315789474
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5036945812807881, Precision: 0.34146341463414637, Recall: 1.0, F1-score: 0.5090909090909091
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7746305418719213, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6305418719211823, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4778325123152709, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6539408866995075, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295566, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4347290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.20073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650246, Precision: 0.3333333333333333, Recall: 1.0, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448275, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837438, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6366995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.48, Recall: 0.8571428571428571, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8275862068965518, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.646551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502462, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059115, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192119, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955666, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704434, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5394088669950738, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5615763546798029, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8091133004926108, Precision: 0.5714285714285714, Recall: 0.8571428571428571, F1-score: 0.6857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.623152709359606, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236452, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.874384236453202, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7881773399014779, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630542, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.631578947368421, Recall: 0.8571428571428571, F1-score: 0.7272727272727273
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6625615763546798, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349754, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8719211822660099, Precision: 0.6666666666666666, Recall: 0.8571428571428571, F1-score: 0.75
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827586, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5899014778325122, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5714285714285714, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7586206896551724, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369457, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394089, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6564039408866995, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502463, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162562, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7118226600985222, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.625615763546798, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142856, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6490147783251231, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8571428571428572, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.31157635467980294, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.631578947368421, Recall: 0.8571428571428571, F1-score: 0.7272727272727273
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729065, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369458, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.48275862068965514, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4778325123152709, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7746305418719213, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906403, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5985221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5886699507389163, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5320197044334976, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783251, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527094, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25985221674876846, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7536945812807881, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.34782608695652173, Recall: 0.5714285714285714, F1-score: 0.4324324324324324
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.646551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270935, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6736453201970444, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.731527093596059, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8645320197044335, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6391625615763548, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837438, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7142857142857143, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6514778325123152, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394088, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.583743842364532, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5714285714285714, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5320197044334976, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6096059113300493, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8497536945812808, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6416256157635468, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7967980295566502, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6773399014778325, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729065, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783251, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5935960591133005, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.625615763546798, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857142, Precision: 0.5, Recall: 0.8571428571428571, F1-score: 0.631578947368421
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6453201970443351, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625615, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7697044334975369, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8054187192118226, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.4482758620689655, Recall: 0.9285714285714286, F1-score: 0.6046511627906977
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4766009852216749, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.624384236453202, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.5, Recall: 0.9285714285714286, F1-score: 0.65
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7746305418719213, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6798029556650246, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133005, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142857, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029556, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5246305418719213, Precision: 0.23076923076923078, Recall: 0.21428571428571427, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8472906403940887, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650246, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5899014778325122, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704433, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157635, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704433, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083744, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4630541871921182, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906403, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.48, Recall: 0.8571428571428571, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527093, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453203, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7881773399014778, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162561, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5110837438423645, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6465517241379309, Precision: 0.3333333333333333, Recall: 1.0, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246306, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059114, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704433, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6059113300492611, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7339901477832512, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374385, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.31157635467980294, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.325, Recall: 0.9285714285714286, F1-score: 0.48148148148148157
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192119, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7894088669950738, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.43333333333333335, Recall: 0.9285714285714286, F1-score: 0.5909090909090909
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083744, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349754, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.625615763546798, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7746305418719213, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679802, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423647, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522169, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Best AUC: 0.9667487684729064
Best parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

In [91]:
model = XGBClassifier(**best_params, random_state = 42)

In [92]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)

            

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857, Accuracy: 0.32558139534883723, Balanced Accuracy: 0.5

# Logistic Regression

In [103]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [104]:
from imblearn.pipeline import Pipeline as ImbPipeline

groups = group
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8472906403940887, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7660098522167488, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7315270935960592, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7315270935960593, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.812807881773399, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6970443349753693, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.70935960591133, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7044334975369458, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8078817733990148, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.687192118226601, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.70935960591133, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6970443349753696, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7807881773399015, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6798029556650246, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7019704433497537, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6748768472906403, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7586206896551724, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6773399014778326, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7019704433497537, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6847290640394088, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7438423645320197, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6822660098522167, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7118226600985222, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6871921182266011, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7389162561576355, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6748768472906403, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7142857142857143, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6798029556650246, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.6600985221674877, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6822660098522166, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7142857142857143, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6798029556650246, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7192118226600986, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.687192118226601, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7167487684729065, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6724137931034483, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7463054187192119, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6798029556650246, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7093596059113301, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.6798029556650246, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Best AUC: 0.8472906403940887
Best parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

In [105]:
best_params

{'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

In [106]:
model = linear_model.LogisticRegression()



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe

In [107]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 LogisticRegression(penalty='l1', solver='liblinear'))])

In [108]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8472906403940887, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.7894088669950738

# LR + SMOTE

In [109]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [110]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.854679802955665, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7339901477832512, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7512315270935961, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7339901477832512, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8300492610837439, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6945812807881774, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7216748768472906, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7364532019704434, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8029556650246306, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7044334975369458, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.729064039408867, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7167487684729064, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7660098522167488, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7142857142857143, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.729064039408867, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7068965517241378, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7610837438423645, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7192118226600985, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7339901477832512, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7118226600985221, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.6699507389162561, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7192118226600985, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7290640394088669, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.706896551724138, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.6847290640394088, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7118226600985222, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.729064039408867, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7093596059113301, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.6995073891625616, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.6995073891625616, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7241379310344828, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7019704433497538, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.6773399014778325, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7093596059113301, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7241379310344828, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7315270935960592, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.6379310344827586, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.7142857142857144, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.7290640394088671, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.7438423645320197, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Best AUC: 0.854679802955665
Best parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

In [111]:
model = linear_model.LogisticRegression()



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 LogisticRegression(penalty='l1', solver='liblinear'))])

In [112]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)
            


    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8694581280788177, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001, Accuracy: 0.7674418604651163, Balanced Accuracy: 0.7721674876847291

# k-NN

In [113]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier
    



from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7869458128078818, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7869458128078818, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8460591133004927, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8953201970443351, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6527093596059113, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6551724137931035, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5800492610837438, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5899014778325122, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5738916256157635, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5935960591133005, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5258620689655172, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5591133004926108, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9298029556650245, Precision: 1.0, Recall: 0.8571428571428571, F1-score: 0.923076923076923
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9347290640394088, Precision: 1.0, Recall: 0.8571428571428571, F1-score: 0.923076923076923
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8312807881773399, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.791871921182266, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5985221674876847, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6059113300492611, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5812807881773399, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5960591133004927, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.4938423645320197, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5369458128078817, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9125615763546798, Precision: 1.0, Recall: 0.35714285714285715, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9211822660098523, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7389162561576355, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7635467980295567, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5738916256157636, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5874384236453201, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5394088669950738, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5541871921182266, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.49630541871921174, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5295566502463054, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8608374384236452, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8990147783251232, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7068965517241379, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7413793103448276, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5665024630541872, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216

Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5812807881773399, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5123152709359606, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5123152709359605, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.4729064039408867, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.4938423645320197, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8805418719211823, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8965517241379312, Precision: 1.0, Recall: 0.7142857142857143, F1-score: 0.8333333333333333
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7389162561576356, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5578817733990148, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5738916256157636, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5012315270935961, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.519704433497537, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.4556650246305419, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.49014778325123154, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8879310344827586, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9137931034482759, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7610837438423645, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5701970443349754, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5874384236453203, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.4938423645320197, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5123152709359606, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.48152709359605916, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.49507389162561577, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8903940886699507, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9162561576354681, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.772167487684729, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7758620689655171, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5874384236453203, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5763546798029557, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.48152709359605916, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5073891625615764, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.48522167487684725, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5073891625615764, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8645320197044335, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8940886699507389, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.810344827586207, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8226600985221675, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5788177339901478, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5775862068965517, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.4839901477832512, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.49507389162561577, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.4532019704433498, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.46059113300492616, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523

Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8842364532019703, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9211822660098522, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7733990147783252, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7980295566502463, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5221674876847291, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5369458128078818, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.45935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.4753694581280788, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.40024630541871925, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.4039408866995074, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9014778325123153, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9236453201970443, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7463054187192119, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7758620689655172, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5541871921182265, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5689655172413793, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.4605911330049261, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.4753694581280788, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.42980295566502463, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.4433497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8879310344827587, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9014778325123153, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6982758620689655, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7315270935960592, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5110837438423645, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5295566502463054, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.46182266009852213, Precision: 0.16666666666666666, Recall: 0.07142857142857142, F1-score: 0.1
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.4753694581280788, Precision: 0.16666666666666666, Recall: 0.07142857142857142, F1-score: 0.1
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.42487684729064035, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8596059113300493, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8842364532019705, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7068965517241379, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.4913793103448276, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5073891625615763, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.43842364532019706, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.46798029556650245, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.4137931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.42610837438423643, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8620689655172413, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8916256157635468, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6711822660098522, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7068965517241379, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.4987684729064039, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5172413793103449, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125

Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.45566502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.4704433497536946, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.4211822660098522, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.44581280788177335, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8460591133004927, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8793103448275863, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6748768472906403, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7019704433497537, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.49137931034482757, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.5098522167487685, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.458128078817734, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.47044334975369456, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.437192118226601, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.4408866995073891, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Best AUC: 0.9347290640394088
Best parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}

In [114]:
best_score

0.9347290640394088

In [115]:
best_params

{'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}

In [116]:
model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe

In [117]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 KNeighborsClassifier(n_neighbors=3, p=1, weights='distance'))])

In [118]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9347290640394088, Precision: 1.0, Recall: 0.8571428571428571, F1-score: 0.923076923076923, Accuracy: 0.9534883720930233, Balanced Accuracy: 0.9285714285714286

# k-NN + SMOTE

In [119]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np


param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier
    



from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8238916256157635, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8054187192118227, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6490147783251231, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5960591133004927, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5615763546798029, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8460591133004927, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.855911330049261, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.5997536945812807, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6600985221674878, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.583743842364532, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6305418719211824, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5689655172413792, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6280788177339901, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6059113300492611, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5948275862068966, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.874384236453202, Precision: 0.6190476190476191, Recall: 0.9285714285714286, F1-score: 0.742857142857143
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8830049261083744, Precision: 0.5909090909090909, Recall: 0.9285714285714286, F1-score: 0.7222222222222223
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7204433497536946, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.602216748768473, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6354679802955665, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.623152709359606, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6502463054187193, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6133004926108374, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6083743842364532, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8940886699507389, Precision: 0.6842105263157895, Recall: 0.9285714285714286, F1-score: 0.7878787878787878
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.916256157635468, Precision: 0.6842105263157895, Recall: 0.9285714285714286, F1-score: 0.7878787878787878
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7364532019704433, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8078817733990148, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6773399014778325, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.603448275862069, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6120689655172414, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.624384236453202, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6071428571428572, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6576354679802956, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9199507389162562, Precision: 0.7647058823529411, Recall: 0.9285714285714286, F1-score: 0.8387096774193549
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9408866995073892, Precision: 0.7222222222222222, Recall: 0.9285714285714286, F1-score: 0.8125000000000001
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8435960591133005, Precision: 0.48, Recall: 0.8571428571428571, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.8571428571428571, F1-score: 0.631578947368421

Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.645320197044335, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6600985221674877, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6748768472906405, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6330049261083744, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5997536945812808, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5812807881773399, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9630541871921182, Precision: 0.75, Recall: 0.8571428571428571, F1-score: 0.7999999999999999
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9458128078817734, Precision: 0.6666666666666666, Recall: 0.8571428571428571, F1-score: 0.75
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8312807881773399, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8017241379310345, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6576354679802957, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6724137931034484, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6280788177339902, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5825123152709359, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5960591133004927, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6773399014778325, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9396551724137931, Precision: 0.65, Recall: 0.9285714285714286, F1-score: 0.7647058823529412
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9630541871921183, Precision: 0.65, Recall: 0.9285714285714286, F1-score: 0.7647058823529412
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7758620689655172, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7931034482758621, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6293103448275862, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6748768472906405, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6576354679802956, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.665024630541872, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5948275862068966, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5911330049261084, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9753694581280787, Precision: 0.65, Recall: 0.9285714285714286, F1-score: 0.7647058823529412
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9704433497536946, Precision: 0.6086956521739131, Recall: 1.0, F1-score: 0.7567567567567568
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.791871921182266, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.854679802955665, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.669950738916256, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6354679802955664, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6403940886699508, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.645320197044335, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5997536945812808, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6157635467980296, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9421182266009852, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.960591133004926, Precision: 0.5384615384615384, Recall: 1.0, F1-score: 0.7000000000000001
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8325123152709359, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.854679802955665, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6933497536945814, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6514778325123152, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6120689655172413, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.562807881773399, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865

Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5726600985221675, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5911330049261083, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9568965517241379, Precision: 0.65, Recall: 0.9285714285714286, F1-score: 0.7647058823529412
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9556650246305419, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8620689655172414, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8472906403940887, Precision: 0.48, Recall: 0.8571428571428571, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6379310344827586, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6945812807881774, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5726600985221675, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6009852216748769, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5763546798029557, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5935960591133005, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9064039408866995, Precision: 0.5454545454545454, Recall: 0.8571428571428571, F1-score: 0.6666666666666665
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9384236453201971, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8472906403940887, Precision: 0.5, Recall: 0.8571428571428571, F1-score: 0.631578947368421
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8669950738916257, Precision: 0.52, Recall: 0.9285714285714286, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7302955665024631, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6699507389162561, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6096059113300493, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6219211822660098, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5911330049261084, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6133004926108375, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.937192118226601, Precision: 0.5714285714285714, Recall: 0.8571428571428571, F1-score: 0.6857142857142857
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9753694581280788, Precision: 0.6190476190476191, Recall: 0.9285714285714286, F1-score: 0.742857142857143
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8596059113300493, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8374384236453203, Precision: 0.5909090909090909, Recall: 0.9285714285714286, F1-score: 0.7222222222222223
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6576354679802956, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6625615763546798, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.604679802955665, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6083743842364532, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5344827586206897, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5862068965517242, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9248768472906403, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9507389162561577, Precision: 0.5384615384615384, Recall: 1.0, F1-score: 0.7000000000000001
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8251231527093595, Precision: 0.5, Recall: 0.8571428571428571, F1-score: 0.631578947368421
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8054187192118227, Precision: 0.52, Recall: 0.9285714285714286, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6551724137931034, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6576354679802957, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5825123152709359, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6157635467980296, Precision: 0.35714285714285715, Recall: 0.7142857142857143, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5554187192118226, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5541871921182266, Precision: 0.35714285714285715, Recall: 0.7142857142857143, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9766009852216748, Precision: 0.5833333333333334, Recall: 1.0, F1-score: 0.7368421052631579
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9679802955665024, Precision: 0.5, Recall: 0.9285714285714286, F1-score: 0.65

Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.833743842364532, Precision: 0.5217391304347826, Recall: 0.8571428571428571, F1-score: 0.6486486486486486
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8251231527093597, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6231527093596059, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6945812807881774, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6059113300492611, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6305418719211823, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5628078817733991, Precision: 0.36, Recall: 0.6428571428571429, F1-score: 0.4615384615384615
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5443349753694581, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9298029556650246, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9408866995073892, Precision: 0.5185185185185185, Recall: 1.0, F1-score: 0.6829268292682926
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8399014778325122, Precision: 0.4444444444444444, Recall: 0.8571428571428571, F1-score: 0.5853658536585367
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8497536945812808, Precision: 0.5, Recall: 0.9285714285714286, F1-score: 0.65
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6256157635467979, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6822660098522169, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5295566502463054, Precision: 0.32142857142857145, Recall: 0.6428571428571429, F1-score: 0.4285714285714286
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6009852216748768, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5431034482758621, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5862068965517241, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Best AUC: 0.9766009852216748
Best parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}

In [120]:
best_params

{'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}

In [121]:
model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model', KNeighborsClassifier(n_neighbors=14, p=1))])

In [122]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)
            


    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9236453201970444, Precision: 0.5652173913043478, Recall: 0.9285714285714286, F1-score: 0.7027027027027025, Accuracy: 0.7441860465116279, Balanced Accuracy: 0.791871921182266

# SVM

In [123]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6798029556650246, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.583743842364532, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.623152709359606, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666

Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6009852216748768, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.19458128078817732, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4729064039408867, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.665024630541872, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857

Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.004926108374384238, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.09113300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Best AUC: 0.7586206896551724
Best parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}

In [124]:
best_params

{'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}

In [125]:
best_score

0.7586206896551724

In [126]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
pipeline = pipe

In [127]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('clf',
                 SVC(C=0.1, degree=0, gamma=0.1, kernel='linear',
                     probability=True, random_state=100))])

In [128]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.7524630541871922

# SVM + SMOTE

In [129]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2463054187192118, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7783251231527093, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2770935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7487684729064039, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.27463054187192115, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7463054187192119, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7684729064039408, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2573891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7389162561576355, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167487, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2881773399014778, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7610837438423647, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7413793103448276, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7536945812807883, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.28694581280788173, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7536945812807881, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2561576354679803, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5049261083743842, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7536945812807881, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.28201970443349755, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5344827586206897, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7561576354679804, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.28694581280788173, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7167487684729064, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27216748768472904, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6995073891625616, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7512315270935961, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2561576354679803, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5960591133004927, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7413793103448276, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.28201970443349755, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7758620689655172, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.28940886699507384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6477832512315271, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7512315270935961, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.28940886699507384, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5862068965517242, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.24507389162561574, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.3596059113300493, Precision: 0.29411764705882354, Recall: 0.7142857142857143, F1-score: 0.4166666666666667
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7635467980295566, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6059113300492611, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.27709359605911327, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6083743842364532, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7413793103448276, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27216748768472904, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5344827586206896, Precision: 0.3333333333333333, Recall: 0.7857142857142857, F1-score: 0.4680851063829786
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7315270935960592, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27586206896551724, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.3472906403940887, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7660098522167488, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.27463054187192115, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.44827586206896547, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7561576354679803, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.16666666666666666, Recall: 0.07142857142857142, F1-score: 0.1
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4704433497536945, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7487684729064039, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22044334975369456, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.325, Recall: 0.9285714285714286, F1-score: 0.48148148148148157
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7758620689655173, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27339901477832507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.46305418719211827, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7660098522167489, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2844827586206896, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5541871921182266, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7463054187192117, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27463054187192115, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5517241379310345, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.26354679802955666, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7561576354679803, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7758620689655172, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5123152709359606, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.44704433497536944, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7733990147783252, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.37684729064039413, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7733990147783251, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7536945812807881, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.32142857142857145, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7487684729064039, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7413793103448276, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4014778325123153, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.31773399014778325, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5517241379310345, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7807881773399015, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.269704433497537, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6428571428571428, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3238916256157635, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6871921182266011, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5960591133004927, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7364532019704434, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3152709359605911, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6133004926108375, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7783251231527093, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.45443349753694584, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6354679802955665, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7536945812807883, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.25, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6305418719211823, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7463054187192119, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3497536945812808, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6576354679802956, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.376847290640394, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6354679802955665, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.46921182266009853, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6403940886699507, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666

Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.43226600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6354679802955665, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7561576354679803, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4766009852216749, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7167487684729064, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7463054187192119, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.38916256157635465, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.480295566502463, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7733990147783253, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.49014778325123154, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7438423645320197, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.6650246305418719, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.541871921182266, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7463054187192119, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5689655172413793, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.748768472906404, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.38916256157635465, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5467980295566501, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7684729064039408, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.38916256157635465, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6280788177339901, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7561576354679802, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4815270935960591, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5049261083743842, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4051724137931034, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5517241379310345, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7758620689655171, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.43842364532019706, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7783251231527093, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5800492610837438, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3731527093596059, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7389162561576355, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5197044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2536945812807882, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7389162561576355, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7512315270935962, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3657635467980295, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7536945812807881, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666

Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7733990147783252, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5677339901477833, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7610837438423645, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7832512315270935, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.6280788177339902, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167488, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.1330049261083744, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6773399014778325, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4445812807881773, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6527093596059114, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7487684729064039, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3657635467980296, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7044334975369458, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7364532019704433, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6157635467980296, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7610837438423644, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4802955665024631, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6280788177339901, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7389162561576355, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4642857142857143, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7192118226600985, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7733990147783252, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3694581280788177, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6059113300492611, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7536945812807881, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5381773399014779, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.726600985221675, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.43349753694581283, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7389162561576355, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7733990147783251, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3140394088669951, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4963054187192118, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6280788177339901, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5751231527093597, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6403940886699507, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7389162561576356, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4876847290640394, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167488, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924

Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3214285714285714, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4507389162561576, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7635467980295567, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4926108374384236, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5911330049261083, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7463054187192119, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5147783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.4408866995073891, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167487, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3374384236453202, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5541871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167488, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3633004926108374, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6502463054187192, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7807881773399015, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.520935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5295566502463054, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7389162561576355, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.6379310344827586, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5935960591133005, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7733990147783251, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.28078817733990147, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7389162561576355, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.31650246305418717, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2327586206896552, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.6773399014778325, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3078817733990148, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7660098522167488, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.42241379310344834, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7536945812807881, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.47536945812807885, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7660098522167488, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4864532019704434, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.729064039408867, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4014778325123152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.645320197044335, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186

Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.42980295566502463, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6748768472906405, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.42241379310344823, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7660098522167488, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5184729064039408, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6650246305418719, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7758620689655172, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.19704433497536947, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6379310344827586, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7635467980295566, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5110837438423645, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7536945812807883, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3435960591133005, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6576354679802956, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7857142857142857, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5381773399014779, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6280788177339902, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.15517241379310343, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.748768472906404, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.43226600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6921182266009852, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.49014778325123154, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7487684729064039, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4347290640394089, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7093596059113301, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22167487684729065, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.45320197044334976, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5480295566502463, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5517241379310345, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7512315270935961, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.45320197044334976, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6157635467980296, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7561576354679803, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5172413793103449, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5541871921182266, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167488, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666

Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.27586206896551724, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5788177339901478, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2105911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5985221674876847, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7807881773399015, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.520935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.42610837438423643, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.479064039408867, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5862068965517241, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7684729064039408, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.43103448275862066, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7635467980295567, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.1982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7487684729064039, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3940886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7536945812807883, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5714285714285714, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.23399014778325122, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7561576354679804, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4310344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7463054187192119, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7660098522167489, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4642857142857143, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7339901477832513, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4211822660098523, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7586206896551725, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7536945812807883, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.41625615763546797, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7463054187192119, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6206896551724137, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7660098522167489, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.39285714285714285, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5960591133004927, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7536945812807881, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.35344827586206895, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.583743842364532, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.748768472906404, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3177339901477832, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6133004926108374, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7487684729064039, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3140394088669951, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7142857142857143, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7783251231527094, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4359605911330049, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7339901477832511, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7610837438423645, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4470443349753695, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6379310344827586, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7586206896551725, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3004926108374384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7339901477832512, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.21798029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5147783251231527, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7561576354679803, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5431034482758621, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6182266009852216, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.748768472906404, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5763546798029557, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.7660098522167489, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.26354679802955666, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.43842364532019706, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7315270935960592, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5061576354679804, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.539408866995074, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7364532019704434, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.41009852216748766, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.41379310344827586, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7438423645320198, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5578817733990147, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5270935960591133, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.770935960591133, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3448275862068966, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5911330049261084, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.7536945812807881, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.20073891625615767, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.58128078817734, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.7364532019704434, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.48645320197044334, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6009852216748768, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32

Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.7586206896551724, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3977832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5147783251231527, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Best AUC: 0.7857142857142857
Best parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}

In [130]:
best_params

{'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}

In [131]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
pipeline = pipe

In [132]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('clf',
                 SVC(C=100, gamma=100, kernel='linear', probability=True,
                     random_state=100))])

In [133]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.7660098522167489, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924, Accuracy: 0.813953488372093, Balanced Accuracy: 0.7697044334975369