In [64]:
import pandas as pd
import numpy as np
from os import listdir

In [65]:
import sklearn

In [66]:
# Ignore warnings
import warnings; warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.model_selection import ParameterGrid


from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
from sklearn import svm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

#from skbold.preproc.confounds import ConfoundRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn import preprocessing
    
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.impute import SimpleImputer



# Import libraries
import os
import numpy as np
import pandas as pd


from sklearn.feature_selection import RFE
from sklearn.metrics import balanced_accuracy_score

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn.model_selection import cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import make_scorer
from sklearn.metrics import \
    confusion_matrix, \
    accuracy_score, \
    matthews_corrcoef, \
    precision_score, \
    recall_score, \
    f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

import pymrmr

# Set the random generator seed
seed = 42

# Matplotlib settings
plt.style.use("classic")

# Seaborn settings
sns.set()
sns.set(font_scale=1.0)
sns.set_style({"font.family":"serif", "font.serif":["Times New Roman"]})

# Show seaborn settings
sns.axes_style()

{'axes.facecolor': '#EAEAF2',
 'axes.edgecolor': 'white',
 'axes.grid': True,
 'axes.axisbelow': True,
 'axes.labelcolor': '.15',
 'figure.facecolor': 'white',
 'grid.color': 'white',
 'grid.linestyle': '-',
 'text.color': '.15',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'lines.solid_capstyle': <CapStyle.round: 'round'>,
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'font.family': ['serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'xtick.bottom': False,
 'xtick.top': False,
 'ytick.left': False,
 'ytick.right': False,
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True}

In [67]:
# ------------------------------
# Define the classifier settings
# ------------------------------

model_params = {
    
    # General parameters
    "booster": "gbtree", 
    "silent": True, 
    "n_jobs": -1, 
    
    # Learning task parameters
    "objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "eval_metric": "error", 
    "seed": seed, 
    
    # Tree Booster parameters
    "n_estimators": 500, 
    "learning_rate": 0.20, 
    "gamma": 1.0, 
    "max_depth": 10, 
    "subsample": 1.0, 
    "colsample_bylevel": 1, 
    "colsample_bytree": 1.0, 
    "min_child_weight": 5
}

# ------------------------------------------
# Define the hyper-parameter tuning settings
# ------------------------------------------

param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [1, 3, 5, 6, 7, 9]  # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
#scale_pos_weight = total_negative_examples / total_positive_examples
}

search_settings = {
    "param_distributions": param_grid, 
    "scoring": "balanced_accuracy",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
}

In [68]:
# ---------------------------------
# Define the classification metrics
# ---------------------------------

def sensitivity_score(y_true, y_pred):
    return recall_score(y_true, y_pred)

def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)

In [69]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import os

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

# For models
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# For evaluation
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score

In [70]:
dataset = pd.read_csv('prob_eye_features.csv')

In [71]:
dataset

,Unnamed: 0,index,patient,record,diagnosis,timestamp_start,timestamp_end,lefteye_mid_Absolute energy,lefteye_mid_Area under the curve,lefteye_mid_Autocorrelation,...,smiling_eve_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1,smiling_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1,smiling_eve_SP_Summaries_welch_rect_centroid,smiling_eve_FC_LocalSimple_mean3_stderr,lefteye_eve_app_ent,righteye_eve_app_ent,smiling_eve_app_ent,lefteye_eve_rsd,righteye_eve_rsd,smiling_eve_rsd
0,0,0,P08,0,0,1.658354e+09,1.659996e+09,159.815202,1.754196,1.0,...,0.142857,0.775510,0.133456,0.731912,1.109208,1.273205,0.903131,31.248418,34.398221,161.223253
1,1,0,P08,1,0,1.659996e+09,1.661206e+09,2994.914034,32.251584,3.0,...,0.291667,0.145833,0.527689,0.941336,0.950498,1.165241,0.939005,30.496000,44.894973,156.000227
2,2,0,P10,2,1,1.658354e+09,1.659996e+09,934.998350,9.668103,1.0,...,0.333333,0.166667,0.285320,0.769152,0.649302,1.101207,0.211475,29.254278,47.014199,308.947966
3,3,0,P10,3,0,1.659996e+09,1.662070e+09,796.366897,9.202542,2.0,...,0.163265,0.877551,0.061359,0.511171,0.966557,1.240839,0.324205,44.624507,58.077534,246.734071
4,4,0,P12,4,1,1.658441e+09,1.659996e+09,47.911319,0.690634,1.0,...,0.790698,0.860465,0.662680,0.998367,0.938760,0.973181,0.404289,44.966219,47.288089,233.670461
5,5,0,P12,5,1,1.659996e+09,1.661206e+09,56.150528,0.624009,1.0,...,0.857143,0.738095,0.490874,0.878668,0.843667,0.936040,0.614584,29.475036,30.276012,185.631759
6,6,0,P13,6,0,1.658700e+09,1.659996e+09,3223.834261,32.655868,1.0,...,0.244898,0.857143,0.131155,0.653258,0.362176,0.705464,0.296124,16.339966,20.764821,292.398782
7,7,0,P13,7,0,1.659996e+09,1.661206e+09,239.778514,2.417260,1.0,...,0.853659,0.853659,0.392699,0.868253,0.255308,0.380562,0.414977,19.979949,15.211448,184.687507
8,8,0,P14,8,0,1.658700e+09,1.659910e+09,125.931396,1.407684,3.0,...,0.306122,0.877551,0.319068,0.859923,1.101882,0.904987,1.084499,42.789612,34.070540,137.389819
9,9,0,P15,9,0,1.658786e+09,1.660082e+09,NaN,NaN,NaN,...,0.326531,0.877551,0.161068,0.711376,1.208809,1.456139,0.330840,46.953204,49.437349,286.834391
10,10,0,P15,10,1,1.660082e+09,1.661206e+09,148.221916,2.365285,3.0,...,0.326531,0.877551,0.122718,0.585557,1.364536,1.475528,0.383828,59.648103,65.863117,233.048602
11,11,0,P16,11,0,1.658873e+09,1.659996e+09,5588.553399,62.150725,50.0,...,0.320000,0.780000,0.088204,0.595745,0.762125,0.835477,0.332558,30.701462,24.094999,297.095150
12,12,0,P16,12,0,1.659996e+09,1.661206e+09,5845.796135,62.812529,4.0,...,0.380000,0.580000,0.130772,0.669807,0.852456,0.884501,0.405318,29.720287,24.592209,274.993422
13,13,0,P17,13,1,1.658786e+09,1.659996e+09,615.099315,6.301963,1.0,...,0.270833,0.125000,0.273049,0.844975,1.048595,1.188359,1.156473,37.329703,55.659185,111.339240
14,14,0,P18,14,1,1.658873e+09,1.659996e+09,1131.708123,13.521887,21.0,...,0.122449,0.122449,0.072097,0.669549,1.096102,1.123428,0.781109,75.955618,82.369563,141.626699
15,15,0,P18,15,1,1.659996e+09,1.661206e+09,1050.551582,12.762046,5.0,...,0.877551,0.306122,0.111981,0.759323,1.076727,1.201481,1.019533,74.765557,69.809124,135.728765
16,16,0,P19,16,1,1.658873e+09,1.660255e+09,785.233486,8.650786,8.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
17,17,0,P19,17,1,1.660255e+09,1.661897e+09,166.931668,2.160410,8.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
18,18,0,P20,18,0,1.658786e+09,1.660082e+09,619.511367,6.606506,4.0,...,0.520833,0.125000,0.134990,0.616732,0.964032,1.175585,0.672123,35.691050,50.930992,166.231026
19,19,0,P20,19,0,1.660082e+09,1.661810e+09,458.245990,5.044652,5.0,...,0.787234,0.872340,0.362019,0.860334,0.934679,1.322405,0.460527,35.978999,60.945181,200.804377
20,20,0,P21,20,0,1.658959e+09,1.660169e+09,956.519423,11.600969,11.0,...,0.244898,0.877551,0.055223,0.556824,0.771458,0.770246,0.250172,39.932150,61.830751,294.667954
21,21,0,P21,21,1,1.660169e+09,1.661810e+09,318.133891,3.996044,24.0,...,0.551020,0.551020,0.064427,0.557014,0.898230,1.002707,0.295885,37.067773,42.618275,264.953752
22,22,0,P23,22,0,1.659046e+09,1.660255e+09,1557.863100,16.062215,2.0,...,0.571429,0.469388,0.061359,0.565418,0.538977,1.348448,0.378350,17.078093,33.430416,223.986300
23,23,0,P23,23,0,1.660255e+09,1.661810e+09,1809.680737,19.678477,2.0,...,0.122449,0.122449,0.078233,0.665164,1.149385,1.341509,0.559583,31.562084,50.388901,184.683560
24,24,0,P24,24,1,1.659046e+09,1.660428e+09,6079.611278,64.336221,2.0,...,0.300000,0.120000,0.184845,0.776954,0.954803,1.086713,1.102212,33.204104,29.921619,131.767550
25,25,0,P24,25,1,1.660428e+09,1.661810e+09,2421.853802,25.353976,2.0,...,0.142857,0.836735,0.225495,0.793708,1.062141,1.140507,1.251668,36.384238,33.841252,109.062406
26,26,0,P25,26,0,1.660774e+09,1.661983e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
27,27,0,P27,27,0,1.660514e+09,1.661724e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
28,28,0,P28,28,0,1.660514e+09,1.663279e+09,745.251631,8.498635,2.0,...,0.183673,0.122449,0.070563,0.645212,1.437934,1.404281,0.486347,60.487154,63.429320,210.896877
29,29,0,P29,29,0,1.659305e+09,1.660255e+09,1311.915711,17.357964,32.0,...,0.591837,0.387755,0.099709,0.639630,1.278772,0.937102,0.195279,96.713766,152.161785,299.925891
30,30,0,P29,30,0,1.660255e+09,1.661810e+09,347.214901,6.649285,12.0,...,0.346939,0.122449,0.156466,0.652597,1.470113,0.929280,0.130678,99.186103,162.618464,329.444500
31,31,0,P30,31,1,1.659305e+09,1.660255e+09,3589.945864,40.884938,2.0,...,0.244898,0.122449,0.128087,0.734137,1.297072,1.257440,0.419275,57.650990,88.540594,259.259532
32,32,0,P30,32,1,1.660255e+09,1.661810e+09,2971.336252,33.418946,1.0,...,0.244898,0.877551,0.115816,0.657115,1.356120,1.263509,0.527882,61.105682,93.442520,231.886791
33,33,0,P31,33,0,1.659391e+09,1.660601e+09,281.396085,4.774415,47.0,...,0.122449,0.142857,0.182544,0.755975,1.539875,1.706212,0.466452,65.649002,62.926655,130.854432
34,34,0,P31,34,0,1.660601e+09,1.661810e+09,254.325297,3.971961,59.0,...,0.297872,0.148936,0.134990,0.643366,1.401121,0.871966,0.177829,66.772768,102.396749,259.917089
35,35,0,P33,35,0,1.659478e+09,1.660601e+09,1666.263975,18.846772,1.0,...,0.142857,0.836735,0.191748,0.769503,0.928077,1.161691,0.546959,34.968676,35.347310,199.313122
36,36,0,P33,36,0,1.660601e+09,1.662070e+09,1725.591886,19.021559,2.0,...,0.285714,0.857143,0.480136,0.906507,1.275150,1.207110,0.529577,46.807877,39.978393,210.880136
37,37,0,P34,37,0,1.659564e+09,1.660774e+09,407.595456,5.665456,5.0,...,0.125000,0.187500,0.576777,0.942715,1.257130,1.057423,0.553584,70.298913,100.433819,171.129060
38,38,0,P35,38,0,1.659564e+09,1.660774e+09,1822.229000,18.909761,1.0,...,0.551020,0.346939,0.168738,0.743202,0.883756,1.080286,0.252690,31.043004,31.412967,416.442165
39,39,0,P35,39,0,1.660774e+09,1.662070e+09,2062.923103,21.886699,4.0,...,0.326531,0.306122,0.208621,0.753538,0.873255,1.082971,0.251051,32.657172,30.336398,373.262006
40,40,0,P36,40,0,1.660860e+09,1.662070e+09,2774.319378,29.587614,2.0,...,0.653061,0.428571,0.332874,0.859071,0.985478,1.172057,1.123381,23.449370,28.764549,141.769747
41,41,0,P38,41,0,1.659564e+09,1.661206e+09,1751.929408,18.344965,1.0,...,0.265306,0.877551,0.093573,0.703637,1.010465,1.522383,0.350549,29.838800,57.584418,235.288671
42,42,0,P38,42,0,1.661206e+09,1.661983e+09,618.188985,6.426493,2.0,...,0.437500,0.479167,0.110447,0.611543,0.989792,1.248439,0.214802,45.346983,55.594797,275.951876

In [72]:
del dataset['Unnamed: 0']
del dataset['index']

In [73]:
group = dataset['patient']

In [74]:
del dataset['patient']

In [76]:
#dataset = dataset.fillna(dataset.mean())

In [77]:
y = dataset['diagnosis']

In [78]:
del dataset['diagnosis']

In [79]:
records  = dataset['record']

In [80]:
del dataset['record']

In [81]:
del dataset['timestamp_start']
del dataset['timestamp_end']

# Binary classification

# Splitting and training

# Feature selection

In [20]:
import pymrmr

In [82]:
X = dataset.copy()

In [26]:
type_classification = 'binary'



#X = X.replace([np.nan, -np.inf, np.inf], 0)
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
#y = y.reshape((len(y), ))
X.insert(loc=0, column='class', value=y)
X_to_choose = X.copy()
#Discritize data
_, nr_col = np.shape(X)
for i in range(1, nr_col):
    discretizer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='kmeans')
    X.iloc[:, i] = discretizer.fit_transform(X.iloc[:, i].values.reshape(-1,1))
    
col = pymrmr.mRMR(X, 'MIQ', 50)

# Read the data again to import data with NaN values

In [ ]:
dataset = pd.read_csv('euler_features.csv')
del dataset['Unnamed: 0']
del dataset['index']
group = dataset['patient']
groups = group
del dataset['patient']
y = dataset['diagnosis']
del dataset['diagnosis']
records  = dataset['record']
del dataset['record']
del dataset['timestamp_start']
del dataset['timestamp_end']
X = dataset.copy()

In [27]:
col

['smiling_eve_Wavelet variance_25.0Hz',
 'lefteye_mor_CO_Embed2_Dist_tau_d_expfit_meandiff',
 'righteye_eve_CO_trev_1_num',
 'smiling_mor_PD_PeriodicityWang_th0_01',
 'lefteye_aft_Wavelet variance_3.57Hz',
 'righteye_eve_Wavelet standard deviation_2.78Hz',
 'lefteye_eve_MFCC_10',
 'lefteye_mid_ECDF Percentile_0',
 'righteye_aft_MFCC_1',
 'lefteye_mid_MFCC_7',
 'smiling_mid_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1',
 'smiling_mor_MFCC_6',
 'smiling_aft_LPCC_8',
 'righteye_eve_Median diff',
 'smiling_mid_Median absolute deviation',
 'lefteye_mid_Wavelet variance_5.0Hz',
 'smiling_eve_Average power',
 'lefteye_aft_CO_f1ecac',
 'smiling_aft_MFCC_6',
 'smiling_mid_Zero crossing rate',
 'lefteye_eve_Median diff',
 'righteye_eve_Wavelet energy_4.17Hz',
 'lefteye_mor_SB_BinaryStats_diff_longstretch0',
 'lefteye_mor_Wavelet standard deviation_6.25Hz',
 'lefteye_mid_SB_TransitionMatrix_3ac_sumdiagcov',
 'lefteye_mid_CO_trev_1_num',
 'smiling_eve_ECDF Percentile_1',
 'smiling_mid_MFCC_9',
 'lefteye_eve_Wavelet variance_8.33Hz',
 'smiling_mid_Interquartile range',
 'lefteye_aft_SB_BinaryStats_diff_longstretch0',
 'lefteye_mid_Wavelet variance_4.17Hz',
 'smiling_eve_Wavelet variance_6.25Hz',
 'righteye_mor_Spectral entropy',
 'smiling_mid_ECDF Percentile_0',
 'smiling_mid_Wavelet standard deviation_3.12Hz',
 'righteye_eve_Wavelet standard deviation_3.57Hz',
 'smiling_mid_Max power spectrum',
 'lefteye_aft_Wavelet variance_3.12Hz',
 'smiling_mid_Median',
 'smiling_aft_LPCC_0',
 'lefteye_mor_Wavelet variance_6.25Hz',
 'righteye_eve_Wavelet variance_12.5Hz',
 'righteye_eve_Wavelet energy_3.57Hz',
 'smiling_mid_Median absolute diff',
 'righteye_mor_Median absolute diff',
 'smiling_aft_MFCC_11',
 'lefteye_mor_MFCC_0',
 'smiling_eve_Wavelet absolute mean_25.0Hz',
 'smiling_aft_MFCC_3']

In [83]:
col = ['smiling_eve_Wavelet variance_25.0Hz',
 'lefteye_mor_CO_Embed2_Dist_tau_d_expfit_meandiff',
 'righteye_eve_CO_trev_1_num',
 'smiling_mor_PD_PeriodicityWang_th0_01',
 'lefteye_aft_Wavelet variance_3.57Hz',
 'righteye_eve_Wavelet standard deviation_2.78Hz',
 'lefteye_eve_MFCC_10',
 'lefteye_mid_ECDF Percentile_0',
 'righteye_aft_MFCC_1',
 'lefteye_mid_MFCC_7',
 'smiling_mid_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1',
 'smiling_mor_MFCC_6',
 'smiling_aft_LPCC_8',
 'righteye_eve_Median diff',
 'smiling_mid_Median absolute deviation',
 'lefteye_mid_Wavelet variance_5.0Hz',
 'smiling_eve_Average power',
 'lefteye_aft_CO_f1ecac',
 'smiling_aft_MFCC_6',
 'smiling_mid_Zero crossing rate',
 'lefteye_eve_Median diff',
 'righteye_eve_Wavelet energy_4.17Hz',
 'lefteye_mor_SB_BinaryStats_diff_longstretch0',
 'lefteye_mor_Wavelet standard deviation_6.25Hz',
 'lefteye_mid_SB_TransitionMatrix_3ac_sumdiagcov',
 'lefteye_mid_CO_trev_1_num',
 'smiling_eve_ECDF Percentile_1',
 'smiling_mid_MFCC_9',
 'lefteye_eve_Wavelet variance_8.33Hz',
 'smiling_mid_Interquartile range',
 'lefteye_aft_SB_BinaryStats_diff_longstretch0',
 'lefteye_mid_Wavelet variance_4.17Hz',
 'smiling_eve_Wavelet variance_6.25Hz',
 'righteye_mor_Spectral entropy',
 'smiling_mid_ECDF Percentile_0',
 'smiling_mid_Wavelet standard deviation_3.12Hz',
 'righteye_eve_Wavelet standard deviation_3.57Hz',
 'smiling_mid_Max power spectrum',
 'lefteye_aft_Wavelet variance_3.12Hz',
 'smiling_mid_Median',
 'smiling_aft_LPCC_0',
 'lefteye_mor_Wavelet variance_6.25Hz',
 'righteye_eve_Wavelet variance_12.5Hz',
 'righteye_eve_Wavelet energy_3.57Hz',
 'smiling_mid_Median absolute diff',
 'righteye_mor_Median absolute diff',
 'smiling_aft_MFCC_11',
 'lefteye_mor_MFCC_0',
 'smiling_eve_Wavelet absolute mean_25.0Hz',
 'smiling_aft_MFCC_3']

In [84]:
X_new = X[col]

In [85]:
X_new = X_new.astype(float)

In [86]:
X_new

,smiling_eve_Wavelet variance_25.0Hz,lefteye_mor_CO_Embed2_Dist_tau_d_expfit_meandiff,righteye_eve_CO_trev_1_num,smiling_mor_PD_PeriodicityWang_th0_01,lefteye_aft_Wavelet variance_3.57Hz,righteye_eve_Wavelet standard deviation_2.78Hz,lefteye_eve_MFCC_10,lefteye_mid_ECDF Percentile_0,righteye_aft_MFCC_1,lefteye_mid_MFCC_7,...,smiling_aft_LPCC_0,lefteye_mor_Wavelet variance_6.25Hz,righteye_eve_Wavelet variance_12.5Hz,righteye_eve_Wavelet energy_3.57Hz,smiling_mid_Median absolute diff,righteye_mor_Median absolute diff,smiling_aft_MFCC_11,lefteye_mor_MFCC_0,smiling_eve_Wavelet absolute mean_25.0Hz,smiling_aft_MFCC_3
0,0.005162,0.171183,0.113936,101.0,0.119674,0.425248,77.774687,0.755065,-19.797042,25.861420,...,0.183941,0.089738,0.057925,0.396386,0.020250,0.031455,102.891633,-49.286221,0.000023,-21.604380
1,0.005425,0.133204,0.087686,13.0,0.103056,0.554675,95.143428,0.733824,-31.960987,58.600567,...,0.126563,0.076072,0.099422,0.488980,0.021231,0.009838,112.829831,-44.378906,0.000161,-38.021886
2,0.002476,NaN,0.188471,NaN,0.070962,0.557865,79.955852,0.951033,-39.223072,62.700785,...,0.187237,NaN,0.083316,0.474999,0.002469,NaN,90.653878,NaN,0.000346,13.580245
3,0.004880,NaN,0.048405,NaN,0.171384,0.499248,51.198701,0.326910,-10.523305,30.975970,...,0.213140,NaN,0.080197,0.476188,0.003003,NaN,35.544744,NaN,0.000011,-6.792367
4,0.010255,0.130021,0.212006,4.0,0.173614,0.678549,111.125483,0.146387,-22.989919,-38.833987,...,0.215322,0.100627,0.115205,0.596445,0.139420,0.059120,104.389768,-43.696259,0.001546,-1.268343
5,0.015832,0.140266,0.260562,4.0,0.228066,0.425741,77.102626,0.285369,-28.987946,-112.001627,...,0.182506,0.164179,0.066368,0.416550,0.015553,0.116495,51.191589,-33.443628,0.001740,-12.493352
6,0.002914,NaN,-0.095022,NaN,0.039668,0.233794,57.373464,0.992363,-23.245065,78.611350,...,0.398388,NaN,0.030915,0.221625,0.002274,NaN,-44.864341,NaN,0.000013,61.629384
7,0.001394,NaN,0.737222,NaN,NaN,0.468916,36.337800,0.995686,NaN,40.797431,...,NaN,NaN,0.023368,0.406453,0.001481,NaN,NaN,NaN,0.001021,NaN
8,0.016559,0.188614,-0.006189,101.0,0.227310,0.521474,165.623338,0.285369,-11.062334,31.119063,...,0.210219,0.125487,0.057522,0.472665,0.002161,0.042413,74.455044,-38.549873,0.000065,46.653735
9,0.009935,0.267465,-0.005994,12.0,0.194764,0.449668,115.028155,NaN,-13.965829,NaN,...,0.239789,0.078306,0.053974,0.411711,NaN,0.070028,105.482601,-38.585573,0.000007,-13.176702
10,0.009822,0.185926,-0.033446,191.0,0.225952,0.604727,90.813498,0.074979,-12.983440,88.140423,...,0.256517,0.090336,0.077098,0.545086,0.001851,0.120871,113.765064,-33.157369,0.000280,7.675971
11,0.005456,0.243432,0.091177,0.0,0.224179,0.348451,53.502158,0.433152,-25.362660,68.934296,...,0.207154,NaN,0.036708,0.306967,0.001481,NaN,-4.236459,NaN,0.000005,-28.798363
12,0.004495,0.140357,0.023537,77.0,0.172327,0.371038,34.001986,0.755065,-25.546054,18.305847,...,0.187716,0.089640,0.039804,0.330029,0.001567,0.001605,103.107153,-50.108323,0.000002,13.569728
13,0.022538,0.053967,0.033813,2.0,0.315859,0.466367,86.604151,0.982590,-47.168884,134.535136,...,0.178733,0.078513,0.074009,0.401298,0.073968,0.148730,88.407530,-26.040905,0.000367,15.659688
14,0.006897,0.123336,0.096220,12.0,0.311720,0.663681,108.618058,0.136162,-57.792619,55.070788,...,0.241788,0.149701,0.103688,0.590787,0.022485,0.059230,87.552284,-22.773216,0.000231,15.394659
15,0.017272,0.178428,0.030340,25.0,0.610379,0.607350,116.389908,0.279111,-31.129380,97.442252,...,0.223286,0.166457,0.095828,0.521707,0.035083,0.011334,87.190090,-29.403022,0.000006,-3.088868
16,NaN,0.113849,NaN,11.0,0.128857,NaN,NaN,0.245617,-41.847970,23.980203,...,0.211044,0.091982,NaN,NaN,0.019070,0.097553,101.159952,-40.602306,NaN,-4.157911
17,NaN,0.109048,NaN,6.0,0.157720,NaN,NaN,0.010039,-22.898045,2.499427,...,0.193923,0.060158,NaN,NaN,0.007839,0.044423,69.482375,-51.223115,NaN,22.683500
18,0.007998,0.060939,0.054637,4.0,0.145501,0.444267,147.919558,0.763449,-39.069918,90.720457,...,0.104135,0.123823,0.084618,0.416301,0.015209,0.060861,-5.316038,-42.800918,0.000695,-4.049689
19,0.006343,0.096460,0.019482,124.0,0.180964,0.460511,147.255557,0.275982,-27.502096,96.260711,...,0.148321,0.083735,0.108329,0.419781,0.015676,0.006079,130.060640,-45.064377,0.000014,12.860036
20,0.004724,0.059959,0.002257,4.0,0.064809,0.402924,118.781197,0.140735,-39.404565,22.624492,...,0.183649,0.069548,0.053620,0.347008,0.005161,0.197342,82.706684,-13.984224,0.000090,12.519152
21,0.006254,0.237060,0.023173,13.0,0.038531,0.539812,79.407336,0.055393,-39.877231,122.218011,...,0.139810,0.145759,0.060094,0.446455,0.065297,0.008469,75.993437,-39.422854,0.000103,-27.095294
22,0.004474,0.070382,-0.155715,36.0,0.162765,0.404016,110.863769,0.985857,-16.715806,50.469920,...,0.073945,0.042029,0.059131,0.365056,0.002355,0.044857,65.753590,-39.065174,0.000127,19.882084
23,0.005109,0.102164,-0.036271,24.0,0.208283,0.462914,57.966092,0.775983,-28.658649,134.810318,...,0.213677,0.096908,0.062293,0.403480,0.004741,0.105215,30.137809,-42.207778,0.000233,30.981852
24,0.009307,NaN,-0.148471,NaN,0.257698,0.432485,70.320826,0.804988,-29.710793,96.339715,...,0.230021,NaN,0.055179,0.386958,0.001873,NaN,62.262524,NaN,0.000001,-98.541647
25,0.007623,0.119859,-0.069005,3.0,0.238521,0.497846,78.733313,0.903600,-31.601804,114.058747,...,0.192897,0.142565,0.065443,0.454668,0.001396,0.005998,80.794912,-26.991862,0.000003,-77.541723
26,NaN,0.123529,NaN,8.0,0.136460,NaN,NaN,NaN,-28.317469,NaN,...,0.095667,0.097061,NaN,NaN,NaN,0.003009,77.901256,-42.430851,NaN,13.586746
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.007112,0.102218,-0.150970,5.0,0.185826,0.546354,109.009029,0.415110,-39.430019,73.814024,...,0.172964,0.191759,0.085195,0.476366,0.002667,0.138823,73.304267,-36.369220,0.000005,43.297915
29,0.003075,0.120622,-0.002169,8.0,0.209365,0.502942,68.113378,0.015515,-28.115883,52.220333,...,0.103174,0.100851,0.060669,0.438362,0.003196,0.051363,130.537874,-41.920480,0.000008,14.744387
30,0.002263,0.159141,-0.103615,10.0,0.130434,0.360188,30.784953,0.010039,-33.826021,124.224925,...,0.086519,0.124387,0.030254,0.328080,0.002300,0.035446,121.643711,-44.133096,0.000009,2.262965
31,0.008408,0.126248,0.074776,17.0,0.286791,0.658901,163.357834,0.285369,-22.109738,132.075453,...,0.204867,0.195949,0.151054,0.610388,0.006941,0.081140,143.180239,-36.470765,0.000004,-4.576435
32,0.008378,0.118954,0.055973,8.0,0.221055,0.649198,89.115046,0.275982,-54.323129,111.101732,...,0.110982,0.196181,0.136297,0.597784,0.007647,0.087035,82.217803,-37.660932,0.000004,-18.494383
33,0.000498,0.216565,0.045870,3.0,0.386282,0.301347,55.522160,0.118761,0.550208,23.047547,...,0.032414,0.082381,0.027951,0.283743,0.004342,0.079625,-3.131190,-42.951494,0.000020,-42.374979
34,0.002372,0.160606,-0.058805,7.0,NaN,0.459332,30.291093,0.055393,NaN,112.680660,...,NaN,0.161018,0.044363,0.372388,0.004651,0.055262,NaN,-31.384610,0.000059,NaN
35,0.004474,NaN,0.029900,NaN,0.220609,0.383717,173.993936,0.555495,-61.202897,50.114954,...,0.100413,NaN,0.080113,0.351790,0.005499,NaN,85.472367,NaN,0.000068,-17.104244
36,0.005540,NaN,0.077216,NaN,0.195914,0.362886,176.016515,0.573595,-25.414021,66.115332,...,0.076957,NaN,0.093045,0.340176,0.004923,NaN,48.413258,NaN,0.000009,11.064513
37,0.002848,0.038480,-0.039036,11.0,0.187322,0.642228,80.702559,0.151795,-20.013108,47.825871,...,0.111467,0.103197,0.076627,0.553812,0.010225,0.222392,91.464703,-23.091381,0.000040,-10.007308
38,0.001416,0.270086,0.085078,0.0,0.211993,0.423853,168.083069,0.951033,-22.554449,67.644232,...,0.040139,NaN,0.061472,0.391612,0.001964,NaN,47.389953,NaN,0.000005,16.666771
39,0.003984,NaN,0.082530,NaN,0.188054,0.366362,130.121915,0.770969,-29.811591,74.010563,...,0.144015,NaN,0.052685,0.340781,0.001830,NaN,199.707350,NaN,0.000004,77.450458
40,0.007966,0.072595,0.097773,8.0,0.093293,0.395072,124.072029,0.785611,-36.220117,53.025164,...,0.179573,0.105828,0.055322,0.354901,0.016394,0.081996,71.863367,-15.366501,0.000100,-6.771583
41,0.005609,NaN,-0.029346,NaN,0.251879,0.495226,153.293967,0.944556,-22.704203,46.020138,...,0.050374,NaN,0.074086,0.444981,0.003077,NaN,76.470349,NaN,0.000004,-16.702389
42,0.005739,0.033094,-0.019451,3.0,0.118118,0.588238,17.158842,0.949705,-32.837032,26.107059,...,0.486483,0.053633,0.091258,0.543014,0.003931,0.005759,151.494644,-0.892179,0.000493,90.923442

# Training and validation

# Test

In [87]:
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
ratio_scaler

2.0714285714285716

In [88]:
from sklearn.model_selection import LeaveOneGroupOut

logo = LeaveOneGroupOut()
logo.get_n_splits(X_new, y, group)

25

# Decision Tree

In [89]:
from sklearn.model_selection import RandomizedSearchCV, LeaveOneGroupOut
from xgboost import XGBClassifier
from scipy.stats import randint, uniform
import numpy as np

In [90]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
distributions_dt = dict(max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced', None])

In [91]:
param_dist = distributions_dt
model = dt

In [92]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'max_depth': np.random.choice(distributions_dt['max_depth']),
            'min_samples_split': np.random.choice(distributions_dt['min_samples_split']),
            'min_samples_leaf': np.random.choice(distributions_dt['min_samples_leaf']),
            'max_features': np.random.choice(distributions_dt['max_features']),
            'class_weight': np.random.choice(distributions_dt['class_weight']),
        }
        print(f"Testing parameters: {params}")
        model = DecisionTreeClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(dt, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 56, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 56, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.5394088669950738, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 5, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.5246305418719212, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': None}
AUC: 0.7007389162561576, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': None}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 85, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 85, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}

Parameters: {'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': None}
AUC: 0.4704433497536945, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4532019704433497, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.48768472906403937, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.48768472906403937, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}

Parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 87, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 87, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': None}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': None}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
AUC: 0.5960591133004927, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.45197044334975367, Precision: 0.25, Recall: 0.21428571428571427, F1-score: 0.23076923076923075
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': None}

Parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 91, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 91, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': None}
AUC: 0.48768472906403937, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': None}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.5960591133004927, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}

Parameters: {'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 43, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 43, 'class_weight': None}
AUC: 0.4889162561576355, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.666256157635468, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 78, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 78, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': None}
AUC: 0.7019704433497538, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': None}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': None}

Parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 54, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 54, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': None}

Parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 7, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 2, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 2, 'class_weight': None}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 79, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 79, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': None}
AUC: 0.48768472906403937, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': None}
AUC: 0.6834975369458128, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': None}

Parameters: {'max_depth': 17, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.7007389162561576, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.4889162561576355, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': None}
Parameters: {'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': None}

Parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': None}
AUC: 0.5246305418719212, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.6317733990147784, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.48768472906403937, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.541871921182266, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': None}
AUC: 0.5615763546798029, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.5246305418719212, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 58, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 58, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 63, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 63, 'class_weight': None}
AUC: 0.5073891625615764, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': None}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': None}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.522167487684729, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': None}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': None}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': None}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}

Parameters: {'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Best AUC: 0.7019704433497538
Best parameters: {'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': None}

In [93]:
model.set_params(**best_params)

DecisionTreeClassifier(max_depth=20, max_features=37,
                       min_samples_leaf=0.30000000000000004,
                       min_samples_split=1.0)

In [94]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    model.fit(X_train, y_train)

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.6293103448275862, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061, Accuracy: 0.6976744186046512, Balanced Accuracy: 0.7019704433497538

# Decision Tree + SMOTE

In [95]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'max_depth': np.random.choice(distributions_dt['max_depth']),
            'min_samples_split': np.random.choice(distributions_dt['min_samples_split']),
            'min_samples_leaf': np.random.choice(distributions_dt['min_samples_leaf']),
            'max_features': np.random.choice(distributions_dt['max_features']),
            'class_weight': np.random.choice(distributions_dt['class_weight']),
        }
        print(f"Testing parameters: {params}")
        model = DecisionTreeClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(dt, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 36, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 36, 'class_weight': None}
AUC: 0.4938423645320197, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': None}
AUC: 0.5665024630541872, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.5246305418719213, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.5283251231527093, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': None}
AUC: 0.43965517241379315, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.6366995073891626, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.6194581280788178, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.5123152709359606, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': None}
AUC: 0.5566502463054187, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.5701970443349754, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.5369458128078818, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 54, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 54, 'class_weight': None}
AUC: 0.6022167487684729, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': None}
AUC: 0.5874384236453202, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.43965517241379304, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': None}
AUC: 0.4347290640394088, Precision: 0.17647058823529413, Recall: 0.21428571428571427, F1-score: 0.1935483870967742
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
AUC: 0.5406403940886699, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': None}
AUC: 0.5997536945812807, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.3879310344827586, Precision: 0.2, Recall: 0.21428571428571427, F1-score: 0.20689655172413796
Testing parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': None}
AUC: 0.4926108374384236, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
AUC: 0.5874384236453202, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.520935960591133, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}

Parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5246305418719213, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.6502463054187192, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': None}
AUC: 0.6428571428571428, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': None}
AUC: 0.5270935960591132, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.5714285714285714, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4913793103448275, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.6133004926108374, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5997536945812807, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': None}
AUC: 0.5677339901477833, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.6859605911330048, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.562807881773399, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.5258620689655173, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': None}
AUC: 0.5258620689655172, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5985221674876848, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': None}
AUC: 0.6539408866995075, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.5566502463054187, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.623152709359606, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': None}
AUC: 0.6293103448275862, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
AUC: 0.6366995073891625, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 32, 'class_weight': None}

Parameters: {'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 32, 'class_weight': None}
AUC: 0.5677339901477833, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5086206896551724, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.5541871921182266, Precision: 0.23529411764705882, Recall: 0.2857142857142857, F1-score: 0.2580645161290323
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.5357142857142857, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': None}
AUC: 0.45320197044334976, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.5147783251231526, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': None}
AUC: 0.6366995073891626, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
AUC: 0.47536945812807885, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.5800492610837438, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.44581280788177335, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': None}
AUC: 0.7155172413793104, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': None}
AUC: 0.6342364532019704, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': None}
AUC: 0.5849753694581281, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.603448275862069, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': None}
AUC: 0.5529556650246304, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.5529556650246304, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 18, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 18, 'class_weight': None}
AUC: 0.5886699507389163, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': None}
AUC: 0.518472906403941, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.5455665024630542, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': None}
AUC: 0.518472906403941, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.5073891625615763, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 63, 'class_weight': 'balanced'}

Parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.5837438423645319, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
AUC: 0.6342364532019704, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6009852216748767, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 18, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 18, 'class_weight': None}
AUC: 0.5098522167487685, Precision: 0.36, Recall: 0.6428571428571429, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.7142857142857143, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.543103448275862, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5603448275862069, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': None}
AUC: 0.564039408866995, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': None}
AUC: 0.46921182266009853, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': None}
AUC: 0.5726600985221675, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.564039408866995, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 27, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 27, 'class_weight': None}
AUC: 0.5283251231527094, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': None}
AUC: 0.5812807881773399, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': None}
AUC: 0.5394088669950738, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.6625615763546798, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': None}
AUC: 0.48768472906403937, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.4618226600985222, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.5640394088669951, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5566502463054187, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}

Parameters: {'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.5800492610837439, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 81, 'class_weight': None}
AUC: 0.4445812807881774, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.6145320197044335, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.4507389162561576, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': None}
AUC: 0.4802955665024631, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': None}
AUC: 0.6009852216748768, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': None}
AUC: 0.5812807881773399, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.5972906403940886, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': None}
AUC: 0.4568965517241379, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': None}
AUC: 0.5714285714285714, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.5862068965517241, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': None}
AUC: 0.5886699507389163, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': None}
AUC: 0.5517241379310345, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 5, 'class_weight': None}
AUC: 0.5369458128078819, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 84, 'class_weight': None}
AUC: 0.5258620689655172, Precision: 0.2, Recall: 0.21428571428571427, F1-score: 0.20689655172413796
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6194581280788177, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': None}
AUC: 0.5295566502463054, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.5295566502463054, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': None}
AUC: 0.5591133004926108, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': None}
AUC: 0.3694581280788177, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': None}
AUC: 0.543103448275862, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': None}
AUC: 0.541871921182266, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': None}
AUC: 0.5566502463054187, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': None}

Parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': None}
AUC: 0.584975369458128, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4051724137931035, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': None}
AUC: 0.5874384236453202, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.5295566502463054, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': None}
AUC: 0.524630541871921, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': None}
AUC: 0.42610837438423643, Precision: 0.17647058823529413, Recall: 0.21428571428571427, F1-score: 0.1935483870967742
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 60, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 60, 'class_weight': None}
AUC: 0.5233990147783251, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': None}
AUC: 0.6268472906403941, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.543103448275862, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': None}
AUC: 0.6613300492610837, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.49753694581280783, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.5073891625615763, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': None}
AUC: 0.5, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5899014778325122, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.5049261083743842, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': None}
AUC: 0.5874384236453202, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.5738916256157636, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': None}
AUC: 0.4839901477832512, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': None}
AUC: 0.6416256157635468, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': None}
AUC: 0.6206896551724138, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 13, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 13, 'class_weight': None}
AUC: 0.5603448275862069, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.6391625615763546, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}

Parameters: {'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5307881773399015, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5899014778325122, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.5948275862068965, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6009852216748769, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.46674876847290636, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': None}
AUC: 0.5800492610837437, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 65, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 65, 'class_weight': None}
AUC: 0.5825123152709359, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': None}
AUC: 0.46674876847290636, Precision: 0.25, Recall: 0.21428571428571427, F1-score: 0.23076923076923075
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5714285714285715, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.3916256157635468, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 86, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 86, 'class_weight': None}
AUC: 0.48522167487684725, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': None}
AUC: 0.5825123152709359, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.5320197044334976, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': None}
AUC: 0.5529556650246306, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.5467980295566502, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.604679802955665, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.5184729064039408, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': None}
AUC: 0.5985221674876846, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': None}
AUC: 0.5061576354679803, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
AUC: 0.5862068965517241, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': None}
AUC: 0.6674876847290641, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.5517241379310345, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}

Parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.49507389162561577, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': None}
AUC: 0.5307881773399015, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': None}
AUC: 0.5726600985221675, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': None}
AUC: 0.39532019704433496, Precision: 0.23809523809523808, Recall: 0.35714285714285715, F1-score: 0.2857142857142857
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.6194581280788177, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': None}
AUC: 0.584975369458128, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.3879310344827586, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.6145320197044335, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 32, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 32, 'class_weight': None}
AUC: 0.5012315270935961, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': None}
AUC: 0.5911330049261084, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.6009852216748769, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.5997536945812808, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.6219211822660099, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': None}
AUC: 0.5726600985221675, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5320197044334976, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 23, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 23, 'class_weight': None}
AUC: 0.48399014778325117, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': None}
AUC: 0.5369458128078818, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': None}
AUC: 0.458128078817734, Precision: 0.25, Recall: 0.2857142857142857, F1-score: 0.26666666666666666
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': None}
AUC: 0.5529556650246306, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': None}

Parameters: {'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': None}
AUC: 0.4778325123152709, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6379310344827586, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.47167487684729065, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.5270935960591133, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4199507389162561, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': None}
AUC: 0.602216748768473, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5443349753694581, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': None}
AUC: 0.5837438423645319, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.6637931034482759, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.5147783251231527, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.49507389162561566, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.5270935960591132, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': None}
AUC: 0.5369458128078818, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': None}
AUC: 0.5431034482758621, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': None}
AUC: 0.5591133004926108, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': None}
AUC: 0.6539408866995075, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': None}
AUC: 0.4495073891625616, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.49753694581280794, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.36083743842364535, Precision: 0.22727272727272727, Recall: 0.35714285714285715, F1-score: 0.2777777777777778
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': None}
Parameters: {'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': None}
AUC: 0.5455665024630542, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': None}
AUC: 0.4975369458128079, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': None}
AUC: 0.3657635467980295, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Best AUC: 0.7155172413793104
Best parameters: {'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': None}

In [96]:
model = dt.set_params(**best_params)

In [97]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.5862068965517241, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667, Accuracy: 0.627906976744186, Balanced Accuracy: 0.5948275862068966

# Random Forest

In [98]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param_grid = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])

In [100]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'n_estimators': np.random.choice(param_grid['n_estimators']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'min_samples_split': np.random.choice(param_grid['min_samples_split']),
            'min_samples_leaf': np.random.choice(param_grid['min_samples_leaf']),
            'max_features': np.random.choice(param_grid['max_features']),
            'class_weight': np.random.choice(param_grid['class_weight']),

        }
        print(f"Testing parameters: {params}")
        pipeline = RandomForestClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

rf = RandomForestClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(rf, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.5665024630541872, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.7290640394088671, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.7339901477832512, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.7536945812807881, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4421182266009852, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6810344827586207, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.7044334975369457, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.6970443349753696, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.48891625615763545, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.6970443349753696, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6822660098522169, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 51, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.6330049261083743, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 32, 'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.272167487684729, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.7450738916256158, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6847290640394088, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.6724137931034483, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.7980295566502463, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6970443349753694, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6600985221674877, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.5665024630541872, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6822660098522169, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.7733990147783252, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.5849753694581281, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.7118226600985221, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'n_estimators': 4, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6970443349753694, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.7192118226600985, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.6810344827586208, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.5049261083743842, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5492610837438423, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.645320197044335, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.6798029556650247, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.6280788177339901, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.4495073891625616, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6871921182266011, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.6699507389162561, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.7192118226600985, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.32512315270935965, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.7635467980295566, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.6576354679802956, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.7610837438423644, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.7266009852216749, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.46921182266009853, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.32512315270935965, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.5726600985221676, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.6674876847290641, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.6748768472906405, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.31896551724137934, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.3805418719211823, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.31896551724137934, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6157635467980296, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.48891625615763545, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.7339901477832512, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.5997536945812808, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.623152709359606, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.48275862068965514, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.6305418719211824, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 1, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.7610837438423645, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 32, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.4014778325123153, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.4568965517241379, Precision: 0.2857142857142857, Recall: 0.42857142857142855, F1-score: 0.34285714285714286
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.6674876847290641, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6798029556650247, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5394088669950738, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.6625615763546798, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.7315270935960592, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6847290640394089, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.43596059113300495, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.5591133004926108, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.5517241379310345, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.6280788177339901, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6798029556650246, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.48891625615763545, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 4, 'max_depth': 11, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 11, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.7266009852216749, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6970443349753696, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.29310344827586204, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.5788177339901478, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.623152709359606, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.6908866995073891, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.7266009852216749, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.7118226600985221, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6748768472906405, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4495073891625616, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.708128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.272167487684729, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.32512315270935965, Precision: 0.2631578947368421, Recall: 0.35714285714285715, F1-score: 0.30303030303030304
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.7155172413793103, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6724137931034483, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Best AUC: 0.7980295566502463
Best parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}

In [101]:
model = RandomForestClassifier(**best_params, random_state = 42)

In [102]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train, y_train)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.7980295566502463, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.770935960591133

# Random Forest + SMOTE

In [103]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param_grid = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])

In [104]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'n_estimators': np.random.choice(param_grid['n_estimators']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'min_samples_split': np.random.choice(param_grid['min_samples_split']),
            'min_samples_leaf': np.random.choice(param_grid['min_samples_leaf']),
            'max_features': np.random.choice(param_grid['max_features']),
            'class_weight': np.random.choice(param_grid['class_weight']),

        }
        print(f"Testing parameters: {params}")
        pipeline = RandomForestClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

rf = RandomForestClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(rf, X_new, y, group, param_grid, n_iter = 200)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.7413793103448276, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.41256157635467977, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.5985221674876848, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5738916256157636, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5677339901477834, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.5985221674876848, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6022167487684729, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 64, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.625615763546798, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.603448275862069, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6502463054187192, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.5541871921182266, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.7389162561576355, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.5640394088669951, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.768472906403941, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.5578817733990148, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.645320197044335, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.7389162561576355, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.5024630541871921, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.6847290640394089, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.5467980295566501, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.6083743842364533, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.6096059113300493, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.6748768472906405, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6280788177339902, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.6231527093596059, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.6157635467980296, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5738916256157635, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.5738916256157636, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.5221674876847291, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.6502463054187192, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6034482758620691, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.5320197044334976, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5332512315270935, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.45197044334975367, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.6182266009852218, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6428571428571428, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.6145320197044335, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 8, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.6699507389162562, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.583743842364532, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 200, 'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.7758620689655173, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.7118226600985221, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.6428571428571429, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.8152709359605912, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.42733990147783246, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.5911330049261084, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.5911330049261083, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.5788177339901478, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.623152709359606, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5775862068965517, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.40024630541871914, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.706896551724138, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.603448275862069, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.6379310344827586, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.5406403940886699, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6206896551724138, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 4, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.5258620689655172, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'n_estimators': 16, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.396551724137931, Precision: 0.25, Recall: 0.21428571428571427, F1-score: 0.23076923076923075
Testing parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.5566502463054187, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 2, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.4630541871921182, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.5985221674876847, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4876847290640395, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.6428571428571429, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.6798029556650246, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 32, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.6293103448275862, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.6564039408866994, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.645320197044335, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4778325123152709, Precision: 0.2, Recall: 0.21428571428571427, F1-score: 0.20689655172413796
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.41748768472906395, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5763546798029556, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.5541871921182265, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.4458128078817734, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.602216748768473, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.5985221674876848, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.5110837438423644, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.4778325123152709, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.687192118226601, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6280788177339901, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.5, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.4926108374384236, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Best AUC: 0.853448275862069
Best parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}

In [105]:
model = RandomForestClassifier(**best_params, random_state = 42)

In [106]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)
    


            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6, Accuracy: 0.813953488372093, Balanced Accuracy: 0.7142857142857143

# XGBoost

In [107]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [108]:
param_grid

{'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.3],
 'gamma': [0, 0.1, 0.15, 0.25, 0.5],
 'max_depth': [6, 8, 10, 12, 15],
 'subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'colsample_bylevel': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'colsample_bytree': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'min_child_weight': [0.5, 1.0, 3.0, 5.0, 7.0, 10.0],
 'estimators': [50, 100, 200],
 'scale_pos_weight': [2.0714285714285716]}

In [109]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'learning_rate': np.random.choice(param_grid['learning_rate']),
            'gamma': np.random.choice(param_grid['gamma']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'subsample': np.random.choice(param_grid['subsample']),
            'colsample_bylevel': np.random.choice(param_grid['colsample_bylevel']),
            'colsample_bytree': np.random.choice(param_grid['colsample_bytree']),
            'min_child_weight': np.random.choice(param_grid['min_child_weight']),
            'estimators': np.random.choice(param_grid['estimators']),
            'scale_pos_weight': np.random.choice(param_grid['scale_pos_weight'])
        }
        print(f"Testing parameters: {params}")
        pipeline = XGBClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

xgb = XGBClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(xgb, X_new, y, group, param_grid, n_iter = 500)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955666, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07389162561576354, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.051724137931034475, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03694581280788177, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.16871921182266006, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.605911330049261, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05418719211822659, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09482758620689655, Precision: 0.1, Recall: 0.21428571428571427, F1-score: 0.13636363636363638
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187193, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.37931034482758624, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04679802955665024, Precision: 0.05263157894736842, Recall: 0.07142857142857142, F1-score: 0.06060606060606061
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0073891625615763535, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0689655172413793, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.039408866995073885, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08128078817733989, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04679802955665024, Precision: 0.06666666666666667, Recall: 0.07142857142857142, F1-score: 0.0689655172413793
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.051724137931034475, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5615763546798029, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807883, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.15024630541871922, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.012315270935960583, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09729064039408869, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5886699507389164, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5911330049261083, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.039408866995073885, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5862068965517241, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0541871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497538, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5652709359605912, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5295566502463054, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08128078817733991, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09482758620689655, Precision: 0.1, Recall: 0.21428571428571427, F1-score: 0.13636363636363638
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034484, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06157635467980295, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029557, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5689655172413793, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.061576354679802964, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.539408866995074, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.14901477832512322, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364533, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270935, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04926108374384236, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09113300492610836, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05418719211822659, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108375, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6490147783251232, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07881773399014778, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.056650246305418706, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187193, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.623152709359606, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05665024630541871, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.603448275862069, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09482758620689655, Precision: 0.1, Recall: 0.21428571428571427, F1-score: 0.13636363636363638
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06157635467980295, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216749, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5862068965517242, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029556, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083744, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0812807881773399, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5935960591133005, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699506, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0073891625615763535, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0751231527093596, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349754, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.16379310344827586, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5862068965517242, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05911330049261083, Precision: 0.06666666666666667, Recall: 0.07142857142857142, F1-score: 0.0689655172413793
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753696, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07142857142857142, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6958128078817734, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04926108374384235, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04310344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.624384236453202, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.25, Recall: 0.5714285714285714, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364532, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07635467980295566, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.58128078817734, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.013546798029556653, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0812807881773399, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137931, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5554187192118226, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266014, Precision: 0.05263157894736842, Recall: 0.07142857142857142, F1-score: 0.06060606060606061
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08374384236453201, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.017241379310344827, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.034482758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157636, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06773399014778322, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364533, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.25, Recall: 0.5714285714285714, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.14901477832512322, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955666, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12438423645320197, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04187192118226599, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05665024630541872, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0960591133004926, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5948275862068966, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09113300492610837, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.603448275862069, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.647783251231527, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650246, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0665024630541872, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07635467980295567, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06157635467980296, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07881773399014778, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5024630541871922, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10344827586206895, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07512315270935958, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5862068965517241, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5591133004926108, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3768472906403941, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029557, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5862068965517242, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034482, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04310344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0751231527093596, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07266009852216747, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10098522167487683, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0812807881773399, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.051724137931034475, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0541871921182266, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236452, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06403940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369457, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2795566502463054, Precision: 0.22580645161290322, Recall: 0.5, F1-score: 0.3111111111111111
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.013546798029556653, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.012315270935960592, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6280788177339902, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6871921182266011, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.19950738916256155, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.039408866995073885, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5246305418719213, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07881773399014778, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5665024630541872, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05665024630541871, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5886699507389163, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.046798029556650245, Precision: 0.05263157894736842, Recall: 0.07142857142857142, F1-score: 0.06060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266014, Precision: 0.058823529411764705, Recall: 0.07142857142857142, F1-score: 0.06451612903225808
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5886699507389163, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04679802955665024, Precision: 0.05263157894736842, Recall: 0.07142857142857142, F1-score: 0.06060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5443349753694581, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07389162561576354, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07881773399014778, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.02955665024630542, Precision: 0.05555555555555555, Recall: 0.07142857142857142, F1-score: 0.0625
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.19334975369458127, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463051, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10591133004926107, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5935960591133005, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.051724137931034475, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029556, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364532, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236452, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266014, Precision: 0.05263157894736842, Recall: 0.07142857142857142, F1-score: 0.06060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.07635467980295566, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.02955665024630541, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497538, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.25, Recall: 0.5714285714285714, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1502463054187192, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.16133004926108377, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.623152709359606, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.16133004926108377, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23522167487684728, Precision: 0.14285714285714285, Recall: 0.14285714285714285, F1-score: 0.14285714285714285
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06403940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5504926108374385, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679804, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605911, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.706896551724138, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05665024630541871, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0073891625615763535, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522166, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187193, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17857142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3435960591133005, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157636, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778326, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06280788177339898, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2795566502463054, Precision: 0.22580645161290322, Recall: 0.5, F1-score: 0.3111111111111111
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12438423645320196, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17857142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04679802955665024, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034484, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546799, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083744, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364533, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12438423645320196, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0751231527093596, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08620689655172413, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04556650246305415, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5689655172413793, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.25, Recall: 0.5714285714285714, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.19088669950738915, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Best AUC: 0.8349753694581281
Best parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

In [110]:
model = XGBClassifier(**best_params, random_state = 42)

In [111]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train, y_train)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8349753694581281, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216, Accuracy: 0.6976744186046512, Balanced Accuracy: 0.6096059113300493

# XGBoost + SMOTE

In [112]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler, 1]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [113]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'learning_rate': np.random.choice(param_grid['learning_rate']),
            'gamma': np.random.choice(param_grid['gamma']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'subsample': np.random.choice(param_grid['subsample']),
            'colsample_bylevel': np.random.choice(param_grid['colsample_bylevel']),
            'colsample_bytree': np.random.choice(param_grid['colsample_bytree']),
            'min_child_weight': np.random.choice(param_grid['min_child_weight']),
            'estimators': np.random.choice(param_grid['estimators']),
            'scale_pos_weight': np.random.choice(param_grid['scale_pos_weight'])
        }
        print(f"Testing parameters: {params}")
        pipeline = XGBClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

xgb = XGBClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(xgb, X_new, y, group, param_grid, n_iter = 1000)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5270935960591132, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.42364532019704426, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349753, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5246305418719212, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5492610837438423, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6773399014778325, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.665024630541872, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.645320197044335, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6798029556650246, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3559113300492611, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.39532019704433496, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6305418719211823, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5665024630541873, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5985221674876846, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7056650246305418, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5147783251231528, Precision: 0.32432432432432434, Recall: 0.8571428571428571, F1-score: 0.4705882352941177
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6798029556650247, Precision: 0.3333333333333333, Recall: 0.21428571428571427, F1-score: 0.2608695652173913
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083743, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551725, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5788177339901478, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.561576354679803, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.2777777777777778, Recall: 0.35714285714285715, F1-score: 0.31250000000000006
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5443349753694581, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576356, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.35837438423645324, Precision: 0.2926829268292683, Recall: 0.8571428571428571, F1-score: 0.4363636363636364
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236452, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394088, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5812807881773399, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6379310344827587, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6059113300492611, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6576354679802956, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5812807881773399, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753694, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059113, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083744, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.45320197044334976, Precision: 0.25, Recall: 0.42857142857142855, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5775862068965518, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364532, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5073891625615763, Precision: 0.2926829268292683, Recall: 0.8571428571428571, F1-score: 0.4363636363636364
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.34782608695652173, Recall: 0.5714285714285714, F1-score: 0.4324324324324324
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394089, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.541871921182266, Precision: 0.3, Recall: 0.42857142857142855, F1-score: 0.3529411764705882
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7339901477832512, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.645320197044335, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108375, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.70935960591133, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6921182266009852, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674878, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059113, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5049261083743842, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4433497536945813, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6366995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.560344827586207, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.36, Recall: 0.6428571428571429, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.48, Recall: 0.8571428571428571, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6650246305418719, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364533, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.46674876847290636, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133005, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7118226600985222, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157636, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5862068965517242, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.665024630541872, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133005, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295566, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5467980295566502, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6822660098522169, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6194581280788176, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.44334975369458124, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852216, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4150246305418719, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.603448275862069, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.46551724137931033, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5344827586206896, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236452, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187193, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6945812807881773, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4285714285714286, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5960591133004927, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6169950738916257, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.47167487684729065, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4347290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211824, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5024630541871922, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5985221674876848, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748769, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6576354679802956, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881775, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674878, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192119, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5566502463054188, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6453201970443351, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6625615763546798, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906405, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6945812807881774, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216749, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4938423645320197, Precision: 0.3076923076923077, Recall: 0.5714285714285714, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857144, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162562, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4248768472906404, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3793103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6490147783251231, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.623152709359606, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.623152709359606, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.42610837438423643, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6921182266009852, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.48029556650246297, Precision: 0.28205128205128205, Recall: 0.7857142857142857, F1-score: 0.4150943396226415
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.646551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6798029556650246, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724137, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5788177339901477, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.625615763546798, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5049261083743841, Precision: 0.32, Recall: 0.5714285714285714, F1-score: 0.41025641025641024
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6625615763546797, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.539408866995074, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650246, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5049261083743842, Precision: 0.3225806451612903, Recall: 0.7142857142857143, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339902, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748768, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5862068965517242, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157636, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7019704433497538, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7339901477832513, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339902, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6798029556650246, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7142857142857144, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.38916256157635465, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236452, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5197044334975369, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748768, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5123152709359606, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5467980295566502, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7327586206896551, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034484, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6822660098522167, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724139, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852216, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.20073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.44827586206896547, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522169, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133005, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5344827586206896, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.28201970443349755, Precision: 0.125, Recall: 0.14285714285714285, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5246305418719213, Precision: 0.36, Recall: 0.6428571428571429, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546797, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4347290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.731527093596059, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339902, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.645320197044335, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852216, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.561576354679803, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6576354679802956, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5467980295566504, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113301, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955666, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5960591133004927, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5985221674876847, Precision: 0.3142857142857143, Recall: 0.7857142857142857, F1-score: 0.44897959183673464
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5369458128078818, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5517241379310345, Precision: 0.3333333333333333, Recall: 0.5714285714285714, F1-score: 0.4210526315789474
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339902, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5935960591133005, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674878, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4236453201970444, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.37192118226600984, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25985221674876846, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216749, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.625615763546798, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5640394088669951, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059113, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5714285714285714, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5012315270935961, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674878, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6453201970443351, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6379310344827587, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6059113300492611, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004927, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6958128078817734, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5763546798029556, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753696, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364532, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4347290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5147783251231527, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5073891625615763, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5899014778325122, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5911330049261083, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5098522167487685, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7586206896551724, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6736453201970444, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034484, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5443349753694582, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5443349753694582, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364532, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339901, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.647783251231527, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5862068965517242, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5911330049261084, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5467980295566502, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6822660098522167, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7019704433497537, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5886699507389163, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753694, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5615763546798029, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571429, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650246, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6256157635467982, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394088, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157636, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6921182266009852, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7056650246305418, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5603448275862069, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4002463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7401477832512315, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.36666666666666664, Recall: 0.7857142857142857, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5665024630541873, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.603448275862069, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.687192118226601, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133004, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5320197044334976, Precision: 0.34782608695652173, Recall: 0.5714285714285714, F1-score: 0.4324324324324324
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.501231527093596, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6305418719211823, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083744, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5344827586206897, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5603448275862069, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5689655172413793, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083744, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5665024630541872, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7118226600985221, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5369458128078818, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.583743842364532, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4347290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6231527093596059, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5369458128078819, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6059113300492611, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5837438423645321, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7401477832512315, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.646551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5591133004926108, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5738916256157635, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113302, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6280788177339901, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5665024630541872, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6428571428571429, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5911330049261083, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7302955665024631, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349753, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6280788177339901, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5024630541871922, Precision: 0.3125, Recall: 0.7142857142857143, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.541871921182266, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339902, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.3548387096774194, Recall: 0.7857142857142857, F1-score: 0.48888888888888893
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5295566502463054, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394089, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5935960591133005, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6133004926108374, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748769, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187193, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5591133004926109, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906405, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674877, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6871921182266011, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6379310344827587, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.44704433497536944, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522169, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059114, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6551724137931035, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5911330049261084, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3780788177339902, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5578817733990148, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.33866995073891626, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.46059113300492605, Precision: 0.3, Recall: 0.8571428571428571, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162562, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339901, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5566502463054187, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029557, Precision: 0.35714285714285715, Recall: 0.7142857142857143, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339901, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6650246305418719, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.58128078817734, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.665024630541872, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6403940886699507, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5935960591133006, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7056650246305418, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6933497536945813, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5886699507389163, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.75, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5467980295566502, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5960591133004925, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6182266009852218, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5812807881773399, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5566502463054187, Precision: 0.3548387096774194, Recall: 0.7857142857142857, F1-score: 0.48888888888888893
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4458128078817734, Precision: 0.2571428571428571, Recall: 0.6428571428571429, F1-score: 0.36734693877551017
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6083743842364532, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5862068965517241, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.2955665024630542, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.689655172413793, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4987684729064039, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.605911330049261, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5172413793103449, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857142, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5197044334975369, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6428571428571428, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4002463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679802, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5172413793103449, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.645320197044335, Precision: 0.36363636363636365, Recall: 0.8571428571428571, F1-score: 0.5106382978723404
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.49507389162561577, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.29411764705882354, Recall: 0.7142857142857143, F1-score: 0.4166666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4815270935960591, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6551724137931034, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980295, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5640394088669951, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6256157635467982, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.49753694581280794, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.37315270935960587, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6798029556650246, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6428571428571428, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699508, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.31157635467980294, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6576354679802956, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4347290640394089, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.312807881773399, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753696, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.3793103448275862, Recall: 0.7857142857142857, F1-score: 0.5116279069767441
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6182266009852216, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5886699507389163, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5517241379310345, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6625615763546798, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5960591133004927, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5714285714285714, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6576354679802956, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6527093596059114, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7216748768472907, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6182266009852218, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5591133004926108, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6428571428571429, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.41748768472906406, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.645320197044335, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748768, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.665024630541872, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6970443349753696, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6600985221674877, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.645320197044335, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.645320197044335, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6083743842364532, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5394088669950738, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724137, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5566502463054187, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6305418719211824, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.623152709359606, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6428571428571428, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6366995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5911330049261083, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8041871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.43103448275862066, Precision: 0.2894736842105263, Recall: 0.7857142857142857, F1-score: 0.423076923076923
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.41625615763546797, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5172413793103448, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748768, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6847290640394089, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6009852216748768, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.47044334975369456, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699508, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108374, Precision: 0.35714285714285715, Recall: 0.7142857142857143, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5233990147783252, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724137, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931035, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.458128078817734, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6280788177339902, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6059113300492611, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6945812807881773, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724137, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5665024630541873, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6083743842364532, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.665024630541872, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6305418719211823, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162562, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029556, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.539408866995074, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5517241379310345, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5788177339901478, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5911330049261083, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7401477832512315, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5911330049261083, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369458, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083743, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236454, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5320197044334976, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.583743842364532, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7056650246305418, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394089, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6773399014778325, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5566502463054188, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3645320197044335, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6773399014778325, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6822660098522167, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6231527093596059, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5221674876847291, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699507, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5061576354679803, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6539408866995075, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.731527093596059, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852216, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.560344827586207, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6206896551724138, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5443349753694582, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4839901477832512, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6280788177339901, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7093596059113302, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.706896551724138, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931033, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059115, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Best AUC: 0.9667487684729064
Best parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

In [114]:
model = XGBClassifier(**best_params, random_state = 42)

In [115]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)

            

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857, Accuracy: 0.32558139534883723, Balanced Accuracy: 0.5

# Logistic Regression

In [118]:
groups = group

In [119]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [120]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7093596059113301, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.812807881773399, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8596059113300493, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8497536945812808, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7364532019704433, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8152709359605912, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8620689655172413, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8448275862068966, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7561576354679803, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8399014778325123, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8645320197044335, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7684729064039408, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8719211822660099, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7660098522167488, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8596059113300492, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7783251231527093, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8620689655172413, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8743842364532021, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8669950738916257, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8226600985221675, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8472906403940886, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8719211822660099, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8546798029556649, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8004926108374385, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8571428571428571, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8768472906403941, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8399014778325123, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8522167487684729, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8029556650246306, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8546798029556649, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8719211822660099, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8645320197044335, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Best AUC: 0.8768472906403941
Best parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}

In [121]:
best_params

{'model__C': 59.94842503189409,
 'model__penalty': 'l2',
 'model__solver': 'liblinear'}

In [122]:
model = linear_model.LogisticRegression()



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe

In [123]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 LogisticRegression(C=59.94842503189409, solver='liblinear'))])

In [124]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924, Accuracy: 0.813953488372093, Balanced Accuracy: 0.7697044334975369

# LR + SMOTE

In [125]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [126]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8177339901477833, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8596059113300494, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8522167487684729, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7487684729064039, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8497536945812808, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8497536945812807, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8472906403940887, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.7635467980295567, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8325123152709359, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8571428571428572, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8596059113300492, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8029556650246306, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8497536945812808, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8571428571428572, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8374384236453202, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8029556650246306, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8472906403940887, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8719211822660099, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.852216748768473, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8251231527093597, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8399014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8620689655172413, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8645320197044335, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8669950738916257, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8448275862068966, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8596059113300494, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.854679802955665, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8399014778325123, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8866995073891626, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.854679802955665, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8645320197044335, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.8645320197044335, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.8768472906403941, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.8472906403940886, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Best AUC: 0.8866995073891626
Best parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}

In [127]:
model = linear_model.LogisticRegression()



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 LogisticRegression(C=1291.5496650148827, solver='liblinear'))])

In [128]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)
            


    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.7339901477832512

# k-NN

In [129]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier
    



from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.644088669950739, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.644088669950739, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.644088669950739, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.644088669950739, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6982758620689655, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6982758620689655, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7155172413793104, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7155172413793104, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6810344827586207, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6810344827586207, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6317733990147784, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6564039408866996, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6945812807881773, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.710591133004926, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6428571428571429, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6588669950738917, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6096059113300493, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6391625615763546, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5972906403940886, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6366995073891626, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6748768472906403, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7142857142857143, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6490147783251232, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6674876847290641, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6564039408866996, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6736453201970444, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.583743842364532, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6059113300492611, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6059113300492611, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.623152709359606, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6379310344827587, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6748768472906403, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6231527093596059, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6527093596059113, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6699507389162561, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.645320197044335, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6539408866995073, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6317733990147782, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6022167487684729, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6059113300492611, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6169950738916256, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6588669950738916, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6514778325123152, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6798029556650247, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6650246305418719, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6564039408866995, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6

Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6490147783251232, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6206896551724137, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6071428571428571, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6108374384236452, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.5812807881773399, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6206896551724137, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7302955665024631, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7118226600985221, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6945812807881773, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6773399014778325, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6403940886699507, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6194581280788177, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6428571428571429, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6280788177339902, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6120689655172414, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.645320197044335, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7167487684729064, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6884236453201971, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6625615763546797, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6798029556650246, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6440886699507389, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6576354679802956, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.625615763546798, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.5677339901477833, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.604679802955665, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7179802955665024, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6539408866995073, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6280788177339902, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6637931034482759, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6428571428571428, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6674876847290641, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6354679802955665, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6157635467980295, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.647783251231527, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7142857142857143, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7192118226600984, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6822660098522167, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6514778325123153, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6379310344827587, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6564039408866995, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.625615763546798, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7019704433497537, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6995073891625616, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7241379310344828, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333

Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7229064039408867, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6896551724137931, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6391625615763546, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6379310344827586, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6699507389162562, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6600985221674878, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6958128078817734, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6970443349753694, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7032019704433498, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7093596059113301, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6724137931034483, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6440886699507389, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6428571428571428, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6958128078817734, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6625615763546798, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6834975369458128, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6847290640394088, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6711822660098523, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6958128078817734, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6576354679802956, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6650246305418719, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6268472906403941, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6330049261083743, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6859605911330048, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6502463054187192, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6810344827586208, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6773399014778325, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6662561576354681, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6724137931034482, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6588669950738917, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6699507389162561, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6600985221674877, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6403940886699506, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6133004926108374, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7241379310344827, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7019704433497537, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6736453201970445, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6798029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6330049261083746, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6576354679802956, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6145320197044335, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6108374384236454, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.602216748768473, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7118226600985222, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6995073891625615, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7019704433497538, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6945812807881775, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.5972906403940886, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6206896551724138, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.58128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.583743842364532, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.5935960591133005, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5862068965517242, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Best AUC: 0.7302955665024631
Best parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}

In [130]:
best_score

0.7302955665024631

In [131]:
best_params

{'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}

In [132]:
model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe

In [133]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model', KNeighborsClassifier(n_neighbors=6))])

In [134]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.7302955665024631, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25, Accuracy: 0.7209302325581395, Balanced Accuracy: 0.5714285714285714

# k-NN + SMOTE

In [135]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np


param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier
    



from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6798029556650246, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6798029556650246, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7339901477832512, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7339901477832512, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6637931034482759, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6650246305418719, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6576354679802956, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.6798029556650246, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7241379310344829, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6416256157635467, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6206896551724137, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.667487684729064, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7142857142857142, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6477832512315271, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5911330049261083, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6982758620689655, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6958128078817732, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7438423645320197, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6551724137931034, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6108374384236454, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6096059113300492, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6330049261083743, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6219211822660098, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.5935960591133005, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6613300492610839, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6798029556650247, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7044334975369458, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.70935960591133, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6761083743842364, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.624384236453202, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6477832512315271, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6785714285714286, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6416256157635468, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6280788177339902, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6514778325123153, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7549261083743841, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.687192118226601, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6071428571428572, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6625615763546798, Precision: 0.5, Recall: 0.5, F1-score: 0.5

Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6514778325123153, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.5935960591133005, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.687192118226601, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6108374384236455, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6145320197044335, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7142857142857144, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7783251231527094, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.6995073891625616, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.6613300492610837, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6773399014778325, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6539408866995075, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6773399014778326, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6268472906403941, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6748768472906406, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6982758620689655, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6600985221674877, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7229064039408868, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7426108374384237, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7056650246305418, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.666256157635468, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.5972906403940886, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6724137931034483, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6527093596059114, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6145320197044334, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6822660098522166, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6736453201970444, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7623152709359606, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7241379310344829, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7192118226600985, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7635467980295567, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7179802955665024, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7364532019704434, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6169950738916256, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.645320197044335, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.666256157635468, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.687192118226601, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7672413793103449, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7155172413793103, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7512315270935961, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7623152709359606, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7019704433497538, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7623152709359606, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7463054187192119, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7032019704433498, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5

Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7266009852216749, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7561576354679802, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8177339901477833, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.729064039408867, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7684729064039408, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8054187192118227, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6280788177339902, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6219211822660098, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6724137931034483, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7401477832512317, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7241379310344828, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7807881773399015, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7561576354679802, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7339901477832512, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7216748768472907, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7647783251231528, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6921182266009852, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6958128078817735, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6724137931034484, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7623152709359606, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7487684729064039, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7401477832512315, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7758620689655172, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7561576354679803, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7635467980295567, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7352216748768473, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.706896551724138, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.6958128078817735, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6625615763546797, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7857142857142857, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7783251231527094, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7229064039408867, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7438423645320197, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7795566502463054, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7980295566502463, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.6921182266009852, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.6921182266009852, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7019704433497537, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6699507389162562, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7475369458128078, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7142857142857144, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7573891625615764, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7783251231527094, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.770935960591133, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344

Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.6699507389162561, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7044334975369458, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7339901477832512, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7105911330049262, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6896551724137931, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7770935960591134, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.746305418719212, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7733990147783251, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7684729064039408, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7376847290640394, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7660098522167488, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7266009852216749, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7315270935960592, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7266009852216749, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.6674876847290641, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Best AUC: 0.8177339901477833
Best parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}

In [136]:
best_params

{'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}

In [137]:
model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 KNeighborsClassifier(n_neighbors=10, weights='distance'))])

In [138]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)
            


    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.7364532019704434, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344, Accuracy: 0.6976744186046512, Balanced Accuracy: 0.6650246305418719

# SVM

In [139]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8349753694581281, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5147783251231528, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7561576354679803, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473

Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5923645320197045, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.768472906403941, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22413793103448273, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5825123152709359, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.21674876847290642, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666

Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666

Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105

Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.603448275862069, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473

Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6194581280788177, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4113300492610838, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.009852216748768468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5874384236453203, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Best AUC: 0.8817733990147785
Best parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}

In [140]:
best_params

{'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}

In [141]:
best_score

0.8817733990147785

In [142]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
pipeline = pipe

In [143]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('clf',
                 SVC(C=0.1, degree=0, gamma=0.1, kernel='linear',
                     probability=True, random_state=100))])

In [144]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8817733990147785, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.7339901477832512

# SVM + SMOTE

In [145]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.27586206896551724, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8325123152709359, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2832512315270935, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8596059113300493, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.25985221674876846, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8472906403940886, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.25985221674876846, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.24876847290640391, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7980295566502463, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27586206896551724, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8768472906403941, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8694581280788178, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8620689655172413, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.852216748768473, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.25492610837438423, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5443349753694582, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.26847290640394084, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5467980295566501, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8620689655172413, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6527093596059113, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8275862068965517, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5886699507389163, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916256, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.25862068965517243, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7364532019704433, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.26847290640394084, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7561576354679803, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8768472906403941, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2844827586206896, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27709359605911327, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666

Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7721674876847291, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.853448275862069, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.26354679802955666, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.4987684729064039, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2586206896551724, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6551724137931034, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5504926108374384, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8694581280788177, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27709359605911327, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5788177339901478, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2278325123152709, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6798029556650246, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27339901477832507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7068965517241379, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.27709359605911327, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6859605911330049, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147782, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27709359605911327, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7820197044334974, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8374384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.25492610837438423, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5997536945812808, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8472906403940886, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.25738916256157635, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5566502463054187, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2820197044334975, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7155172413793104, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.272167487684729, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5566502463054187, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.28571428571428575, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8620689655172413, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3448275862068966, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8596059113300494, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4051724137931035, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857

Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5665024630541872, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8620689655172414, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5123152709359606, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8596059113300492, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.23891625615763548, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8620689655172414, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4298029556650246, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8793103448275863, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.40024630541871925, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8694581280788177, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4285714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6206896551724138, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.08620689655172414, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5443349753694582, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8990147783251231, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.27463054187192115, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5270935960591132, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.48152709359605905, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.541871921182266, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8596059113300494, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.539408866995074, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7721674876847291, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8472906403940887, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.18226600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7438423645320198, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8768472906403941, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5615763546798029, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8054187192118227, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8472906403940886, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5566502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3620689655172414, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6588669950738917, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8399014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3349753694581281, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6724137931034483, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.1958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.562807881773399, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.47290640394088673, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6785714285714286, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3916256157635468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5467980295566504, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.44334975369458124, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7807881773399015, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.43965517241379315, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7413793103448275, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5504926108374384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7635467980295566, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.32758620689655177, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7155172413793104, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8866995073891626, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4064039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5701970443349754, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8694581280788178, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.45935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029557, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8891625615763546, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.48522167487684736, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6071428571428571, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.26108374384236455, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.20935960591133004, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8793103448275862, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5504926108374384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916256, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8694581280788176, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.47783251231527096, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8349753694581281, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2438423645320197, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64

Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.7783251231527094, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.40517241379310354, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4211822660098522, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.1502463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5098522167487685, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8497536945812807, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4704433497536946, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5517241379310345, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8029556650246306, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5960591133004927, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7216748768472907, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8399014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.29064039408867, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8226600985221675, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8300492610837438, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.23399014778325125, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7783251231527094, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8866995073891626, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.29310344827586204, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8066502463054187, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7044334975369458, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2512315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7241379310344828, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8719211822660099, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4039408866995074, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5911330049261083, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4630541871921182, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6317733990147784, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8448275862068966, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3805418719211823, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.729064039408867, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8374384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3645320197044335, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.685960591133005, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8374384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.35960591133004927, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6157635467980296, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333

Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7598522167487685, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5270935960591132, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.875615763546798, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3793103448275862, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4704433497536946, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5578817733990149, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.876847290640394, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3866995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5874384236453202, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8399014778325122, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5665024630541873, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6059113300492611, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8694581280788178, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.39162561576354676, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.46551724137931033, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8472906403940886, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.41009852216748766, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8596059113300493, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5049261083743842, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.44581280788177335, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8448275862068966, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.40394088669950745, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8620689655172413, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.33866995073891626, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8842364532019704, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5467980295566501, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8866995073891626, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5197044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6206896551724138, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8275862068965517, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64

Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.1921182266009852, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6206896551724138, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8842364532019704, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5369458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5270935960591133, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3497536945812808, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7044334975369458, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8596059113300493, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4014778325123153, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7561576354679803, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8325123152709359, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5369458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8669950738916257, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8620689655172414, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5652709359605912, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3669950738916256, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5849753694581281, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8448275862068966, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.49507389162561577, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5135467980295567, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8399014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.35221674876847286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5775862068965517, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8842364532019704, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5394088669950738, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5714285714285715, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8916256157635468, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.45073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5467980295566502, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2684729064039409, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7931034482758621, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8497536945812807, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6133004926108375, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5320197044334976, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6391625615763546, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8596059113300492, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.33251231527093594, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5886699507389163, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365

Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2512315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7229064039408868, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8719211822660098, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4568965517241379, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6133004926108375, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4618226600985222, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7241379310344827, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.3201970443349753, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8620689655172414, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.30295566502463056, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8374384236453203, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.6206896551724138, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8916256157635468, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5295566502463055, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8669950738916257, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2068965517241379, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8669950738916256, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8620689655172413, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4408866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8719211822660099, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4421182266009852, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8497536945812808, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3879310344827586, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8448275862068966, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4433497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6847290640394088, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8522167487684729, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.38916256157635465, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6083743842364533, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8694581280788176, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.39285714285714285, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5665024630541873, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8472906403940886, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5369458128078817, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5517241379310345, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8694581280788177, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64

Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.42857142857142855, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8066502463054188, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4876847290640394, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7586206896551724, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8866995073891626, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.26724137931034486, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8029556650246306, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.6206896551724138, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7660098522167489, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8645320197044335, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.20935960591133007, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029556, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.312807881773399, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6182266009852216, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8596059113300493, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.6527093596059113, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.562807881773399, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.49630541871921185, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7130541871921182, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.8596059113300492, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4802955665024631, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7955665024630542, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8399014778325123, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7032019704433498, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.874384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2894088669950739, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6822660098522167, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8571428571428572, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.49753694581280783, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6428571428571429, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.854679802955665, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4704433497536946, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5874384236453202, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.8571428571428571, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.40394088669950734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6440886699507389, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.8793103448275862, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.42857142857142855, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.605911330049261, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.8817733990147782, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3645320197044335, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.58128078817734, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Best AUC: 0.8990147783251231
Best parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}

In [146]:
best_params

{'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}

In [147]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
pipeline = pipe

In [148]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('clf',
                 SVC(C=1, degree=2, gamma=10, kernel='linear', probability=True,
                     random_state=100))])

In [149]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.7339901477832512

In [150]:
best_params

{'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}