In [1]:
import pandas as pd
import numpy as np
from os import listdir

In [2]:
import sklearn

In [3]:
# Ignore warnings
import warnings; warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline



from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
from sklearn import svm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

#from skbold.preproc.confounds import ConfoundRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn import preprocessing
    
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.impute import SimpleImputer



# Import libraries
import os
import numpy as np
import pandas as pd


from sklearn.feature_selection import RFE
from sklearn.metrics import balanced_accuracy_score

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn.model_selection import cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import make_scorer
from sklearn.metrics import \
    confusion_matrix, \
    accuracy_score, \
    matthews_corrcoef, \
    precision_score, \
    recall_score, \
    f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

import pymrmr

# Set the random generator seed
seed = 42

# Matplotlib settings
plt.style.use("classic")

# Seaborn settings
sns.set()
sns.set(font_scale=1.0)
sns.set_style({"font.family":"serif", "font.serif":["Times New Roman"]})

# Show seaborn settings
sns.axes_style()

{'axes.facecolor': '#EAEAF2',
 'axes.edgecolor': 'white',
 'axes.grid': True,
 'axes.axisbelow': True,
 'axes.labelcolor': '.15',
 'figure.facecolor': 'white',
 'grid.color': 'white',
 'grid.linestyle': '-',
 'text.color': '.15',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'lines.solid_capstyle': <CapStyle.round: 'round'>,
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'font.family': ['serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'xtick.bottom': False,
 'xtick.top': False,
 'ytick.left': False,
 'ytick.right': False,
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True}

In [4]:
# ------------------------------
# Define the classifier settings
# ------------------------------

model_params = {
    
    # General parameters
    "booster": "gbtree", 
    "silent": True, 
    "n_jobs": -1, 
    
    # Learning task parameters
    "objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "eval_metric": "error", 
    "seed": seed, 
    
    # Tree Booster parameters
    "n_estimators": 500, 
    "learning_rate": 0.20, 
    "gamma": 1.0, 
    "max_depth": 10, 
    "subsample": 1.0, 
    "colsample_bylevel": 1, 
    "colsample_bytree": 1.0, 
    "min_child_weight": 5
}

# ------------------------------------------
# Define the hyper-parameter tuning settings
# ------------------------------------------

param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [1, 3, 5, 6, 7, 9]  # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
#scale_pos_weight = total_negative_examples / total_positive_examples
}

search_settings = {
    "param_distributions": param_grid, 
    "scoring": "balanced_accuracy",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
}

In [5]:
# ---------------------------------
# Define the classification metrics
# ---------------------------------

def sensitivity_score(y_true, y_pred):
    return recall_score(y_true, y_pred)

def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)

In [6]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import os

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

# For models
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# For evaluation
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score

In [7]:
dataset = pd.read_csv('AU_features.csv')

In [8]:
dataset

,Unnamed: 0,index,patient,record,diagnosis,timestamp_start,timestamp_end,AU01_mid_Absolute energy,AU01_mid_Area under the curve,AU01_mid_Autocorrelation,...,AU04_eve_rsd,AU06_eve_rsd,AU07_eve_rsd,AU10_eve_rsd,AU12_eve_rsd,AU14_eve_rsd,AU15_eve_rsd,AU17_eve_rsd,AU23_eve_rsd,AU24_eve_rsd
0,0,0,P08,0,0,1.658354e+09,1.659996e+09,9.678860,0.135414,1.0,...,640.933848,138.122806,67.855963,196.857019,66.814940,115.890566,113.386691,50.928506,148.995611,245.019331
1,1,0,P08,1,0,1.659996e+09,1.661206e+09,346.605312,4.324380,3.0,...,259.048799,105.779751,44.732121,216.912520,76.445191,129.562811,152.426847,60.490611,132.494496,313.892010
2,2,0,P10,2,1,1.658354e+09,1.659996e+09,11.415247,0.220840,2.0,...,265.374413,121.008673,67.176427,179.301774,89.136093,96.213302,138.309344,69.726973,135.622399,202.271039
3,3,0,P10,3,0,1.659996e+09,1.662070e+09,94.056685,1.252902,28.0,...,337.776724,132.427033,49.625233,199.063960,105.206820,88.204114,150.012813,61.994076,175.510401,187.385402
4,4,0,P12,4,1,1.658441e+09,1.659996e+09,21.142705,0.263578,1.0,...,116.988466,134.024675,46.498004,202.483565,118.604478,92.273881,106.845779,70.164313,109.443031,191.562723
5,5,0,P12,5,1,1.659996e+09,1.661206e+09,20.994168,0.265975,4.0,...,291.131247,162.944912,71.969314,400.045107,112.831481,55.994326,136.362200,128.327725,247.829012,716.936198
6,6,0,P13,6,0,1.658700e+09,1.659996e+09,181.566144,2.958368,8.0,...,117.830345,53.715064,51.059604,207.427112,120.569142,72.696209,51.834430,21.960962,99.607412,262.799857
7,7,0,P13,7,0,1.659996e+09,1.661206e+09,11.106465,0.244671,2.0,...,113.367852,14.180311,3.167624,248.513328,78.299349,11.102685,54.539460,12.858752,52.764130,96.930184
8,8,0,P14,8,0,1.658700e+09,1.659910e+09,22.525144,0.321874,3.0,...,226.534759,121.200776,71.706519,233.281849,134.745633,141.773571,135.110341,53.541805,136.021599,292.753501
9,9,0,P15,9,0,1.658786e+09,1.660082e+09,NaN,NaN,NaN,...,149.356222,127.167824,47.665138,252.503638,157.825090,103.602792,142.036647,91.645749,128.844890,245.636518
10,10,0,P15,10,1,1.660082e+09,1.661206e+09,9.122883,0.145782,2.0,...,176.010829,205.710660,80.940490,334.540653,255.280704,232.573141,224.974399,111.707370,315.072176,756.285165
11,11,0,P16,11,0,1.658873e+09,1.659996e+09,1095.311385,14.134593,106.0,...,143.109325,102.441982,81.791770,264.078243,185.463949,184.215295,180.057549,93.819228,167.026598,583.883302
12,12,0,P16,12,0,1.659996e+09,1.661206e+09,681.964975,8.429412,75.0,...,123.366342,119.985935,96.157310,287.292748,330.117073,184.979622,238.650168,123.327143,242.287104,825.161342
13,13,0,P17,13,1,1.658786e+09,1.659996e+09,103.357981,1.222127,17.0,...,233.828141,133.229961,74.018833,382.003612,112.218930,111.523354,170.431072,96.982193,148.565087,201.637073
14,14,0,P18,14,1,1.658873e+09,1.659996e+09,143.395653,2.238986,3.0,...,199.171956,147.300449,70.534243,299.204224,151.707252,110.115983,127.825284,53.339761,159.486032,570.492425
15,15,0,P18,15,1,1.659996e+09,1.661206e+09,165.125454,2.305494,3.0,...,251.089074,151.898807,83.133014,289.405013,155.340625,99.134680,124.391735,58.558246,137.297885,433.001841
16,16,0,P19,16,1,1.658873e+09,1.660255e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,0,P19,17,1,1.660255e+09,1.661897e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,0,P20,18,0,1.658786e+09,1.660082e+09,93.122488,1.471653,15.0,...,223.227290,74.228437,35.484323,104.256564,81.664274,100.630279,204.572232,55.673490,105.513047,152.960011
19,19,0,P20,19,0,1.660082e+09,1.661810e+09,21.993645,0.418841,2.0,...,175.725185,101.650089,40.142880,135.156750,108.208542,90.361813,221.499680,64.376641,213.354004,304.211543
20,20,0,P21,20,0,1.658959e+09,1.660169e+09,85.657739,1.176673,2.0,...,170.149930,96.077160,24.357688,116.258776,116.609282,73.131860,85.603287,41.694647,108.089455,660.011791
21,21,0,P21,21,1,1.660169e+09,1.661810e+09,42.924443,0.610312,4.0,...,144.766483,62.805806,39.511453,88.369386,84.034607,90.932349,125.965679,54.331211,102.688696,681.279367
22,22,0,P23,22,0,1.659046e+09,1.660255e+09,155.213290,2.267547,9.0,...,198.896271,107.861649,54.578204,392.919226,137.959790,160.581798,171.616260,72.355338,162.307410,243.233741
23,23,0,P23,23,0,1.660255e+09,1.661810e+09,534.085917,6.975295,5.0,...,226.408986,129.136013,37.601563,268.066415,157.243745,79.333382,249.226501,84.421874,129.308944,224.228218
24,24,0,P24,24,1,1.659046e+09,1.660428e+09,138.596402,2.612807,26.0,...,59.130596,180.889244,31.778058,284.477056,170.252081,54.163010,40.953834,18.677663,61.513525,586.987408
25,25,0,P24,25,1,1.660428e+09,1.661810e+09,115.728873,2.464224,3.0,...,75.472210,188.103775,59.787927,370.667139,356.622469,96.086324,63.146310,18.664397,98.009214,1022.233854
26,26,0,P25,26,0,1.660774e+09,1.661983e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,0,P27,27,0,1.660514e+09,1.661724e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,0,P28,28,0,1.660514e+09,1.663279e+09,84.142252,1.221990,45.0,...,122.896545,82.315730,70.340876,203.538189,95.435663,119.512615,151.076418,79.773905,110.466292,594.009512
29,29,0,P29,29,0,1.659305e+09,1.660255e+09,820.571764,10.937797,52.0,...,326.163080,268.213295,189.061852,563.043404,413.715468,126.146560,281.737914,119.292613,270.373123,567.577611
30,30,0,P29,30,0,1.660255e+09,1.661810e+09,393.173109,6.846644,3.0,...,254.229115,221.596918,122.201653,414.903052,243.616697,125.401348,153.842572,80.639075,214.196939,624.834400
31,31,0,P30,31,1,1.659305e+09,1.660255e+09,1416.620799,16.535962,4.0,...,105.946971,93.830646,68.416012,191.139851,176.419904,235.518350,269.925095,96.137536,179.087188,1306.713779
32,32,0,P30,32,1,1.660255e+09,1.661810e+09,1160.854156,14.431542,4.0,...,114.778733,116.556963,86.600239,200.048984,161.740007,192.335126,199.418447,88.729381,199.037527,881.704162
33,33,0,P31,33,0,1.659391e+09,1.660601e+09,343.600896,3.752019,117.0,...,124.572221,159.961657,68.138527,162.203306,118.985189,29.275468,77.136295,20.850092,65.509279,109.147858
34,34,0,P31,34,0,1.660601e+09,1.661810e+09,88.795518,1.229210,9.0,...,78.754119,358.531784,42.900599,365.140726,148.064797,46.024062,204.973953,20.673249,277.241052,618.160373
35,35,0,P33,35,0,1.659478e+09,1.660601e+09,683.500080,8.385086,37.0,...,257.053051,63.041628,52.408926,93.484244,51.776076,232.714717,198.571807,96.446632,232.715141,740.728669
36,36,0,P33,36,0,1.660601e+09,1.662070e+09,739.117689,9.181307,49.0,...,237.285428,39.959283,46.353555,86.272375,48.590646,244.347590,161.575625,86.046657,312.787140,1277.881742
37,37,0,P34,37,0,1.659564e+09,1.660774e+09,49.064325,0.831729,5.0,...,132.593169,118.091150,44.411083,188.987689,130.145547,56.344655,104.679489,35.006988,92.109378,291.145953
38,38,0,P35,38,0,1.659564e+09,1.660774e+09,175.417481,2.792106,9.0,...,77.207277,70.274420,40.971311,111.910188,112.752043,84.181463,165.161023,76.876100,85.326094,483.397770
39,39,0,P35,39,0,1.660774e+09,1.662070e+09,360.949977,4.917896,11.0,...,82.736228,61.950241,37.731644,114.156391,119.057369,123.036794,166.337261,115.358173,81.844017,753.624206
40,40,0,P36,40,0,1.660860e+09,1.662070e+09,536.410087,7.089358,4.0,...,262.206323,78.567966,32.285163,273.577360,83.810995,152.070219,131.615641,38.341760,90.493755,585.309642
41,41,0,P38,41,0,1.659564e+09,1.661206e+09,36.118396,0.548272,3.0,...,114.902903,116.098638,49.560351,173.450666,154.911011,112.229959,208.413822,63.154765,195.126945,450.001606
42,42,0,P38,42,0,1.661206e+09,1.661983e+09,96.558084,1.334526,28.0,...,180.460393,96.917000,62.957496,141.880115,174.594280,159.757598,218.710025,86.989420,224.118844,838.483503

In [9]:
del dataset['Unnamed: 0']
del dataset['index']

In [10]:
group = dataset['patient']

In [11]:
del dataset['patient']

In [12]:
dataset = dataset.fillna(dataset.mean())

In [13]:
y = dataset['diagnosis']

In [14]:
del dataset['diagnosis']

In [15]:
records  = dataset['record']

In [16]:
del dataset['record']

# Binary classification

# Splitting and training

# Feature selection

In [17]:
import pymrmr

In [18]:
X = dataset.copy()

In [19]:
type_classification = 'binary'



#X = X.replace([np.nan, -np.inf, np.inf], 0)
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
#y = y.reshape((len(y), ))
X.insert(loc=0, column='class', value=y)
X_to_choose = X.copy()
#Discritize data
_, nr_col = np.shape(X)
for i in range(1, nr_col):
    discretizer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='kmeans')
    X.iloc[:, i] = discretizer.fit_transform(X.iloc[:, i].values.reshape(-1,1))
    
col = pymrmr.mRMR(X, 'MIQ', 50)

# Read the data again to import data with NaN values

In [21]:
dataset = pd.read_csv('AU_features.csv')
del dataset['Unnamed: 0']
del dataset['index']
group = dataset['patient']
groups = group
del dataset['patient']
y = dataset['diagnosis']
del dataset['diagnosis']
records  = dataset['record']
del dataset['record']
X = dataset.copy()

In [22]:
col100 = ['AU02_mor_Wavelet variance_3.57Hz',
 'AU02_aft_Power bandwidth',
 'AU04_mid_Median absolute diff',
 'AU23_mor_Spectral spread',
 'AU10_mid_SP_Summaries_welch_rect_centroid',
 'AU07_mor_Min',
 'AU06_mid_CO_FirstMin_ac',
 'AU17_aft_Wavelet variance_8.33Hz',
 'AU15_eve_Fundamental frequency',
 'AU14_aft_SB_BinaryStats_diff_longstretch0',
 'AU07_mor_Mean absolute diff',
 'AU01_eve_MFCC_0',
 'AU12_aft_MFCC_10',
 'AU17_mor_Median absolute diff',
 'AU12_mid_Wavelet absolute mean_3.12Hz',
 'AU12_eve_LPCC_11',
 'AU02_mor_Wavelet variance_4.17Hz',
 'AU02_aft_Spectral entropy',
 'AU14_mid_LPCC_9',
 'AU06_eve_CO_HistogramAMI_even_2_5',
 'AU07_mid_MFCC_5',
 'AU07_mid_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1',
 'AU12_mid_FC_LocalSimple_mean1_tauresrat',
 'AU01_mor_SP_Summaries_welch_rect_area_5_1',
 'AU12_aft_SB_BinaryStats_mean_longstretch1',
 'AU24_eve_FC_LocalSimple_mean1_tauresrat',
 'AU14_mid_SB_BinaryStats_mean_longstretch1',
 'AU02_mid_Sum absolute diff',
 'AU02_mor_Wavelet variance_2.78Hz',
 'AU06_mid_MFCC_0',
 'AU07_mor_MFCC_4',
 'AU15_eve_CO_FirstMin_ac',
 'AU23_mid_CO_trev_1_num',
 'AU06_aft_Wavelet variance_2.78Hz',
 'AU06_mor_Skewness',
 'AU04_mor_ECDF Percentile_1',
 'AU06_mid_SP_Summaries_welch_rect_area_5_1',
 'AU06_eve_Max power spectrum',
 'AU02_aft_Slope',
 'AU17_aft_Wavelet variance_6.25Hz',
 'AU02_mor_Wavelet variance_3.12Hz',
 'AU12_mid_Wavelet absolute mean_3.57Hz',
 'AU24_eve_Spectral centroid',
 'AU04_aft_Median frequency',
 'AU06_eve_Mean absolute deviation',
 'AU04_mid_Wavelet variance_25.0Hz',
 'AU01_mor_Spectral centroid',
 'AU23_aft_SB_BinaryStats_diff_longstretch0',
 'AU10_aft_MFCC_3',
 'AU02_mor_MFCC_11',
 'AU23_mor_Wavelet standard deviation_4.17Hz',
 'AU12_mid_MFCC_9',
 'AU02_aft_Spectral roll-off',
 'AU17_mor_Wavelet variance_25.0Hz',
 'AU17_mid_Wavelet variance_2.78Hz',
 'AU01_mor_SB_MotifThree_quantile_hh',
 'AU24_eve_CO_trev_1_num',
 'AU07_eve_Wavelet variance_8.33Hz',
 'AU14_aft_LPCC_4',
 'AU07_mid_IN_AutoMutualInfoStats_40_gaussian_fmmi',
 'AU15_mid_Variance',
 'AU14_mor_Mean diff',
 'AU02_aft_MFCC_6',
 'AU01_aft_Wavelet absolute mean_3.57Hz',
 'AU02_mor_Wavelet standard deviation_12.5Hz',
 'AU02_aft_SB_TransitionMatrix_3ac_sumdiagcov',
 'AU14_mid_LPCC_3',
 'AU12_eve_Spectral roll-on',
 'AU02_aft_Kurtosis',
 'AU14_mid_SP_Summaries_welch_rect_centroid',
 'AU01_mor_Spectral entropy',
 'AU17_aft_Wavelet variance_12.5Hz',
 'AU12_eve_SP_Summaries_welch_rect_centroid',
 'AU17_mor_SB_BinaryStats_mean_longstretch1',
 'AU12_aft_Median absolute deviation',
 'AU01_aft_Wavelet absolute mean_5.0Hz',
 'AU14_eve_Spectral distance',
 'AU14_mor_Human range energy',
 'AU02_mor_Wavelet energy_12.5Hz',
 'AU24_aft_ECDF Percentile_1',
 'AU04_mid_Slope',
 'AU23_aft_FC_LocalSimple_mean3_stderr',
 'AU02_mid_LPCC_3',
 'AU07_eve_Mean absolute diff',
 'AU06_mid_PD_PeriodicityWang_th0_01',
 'AU07_mid_Kurtosis',
 'AU14_eve_DN_OutlierInclude_p_001_mdrmd',
 'AU01_mor_FC_LocalSimple_mean3_stderr',
 'AU04_eve_Median',
 'AU14_mid_Human range energy',
 'AU01_aft_Wavelet absolute mean_2.78Hz',
 'AU01_mid_MFCC_10',
 'AU01_mid_MD_hrv_classic_pnn40',
 'AU04_mid_Wavelet standard deviation_8.33Hz',
 'AU02_aft_Maximum frequency',
 'AU12_mor_DN_OutlierInclude_n_001_mdrmd',
 'AU10_aft_Wavelet absolute mean_2.78Hz',
 'AU07_eve_Wavelet variance_12.5Hz',
 'AU17_aft_Neighbourhood peaks',
 'AU17_mor_Wavelet variance_5.0Hz']

In [23]:
col = ['AU02_mor_Wavelet variance_3.57Hz',
 'AU02_aft_Power bandwidth',
 'AU04_mid_Median absolute diff',
 'AU23_mor_Spectral spread',
 'AU10_mid_SP_Summaries_welch_rect_centroid',
 'AU07_mor_Min',
 'AU06_mid_CO_FirstMin_ac',
 'AU17_aft_Wavelet variance_8.33Hz',
 'AU15_eve_Fundamental frequency',
 'AU14_aft_SB_BinaryStats_diff_longstretch0',
 'AU07_mor_Mean absolute diff',
 'AU01_eve_MFCC_0',
 'AU12_aft_MFCC_10',
 'AU17_mor_Median absolute diff',
 'AU12_mid_Wavelet absolute mean_3.57Hz',
 'AU12_eve_LPCC_1',
 'AU02_mor_Wavelet variance_4.17Hz',
 'AU02_aft_Spectral entropy',
 'AU14_mid_LPCC_3',
 'AU06_eve_CO_HistogramAMI_even_2_5',
 'AU07_mid_MFCC_5',
 'AU07_mid_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1',
 'AU24_eve_FC_LocalSimple_mean1_tauresrat',
 'AU12_aft_SB_BinaryStats_mean_longstretch1',
 'AU01_mor_SP_Summaries_welch_rect_area_5_1',
 'AU02_mor_Wavelet variance_3.12Hz',
 'AU23_mid_CO_trev_1_num',
 'AU06_mid_MFCC_0',
 'AU07_eve_Wavelet variance_8.33Hz',
 'AU15_eve_CO_FirstMin_ac',
 'AU02_mid_Sum absolute diff',
 'AU06_aft_Wavelet variance_2.78Hz',
 'AU06_mid_SP_Summaries_welch_rect_area_5_1',
 'AU06_eve_Max power spectrum',
 'AU24_eve_CO_trev_1_num',
 'AU02_aft_Spectral roll-off',
 'AU02_mor_Wavelet variance_2.78Hz',
 'AU04_mor_ECDF Percentile_1',
 'AU07_mor_MFCC_4',
 'AU12_mid_MFCC_9',
 'AU06_mor_Skewness',
 'AU23_aft_SB_BinaryStats_diff_longstretch0',
 'AU17_aft_Wavelet variance_6.25Hz',
 'AU17_mid_Spectral spread',
 'AU04_aft_PD_PeriodicityWang_th0_01',
 'AU17_mor_Wavelet variance_25.0Hz',
 'AU12_mid_Wavelet absolute mean_3.12Hz',
 'AU04_mid_Wavelet variance_25.0Hz',
 'AU01_aft_Wavelet absolute mean_3.57Hz',
 'AU06_eve_Mean absolute deviation']

In [24]:
X_new = X[col]

In [25]:
X_new

,AU02_mor_Wavelet variance_3.57Hz,AU02_aft_Power bandwidth,AU04_mid_Median absolute diff,AU23_mor_Spectral spread,AU10_mid_SP_Summaries_welch_rect_centroid,AU07_mor_Min,AU06_mid_CO_FirstMin_ac,AU17_aft_Wavelet variance_8.33Hz,AU15_eve_Fundamental frequency,AU14_aft_SB_BinaryStats_diff_longstretch0,...,AU06_mor_Skewness,AU23_aft_SB_BinaryStats_diff_longstretch0,AU17_aft_Wavelet variance_6.25Hz,AU17_mid_Spectral spread,AU04_aft_PD_PeriodicityWang_th0_01,AU17_mor_Wavelet variance_25.0Hz,AU12_mid_Wavelet absolute mean_3.12Hz,AU04_mid_Wavelet variance_25.0Hz,AU01_aft_Wavelet absolute mean_3.57Hz,AU06_eve_Mean absolute deviation
0,0.186567,43.951400,0.000605,15.589326,0.490874,2.221583e-11,4.0,0.151799,0.086281,7.0,...,0.764510,9.0,0.192054,16.541173,9.0,0.055246,0.384620,0.003791,0.000843,0.309439
1,0.147166,43.767840,0.004802,15.370427,0.607456,1.824056e-07,9.0,0.084129,0.355872,5.0,...,0.702563,6.0,0.107988,15.293679,9.0,0.056255,0.019816,0.034760,0.011656,0.363282
2,NaN,31.007752,0.000410,NaN,0.098175,NaN,4.0,0.100580,0.128370,5.0,...,NaN,6.0,0.121938,15.765825,46.0,NaN,0.058303,0.006476,0.012466,0.294600
3,NaN,47.572816,0.016624,NaN,0.570641,NaN,7.0,0.118071,0.133958,6.0,...,NaN,8.0,0.147971,15.744293,9.0,NaN,0.006711,0.028161,0.025008,0.235812
4,0.240490,45.569620,0.008968,15.819602,0.981748,1.519344e-07,1.0,0.162319,1.025641,7.0,...,1.337029,6.0,0.214239,15.576191,9.0,0.064349,0.162190,0.028769,0.022244,0.317031
5,0.253240,43.548387,0.046149,15.477934,0.834486,7.581991e-09,3.0,0.226006,1.290323,6.0,...,1.542809,6.0,0.285970,15.585747,7.0,0.069865,0.162574,0.059110,0.025283,0.215253
6,NaN,44.879899,0.071021,NaN,0.220893,NaN,10.0,0.087294,0.033795,9.0,...,NaN,8.0,0.102071,15.898847,4.0,NaN,0.003445,0.035580,0.009192,0.336451
7,NaN,NaN,0.017715,NaN,0.638136,NaN,4.0,NaN,2.500000,NaN,...,NaN,NaN,NaN,12.013805,NaN,NaN,0.057547,0.012378,NaN,0.078012
8,0.194593,45.175936,0.059333,15.610962,0.147262,3.748437e-11,2.0,0.142290,0.128535,6.0,...,0.166680,7.0,0.194439,15.509516,18.0,0.058207,0.030181,0.046384,0.004222,0.346560
9,0.217247,45.868152,NaN,15.964415,NaN,4.287292e-07,NaN,0.123698,0.095329,7.0,...,0.333888,6.0,0.162191,NaN,4.0,0.051073,NaN,NaN,0.010691,0.337696
10,0.280841,45.293315,0.006238,15.710559,1.521709,1.982381e-09,4.0,0.094999,0.107643,6.0,...,0.847903,7.0,0.125388,15.750868,5.0,0.086313,0.024650,0.020487,0.028593,0.209608
11,NaN,38.376754,0.046292,NaN,0.141126,NaN,6.0,0.133368,0.016844,7.0,...,NaN,8.0,0.187307,15.891538,26.0,NaN,0.001044,0.036406,0.001419,0.386518
12,0.191363,37.598598,0.005444,16.117730,0.113515,2.105434e-08,15.0,0.119744,0.027278,7.0,...,-1.303342,10.0,0.153770,15.670278,7.0,0.023394,0.009274,0.026162,0.003500,0.354670
13,0.249191,43.243243,0.001653,16.903918,0.932660,5.486475e-01,5.0,0.204348,0.377834,5.0,...,1.544158,5.0,0.293788,15.682235,3.0,0.005989,0.094718,0.009857,0.024609,0.250735
14,0.304589,27.842227,0.003915,16.496403,1.122874,3.246766e-07,3.0,0.092718,0.080710,6.0,...,1.913651,7.0,0.114606,15.797915,21.0,0.051755,0.005071,0.016807,0.057950,0.286617
15,0.200386,37.558685,0.005427,15.621048,1.055379,9.930717e-08,5.0,0.190494,0.179533,5.0,...,1.379404,6.0,0.337676,15.737368,6.0,0.060736,0.010265,0.022171,0.051976,0.301884
16,0.351077,42.433234,NaN,15.399795,1.178097,1.501105e-06,3.0,0.134745,NaN,7.0,...,0.237886,5.0,0.162334,NaN,5.0,0.093614,NaN,NaN,0.083562,NaN
17,0.288127,NaN,NaN,15.581101,2.356194,7.236109e-08,2.0,NaN,NaN,NaN,...,3.909151,NaN,NaN,NaN,NaN,0.058125,NaN,NaN,NaN,NaN
18,0.173641,46.636086,0.006499,15.973883,0.024544,3.279187e-01,4.0,0.098293,0.337268,6.0,...,-0.122449,6.0,0.125670,15.526161,13.0,0.012194,0.045041,0.012859,0.007383,0.342839
19,0.092674,45.302714,0.012632,14.813716,0.220893,1.195912e-06,5.0,0.110467,0.170648,6.0,...,1.077754,6.0,0.136125,15.975334,3.0,0.038212,0.023205,0.027465,0.004710,0.349839
20,NaN,44.075829,0.004638,NaN,0.362019,NaN,3.0,0.076631,0.166667,5.0,...,NaN,7.0,0.128705,15.402081,5.0,NaN,0.011413,0.030531,0.022536,0.406119
21,NaN,45.132743,0.083360,NaN,0.687223,NaN,1.0,0.070863,0.099206,6.0,...,NaN,6.0,0.077190,15.430900,3.0,NaN,0.082294,0.057284,0.001968,0.378174
22,0.105085,40.592784,0.005188,16.118675,0.662680,1.176041e-04,6.0,0.105146,0.061690,9.0,...,-1.417990,7.0,0.159533,15.538799,7.0,0.026453,0.011242,0.011083,0.005137,0.288064
23,0.318868,38.983051,0.010396,14.763885,0.346680,4.473728e-06,10.0,0.104829,0.135044,5.0,...,0.984166,6.0,0.195462,15.382472,27.0,0.027005,0.004326,0.039933,0.147230,0.269276
24,NaN,33.481745,0.015225,NaN,0.131922,NaN,5.0,0.061790,0.042644,6.0,...,NaN,7.0,0.078934,15.499438,196.0,NaN,0.001616,0.027960,0.013146,0.243567
25,0.002442,33.451957,0.037855,16.169932,0.006136,5.005533e-01,4.0,0.020166,0.751880,5.0,...,2.287572,6.0,0.029405,15.832759,0.0,0.061319,0.009605,0.020457,0.002356,0.223165
26,0.125919,47.368421,NaN,15.612467,NaN,1.000295e-09,NaN,0.072849,NaN,5.0,...,1.677944,6.0,0.098373,NaN,8.0,0.025753,NaN,NaN,0.005023,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
28,0.127737,46.000000,0.005040,12.021358,0.711767,2.330979e-02,14.0,0.137010,0.130804,6.0,...,-0.767679,5.0,0.181605,15.506293,6.0,0.039449,0.030718,0.020777,0.024383,0.407023
29,0.120807,44.326699,0.001544,16.498805,0.099709,2.676369e-10,15.0,0.100034,0.029674,6.0,...,6.665126,8.0,0.131590,15.729969,11.0,0.021000,0.000009,0.012141,0.001944,0.148187
30,0.092774,43.017903,0.001256,15.221053,0.536126,1.455245e-06,10.0,0.088444,0.025615,10.0,...,7.150355,7.0,0.112808,16.166528,9.0,0.016208,0.000140,0.007860,0.001386,0.194457
31,0.268779,44.071021,0.060742,15.548697,0.435651,3.394816e-03,5.0,0.236039,0.065660,7.0,...,0.738891,7.0,0.272666,15.374584,19.0,0.063988,0.003135,0.072545,0.004602,0.416871
32,0.370283,43.961503,0.108817,15.413824,0.427981,2.086173e-07,10.0,0.182859,0.030312,7.0,...,2.521185,7.0,0.237233,15.419117,16.0,0.068459,0.000117,0.068331,0.005448,0.385349
33,0.134777,35.294118,0.052307,15.794972,0.362019,5.042003e-06,5.0,0.080375,0.067935,2.0,...,1.955373,3.0,0.075514,15.396033,0.0,0.024960,0.006450,0.030265,0.197075,0.148218
34,0.139976,NaN,0.048178,15.179483,0.674952,1.205475e-09,10.0,NaN,0.300300,NaN,...,9.489764,NaN,NaN,15.746781,NaN,0.048749,0.007161,0.031554,NaN,0.106855
35,NaN,40.481704,0.001533,NaN,0.024544,NaN,8.0,0.156869,0.065253,7.0,...,NaN,9.0,0.217450,15.960727,5.0,NaN,0.020363,0.013580,0.004236,0.386270
36,NaN,44.209215,0.001161,NaN,0.015340,NaN,9.0,0.116929,0.095012,7.0,...,NaN,7.0,0.143361,15.718070,15.0,NaN,0.014173,0.007487,0.006181,0.247371
37,0.110030,44.820183,0.039422,13.135183,0.147262,9.345953e-03,6.0,0.057986,0.219941,7.0,...,0.448804,7.0,0.071122,15.781073,19.0,0.042925,0.012369,0.043917,0.007772,0.315544
38,NaN,43.322607,0.042966,NaN,0.159534,NaN,11.0,0.149271,0.059471,8.0,...,NaN,7.0,0.198054,16.056566,28.0,NaN,0.018810,0.034329,0.007004,0.388350
39,NaN,44.694887,0.044296,NaN,0.184078,NaN,13.0,0.156796,0.029560,8.0,...,NaN,6.0,0.217436,15.948041,15.0,NaN,0.001473,0.042139,0.014283,0.357802
40,0.796562,45.636275,0.007909,15.481633,0.523087,2.252627e-06,15.0,0.122497,0.042617,7.0,...,0.826254,7.0,0.148495,15.453741,5.0,0.045408,0.009702,0.036137,0.003768,0.392873
41,NaN,45.253863,0.014460,NaN,0.257709,NaN,17.0,0.131547,0.101885,8.0,...,NaN,8.0,0.175020,15.447397,17.0,NaN,0.007427,0.038391,0.007773,0.362279
42,0.000753,45.117845,0.017109,14.884282,0.122718,5.314474e-07,4.0,0.055072,0.111607,5.0,...,7.482523,5.0,0.080723,16.350596,2.0,0.013463,0.001740,0.030316,0.003153,0.400042

In [26]:
X_new = X_new.astype(float)

# Training and validation

# Test

In [27]:
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
ratio_scaler

2.0714285714285716

In [28]:
from sklearn.model_selection import LeaveOneGroupOut

logo = LeaveOneGroupOut()
logo.get_n_splits(X_new, y, group)

25

# Decision Tree

In [29]:
from sklearn.model_selection import RandomizedSearchCV, LeaveOneGroupOut
from xgboost import XGBClassifier
from scipy.stats import randint, uniform
import numpy as np

In [30]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
distributions_dt = dict(max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced', None])

In [31]:
param_dist = distributions_dt
model = dt

In [32]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'max_depth': np.random.choice(distributions_dt['max_depth']),
            'min_samples_split': np.random.choice(distributions_dt['min_samples_split']),
            'min_samples_leaf': np.random.choice(distributions_dt['min_samples_leaf']),
            'max_features': np.random.choice(distributions_dt['max_features']),
            'class_weight': np.random.choice(distributions_dt['class_weight']),
        }
        print(f"Testing parameters: {params}")
        model = DecisionTreeClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(dt, X_new, y, group, param_grid, n_iter = 100)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.7007389162561576, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.7179802955665024, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 6, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 6, 'class_weight': None}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6834975369458128, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.6834975369458128, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.5061576354679803, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': None}

Parameters: {'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': None}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 73, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 73, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': None}
Parameters: {'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': None}
AUC: 0.5578817733990148, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 76, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': None}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': None}
Parameters: {'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}

Parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': None}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': None}
AUC: 0.6133004926108374, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': None}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6317733990147784, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.5960591133004927, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.5049261083743841, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.49014778325123154, Precision: 0.3157894736842105, Recall: 0.42857142857142855, F1-score: 0.36363636363636365
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': None}
AUC: 0.6822660098522167, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': None}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'max_depth': 22, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': None}

Parameters: {'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 72, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 72, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': None}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': None}
AUC: 0.5775862068965517, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 65, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 65, 'class_weight': None}
AUC: 0.6834975369458128, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.54064039408867, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.5935960591133005, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.5591133004926109, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 99, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': None}
AUC: 0.5751231527093597, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': None}
AUC: 0.5246305418719212, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}
AUC: 0.7204433497536945, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': None}
AUC: 0.6293103448275861, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': None}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6120689655172414, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 55, 'class_weight': 'balanced'}

Parameters: {'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 80, 'class_weight': None}
Parameters: {'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 80, 'class_weight': None}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': None}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': None}
AUC: 0.6305418719211823, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.646551724137931, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': None}
AUC: 0.5763546798029557, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Best AUC: 0.7204433497536945
Best parameters: {'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': None}

In [33]:
model.set_params(**best_params)

DecisionTreeClassifier(max_depth=7, max_features=10, min_samples_leaf=0.5,
                       min_samples_split=0.2)

In [34]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    model.fit(X_train, y_train)

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.10960591133004924, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682, Accuracy: 0.6046511627906976, Balanced Accuracy: 0.46674876847290636

# Decision Tree + SMOTE

In [35]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'max_depth': np.random.choice(distributions_dt['max_depth']),
            'min_samples_split': np.random.choice(distributions_dt['min_samples_split']),
            'min_samples_leaf': np.random.choice(distributions_dt['min_samples_leaf']),
            'max_features': np.random.choice(distributions_dt['max_features']),
            'class_weight': np.random.choice(distributions_dt['class_weight']),
        }
        print(f"Testing parameters: {params}")
        model = DecisionTreeClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(dt, X_new, y, group, param_grid, n_iter = 100)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 4, 'class_weight': None}
AUC: 0.5714285714285714, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': None}
AUC: 0.35591133004926107, Precision: 0.2222222222222222, Recall: 0.2857142857142857, F1-score: 0.25
Testing parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.770935960591133, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': None}
Parameters: {'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': None}
AUC: 0.4532019704433498, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 95, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 95, 'class_weight': None}
AUC: 0.47660098522167493, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 3, 'class_weight': None}
Parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 3, 'class_weight': None}
AUC: 0.6773399014778325, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': None}
AUC: 0.5541871921182265, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.5344827586206897, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.6502463054187193, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.6970443349753694, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.5677339901477833, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': None}
AUC: 0.7339901477832513, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': None}
AUC: 0.605911330049261, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'max_depth': 25, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': None}
AUC: 0.5012315270935961, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': None}
Parameters: {'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': None}
AUC: 0.5948275862068966, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 3, 'class_weight': None}
AUC: 0.4396551724137931, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': None}
AUC: 0.7229064039408867, Precision: 0.4090909090909091, Recall: 0.6428571428571429, F1-score: 0.5000000000000001
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': None}
AUC: 0.8189655172413793, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': None}
Parameters: {'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': None}
AUC: 0.6366995073891626, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.5665024630541873, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': None}
Parameters: {'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': None}
AUC: 0.6305418719211824, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.5381773399014779, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 80, 'class_weight': None}

Parameters: {'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 80, 'class_weight': None}
AUC: 0.42241379310344823, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.7426108374384235, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5812807881773399, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.5049261083743842, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6416256157635467, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.7746305418719212, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': None}
AUC: 0.5529556650246306, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 39, 'class_weight': None}
AUC: 0.5147783251231527, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': None}
Parameters: {'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': None}
AUC: 0.6428571428571429, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.6231527093596059, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': None}
AUC: 0.46921182266009853, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.480295566502463, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': None}
AUC: 0.5800492610837439, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': None}
Parameters: {'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': None}
AUC: 0.6256157635467979, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.6354679802955665, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': None}
Parameters: {'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': None}
AUC: 0.4704433497536946, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': None}
AUC: 0.37438423645320196, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Testing parameters: {'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': None}
AUC: 0.5357142857142858, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 38, 'class_weight': None}
Parameters: {'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 38, 'class_weight': None}
AUC: 0.6600985221674877, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'max_depth': 16, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.43596059113300495, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}

Parameters: {'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': None}
AUC: 0.6514778325123153, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': None}
Parameters: {'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': None}
AUC: 0.4839901477832512, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': None}
AUC: 0.6958128078817734, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': None}
AUC: 0.5652709359605911, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': None}
AUC: 0.5615763546798029, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.39778325123152714, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': None}
Parameters: {'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': None}
AUC: 0.5726600985221674, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.522167487684729, Precision: 0.42105263157894735, Recall: 0.5714285714285714, F1-score: 0.48484848484848486
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 65, 'class_weight': None}
AUC: 0.6366995073891626, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6847290640394088, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6231527093596059, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.583743842364532, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4495073891625616, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.5184729064039408, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': None}
AUC: 0.5886699507389163, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6440886699507389, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.6354679802955665, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.41133004926108374, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': None}
Parameters: {'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': None}
AUC: 0.5677339901477831, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': None}
Parameters: {'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': None}
AUC: 0.6182266009852216, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.3103448275862069, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}

Parameters: {'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.4655172413793103, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.4421182266009852, Precision: 0.2727272727272727, Recall: 0.21428571428571427, F1-score: 0.23999999999999996
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.8386699507389163, Precision: 0.9090909090909091, Recall: 0.7142857142857143, F1-score: 0.8
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': None}
AUC: 0.6527093596059113, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 46, 'class_weight': None}
Parameters: {'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 46, 'class_weight': None}
AUC: 0.625615763546798, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5849753694581281, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': None}
Parameters: {'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': None}
AUC: 0.5738916256157636, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': None}
Parameters: {'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': None}
AUC: 0.6588669950738917, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.27463054187192115, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Testing parameters: {'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.6514778325123153, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.48275862068965514, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.5480295566502462, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': None}
Parameters: {'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': None}
AUC: 0.4568965517241379, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': None}
AUC: 0.6416256157635468, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.458128078817734, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.7155172413793103, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': None}
AUC: 0.6453201970443351, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': None}
AUC: 0.5147783251231527, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': None}
Parameters: {'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': None}
AUC: 0.37684729064039413, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5233990147783252, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.562807881773399, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': None}

Parameters: {'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': None}
AUC: 0.4839901477832512, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.6120689655172413, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 76, 'class_weight': None}
Parameters: {'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 76, 'class_weight': None}
AUC: 0.5307881773399015, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
Parameters: {'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': None}
AUC: 0.7056650246305418, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5504926108374385, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': None}
Parameters: {'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 16, 'class_weight': None}
AUC: 0.7364532019704434, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': None}
AUC: 0.4482758620689655, Precision: 0.2, Recall: 0.14285714285714285, F1-score: 0.16666666666666666
Testing parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': None}
Parameters: {'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': None}
AUC: 0.603448275862069, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
Parameters: {'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': None}
AUC: 0.47536945812807874, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.42733990147783246, Precision: 0.26666666666666666, Recall: 0.2857142857142857, F1-score: 0.2758620689655172
Best AUC: 0.8386699507389163
Best parameters: {'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}

In [36]:
model = dt.set_params(**best_params)

In [37]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.5233990147783251, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997, Accuracy: 0.5813953488372093, Balanced Accuracy: 0.541871921182266

# Random Forest

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param_grid = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])

In [40]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'n_estimators': np.random.choice(param_grid['n_estimators']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'min_samples_split': np.random.choice(param_grid['min_samples_split']),
            'min_samples_leaf': np.random.choice(param_grid['min_samples_leaf']),
            'max_features': np.random.choice(param_grid['max_features']),
            'class_weight': np.random.choice(param_grid['class_weight']),

        }
        print(f"Testing parameters: {params}")
        pipeline = RandomForestClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

rf = RandomForestClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(rf, X_new, y, group, param_grid, n_iter = 500)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.5504926108374384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5172413793103449, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.6637931034482758, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.6834975369458128, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.8152709359605911, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.7746305418719212, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.8004926108374384, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.7549261083743843, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.624384236453202, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.7980295566502462, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.8152709359605911, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.7857142857142857, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.43842364532019706, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.4963054187192118, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.7216748768472906, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.49507389162561577, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.6637931034482758, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 64, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.7857142857142857, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.8078817733990147, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.7980295566502462, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.896551724137931, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.8078817733990149, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.7733990147783252, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.6982758620689655, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.7832512315270936, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.3805418719211823, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.5825123152709359, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.8472906403940886, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.7758620689655172, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.3879310344827586, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.6674876847290641, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.8189655172413793, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.8522167487684729, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.7783251231527093, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.4568965517241379, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.6637931034482758, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.6773399014778325, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 4, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.583743842364532, Precision: 0.36363636363636365, Recall: 0.5714285714285714, F1-score: 0.4444444444444444
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.6958128078817735, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.7955665024630542, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.8620689655172414, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.8103448275862069, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4852216748768473, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.6884236453201971, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.7635467980295567, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.7610837438423645, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.7623152709359606, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.7487684729064039, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5972906403940885, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5504926108374384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.6588669950738916, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.7364532019704434, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.7610837438423645, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.7204433497536946, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.6169950738916257, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.7105911330049262, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.8078817733990149, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.5110837438423645, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6847290640394089, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.8522167487684729, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.7857142857142857, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.8029556650246306, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.8374384236453202, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.7376847290640394, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.8645320197044335, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.852216748768473, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.7487684729064039, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.812807881773399, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.5036945812807881, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.7783251231527093, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.7364532019704433, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.5344827586206896, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.6970443349753694, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.6933497536945814, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.7561576354679803, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.4679802955665025, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.519704433497537, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'n_estimators': 2, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.7561576354679803, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.729064039408867, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.7192118226600985, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.6798029556650246, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.4273399014778326, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.5233990147783251, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.7733990147783252, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.5147783251231527, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.8103448275862069, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.8226600985221675, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.8349753694581281, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.6822660098522167, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.6490147783251231, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.6428571428571428, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.7807881773399015, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.6108374384236454, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.7844827586206896, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.7783251231527093, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.6945812807881774, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4568965517241379, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6391625615763546, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.8078817733990148, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.7142857142857143, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.6539408866995073, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.7376847290640394, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.8571428571428572, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.8596059113300493, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 4, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6502463054187192, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6169950738916257, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.708128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.6600985221674878, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.6834975369458128, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.5763546798029556, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.5061576354679804, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.6810344827586208, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.7463054187192117, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 20, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.8078817733990148, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.7475369458128079, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.8103448275862069, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.7610837438423644, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.8078817733990148, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.519704433497537, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.8177339901477834, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6724137931034483, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.8300492610837438, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.479064039408867, Precision: 0.3333333333333333, Recall: 0.5714285714285714, F1-score: 0.4210526315789474
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.6588669950738916, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.8497536945812808, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Testing parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.7007389162561577, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.8078817733990149, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.8152709359605912, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.6810344827586208, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.8078817733990149, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.8842364532019704, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.6810344827586208, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.7487684729064039, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.4975369458128079, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.812807881773399, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.812807881773399, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.6342364532019704, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.6588669950738916, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.7549261083743842, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.5344827586206896, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.8251231527093595, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.8842364532019705, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.9064039408866995, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 87, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.6982758620689654, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.6416256157635467, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.5123152709359605, Precision: 0.3333333333333333, Recall: 0.5, F1-score: 0.4
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.7278325123152709, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.7857142857142857, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.7266009852216748, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.5036945812807881, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.4667487684729064, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5751231527093595, Precision: 0.34782608695652173, Recall: 0.5714285714285714, F1-score: 0.4324324324324324
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.7105911330049262, Precision: 1.0, Recall: 0.35714285714285715, F1-score: 0.5263157894736842
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.7635467980295567, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.6428571428571429, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.6490147783251232, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.7832512315270936, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6490147783251232, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6231527093596059, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.519704433497537, Precision: 0.391304347826087, Recall: 0.6428571428571429, F1-score: 0.4864864864864865
Testing parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.8300492610837439, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.6982758620689655, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.8152709359605911, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.6810344827586208, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5135467980295566, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.3362068965517241, Precision: 0.29411764705882354, Recall: 0.35714285714285715, F1-score: 0.3225806451612903
Testing parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.7746305418719213, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 200, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.7857142857142857, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Testing parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 8, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.7204433497536947, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 31, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.7955665024630542, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.6293103448275863, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.7647783251231527, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4667487684729065, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.6366995073891626, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.38916256157635465, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.48891625615763556, Precision: 0.3333333333333333, Recall: 0.7142857142857143, F1-score: 0.4545454545454545
Testing parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.6834975369458128, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.3830049261083744, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.5701970443349753, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.4766009852216748, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.7155172413793104, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.7635467980295567, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.7229064039408868, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6982758620689654, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.5024630541871922, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 4, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 17, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.5233990147783251, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.8078817733990149, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.812807881773399, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.8300492610837438, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.8103448275862069, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.7881773399014778, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.7635467980295566, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.8669950738916257, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.7167487684729064, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.8152709359605911, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 48, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.7586206896551724, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.8522167487684729, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 2, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.768472906403941, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.7229064039408867, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 26, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.7561576354679802, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.8399014778325122, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.7955665024630543, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.6600985221674878, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.6391625615763548, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.3682266009852217, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.4298029556650247, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.7758620689655172, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.7980295566502462, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.3460591133004926, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.42980295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6810344827586208, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Best AUC: 0.9064039408866995
Best parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}

In [41]:
model = RandomForestClassifier(**best_params, random_state = 42)

In [42]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train, y_train)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9064039408866995, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75, Accuracy: 0.8604651162790697, Balanced Accuracy: 0.8041871921182266

# Random Forest + SMOTE

In [43]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param_grid = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])

In [44]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'n_estimators': np.random.choice(param_grid['n_estimators']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'min_samples_split': np.random.choice(param_grid['min_samples_split']),
            'min_samples_leaf': np.random.choice(param_grid['min_samples_leaf']),
            'max_features': np.random.choice(param_grid['max_features']),
            'class_weight': np.random.choice(param_grid['class_weight']),

        }
        print(f"Testing parameters: {params}")
        pipeline = RandomForestClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

rf = RandomForestClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(rf, X_new, y, group, param_grid, n_iter = 500)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 16, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.6699507389162561, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.7906403940886699, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.7339901477832512, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.7364532019704434, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6871921182266011, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 5, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 92, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.479064039408867, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.6724137931034483, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.7241379310344827, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.560344827586207, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.6514778325123153, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.6736453201970443, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.6896551724137931, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.7955665024630542, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.8251231527093597, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.520935960591133, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6145320197044335, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.3669950738916256, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.6748768472906405, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.7413793103448276, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 25, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.6293103448275862, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 4, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 16, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.6182266009852215, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 65, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.7635467980295567, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6798029556650246, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.6699507389162561, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.7487684729064039, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6773399014778325, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.6576354679802956, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.7142857142857143, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.6699507389162561, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6798029556650247, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.7167487684729064, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.6798029556650247, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.7118226600985222, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.8448275862068966, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.583743842364532, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.45443349753694584, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.6379310344827587, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 32, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.7610837438423645, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 9, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 9, 'class_weight': 'balanced'}
AUC: 0.8078817733990148, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.7044334975369457, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.6847290640394089, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.70935960591133, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.603448275862069, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 40, 'class_weight': 'balanced'}
AUC: 0.5480295566502463, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.46798029556650245, Precision: 0.18181818181818182, Recall: 0.14285714285714285, F1-score: 0.16
Testing parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 31, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.7450738916256157, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 11, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.7130541871921182, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.7512315270935961, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 7, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.42733990147783246, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.897783251231527, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6945812807881773, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.6687192118226601, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.7463054187192119, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6945812807881773, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.7697044334975369, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 2, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5369458128078817, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.7044334975369458, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.6896551724137931, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 9, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6600985221674878, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6650246305418719, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 27, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.5997536945812807, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 8, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.7635467980295566, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 8, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 28, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.7315270935960592, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6896551724137931, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.5948275862068966, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 64, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6822660098522167, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.6490147783251231, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.8669950738916257, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.7315270935960592, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.39532019704433496, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.75, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 9, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.3076923076923077, Recall: 0.2857142857142857, F1-score: 0.29629629629629634
Testing parameters: {'n_estimators': 64, 'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 16, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.7266009852216749, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 5, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.876847290640394, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.624384236453202, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.6921182266009851, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.5726600985221675, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.6539408866995075, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.70935960591133, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.6096059113300492, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 21, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.5628078817733991, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'n_estimators': 32, 'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 51, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 25, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 51, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 11, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 30, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 20, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 73, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 6, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.8399014778325123, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.28940886699507384, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 12, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 8, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 33, 'class_weight': 'balanced'}
AUC: 0.6970443349753693, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.7253694581280787, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 24, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 24, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.688423645320197, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.6637931034482759, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 23, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.7955665024630542, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 5, 'class_weight': 'balanced'}
AUC: 0.5997536945812808, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.8448275862068966, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Testing parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.8152709359605912, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.7019704433497537, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.7315270935960592, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 4, 'max_depth': 3, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 21, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 38, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 25, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 14, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.6588669950738917, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 32, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 25, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 86, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 26, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 85, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.6366995073891626, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.7056650246305418, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.7339901477832511, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.730295566502463, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.6613300492610837, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 30, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 18, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.7635467980295567, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.7352216748768473, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 13, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 1, 'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 19, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 2, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.5529556650246306, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 24, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.7142857142857143, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 0.1, 'min_samples_leaf': 0.2, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.7364532019704434, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 8, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.7844827586206897, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.5024630541871922, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.5874384236453203, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 0.8, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 24, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.479064039408867, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.8066502463054187, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 4, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.729064039408867, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 10, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 20, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.7770935960591132, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 48, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.6921182266009852, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 8, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 6, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.6428571428571429, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.6945812807881773, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 22, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 11, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 6, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.7167487684729065, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.6637931034482758, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 32, 'class_weight': 'balanced'}
AUC: 0.6428571428571428, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 16, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.6921182266009852, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 64, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.5, 'max_features': 84, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.7007389162561577, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 42, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.6330049261083743, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.6859605911330049, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.30000000000000004, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.7118226600985221, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 35, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 25, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 14, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.6625615763546798, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 95, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 95, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 3, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.7118226600985221, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 19, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 29, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.7783251231527094, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.768472906403941, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.1, 'max_features': 59, 'class_weight': 'balanced'}
AUC: 0.7931034482758621, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.6995073891625616, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.41625615763546797, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.7216748768472907, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 9, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.4150246305418719, Precision: 0.18181818181818182, Recall: 0.14285714285714285, F1-score: 0.16
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.6884236453201971, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 34, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 68, 'class_weight': 'balanced'}
AUC: 0.6256157635467979, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Testing parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 32, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 28, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.7167487684729065, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 5, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 99, 'class_weight': 'balanced'}
AUC: 0.7647783251231527, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.6243842364532018, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 44, 'class_weight': 'balanced'}
AUC: 0.7660098522167488, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 54, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 46, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 32, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.2, 'max_features': 46, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 17, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 30, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 88, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 49, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 36, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.7413793103448276, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 55, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 29, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 79, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 54, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 2, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 54, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.6748768472906405, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 29, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 18, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 0.5, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.7142857142857144, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 70, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 89, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 12, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 66, 'class_weight': 'balanced'}
AUC: 0.6059113300492611, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 19, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 4, 'class_weight': 'balanced'}
AUC: 0.5221674876847291, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 14, 'class_weight': 'balanced'}
AUC: 0.7881773399014779, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 7, 'class_weight': 'balanced'}
AUC: 0.8078817733990148, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.5480295566502462, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.7635467980295566, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 4, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.770935960591133, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 0.8, 'min_samples_leaf': 0.30000000000000004, 'max_features': 60, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 1, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.6822660098522169, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 17, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 41, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 27, 'class_weight': 'balanced'}
AUC: 0.7906403940886699, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.7364532019704434, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 12, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.5874384236453202, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 7, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 1, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 19, 'min_samples_split': 0.2, 'min_samples_leaf': 0.4, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 27, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 17, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 21, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.4, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 23, 'min_samples_split': 0.8, 'min_samples_leaf': 0.4, 'max_features': 47, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 0.9, 'min_samples_leaf': 0.5, 'max_features': 22, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 28, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 4, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 20, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 23, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.5, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 21, 'min_samples_split': 0.9, 'min_samples_leaf': 0.4, 'max_features': 52, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 1, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 6, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 1, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 31, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.5677339901477831, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 4, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 50, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 32, 'min_samples_split': 0.9, 'min_samples_leaf': 0.1, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.30000000000000004, 'max_features': 15, 'class_weight': 'balanced'}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 16, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 28, 'class_weight': 'balanced'}
AUC: 0.7487684729064039, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 2, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 74, 'class_weight': 'balanced'}
AUC: 0.5652709359605911, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 4, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 11, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}
AUC: 0.7118226600985221, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 12, 'class_weight': 'balanced'}
AUC: 0.6096059113300493, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 13, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 90, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 15, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 21, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 1, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 76, 'class_weight': 'balanced'}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 13, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 26, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.2, 'max_features': 29, 'class_weight': 'balanced'}
AUC: 0.7881773399014778, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 64, 'class_weight': 'balanced'}
AUC: 0.6748768472906403, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.2, 'max_features': 72, 'class_weight': 'balanced'}
AUC: 0.7364532019704433, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 10, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 93, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 0.8, 'min_samples_leaf': 0.2, 'max_features': 96, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 12, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 61, 'class_weight': 'balanced'}
AUC: 0.6785714285714286, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 10, 'min_samples_split': 0.8, 'min_samples_leaf': 0.5, 'max_features': 26, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.4, 'max_features': 11, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 31, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.6613300492610839, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 77, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 26, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 1, 'max_depth': 11, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 83, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 26, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 78, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 28, 'min_samples_split': 1.0, 'min_samples_leaf': 0.4, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 71, 'class_weight': 'balanced'}
AUC: 0.6576354679802955, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'n_estimators': 1, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 31, 'min_samples_split': 0.4, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.5221674876847291, Precision: 0.3333333333333333, Recall: 0.35714285714285715, F1-score: 0.3448275862068965
Testing parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.853448275862069, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 29, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 57, 'class_weight': 'balanced'}
AUC: 0.5923645320197044, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 16, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 87, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 23, 'min_samples_split': 0.1, 'min_samples_leaf': 0.5, 'max_features': 92, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 27, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.7364532019704434, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'n_estimators': 4, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 22, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 80, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.1, 'min_samples_leaf': 0.30000000000000004, 'max_features': 56, 'class_weight': 'balanced'}
AUC: 0.6637931034482758, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 24, 'min_samples_split': 0.1, 'min_samples_leaf': 0.4, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 1, 'min_samples_split': 0.5, 'min_samples_leaf': 0.1, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.6625615763546798, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 18, 'min_samples_split': 0.2, 'min_samples_leaf': 0.2, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.7253694581280787, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 32, 'max_depth': 19, 'min_samples_split': 0.5, 'min_samples_leaf': 0.30000000000000004, 'max_features': 91, 'class_weight': 'balanced'}
AUC: 0.6083743842364532, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 0.5, 'min_samples_leaf': 0.5, 'max_features': 31, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 39, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 24, 'min_samples_split': 0.9, 'min_samples_leaf': 0.2, 'max_features': 39, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 30, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 37, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 10, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 43, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}

Parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 0.6, 'min_samples_leaf': 0.30000000000000004, 'max_features': 6, 'class_weight': 'balanced'}
AUC: 0.8300492610837438, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Testing parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 200, 'max_depth': 2, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.30000000000000004, 'max_features': 65, 'class_weight': 'balanced'}
AUC: 0.8201970443349754, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 24, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 16, 'class_weight': 'balanced'}
AUC: 0.8485221674876847, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'n_estimators': 1, 'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 1, 'max_depth': 8, 'min_samples_split': 0.6, 'min_samples_leaf': 0.4, 'max_features': 30, 'class_weight': 'balanced'}
AUC: 0.4322660098522168, Precision: 0.34210526315789475, Recall: 0.9285714285714286, F1-score: 0.5
Testing parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 24, 'min_samples_split': 0.4, 'min_samples_leaf': 0.2, 'max_features': 63, 'class_weight': 'balanced'}
AUC: 0.8362068965517241, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 0.9, 'min_samples_leaf': 0.30000000000000004, 'max_features': 97, 'class_weight': 'balanced'}
AUC: 0.8017241379310346, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Testing parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 69, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 4, 'max_depth': 7, 'min_samples_split': 1.0, 'min_samples_leaf': 0.30000000000000004, 'max_features': 69, 'class_weight': 'balanced'}
AUC: 0.4642857142857143, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 22, 'min_samples_split': 1.0, 'min_samples_leaf': 0.1, 'max_features': 98, 'class_weight': 'balanced'}
AUC: 0.6071428571428572, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 0.2, 'min_samples_leaf': 0.5, 'max_features': 82, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 62, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 19, 'min_samples_split': 0.1, 'min_samples_leaf': 0.1, 'max_features': 62, 'class_weight': 'balanced'}
AUC: 0.7192118226600985, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 18, 'min_samples_split': 1.0, 'min_samples_leaf': 0.2, 'max_features': 53, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 23, 'min_samples_split': 0.4, 'min_samples_leaf': 0.5, 'max_features': 45, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 64, 'max_depth': 14, 'min_samples_split': 0.5, 'min_samples_leaf': 0.4, 'max_features': 3, 'class_weight': 'balanced'}
AUC: 0.6958128078817734, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 27, 'min_samples_split': 1.0, 'min_samples_leaf': 0.5, 'max_features': 94, 'class_weight': 'balanced'}
AUC: 0.4100985221674877, Precision: 0.2, Recall: 0.2857142857142857, F1-score: 0.23529411764705882
Testing parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 2, 'max_depth': 2, 'min_samples_split': 0.4, 'min_samples_leaf': 0.30000000000000004, 'max_features': 81, 'class_weight': 'balanced'}
AUC: 0.4482758620689655, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 100, 'max_depth': 28, 'min_samples_split': 0.30000000000000004, 'min_samples_leaf': 0.1, 'max_features': 58, 'class_weight': 'balanced'}
AUC: 0.7438423645320197, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 8, 'max_depth': 19, 'min_samples_split': 0.4, 'min_samples_leaf': 0.4, 'max_features': 75, 'class_weight': 'balanced'}
AUC: 0.4273399014778325, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
Parameters: {'n_estimators': 16, 'max_depth': 1, 'min_samples_split': 0.6, 'min_samples_leaf': 0.1, 'max_features': 67, 'class_weight': 'balanced'}
AUC: 0.6551724137931034, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Best AUC: 0.897783251231527
Best parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 0.7000000000000001, 'min_samples_leaf': 0.1, 'max_features': 13, 'class_weight': 'balanced'}

In [45]:
model = RandomForestClassifier(**best_params, random_state = 42)

In [46]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)
    


            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9150246305418719, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435, Accuracy: 0.8372093023255814, Balanced Accuracy: 0.7684729064039408

# XGBoost

In [47]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [48]:
param_grid

{'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.3],
 'gamma': [0, 0.1, 0.15, 0.25, 0.5],
 'max_depth': [6, 8, 10, 12, 15],
 'subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'colsample_bylevel': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'colsample_bytree': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
 'min_child_weight': [0.5, 1.0, 3.0, 5.0, 7.0, 10.0],
 'estimators': [50, 100, 200],
 'scale_pos_weight': [2.0714285714285716]}

In [49]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'learning_rate': np.random.choice(param_grid['learning_rate']),
            'gamma': np.random.choice(param_grid['gamma']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'subsample': np.random.choice(param_grid['subsample']),
            'colsample_bylevel': np.random.choice(param_grid['colsample_bylevel']),
            'colsample_bytree': np.random.choice(param_grid['colsample_bytree']),
            'min_child_weight': np.random.choice(param_grid['min_child_weight']),
            'estimators': np.random.choice(param_grid['estimators']),
            'scale_pos_weight': np.random.choice(param_grid['scale_pos_weight'])
        }
        print(f"Testing parameters: {params}")
        pipeline = XGBClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

xgb = XGBClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(xgb, X_new, y, group, param_grid, n_iter = 500)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1206896551724138, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8719211822660099, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11330049261083744, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04310344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832513, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9039408866995073, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10591133004926107, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17241379310344826, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679802, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147784, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.019704433497536943, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.16995073891625617, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.689655172413793, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8891625615763548, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12068965517241378, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325122, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5714285714285714, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1576354679802956, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.15517241379310343, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2795566502463054, Precision: 0.22580645161290322, Recall: 0.5, F1-score: 0.3111111111111111
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7943349753694581, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04556650246305415, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5455665024630542, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3189655172413793, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5591133004926109, Precision: 0.23076923076923078, Recall: 0.21428571428571427, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724138, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17241379310344826, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216749, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6354679802955665, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.16502463054187191, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04187192118226599, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.43226600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.020935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5775862068965518, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8596059113300494, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09605911330049259, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06403940886699507, Precision: 0.05555555555555555, Recall: 0.07142857142857142, F1-score: 0.0625
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8866995073891626, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438404, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25369458128078815, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.43349753694581283, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502463, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5541871921182266, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502463, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.45566502463054187, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.020935960591133004, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20197044334975367, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.21674876847290642, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11822660098522167, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6453201970443349, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6169950738916257, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679802, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4236453201970444, Precision: 0.25, Recall: 0.14285714285714285, F1-score: 0.18181818181818182
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7426108374384237, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06650246305418717, Precision: 0.06666666666666667, Recall: 0.07142857142857142, F1-score: 0.0689655172413793
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.10714285714285715, Precision: 0.09375, Recall: 0.21428571428571427, F1-score: 0.13043478260869562
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802956, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674877, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23152709359605914, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.14901477832512322, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.018472906403940885, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.22413793103448276, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5049261083743842, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502462, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2450738916256158, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.05295566502463053, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6157635467980296, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12068965517241376, Precision: 0.125, Recall: 0.07142857142857142, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17857142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8596059113300493, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.22413793103448276, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.14285714285714285, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857142, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06650246305418717, Precision: 0.05263157894736842, Recall: 0.07142857142857142, F1-score: 0.06060606060606061
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502462, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08004926108374387, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857143, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11699507389162564, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17857142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748768, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8596059113300493, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172413, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17733990147783252, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655173, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6798029556650247, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6133004926108373, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009853, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8916256157635468, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6699507389162561, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216749, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1330049261083744, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172414, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197042, Precision: 0.14285714285714285, Recall: 0.14285714285714285, F1-score: 0.14285714285714285
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25862068965517243, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.019704433497536946, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320198, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2795566502463054, Precision: 0.22580645161290322, Recall: 0.5, F1-score: 0.3111111111111111
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1810344827586207, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.19950738916256158, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20935960591133007, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453203, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.08990147783251229, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.32389162561576357, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17733990147783252, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6280788177339902, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2241379310344828, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1502463054187192, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852216, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497537, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093595, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502463, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2844827586206896, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7019704433497537, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.020935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6108374384236454, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2623152709359606, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5615763546798029, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6022167487684729, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.1896551724137931, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5640394088669951, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8940886699507389, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.18226600985221678, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.020935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216749, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147782, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.810344827586207, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04556650246305415, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192117, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.562807881773399, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.019704433497536943, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23522167487684728, Precision: 0.14285714285714285, Recall: 0.14285714285714285, F1-score: 0.14285714285714285
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6970443349753694, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.06896551724137931, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172414, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17857142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187193, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.624384236453202, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423644, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.023399014778325122, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.46921182266009853, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.019704433497536936, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11330049261083742, Precision: 0.14285714285714285, Recall: 0.07142857142857142, F1-score: 0.09523809523809523
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5110837438423645, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.12931034482758616, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09359605911330049, Precision: 0.07692307692307693, Recall: 0.07142857142857142, F1-score: 0.07407407407407408
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2315270935960591, Precision: 0.1, Recall: 0.07142857142857142, F1-score: 0.08333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5985221674876848, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.019704433497536943, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.13423645320197045, Precision: 0.20588235294117646, Recall: 0.5, F1-score: 0.2916666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23399014778325125, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2315270935960591, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.21674876847290642, Precision: 0.09090909090909091, Recall: 0.07142857142857142, F1-score: 0.08
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.11822660098522167, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990147, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.19458128078817732, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147784, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6403940886699508, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325123, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.0665024630541872, Precision: 0.0625, Recall: 0.07142857142857142, F1-score: 0.06666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147784, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.041871921182266014, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5825123152709359, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.04556650246305415, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.050492610837438424, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.09359605911330049, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8866995073891626, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.23522167487684728, Precision: 0.14285714285714285, Recall: 0.14285714285714285, F1-score: 0.14285714285714285
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6477832512315271, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01354679802955664, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17980295566502463, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.03325123152709359, Precision: 0.06666666666666667, Recall: 0.14285714285714285, F1-score: 0.09090909090909091
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.2019704433497537, Precision: 0.08333333333333333, Recall: 0.07142857142857142, F1-score: 0.07692307692307691
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320198, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6761083743842364, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.731527093596059, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.4166666666666667, Recall: 0.35714285714285715, F1-score: 0.3846153846153846
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.17980295566502466, Precision: 0.1111111111111111, Recall: 0.07142857142857142, F1-score: 0.08695652173913043
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5492610837438424, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Best AUC: 0.9039408866995073
Best parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

In [50]:
model = XGBClassifier(**best_params, random_state = 42)

In [51]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train, y_train)

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9039408866995073, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714, Accuracy: 0.7906976744186046, Balanced Accuracy: 0.6970443349753694

# XGBoost + SMOTE

In [52]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler, 1]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [53]:


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid, n_iter):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for _ in range(n_iter):
        # Randomly sample hyperparameters
        params = {
            'learning_rate': np.random.choice(param_grid['learning_rate']),
            'gamma': np.random.choice(param_grid['gamma']),
            'max_depth': np.random.choice(param_grid['max_depth']),
            'subsample': np.random.choice(param_grid['subsample']),
            'colsample_bylevel': np.random.choice(param_grid['colsample_bylevel']),
            'colsample_bytree': np.random.choice(param_grid['colsample_bytree']),
            'min_child_weight': np.random.choice(param_grid['min_child_weight']),
            'estimators': np.random.choice(param_grid['estimators']),
            'scale_pos_weight': np.random.choice(param_grid['scale_pos_weight'])
        }
        print(f"Testing parameters: {params}")
        pipeline = XGBClassifier(**params, random_state=42)

        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

xgb = XGBClassifier()


# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(xgb, X_new, y, group, param_grid, n_iter = 1000)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8620689655172414, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8423645320197044, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8620689655172413, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.20073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6527093596059114, Precision: 0.2972972972972973, Recall: 0.7857142857142857, F1-score: 0.43137254901960786
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374385, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5086206896551724, Precision: 0.375, Recall: 0.6428571428571429, F1-score: 0.4736842105263159
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423645, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8522167487684729, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7881773399014778, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807883, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4396551724137931, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5899014778325122, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6071428571428572, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8399014778325122, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8669950738916257, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630543, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7426108374384236, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.704433497536946, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25985221674876846, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320198, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.731527093596059, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4002463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7660098522167488, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6317733990147782, Precision: 0.3, Recall: 0.8571428571428571, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6280788177339902, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527094, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827586, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.70935960591133, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7536945812807883, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.42857142857142855, Recall: 0.8571428571428571, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5049261083743842, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25985221674876846, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.28201970443349755, Precision: 0.125, Recall: 0.14285714285714285, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8399014778325122, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8768472906403941, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6391625615763548, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8645320197044335, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8793103448275863, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320198, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.731527093596059, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7241379310344828, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8423645320197044, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655173, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502464, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837438, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.687192118226601, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7302955665024631, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837439, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7549261083743842, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6120689655172413, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8891625615763548, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.49261083743842365, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246306, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576356, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8128078817733991, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5455665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551725, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423645, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463055, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8054187192118227, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.3684210526315789, Recall: 0.5, F1-score: 0.4242424242424242
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359606, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7524630541871922, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.41009852216748766, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6009852216748769, Precision: 0.2702702702702703, Recall: 0.7142857142857143, F1-score: 0.39215686274509803
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.625615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8399014778325123, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8546798029556649, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.689655172413793, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216749, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.41379310344827586, Recall: 0.8571428571428571, F1-score: 0.5581395348837208
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5652709359605912, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6822660098522167, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679802, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8645320197044335, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527093, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5886699507389163, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5886699507389163, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7931034482758621, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7105911330049262, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246306, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8571428571428572, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8793103448275862, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197044, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8226600985221675, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8571428571428572, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7906403940886699, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.38095238095238093, Recall: 0.5714285714285714, F1-score: 0.4571428571428571
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8768472906403941, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8620689655172413, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7536945812807883, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7032019704433498, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7881773399014779, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.20073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8485221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6305418719211823, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6945812807881773, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6896551724137931, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630543, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6403940886699508, Precision: 0.3333333333333333, Recall: 0.2857142857142857, F1-score: 0.30769230769230765
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.768472906403941, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3004926108374384, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704434, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8694581280788176, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807881, Precision: 0.4444444444444444, Recall: 0.5714285714285714, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.810344827586207, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7697044334975369, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8472906403940887, Precision: 0.8333333333333334, Recall: 0.35714285714285715, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837438, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625617, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837439, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5751231527093597, Precision: 0.3, Recall: 0.8571428571428571, F1-score: 0.4444444444444444
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8916256157635468, Precision: 0.6, Recall: 0.8571428571428571, F1-score: 0.7058823529411764
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5455665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8891625615763546, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.79064039408867, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246306, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7881773399014779, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6071428571428572, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.665024630541872, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8596059113300493, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8817733990147784, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4236453201970443, Precision: 0.2777777777777778, Recall: 0.7142857142857143, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5960591133004925, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.31157635467980294, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6330049261083743, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5504926108374384, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7376847290640394, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7536945812807881, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6637931034482759, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8214285714285714, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172413, Precision: 0.5416666666666666, Recall: 0.9285714285714286, F1-score: 0.6842105263157894
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.37037037037037035, Recall: 0.7142857142857143, F1-score: 0.4878048780487805
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783251, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655173, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729065, Precision: 0.43333333333333335, Recall: 0.9285714285714286, F1-score: 0.5909090909090909
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.874384236453202, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477834, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.47619047619047616, Recall: 0.7142857142857143, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6847290640394088, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6576354679802955, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7142857142857144, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965518, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7561576354679803, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.731527093596059, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8940886699507389, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7475369458128078, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8743842364532021, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6551724137931034, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7019704433497537, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8620689655172413, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965516, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7241379310344828, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8374384236453203, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5997536945812809, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5763546798029557, Precision: 0.2894736842105263, Recall: 0.7857142857142857, F1-score: 0.423076923076923
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7721674876847291, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8694581280788177, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679802, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704434, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6354679802955665, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837439, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546798, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7586206896551724, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8694581280788178, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7266009852216748, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8768472906403941, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034483, Precision: 0.36363636363636365, Recall: 0.2857142857142857, F1-score: 0.32
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7315270935960592, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8842364532019704, Precision: 0.5454545454545454, Recall: 0.8571428571428571, F1-score: 0.6666666666666665
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8694581280788177, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8719211822660098, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014778, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4495073891625616, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7093596059113301, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.36576354679802947, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4618226600985222, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704434, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8472906403940887, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4630541871921182, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704433, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.770935960591133, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5357142857142858, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.375, Recall: 0.42857142857142855, F1-score: 0.39999999999999997
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270936, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369458, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8054187192118227, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7376847290640395, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472907, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6440886699507389, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7894088669950738, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.4166666666666667, Recall: 0.7142857142857143, F1-score: 0.5263157894736842
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5997536945812807, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270935, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8128078817733989, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423644, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349754, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8423645320197044, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6674876847290641, Precision: 0.35294117647058826, Recall: 0.42857142857142855, F1-score: 0.3870967741935484
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5147783251231527, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7192118226600985, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837439, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8325123152709359, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5738916256157635, Precision: 0.3157894736842105, Recall: 0.8571428571428571, F1-score: 0.46153846153846156
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5874384236453202, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8251231527093597, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4507389162561576, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8423645320197044, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837438, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6810344827586207, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6465517241379312, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5036945812807883, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.602216748768473, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8177339901477834, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7044334975369458, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5049261083743842, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8165024630541873, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8177339901477833, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5394088669950738, Precision: 0.3, Recall: 0.21428571428571427, F1-score: 0.25
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8719211822660098, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.1933497536945813, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7364532019704433, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6748768472906405, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6428571428571428, Precision: 0.35, Recall: 0.5, F1-score: 0.4117647058823529
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8817733990147784, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6871921182266009, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5172413793103448, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147784, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8472906403940887, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8522167487684729, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8768472906403941, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5455665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7931034482758621, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295566, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6330049261083743, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8990147783251232, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5874384236453203, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142857, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3374384236453202, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7610837438423645, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.4782608695652174, Recall: 0.7857142857142857, F1-score: 0.5945945945945946
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8177339901477833, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837438, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502462, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8669950738916256, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837438, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6699507389162562, Precision: 0.5, Recall: 0.42857142857142855, F1-score: 0.4615384615384615
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5320197044334976, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.687192118226601, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5123152709359606, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8004926108374384, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7980295566502464, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7684729064039408, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.4230769230769231, Recall: 0.7857142857142857, F1-score: 0.55
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5184729064039408, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7167487684729064, Precision: 0.4074074074074074, Recall: 0.7857142857142857, F1-score: 0.5365853658536585
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.3485221674876847, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014779, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118226, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6674876847290641, Precision: 0.46153846153846156, Recall: 0.42857142857142855, F1-score: 0.4444444444444445
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8497536945812808, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837438, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6600985221674878, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8177339901477833, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8866995073891626, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6416256157635468, Precision: 0.3125, Recall: 0.35714285714285715, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502462, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6896551724137931, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5726600985221675, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6182266009852218, Precision: 0.2972972972972973, Recall: 0.7857142857142857, F1-score: 0.43137254901960786
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187191, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6379310344827587, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192119, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.47536945812807885, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7684729064039408, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6071428571428572, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.33866995073891626, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7167487684729064, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7672413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7241379310344828, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527094, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6502463054187192, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7216748768472906, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8497536945812808, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.625615763546798, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7536945812807883, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6625615763546797, Precision: 0.3125, Recall: 0.7142857142857143, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6982758620689655, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.33866995073891626, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600985, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8472906403940886, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8497536945812808, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7857142857142857, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8891625615763548, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8694581280788177, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369458, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8399014778325122, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.4199507389162561, Precision: 0.21428571428571427, Recall: 0.21428571428571427, F1-score: 0.21428571428571427
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6379310344827587, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423645, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6908866995073892, Precision: 0.45, Recall: 0.6428571428571429, F1-score: 0.5294117647058824
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399015, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906403, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4002463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527093, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147784, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630542, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5849753694581281, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7635467980295567, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.832512315270936, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6059113300492611, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8497536945812808, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.706896551724138, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.75, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985221, Precision: 0.4074074074074074, Recall: 0.7857142857142857, F1-score: 0.5365853658536585
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.854679802955665, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8645320197044335, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7487684729064039, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8275862068965517, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.9064039408866995, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8325123152709359, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8349753694581281, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8349753694581281, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940886, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8596059113300492, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6785714285714286, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7832512315270935, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8719211822660098, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6822660098522167, Precision: 0.4583333333333333, Recall: 0.7857142857142857, F1-score: 0.5789473684210527
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8645320197044335, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6810344827586207, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6293103448275862, Precision: 0.4, Recall: 0.7142857142857143, F1-score: 0.5128205128205129
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6440886699507389, Precision: 0.42857142857142855, Recall: 0.6428571428571429, F1-score: 0.5142857142857143
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7623152709359606, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4137931034482759, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527093, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.795566502463054, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7007389162561576, Precision: 0.5, Recall: 0.7857142857142857, F1-score: 0.6111111111111112
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6995073891625616, Precision: 0.4, Recall: 0.2857142857142857, F1-score: 0.3333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4002463054187192, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8275862068965517, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7894088669950738, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8078817733990148, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8201970443349753, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6982758620689655, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305418, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6613300492610837, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8571428571428571, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8817733990147784, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7339901477832512, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7783251231527094, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8817733990147784, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7241379310344828, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7881773399014778, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8103448275862069, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5529556650246306, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7881773399014779, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7487684729064039, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.45454545454545453, Recall: 0.7142857142857143, F1-score: 0.5555555555555556
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7019704433497538, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8300492610837439, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630543, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8004926108374384, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.4666666666666667, Recall: 0.5, F1-score: 0.4827586206896552
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.770935960591133, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4741379310344827, Precision: 0.25, Recall: 0.35714285714285715, F1-score: 0.2941176470588235
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192119, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320197, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.3888888888888889, Recall: 0.5, F1-score: 0.43750000000000006
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7733990147783252, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.603448275862069, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940886, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.4074074074074074, Recall: 0.7857142857142857, F1-score: 0.5365853658536585
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6933497536945813, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.46153846153846156, Recall: 0.8571428571428571, F1-score: 0.6
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7758620689655172, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8226600985221675, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7857142857142858, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.31157635467980294, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216749, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246306, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6773399014778325, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7118226600985222, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6834975369458128, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8768472906403941, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7007389162561576, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.687192118226601, Precision: 0.4117647058823529, Recall: 0.5, F1-score: 0.45161290322580644
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4913793103448276, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6724137931034484, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7463054187192117, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6724137931034483, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7056650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.727832512315271, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6108374384236452, Precision: 0.4444444444444444, Recall: 0.2857142857142857, F1-score: 0.34782608695652173
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3091133004926109, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6859605911330049, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7807881773399016, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7844827586206896, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7610837438423645, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6908866995073892, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8226600985221675, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7019704433497537, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8078817733990148, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7130541871921183, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.25985221674876846, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4778325123152709, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7758620689655172, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7955665024630543, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5788177339901478, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3411330049261084, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935961, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8226600985221675, Precision: 0.6666666666666666, Recall: 0.5714285714285714, F1-score: 0.6153846153846153
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576355, Precision: 0.47058823529411764, Recall: 0.5714285714285714, F1-score: 0.5161290322580646
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7512315270935962, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7315270935960592, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.45454545454545453, Recall: 0.35714285714285715, F1-score: 0.4
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7302955665024631, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5061576354679803, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8300492610837439, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7438423645320198, Precision: 0.5, Recall: 0.6428571428571429, F1-score: 0.5625000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7450738916256158, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.812807881773399, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7204433497536946, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7746305418719213, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.20320197044334976, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6921182266009852, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7364532019704433, Precision: 0.55, Recall: 0.7857142857142857, F1-score: 0.6470588235294117
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7549261083743843, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5086206896551724, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7733990147783252, Precision: 0.6153846153846154, Recall: 0.5714285714285714, F1-score: 0.5925925925925927
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8054187192118226, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.47413793103448276, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8325123152709359, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369457, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6613300492610839, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7561576354679803, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399016, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.4150246305418719, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7044334975369457, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.9125615763546798, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6403940886699507, Precision: 0.35714285714285715, Recall: 0.35714285714285715, F1-score: 0.35714285714285715
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8029556650246306, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8448275862068966, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7253694581280787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605912, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7389162561576355, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6785714285714286, Precision: 0.38461538461538464, Recall: 0.7142857142857143, F1-score: 0.5
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.812807881773399, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.5295566502463054, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7401477832512315, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.3928571428571429, Precision: 0.2857142857142857, Recall: 0.2857142857142857, F1-score: 0.2857142857142857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6736453201970444, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7586206896551724, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7389162561576356, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7068965517241379, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8201970443349753, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8571428571428572, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7068965517241379, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453202, Precision: 0.6363636363636364, Recall: 0.5, F1-score: 0.56
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7931034482758621, Precision: 0.5384615384615384, Recall: 0.5, F1-score: 0.5185185185185186
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.729064039408867, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6884236453201971, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6071428571428572, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881773, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6231527093596059, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8152709359605911, Precision: 0.47368421052631576, Recall: 0.6428571428571429, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.727832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7783251231527094, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8768472906403941, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8275862068965517, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935962, Precision: 0.43478260869565216, Recall: 0.7142857142857143, F1-score: 0.5405405405405405
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.44, Recall: 0.7857142857142857, F1-score: 0.5641025641025641
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7327586206896552, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.9, 'min_child_weight': 3.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7192118226600986, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8497536945812808, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6342364532019704, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.42857142857142855, Recall: 0.42857142857142855, F1-score: 0.42857142857142855
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5172413793103448, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.5467980295566502, Precision: 0.2926829268292683, Recall: 0.8571428571428571, F1-score: 0.4363636363636364
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8694581280788177, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 10, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7241379310344828, Precision: 0.4375, Recall: 0.5, F1-score: 0.4666666666666667
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7253694581280788, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.4, Recall: 0.5714285714285714, F1-score: 0.47058823529411764
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.36206896551724144, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7413793103448276, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6428571428571429, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7906403940886699, Precision: 0.5833333333333334, Recall: 0.5, F1-score: 0.5384615384615384
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.8694581280788178, Precision: 0.9, Recall: 0.6428571428571429, F1-score: 0.75
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8522167487684729, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8891625615763548, Precision: 0.5714285714285714, Recall: 0.8571428571428571, F1-score: 0.6857142857142857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6637931034482759, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8029556650246306, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8054187192118227, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.7, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7179802955665024, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295567, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.770935960591133, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7598522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.5775862068965517, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7955665024630542, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7463054187192119, Precision: 0.5, Recall: 0.5714285714285714, F1-score: 0.5333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8423645320197045, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5701970443349754, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.7586206896551724, Precision: 0.5333333333333333, Recall: 0.5714285714285714, F1-score: 0.5517241379310344
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.28201970443349755, Precision: 0.125, Recall: 0.14285714285714285, F1-score: 0.13333333333333333
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8903940886699507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8374384236453203, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8152709359605912, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6157635467980296, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.4704433497536946, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.4, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.832512315270936, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8694581280788178, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 15, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.2524630541871921, Precision: 0.07142857142857142, Recall: 0.07142857142857142, F1-score: 0.07142857142857142
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.25, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 7.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6206896551724139, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.7832512315270936, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8263546798029557, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 10, 'subsample': 0.9, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7980295566502463, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 15, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7635467980295566, Precision: 0.38461538461538464, Recall: 0.35714285714285715, F1-score: 0.3703703703703704
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.25, 'max_depth': 6, 'subsample': 0.9, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6502463054187192, Precision: 0.3333333333333333, Recall: 0.42857142857142855, F1-score: 0.375
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.7, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 8, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.729064039408867, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.8, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8497536945812808, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}

Parameters: {'learning_rate': 0.2, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.8, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.6785714285714286, Precision: 0.5, Recall: 0.5, F1-score: 0.5
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.6, 'min_child_weight': 3.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7266009852216748, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.1, 'gamma': 0.15, 'max_depth': 8, 'subsample': 0.9, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 10.0, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.66871921182266, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.25, 'max_depth': 10, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8497536945812807, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.0, 'max_depth': 6, 'subsample': 1.0, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8275862068965517, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 15, 'subsample': 0.9, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6650246305418719, Precision: 0.39285714285714285, Recall: 0.7857142857142857, F1-score: 0.5238095238095237
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.6748768472906405, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 6, 'subsample': 0.5, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.8, 'colsample_bylevel': 0.4, 'colsample_bytree': 1.0, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8103448275862069, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6995073891625616, Precision: 0.4074074074074074, Recall: 0.7857142857142857, F1-score: 0.5365853658536585
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.01, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 1.0, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.2869458128078818, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.01, 'gamma': 0.0, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.854679802955665, Precision: 0.5, Recall: 0.7142857142857143, F1-score: 0.588235294117647
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 10, 'subsample': 0.7, 'colsample_bylevel': 0.7, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7438423645320197, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.15, 'max_depth': 6, 'subsample': 0.6, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8768472906403941, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.5, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.8325123152709359, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.001, 'gamma': 0.1, 'max_depth': 12, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.7, 'min_child_weight': 1.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7413793103448276, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 15, 'subsample': 0.6, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.6945812807881774, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.3, 'gamma': 0.1, 'max_depth': 8, 'subsample': 0.5, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 7.0, 'estimators': 100, 'scale_pos_weight': 1.0}
AUC: 0.3066502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.5, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.6, 'colsample_bytree': 0.4, 'min_child_weight': 5.0, 'estimators': 50, 'scale_pos_weight': 1.0}
AUC: 0.7807881773399015, Precision: 0.5714285714285714, Recall: 0.5714285714285714, F1-score: 0.5714285714285714
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 12, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8620689655172414, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Testing parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.1, 'gamma': 0.1, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.4, 'colsample_bytree': 0.6, 'min_child_weight': 10.0, 'estimators': 50, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8448275862068966, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Testing parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
Parameters: {'learning_rate': 0.001, 'gamma': 0.0, 'max_depth': 12, 'subsample': 0.5, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.4, 'min_child_weight': 0.5, 'estimators': 200, 'scale_pos_weight': 1.0}
AUC: 0.8251231527093597, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.0, 'max_depth': 6, 'subsample': 0.7, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.5, 'min_child_weight': 5.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.7512315270935961, Precision: 0.4, Recall: 0.42857142857142855, F1-score: 0.4137931034482759
Testing parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.3, 'gamma': 0.15, 'max_depth': 10, 'subsample': 0.8, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8472906403940887, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Testing parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
Parameters: {'learning_rate': 0.2, 'gamma': 0.25, 'max_depth': 12, 'subsample': 1.0, 'colsample_bylevel': 0.5, 'colsample_bytree': 0.9, 'min_child_weight': 0.5, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}
AUC: 0.8054187192118227, Precision: 0.5454545454545454, Recall: 0.42857142857142855, F1-score: 0.4799999999999999
Best AUC: 0.9667487684729064
Best parameters: {'learning_rate': 0.01, 'gamma': 0.1, 'max_depth': 8, 'subsample': 1.0, 'colsample_bylevel': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'estimators': 100, 'scale_pos_weight': 2.0714285714285716}

In [54]:
model = XGBClassifier(**best_params, random_state = 42)

In [55]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
cv = LeaveOneGroupOut()


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, group)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
    model.fit(X_train_oversampled, y_train_oversampled)

            

            

    # Predict on the test data
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9667487684729064, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857, Accuracy: 0.32558139534883723, Balanced Accuracy: 0.5

# Linear Regression

In [56]:
from sklearn import linear_model
from sklearn.model_selection import ParameterGrid
param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [57]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

groups = group


# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9285714285714286, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9408866995073891, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9482758620689655, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9482758620689655, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9556650246305419, Precision: 0.9090909090909091, Recall: 0.7142857142857143, F1-score: 0.8
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9556650246305419, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9482758620689655, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9458128078817735, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9556650246305419, Precision: 0.9090909090909091, Recall: 0.7142857142857143, F1-score: 0.8
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.958128078817734, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9482758620689655, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9482758620689655, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.958128078817734, Precision: 0.9166666666666666, Recall: 0.7857142857142857, F1-score: 0.8461538461538461
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9532019704433498, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9482758620689655, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9458128078817734, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9532019704433499, Precision: 0.9166666666666666, Recall: 0.7857142857142857, F1-score: 0.8461538461538461
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9433497536945813, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9458128078817734, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9532019704433498, Precision: 0.9090909090909091, Recall: 0.7142857142857143, F1-score: 0.8
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9433497536945813, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9458128078817735, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9482758620689655, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9482758620689655, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9458128078817735, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9630541871921182, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9482758620689655, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9458128078817734, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9482758620689655, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9778325123152709, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9532019704433498, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9679802955665024, Precision: 0.9166666666666666, Recall: 0.7857142857142857, F1-score: 0.8461538461538461
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9532019704433498, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Best AUC: 0.9778325123152709
Best parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

In [58]:
best_params

{'model__C': 3593.813663804626,
 'model__penalty': 'l1',
 'model__solver': 'liblinear'}

In [59]:
model = linear_model.LogisticRegression()



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe

In [60]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 LogisticRegression(C=3593.813663804626, penalty='l1',
                                    solver='liblinear'))])

In [61]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9704433497536945, Precision: 0.9230769230769231, Recall: 0.8571428571428571, F1-score: 0.888888888888889, Accuracy: 0.9302325581395349, Balanced Accuracy: 0.9113300492610837

# LR + SMOTE

In [102]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [103]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9187192118226601, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__C': 1.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9605911330049262, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9532019704433498, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 1.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9532019704433498, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.958128078817734, Precision: 0.9166666666666666, Recall: 0.7857142857142857, F1-score: 0.8461538461538461
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9802955665024631, Precision: 0.9230769230769231, Recall: 0.8571428571428571, F1-score: 0.888888888888889
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9556650246305418, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9704433497536946, Precision: 0.9090909090909091, Recall: 0.7142857142857143, F1-score: 0.8
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9655172413793104, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9630541871921182, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 7.742636826811269, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9556650246305419, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9729064039408868, Precision: 1.0, Recall: 0.7857142857142857, F1-score: 0.88
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.958128078817734, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9630541871921182, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 21.544346900318832, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.958128078817734, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9433497536945813, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9532019704433498, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 59.94842503189409, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9655172413793104, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9630541871921182, Precision: 0.9166666666666666, Recall: 0.7857142857142857, F1-score: 0.8461538461538461
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9605911330049262, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 166.81005372000593, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9605911330049262, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9507389162561577, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9605911330049262, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 464.15888336127773, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9556650246305418, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9802955665024631, Precision: 1.0, Recall: 0.7857142857142857, F1-score: 0.88
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9532019704433498, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9630541871921183, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 1291.5496650148827, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9630541871921182, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9482758620689655, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9507389162561576, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9753694581280788, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9433497536945813, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
AUC: 0.9532019704433498, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__C': 10000.0, 'model__penalty': 'l1', 'model__solver': 'saga'}
AUC: 0.9482758620689655, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__C': 10000.0, 'model__penalty': 'l2', 'model__solver': 'saga'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Best AUC: 0.9802955665024631
Best parameters: {'model__C': 2.7825594022071245, 'model__penalty': 'l1', 'model__solver': 'saga'}

In [ ]:
Best parameters: {'model__C': 3593.813663804626, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

In [108]:
model = linear_model.LogisticRegression()



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe
pipeline.set_params(**best_params)
pipeline.set_params(**{'model__C': 3593.813663804626,
 'model__penalty': 'l1',
 'model__solver': 'liblinear'})

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 LogisticRegression(C=3593.813663804626, penalty='l1',
                                    solver='liblinear'))])

In [116]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)
            


    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9975369458128079, Precision: 1.0, Recall: 0.9285714285714286, F1-score: 0.962962962962963, Accuracy: 0.9767441860465116, Balanced Accuracy: 0.9642857142857143

# k-NN

In [66]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier
    



from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.6785714285714286, Precision: 1.0, Recall: 0.35714285714285715, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6785714285714286, Precision: 1.0, Recall: 0.35714285714285715, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7869458128078818, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7869458128078818, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7869458128078818, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7869458128078818, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8054187192118227, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8054187192118227, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7697044334975369, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7697044334975369, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7142857142857143, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7142857142857143, Precision: 1.0, Recall: 0.35714285714285715, F1-score: 0.5263157894736842
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.7623152709359605, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7820197044334974, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7832512315270936, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7955665024630542, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.770935960591133, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7783251231527093, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7660098522167488, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7746305418719212, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8214285714285714, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8214285714285714, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.79064039408867, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.7980295566502463, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8054187192118225, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8201970443349752, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7635467980295566, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7660098522167488, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7610837438423645, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.768472906403941, Precision: 0.6, Recall: 0.42857142857142855, F1-score: 0.5
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8214285714285714, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8214285714285714, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8103448275862069, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.812807881773399, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8054187192118225, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.816502463054187, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7266009852216749, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7487684729064039, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7266009852216748, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7413793103448276, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8928571428571428, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8928571428571428, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.814039408866995, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8177339901477833, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7943349753694581, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105

Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8115763546798029, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7192118226600985, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7413793103448276, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7068965517241379, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7241379310344828, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9187192118226601, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.916256157635468, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8177339901477833, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8177339901477833, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7795566502463054, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7992610837438423, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7032019704433498, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7192118226600985, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.687192118226601, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7044334975369458, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8990147783251231, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9113300492610837, Precision: 1.0, Recall: 0.21428571428571427, F1-score: 0.35294117647058826
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.876847290640394, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8780788177339901, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.7733990147783251, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7512315270935962, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7660098522167489, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.689655172413793, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.710591133004926, Precision: 0.375, Recall: 0.21428571428571427, F1-score: 0.2727272727272727
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9088669950738917, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9298029556650247, Precision: 1.0, Recall: 0.2857142857142857, F1-score: 0.4444444444444445
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.873152709359606, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8756157635467982, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8054187192118227, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8201970443349753, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7413793103448277, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7536945812807883, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7266009852216748, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7413793103448276, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.937192118226601, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9630541871921182, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9100985221674878, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9088669950738917, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8337438423645321, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8472906403940887, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7475369458128078, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.7610837438423645, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7376847290640394, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7561576354679803, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9408866995073892, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25

Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9630541871921182, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9064039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9088669950738917, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8312807881773399, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.854679802955665, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.791871921182266, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.812807881773399, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7709359605911331, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7980295566502463, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9556650246305419, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9655172413793104, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9137931034482758, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9137931034482758, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8399014778325123, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.854679802955665, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7955665024630542, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8078817733990148, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7598522167487686, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7906403940886699, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9605911330049262, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9704433497536946, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9088669950738917, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9113300492610837, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8374384236453203, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8472906403940887, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7807881773399016, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8029556650246306, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7536945812807881, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7733990147783252, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9630541871921182, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9778325123152709, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8990147783251231, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9088669950738917, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8435960591133005, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8620689655172413, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7807881773399015, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.812807881773399, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7610837438423645, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7807881773399015, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9642857142857142, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9802955665024631, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9125615763546798, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9137931034482759, Precision: 1.0, Recall: 0.07142857142857142, F1-score: 0.13333333333333333
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8263546798029556, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8448275862068966, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7770935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8004926108374385, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7832512315270936, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364

Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9679802955665024, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9802955665024631, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8916256157635468, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9088669950738917, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8288177339901478, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8423645320197044, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.7746305418719212, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8004926108374384, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7512315270935961, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.7610837438423645, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Best AUC: 0.9802955665024631
Best parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}

In [67]:
best_score

0.9802955665024631

In [68]:
best_params

{'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}

In [69]:
model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe

In [70]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model',
                 KNeighborsClassifier(n_neighbors=14, p=1,
                                      weights='distance'))])

In [71]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9802955665024631, Precision: 1.0, Recall: 0.14285714285714285, F1-score: 0.25, Accuracy: 0.7209302325581395, Balanced Accuracy: 0.5714285714285714

# k-NN + SMOTE

In [72]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np


param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier
    



from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])



# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.644088669950739, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'model__n_neighbors': 1, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.6970443349753696, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8583743842364532, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 1, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8583743842364532, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8411330049261083, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 1, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8411330049261083, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8411330049261083, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 1, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8238916256157635, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8238916256157635, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 1, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8238916256157635, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.7758620689655173, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Parameters: {'model__n_neighbors': 2, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7389162561576355, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8472906403940886, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 2, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8472906403940886, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8275862068965516, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 2, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.833743842364532, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8399014778325123, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'model__n_neighbors': 2, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8657635467980296, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8583743842364533, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 2, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8596059113300493, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8756157635467979, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.7857142857142856, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8645320197044336, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 3, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8891625615763546, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8669950738916257, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 3, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8669950738916257, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8472906403940887, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 3, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.815270935960591, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.852216748768473, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 3, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.791871921182266, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.8386699507389164, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 4, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8201970443349754, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8793103448275862, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 4, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8743842364532021, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8596059113300493, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 4, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8830049261083744, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8374384236453203, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 4, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8423645320197044, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.850985221674877, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Parameters: {'model__n_neighbors': 4, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8337438423645321, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9421182266009852, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 5, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.8965517241379312, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.8694581280788178, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 5, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.8620689655172414, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408

Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8399014778325123, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Parameters: {'model__n_neighbors': 5, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.854679802955665, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8165024630541873, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Parameters: {'model__n_neighbors': 5, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.832512315270936, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8054187192118227, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 5, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.83128078817734, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9852216748768473, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 6, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9679802955665024, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9298029556650247, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'model__n_neighbors': 6, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9433497536945813, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8669950738916257, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 6, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.876847290640394, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8214285714285714, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 6, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8226600985221675, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7955665024630543, Precision: 0.6428571428571429, Recall: 0.6428571428571429, F1-score: 0.6428571428571429
Parameters: {'model__n_neighbors': 6, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8152709359605912, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.977832512315271, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 7, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.977832512315271, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9199507389162561, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 7, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9359605911330049, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8817733990147782, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Parameters: {'model__n_neighbors': 7, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8571428571428571, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.834975369458128, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 7, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8472906403940886, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7980295566502464, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__n_neighbors': 7, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8300492610837439, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.979064039408867, Precision: 1.0, Recall: 0.42857142857142855, F1-score: 0.6
Parameters: {'model__n_neighbors': 8, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.977832512315271, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9470443349753694, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 8, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9507389162561577, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8633004926108374, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 8, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.9137931034482758, Precision: 0.75, Recall: 0.8571428571428571, F1-score: 0.7999999999999999
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8288177339901477, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__n_neighbors': 8, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8768472906403941, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8091133004926108, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__n_neighbors': 8, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8177339901477833, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9618226600985222, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 9, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9753694581280788, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9334975369458127, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 9, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9482758620689655, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.9137931034482758, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__n_neighbors': 9, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8830049261083744, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8485221674876847, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 9, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.832512315270936, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001

Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8238916256157636, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__n_neighbors': 9, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8201970443349753, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9950738916256159, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9901477832512315, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9482758620689655, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 10, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9236453201970443, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8657635467980296, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 10, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8990147783251232, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8596059113300493, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 10, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8300492610837438, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.812807881773399, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__n_neighbors': 10, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8423645320197045, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9630541871921182, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174
Parameters: {'model__n_neighbors': 11, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9458128078817734, Precision: 1.0, Recall: 0.5, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9482758620689655, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 11, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9532019704433498, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8608374384236454, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Parameters: {'model__n_neighbors': 11, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8990147783251231, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8325123152709359, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__n_neighbors': 11, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8374384236453203, Precision: 0.6, Recall: 0.8571428571428571, F1-score: 0.7058823529411764
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8140394088669951, Precision: 0.5238095238095238, Recall: 0.7857142857142857, F1-score: 0.6285714285714286
Parameters: {'model__n_neighbors': 11, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8423645320197045, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9568965517241379, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 12, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9753694581280788, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9236453201970443, Precision: 0.7692307692307693, Recall: 0.7142857142857143, F1-score: 0.7407407407407408
Parameters: {'model__n_neighbors': 12, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9384236453201971, Precision: 0.75, Recall: 0.6428571428571429, F1-score: 0.6923076923076924
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8780788177339902, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 12, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.9014778325123154, Precision: 0.7333333333333333, Recall: 0.7857142857142857, F1-score: 0.7586206896551724
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8497536945812808, Precision: 0.625, Recall: 0.7142857142857143, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 12, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8423645320197044, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7931034482758621, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__n_neighbors': 12, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8411330049261083, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9716748768472907, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174
Parameters: {'model__n_neighbors': 13, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9926108374384236, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9421182266009853, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__n_neighbors': 13, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9285714285714286, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.9002463054187192, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 13, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.896551724137931, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8275862068965517, Precision: 0.5294117647058824, Recall: 0.6428571428571429, F1-score: 0.5806451612903226
Parameters: {'model__n_neighbors': 13, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8669950738916256, Precision: 0.6666666666666666, Recall: 0.7142857142857143, F1-score: 0.689655172413793
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8251231527093597, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 13, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8177339901477833, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9741379310344828, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174
Parameters: {'model__n_neighbors': 14, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9827586206896551, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273

Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9556650246305419, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'model__n_neighbors': 14, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9630541871921182, Precision: 0.8333333333333334, Recall: 0.7142857142857143, F1-score: 0.7692307692307692
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8805418719211823, Precision: 0.6923076923076923, Recall: 0.6428571428571429, F1-score: 0.6666666666666666
Parameters: {'model__n_neighbors': 14, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8891625615763548, Precision: 0.6875, Recall: 0.7857142857142857, F1-score: 0.7333333333333334
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8497536945812808, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__n_neighbors': 14, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8522167487684729, Precision: 0.5882352941176471, Recall: 0.7142857142857143, F1-score: 0.6451612903225806
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.8004926108374384, Precision: 0.5555555555555556, Recall: 0.7142857142857143, F1-score: 0.6250000000000001
Parameters: {'model__n_neighbors': 14, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8251231527093597, Precision: 0.5789473684210527, Recall: 0.7857142857142857, F1-score: 0.6666666666666667
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'uniform'}
AUC: 0.9766009852216749, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174
Parameters: {'model__n_neighbors': 15, 'model__p': 1, 'model__weights': 'distance'}
AUC: 0.9753694581280788, Precision: 1.0, Recall: 0.5714285714285714, F1-score: 0.7272727272727273
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'uniform'}
AUC: 0.9519704433497537, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'model__n_neighbors': 15, 'model__p': 2, 'model__weights': 'distance'}
AUC: 0.9433497536945814, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'uniform'}
AUC: 0.8842364532019704, Precision: 0.6666666666666666, Recall: 0.8571428571428571, F1-score: 0.75
Parameters: {'model__n_neighbors': 15, 'model__p': 3, 'model__weights': 'distance'}
AUC: 0.8916256157635468, Precision: 0.6470588235294118, Recall: 0.7857142857142857, F1-score: 0.7096774193548386
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'uniform'}
AUC: 0.8596059113300493, Precision: 0.6, Recall: 0.6428571428571429, F1-score: 0.6206896551724138
Parameters: {'model__n_neighbors': 15, 'model__p': 4, 'model__weights': 'distance'}
AUC: 0.8226600985221675, Precision: 0.5625, Recall: 0.6428571428571429, F1-score: 0.6000000000000001
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'uniform'}
AUC: 0.7832512315270936, Precision: 0.5263157894736842, Recall: 0.7142857142857143, F1-score: 0.6060606060606061
Parameters: {'model__n_neighbors': 15, 'model__p': 5, 'model__weights': 'distance'}
AUC: 0.8325123152709359, Precision: 0.6111111111111112, Recall: 0.7857142857142857, F1-score: 0.6875000000000001
Best AUC: 0.9950738916256159
Best parameters: {'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}

In [73]:
best_params

{'model__n_neighbors': 10, 'model__p': 1, 'model__weights': 'uniform'}

In [74]:
model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

pipeline = pipe
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('model', KNeighborsClassifier(n_neighbors=10, p=1))])

In [75]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
    
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)
            


    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9864532019704434, Precision: 1.0, Recall: 0.6428571428571429, F1-score: 0.782608695652174, Accuracy: 0.8837209302325582, Balanced Accuracy: 0.8214285714285714

# SVM

In [76]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train, y_train)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9261083743842364, Precision: 0.8181818181818182, Recall: 0.6428571428571429, F1-score: 0.7200000000000001
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7733990147783252, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857

Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941

Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125

Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4

Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857

Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4

Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8103448275862069, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8411330049261083, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7894088669950738, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.605911330049261, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.0024630541871921152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8189655172413793, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857

Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.01108374384236453, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8140394088669951, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Best AUC: 0.9630541871921182
Best parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}

In [77]:
best_params

{'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}

In [78]:
best_score

0.9630541871921182

In [79]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
pipeline = pipe

In [80]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('clf',
                 SVC(C=0.1, degree=0, gamma=0.1, kernel='linear',
                     probability=True, random_state=100))])

In [81]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            


    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857, Accuracy: 0.8604651162790697, Balanced Accuracy: 0.8411330049261083

# SVM + SMOTE

In [82]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

# Function to evaluate parameters using LeaveOneGroupOut
def evaluate_params_with_leave_one_group_out(pipeline, X, y, groups, param_grid):
    best_score = -1
    best_params = None
    cv = LeaveOneGroupOut()

    # Iterate over all parameter combinations
    for params in ParameterGrid(param_grid):
        pipeline.set_params(**params)
        y_true_all = []
        y_pred_all = []
        y_pred_proba_all = []

        # Manually iterate over each fold
        for i, (train_idx, test_idx) in enumerate(cv.split(X, y, groups)):
            X_train, X_test = X.loc[train_idx], X.loc[test_idx]
            y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
            #Replace nan values
            
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_train = imp.transform(X_train)
            X_test = imp.transform(X_test)
            
            sm = SMOTE()
            X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

            # Fit the pipeline on the training data (SMOTE is applied here)
            pipeline.fit(X_train_oversampled, y_train_oversampled)

            # Predict on the test data
            y_pred = pipeline.predict(X_test)
            y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

        # Compute metrics
        auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
        precision = precision_score(y_true_all, y_pred_all)
        recall = recall_score(y_true_all, y_pred_all)
        f1 = f1_score(y_true_all, y_pred_all)

        print(f'Parameters: {params}')
        print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

        if auc_score > best_score:
            best_score = auc_score
            best_params = params

    return best_score, best_params

# Find the best parameters
best_score, best_params = evaluate_params_with_leave_one_group_out(pipe, X_new, y, groups, param_grid)
print(f'Best AUC: {best_score}')
print(f'Best parameters: {best_params}')

Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9753694581280788, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2438423645320197, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9556650246305419, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27339901477832507, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.291871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9532019704433499, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22660098522167488, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8916256157635467, Precision: 0.7142857142857143, Recall: 0.7142857142857143, F1-score: 0.7142857142857143
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2783251231527093, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9679802955665024, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.291871921182266, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9655172413793104, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9655172413793103, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9729064039408867, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.25985221674876846, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5381773399014779, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921183, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.28078817733990147, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5886699507389163, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2795566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5935960591133005, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9729064039408867, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27216748768472904, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6748768472906403, Precision: 0.5, Recall: 0.35714285714285715, F1-score: 0.41666666666666663
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9729064039408867, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.23522167487684725, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8201970443349753, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.25369458128078815, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270936, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2697044334975369, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8472906403940887, Precision: 0.8888888888888888, Recall: 0.5714285714285714, F1-score: 0.6956521739130435
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666

Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.27093596059113295, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 0.1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8275862068965518, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.2204433497536945, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.45073891625615764, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27832512315270935, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.49014778325123154, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2549261083743842, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6182266009852216, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9753694581280787, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.26724137931034475, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 0.1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6108374384236452, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.23522167487684725, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7980295566502463, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5763546798029556, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9556650246305418, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.27216748768472904, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7401477832512315, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9729064039408867, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.2672413793103448, Precision: 0.2857142857142857, Recall: 0.14285714285714285, F1-score: 0.19047619047619047
Parameters: {'clf__C': 0.1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7807881773399015, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.22660098522167485, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6674876847290641, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2660098522167488, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6182266009852218, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2770935960591132, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5086206896551724, Precision: 0.2, Recall: 0.07142857142857142, F1-score: 0.10526315789473682
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.28940886699507384, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 0.1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5541871921182266, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536945, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5024630541871921, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3571428571428571, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.46798029556650245, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5283251231527094, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.960591133004926, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5123152709359605, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2635467980295566, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.32881773399014774, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.6108374384236454, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9655172413793104, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.522167487684729, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5369458128078818, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.39901477832512317, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5098522167487685, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3411330049261084, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5689655172413793, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5443349753694582, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5788177339901478, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921183, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5123152709359606, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270935, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9556650246305419, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3103448275862069, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8497536945812808, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5332512315270936, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8152709359605912, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.46921182266009853, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8448275862068966, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5073891625615763, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6243842364532018, Precision: 0.4, Recall: 0.14285714285714285, F1-score: 0.21052631578947364
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.33743842364532023, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5985221674876847, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857

Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.33620689655172414, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6231527093596059, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5923645320197045, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5049261083743843, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921183, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7290640394088669, Precision: 0.6666666666666666, Recall: 0.2857142857142857, F1-score: 0.4
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.43349753694581283, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.770935960591133, Precision: 0.5555555555555556, Recall: 0.35714285714285715, F1-score: 0.43478260869565216
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8666666666666667, Recall: 0.9285714285714286, F1-score: 0.896551724137931
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5135467980295567, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7253694581280788, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921183, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5012315270935961, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7783251231527094, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.6009852216748768, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5073891625615764, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4014778325123152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6736453201970443, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.45935960591133007, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5467980295566502, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.48891625615763545, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5270935960591132, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.44334975369458124, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9729064039408868, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3349753694581281, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4002463054187192, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5344827586206897, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.43842364532019706, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9729064039408867, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3078817733990148, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9729064039408867, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4876847290640394, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9704433497536946, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4827586206896552, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.583743842364532, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.35960591133004927, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5197044334975369, Precision: 0.5, Recall: 0.2857142857142857, F1-score: 0.36363636363636365
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.6564039408866995, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5270935960591133, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9729064039408867, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4507389162561576, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5714285714285714, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.6157635467980296, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8029556650246306, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.31527093596059114, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8251231527093595, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3435960591133005, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8300492610837439, Precision: 0.8, Recall: 0.5714285714285714, F1-score: 0.6666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9704433497536945, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.37561576354679804, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7931034482758621, Precision: 0.7, Recall: 0.5, F1-score: 0.5833333333333334
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4876847290640394, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5492610837438424, Precision: 0.3333333333333333, Recall: 0.14285714285714285, F1-score: 0.2
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3201970443349754, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5615763546798029, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5578817733990148, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6637931034482758, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4187192118226601, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6798029556650247, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.4187192118226601, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6995073891625616, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093

Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.27586206896551724, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7438423645320197, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.3694581280788177, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7463054187192119, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.47783251231527096, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8078817733990147, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5295566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.687192118226601, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.3374384236453202, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6625615763546798, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.28817733990147787, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.41379310344827586, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4088669950738917, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 10, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.3300492610837439, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.960591133004926, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.45566502463054187, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5985221674876847, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.47290640394088673, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3275862068965517, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5467980295566502, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9507389162561576, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.229064039408867, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9704433497536946, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.43349753694581283, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.47413793103448276, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857

Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5689655172413793, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.6576354679802956, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6379310344827587, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.312807881773399, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5270935960591132, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.45935960591133007, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5985221674876847, Precision: 0.8, Recall: 0.2857142857142857, F1-score: 0.4210526315789473
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5467980295566502, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8522167487684729, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.32142857142857145, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7561576354679804, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.37807881773399016, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.8571428571428571, Precision: 0.8571428571428571, Recall: 0.42857142857142855, F1-score: 0.5714285714285714
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5529556650246306, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8152709359605911, Precision: 0.6666666666666666, Recall: 0.42857142857142855, F1-score: 0.5217391304347826
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5443349753694582, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6305418719211824, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.29802955665024633, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5997536945812808, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.6330049261083744, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5923645320197044, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.960591133004926, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4014778325123152, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5714285714285714, Precision: 0.3333333333333333, Recall: 0.07142857142857142, F1-score: 0.11764705882352941
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48768472906403937, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7056650246305419, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9802955665024631, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.270935960591133, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.7906403940886699, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.45443349753694573, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7980295566502463, Precision: 0.6, Recall: 0.21428571428571427, F1-score: 0.3157894736842105
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.4827586206896552, Precision: 0.0, Recall: 0.0, F1-score: 0.0

Parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6699507389162562, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48275862068965514, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.645320197044335, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4704433497536946, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.5775862068965518, Precision: 0.75, Recall: 0.21428571428571427, F1-score: 0.3333333333333333
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4445812807881773, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5172413793103448, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.958128078817734, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.6477832512315271, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 100, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.5541871921182266, Precision: 0.42857142857142855, Recall: 0.21428571428571427, F1-score: 0.2857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.6157635467980296, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9704433497536945, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.18226600985221675, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.47660098522167493, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.40270935960591125, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 0, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.27709359605911327, Precision: 0.32558139534883723, Recall: 1.0, F1-score: 0.49122807017543857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5689655172413793, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9507389162561577, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.31773399014778325, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9753694581280788, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.4519704433497537, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.26354679802955666, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 1, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5960591133004927, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.5320197044334976, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793103, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4236453201970444, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.583743842364532, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.25369458128078815, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5246305418719213, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112

Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5615763546798029, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 2, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6330049261083743, Precision: 0.5714285714285714, Recall: 0.2857142857142857, F1-score: 0.38095238095238093
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921183, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.6059113300492611, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.8177339901477833, Precision: 0.75, Recall: 0.42857142857142855, F1-score: 0.5454545454545454
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.2857142857142857, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.8719211822660098, Precision: 0.875, Recall: 0.5, F1-score: 0.6363636363636364
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.8125, Recall: 0.9285714285714286, F1-score: 0.8666666666666666
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.5061576354679803, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.7512315270935961, Precision: 0.7272727272727273, Recall: 0.5714285714285714, F1-score: 0.64
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.47290640394088673, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 3, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.8226600985221675, Precision: 0.7777777777777778, Recall: 0.5, F1-score: 0.6086956521739131
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5763546798029557, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7426108374384236, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.5098522167487685, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.49261083743842365, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.2647783251231527, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5763546798029556, Precision: 0.625, Recall: 0.35714285714285715, F1-score: 0.45454545454545453
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.3152709359605912, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 4, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7536945812807881, Precision: 0.7142857142857143, Recall: 0.35714285714285715, F1-score: 0.4761904761904762
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9630541871921182, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.5886699507389163, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.7832512315270936, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.19950738916256155, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.6477832512315271, Precision: 0.5, Recall: 0.21428571428571427, F1-score: 0.3
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.24753694581280788, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.6133004926108374, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5295566502463054, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 5, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.7167487684729064, Precision: 0.5, Recall: 0.07142857142857142, F1-score: 0.125
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'linear'}
AUC: 0.9655172413793104, Precision: 0.7857142857142857, Recall: 0.7857142857142857, F1-score: 0.7857142857142857
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'rbf'}
AUC: 0.48522167487684736, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 0.1, 'clf__kernel': 'poly'}
AUC: 0.6206896551724137, Precision: 0.5, Recall: 0.14285714285714285, F1-score: 0.22222222222222224
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'linear'}
AUC: 0.9556650246305419, Precision: 0.8461538461538461, Recall: 0.7857142857142857, F1-score: 0.8148148148148148
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'rbf'}
AUC: 0.4556650246305419, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 1, 'clf__kernel': 'poly'}
AUC: 0.4827586206896552, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'linear'}
AUC: 0.9679802955665024, Precision: 0.8571428571428571, Recall: 0.8571428571428571, F1-score: 0.8571428571428571

Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'rbf'}
AUC: 0.35467980295566504, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 10, 'clf__kernel': 'poly'}
AUC: 0.5172413793103449, Precision: 0.6666666666666666, Recall: 0.14285714285714285, F1-score: 0.23529411764705882
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'linear'}
AUC: 0.9605911330049262, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'rbf'}
AUC: 0.5874384236453203, Precision: 0.0, Recall: 0.0, F1-score: 0.0
Parameters: {'clf__C': 1000, 'clf__degree': 6, 'clf__gamma': 100, 'clf__kernel': 'poly'}
AUC: 0.6379310344827587, Precision: 0.25, Recall: 0.07142857142857142, F1-score: 0.11111111111111112
Best AUC: 0.9802955665024631
Best parameters: {'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}

In [83]:
best_params

{'clf__C': 100, 'clf__degree': 5, 'clf__gamma': 1, 'clf__kernel': 'linear'}

In [84]:

# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('sca', StandardScaler()),  # Preprocessing step
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
pipeline = pipe

In [85]:
pipeline.set_params(**best_params)

Pipeline(steps=[('sca', StandardScaler()),
                ('clf',
                 SVC(C=100, degree=5, gamma=1, kernel='linear',
                     probability=True, random_state=100))])

In [86]:
y_true_all = []
y_pred_all = []
y_pred_proba_all = []


# Manually iterate over each fold
for i, (train_idx, test_idx) in enumerate(cv.split(X_new, y, groups)):
    X_train, X_test = X_new.loc[train_idx], X_new.loc[test_idx]
    y_train, y_test = y.loc[train_idx], y.loc[test_idx]
            
    #Replace nan values
            
    imp = SimpleImputer(missing_values=np.nan, strategy='mean')
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    X_test = imp.transform(X_test)
            
    sm = SMOTE()
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)

    # Fit the pipeline on the training data (SMOTE is applied here)
    pipeline.fit(X_train_oversampled, y_train_oversampled)

    # Predict on the test data
    y_pred = pipeline.predict(X_test)
    y_pred_proba = pipeline.predict_proba(X_test)[:, 1]  # Probabilities for AUC

    # Collect predictions and true labels
    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)
    y_pred_proba_all.extend(y_pred_proba)

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.9704433497536946, Precision: 0.8, Recall: 0.8571428571428571, F1-score: 0.8275862068965518, Accuracy: 0.8837209302325582, Balanced Accuracy: 0.8768472906403941