In [1]:
import pandas as pd
import numpy as np
from os import listdir

In [2]:
import sklearn

In [3]:
# Ignore warnings
import warnings; warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline



from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
from sklearn import svm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

#from skbold.preproc.confounds import ConfoundRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn import preprocessing
    
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.impute import SimpleImputer



# Import libraries
import os
import numpy as np
import pandas as pd


from sklearn.feature_selection import RFE
from sklearn.metrics import balanced_accuracy_score

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn.model_selection import cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import make_scorer
from sklearn.metrics import \
    confusion_matrix, \
    accuracy_score, \
    matthews_corrcoef, \
    precision_score, \
    recall_score, \
    f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import LeaveOneOut


import pymrmr

# Set the random generator seed
seed = 42

# Matplotlib settings
plt.style.use("classic")

# Seaborn settings
sns.set()
sns.set(font_scale=1.0)
sns.set_style({"font.family":"serif", "font.serif":["Times New Roman"]})

# Show seaborn settings
sns.axes_style()

{'axes.facecolor': '#EAEAF2',
 'axes.edgecolor': 'white',
 'axes.grid': True,
 'axes.axisbelow': True,
 'axes.labelcolor': '.15',
 'figure.facecolor': 'white',
 'grid.color': 'white',
 'grid.linestyle': '-',
 'text.color': '.15',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'lines.solid_capstyle': <CapStyle.round: 'round'>,
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'font.family': ['serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'xtick.bottom': False,
 'xtick.top': False,
 'ytick.left': False,
 'ytick.right': False,
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True}

In [4]:
# ------------------------------
# Define the classifier settings
# ------------------------------

model_params = {
    
    # General parameters
    "booster": "gbtree", 
    "silent": True, 
    "n_jobs": -1, 
    
    # Learning task parameters
    "objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "eval_metric": "error", 
    "seed": seed, 
    
    # Tree Booster parameters
    "n_estimators": 500, 
    "learning_rate": 0.20, 
    "gamma": 1.0, 
    "max_depth": 10, 
    "subsample": 1.0, 
    "colsample_bylevel": 1, 
    "colsample_bytree": 1.0, 
    "min_child_weight": 5
}

# ------------------------------------------
# Define the hyper-parameter tuning settings
# ------------------------------------------

param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [1, 3, 5, 6, 7, 9]  # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
#scale_pos_weight = total_negative_examples / total_positive_examples
}

search_settings = {
    "param_distributions": param_grid, 
    "scoring": "balanced_accuracy",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
}

In [5]:
# ---------------------------------
# Define the classification metrics
# ---------------------------------

def sensitivity_score(y_true, y_pred):
    return recall_score(y_true, y_pred)

def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)

In [6]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import os

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

# For models
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# For evaluation
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score
from sklearn.preprocessing import OneHotEncoder

In [7]:
colff= ['21_123angle_aft_MFCC_10',
 '40_87angle_aft_MFCC_10',
 '64_116angle_mid_Peak to peak distance',
 '113_121distance_mid_Median',
 '95_120distance_mid_Histogram mode',
 '95_121distance_mid_ECDF Percentile_0',
 '3_49angle_mid_Skewness',
 '65_100angle_eve_MFCC_10',
 '55_105angle_mor_Wavelet variance_12.5Hz',
 '43_131distance_aft_Median absolute deviation',
 '23_58angle_eve_LPCC_6',
 '104_105angle_aft_LPCC_6',
 '13_48angle_aft_Wavelet variance_3.12Hz',
 '16_32distance_aft_Interquartile range',
 '8_37distance_mid_MFCC_11',
 '40_62distance_eve_MFCC_5',
 '19_97distance_aft_MFCC_10',
 '92_96angle_eve_MFCC_9',
 '30_67angle_eve_MFCC_3',
 '89_99distance_mid_Wavelet variance_4.17Hz',
 '24_42angle_eve_Interquartile range',
 '92_118distance_mid_MFCC_7',
 '35_67distance_mid_Median absolute diff',
 '101_102distance_mid_MFCC_8',
 '5_7distance_aft_MFCC_5',
 '27_29distance_aft_Median absolute deviation',
 '54_117angle_eve_Peak to peak distance',
 '4_31distance_mid_Skewness',
 '111_130distance_mid_Interquartile range',
 '22_39angle_eve_Peak to peak distance',
 '22_60angle_eve_Peak to peak distance',
 '3_7distance_aft_MFCC_10',
 '7_49angle_aft_Spectral spread',
 '106_118distance_mid_Interquartile range',
 '22_68angle_mid_MFCC_0',
 '102_106angle_aft_LPCC_6',
 '112_129distance_eve_Wavelet variance_12.5Hz',
 '96_118angle_mid_Min',
 '44_123angle_mor_Median diff',
 '126_129angle_aft_Wavelet variance_2.78Hz',
 '23_58angle_aft_Human range energy',
 '19_119angle_mid_Median',
 '89_130angle_eve_Median diff',
 '50_106angle_aft_MFCC_1',
 '121_130distance_mid_Histogram mode',
 '30_59angle_mid_Spectral variation',
 '48_57distance_eve_Histogram mode',
 '22_113angle_aft_ECDF Percentile_1',
 '101_107angle_aft_LPCC_6',
 '33_69angle_aft_MFCC_7',
 '14_47angle_mid_Spectral entropy',
 '14_78angle_mor_Wavelet entropy',
 '90_123angle_mid_MFCC_4',
 '20_128angle_aft_Interquartile range',
 '4_9distance_aft_MFCC_5',
 '53_62angle_eve_MFCC_3',
 '2_97angle_eve_Peak to peak distance',
 '117_118angle_aft_Spectral spread',
 '43_91angle_aft_Variance',
 '64_124angle_aft_LPCC_2',
 '64_124angle_aft_LPCC_10',
 '129_130distance_aft_Kurtosis',
 '42_129distance_mor_Median diff',
 '30_61angle_eve_MFCC_3',
 '35_100angle_eve_Peak to peak distance',
 '5_52distance_eve_ECDF Percentile_1',
 '53_117angle_eve_MFCC_5',
 '109_130distance_mid_Histogram mode',
 '55_105angle_aft_ECDF Percentile_1',
 '65_99angle_mor_Spectral entropy',
 '115_124angle_mid_Root mean square',
 '15_76angle_eve_Peak to peak distance',
 '0_9distance_aft_MFCC_5',
 '74_107angle_eve_Max',
 '92_116angle_mid_MFCC_10',
 '98_114angle_eve_Spectral roll-on',
 '115_124distance_aft_Wavelet standard deviation_4.17Hz',
 '0_7angle_aft_MFCC_10',
 '67_127angle_aft_MFCC_0',
 '34_71angle_aft_MFCC_8',
 '65_124angle_aft_Wavelet variance_2.78Hz',
 '22_127angle_mor_MFCC_8',
 '14_81angle_eve_Peak to peak distance',
 '15_48angle_eve_Peak to peak distance',
 '55_119distance_aft_Median diff',
 '110_113angle_mid_Spectral decrease',
 '18_107distance_aft_MFCC_10',
 '48_61distance_mor_MFCC_0',
 '0_55angle_eve_Power bandwidth',
 '4_74angle_eve_MFCC_7',
 '73_118angle_aft_Wavelet variance_2.78Hz',
 '63_115angle_eve_MFCC_11',
 '78_82angle_mid_Spectral entropy',
 '35_114angle_aft_LPCC_6',
 '20_98distance_aft_MFCC_10',
 '97_128distance_eve_Variance',
 '15_113angle_eve_MFCC_0',
 '61_99angle_eve_MFCC_10',
 '44_74angle_mid_MFCC_9',
 '103_109angle_mid_MFCC_6',
 '121_128distance_mid_Median',
 '54_67distance_aft_Median frequency',
 '107_109angle_eve_Spectral roll-on',
 '4_130angle_eve_MFCC_0',
 '45_97angle_aft_MFCC_11',
 '72_86angle_eve_MFCC_9',
 '49_61distance_mor_MFCC_0',
 '14_82angle_mor_Mean absolute diff',
 '106_117distance_aft_Median absolute deviation',
 '108_132distance_aft_Mean absolute deviation',
 '14_132angle_eve_Peak to peak distance',
 '15_54angle_eve_Min',
 '107_117distance_mid_ECDF Percentile_1',
 '19_111angle_mor_MFCC_0',
 '63_99angle_mid_Peak to peak distance',
 '57_70distance_mor_MFCC_2',
 '0_114angle_eve_Max',
 '51_52distance_aft_MFCC_5',
 '5_11angle_eve_Peak to peak distance',
 '55_105angle_mor_Wavelet standard deviation_12.5Hz',
 '111_130distance_mid_Median absolute deviation',
 '17_55angle_mid_Peak to peak distance',
 '110_115angle_aft_Human range energy',
 '89_116angle_mid_MFCC_6',
 '21_124angle_aft_LPCC_1',
 '112_121distance_mid_Histogram mode',
 '17_20distance_aft_MFCC_4',
 '65_90angle_aft_Wavelet energy_8.33Hz',
 '70_91angle_aft_Max power spectrum',
 '60_61distance_eve_MFCC_5',
 '44_82distance_eve_Median diff',
 '35_116angle_eve_Peak to peak distance',
 '63_124angle_eve_Human range energy',
 '86_95angle_aft_MFCC_1']

In [8]:
import polars as pl
import csv

In [9]:
file_path = './dataset/ff/data_all_ff.csv'

In [10]:
# Specify the columns you want to read
columns_to_read = colff + ['diagnosis', 'patient', 'record']

In [11]:
 # Step 3: Use scan_csv and select to read specific columns
df = pl.scan_csv(file_path).select(columns_to_read).collect()

In [12]:
dataset = df.to_pandas()

In [13]:
subdata = pd.read_csv('./dataset/ff_cross/ff_0_.csv')
subdata2 =pd.read_csv('./dataset/ff_cross/ff_1_.csv')

In [14]:
subdata_all = pd.concat([subdata, subdata2])
flag = 0 
for i in range(0, 43):
    subdata = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(subdata)>1:
        if flag==0:
            subdata_all = subdata.loc[1:].copy()
            flag = 1
        else:
            subdata_all = pd.concat([subdata_all, subdata.loc[1:]])

In [15]:
subdata_all

,Unnamed: 0,patient,record,diagnosis,type_data,subrecord,0_114angle_mid_Absolute energy,0_114angle_mid_Area under the curve,0_114angle_mid_Autocorrelation,0_114angle_mid_Average power,...,5_11angle_eve_rsd,17_55angle_eve_rsd,110_115angle_eve_rsd,89_116angle_eve_rsd,21_124angle_eve_rsd,65_90angle_eve_rsd,70_91angle_eve_rsd,35_116angle_eve_rsd,63_124angle_eve_rsd,86_95angle_eve_rsd
1,0,P08,0,0,test,1,185.012775,1.346699,1.0,166.678175,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,P08,0,0,train,1,1043.141716,7.499642,1.0,179.852020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,P08,0,0,test,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,P08,0,0,train,2,1226.611615,8.846341,1.0,177.512535,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0,P08,0,0,test,3,470.338330,3.338522,1.0,193.554869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,0,P38,42,0,test,1,351.308100,2.472087,13.0,200.747486,...,-41.154547,-44.018166,57.423641,33.694526,-12.950923,-30.817227,4.356628,-24.731936,-40.307960,-21.717737
3,0,P38,42,0,test,2,393.267350,2.800743,24.0,195.655398,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,P38,42,0,test,2,351.308100,2.472087,13.0,200.747486,...,-34.034396,-35.999350,55.427850,31.695180,-10.430270,-25.040078,12.625896,-19.038558,-31.477863,-19.049126
5,0,P38,42,0,test,3,NaN,NaN,NaN,NaN,...,-1851.305184,2933.342165,-182.206758,24.675427,-22.726390,-832.009167,5.318916,-167.101103,-5436.351972,-26.734821
6,0,P38,42,0,test,3,744.575451,5.287778,30.0,197.500120,...,-34.005574,-35.968358,55.607866,31.669813,-10.422221,-25.019761,12.622032,-19.023512,-31.451526,-19.035648

In [16]:
del subdata_all['Unnamed: 0']
del subdata_all['type_data']
del subdata_all['subrecord']

In [17]:
subdata_all = subdata_all[columns_to_read]

In [18]:
dataset = pd.concat([dataset, subdata_all])

In [19]:
group = dataset['patient']

In [20]:
group = dataset['patient']
patients_pandas_encoded = pd.get_dummies(group, columns=['patient'], drop_first=False)

In [21]:
del dataset['patient']

In [22]:
dataset = dataset.fillna(dataset.mean())

In [23]:
y = dataset['diagnosis']

In [24]:
records  = dataset['record']

In [25]:
del dataset['record']

In [26]:
X = dataset.copy()

# Feature selection

In [27]:
import pymrmr

In [28]:
X = dataset.copy()

In [29]:
del X['diagnosis']

In [30]:
type_classification = 'binary'



#X = X.replace([np.nan, -np.inf, np.inf], 0)
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)
#y = y.reshape((len(y), ))
X.insert(loc=0, column='class', value=y)
X_to_choose = X.copy()
#Discritize data
_, nr_col = np.shape(X)
for i in range(1, nr_col):
    discretizer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='kmeans')
    X.iloc[:, i] = discretizer.fit_transform(X.iloc[:, i].values.reshape(-1,1))
    
col = pymrmr.mRMR(X, 'MIQ', 50)

In [31]:
col

['115_124angle_mid_Root mean square',
 '23_58angle_eve_LPCC_6',
 '14_82angle_mor_Mean absolute diff',
 '16_32distance_aft_Interquartile range',
 '89_99distance_mid_Wavelet variance_4.17Hz',
 '103_109angle_mid_MFCC_6',
 '15_113angle_eve_MFCC_0',
 '107_117distance_mid_ECDF Percentile_1',
 '107_109angle_eve_Spectral roll-on',
 '14_78angle_mor_Wavelet entropy',
 '106_118distance_mid_Interquartile range',
 '92_116angle_mid_MFCC_10',
 '42_129distance_mor_Median diff',
 '112_129distance_eve_Wavelet variance_12.5Hz',
 '55_105angle_mor_Wavelet variance_12.5Hz',
 '19_119angle_mid_Median',
 '72_86angle_eve_MFCC_9',
 '14_47angle_mid_Spectral entropy',
 '98_114angle_eve_Spectral roll-on',
 '44_82distance_eve_Median diff',
 '61_99angle_eve_MFCC_10',
 '20_98distance_aft_MFCC_10',
 '19_111angle_mor_MFCC_0',
 '63_115angle_eve_MFCC_11',
 '44_74angle_mid_MFCC_9',
 '111_130distance_mid_Interquartile range',
 '35_100angle_eve_Peak to peak distance',
 '5_7distance_aft_MFCC_5',
 '89_116angle_mid_MFCC_6',
 '30_67angle_eve_MFCC_3',
 '63_124angle_eve_Human range energy',
 '95_120distance_mid_Histogram mode',
 '55_105angle_mor_Wavelet standard deviation_12.5Hz',
 '92_118distance_mid_MFCC_7',
 '24_42angle_eve_Interquartile range',
 '35_67distance_mid_Median absolute diff',
 '4_31distance_mid_Skewness',
 '4_130angle_eve_MFCC_0',
 '0_55angle_eve_Power bandwidth',
 '111_130distance_mid_Median absolute deviation',
 '3_49angle_mid_Skewness',
 '4_74angle_eve_MFCC_7',
 '117_118angle_aft_Spectral spread',
 '22_39angle_eve_Peak to peak distance',
 '53_117angle_eve_MFCC_5',
 '22_68angle_mid_MFCC_0',
 '0_9distance_aft_MFCC_5',
 '78_82angle_mid_Spectral entropy',
 '95_121distance_mid_ECDF Percentile_0',
 '92_96angle_eve_MFCC_9']

In [32]:
col = ['115_124angle_mid_Root mean square',
 '23_58angle_eve_LPCC_6',
 '14_82angle_mor_Mean absolute diff',
 '16_32distance_aft_Interquartile range',
 '89_99distance_mid_Wavelet variance_4.17Hz',
 '103_109angle_mid_MFCC_6',
 '15_113angle_eve_MFCC_0',
 '107_117distance_mid_ECDF Percentile_1',
 '107_109angle_eve_Spectral roll-on',
 '14_78angle_mor_Wavelet entropy',
 '106_118distance_mid_Interquartile range',
 '92_116angle_mid_MFCC_10',
 '42_129distance_mor_Median diff',
 '112_129distance_eve_Wavelet variance_12.5Hz',
 '55_105angle_mor_Wavelet variance_12.5Hz',
 '19_119angle_mid_Median',
 '72_86angle_eve_MFCC_9',
 '14_47angle_mid_Spectral entropy',
 '98_114angle_eve_Spectral roll-on',
 '44_82distance_eve_Median diff',
 '61_99angle_eve_MFCC_10',
 '20_98distance_aft_MFCC_10',
 '19_111angle_mor_MFCC_0',
 '63_115angle_eve_MFCC_11',
 '44_74angle_mid_MFCC_9',
 '111_130distance_mid_Interquartile range',
 '35_100angle_eve_Peak to peak distance',
 '5_7distance_aft_MFCC_5',
 '89_116angle_mid_MFCC_6',
 '30_67angle_eve_MFCC_3',
 '63_124angle_eve_Human range energy',
 '95_120distance_mid_Histogram mode',
 '55_105angle_mor_Wavelet standard deviation_12.5Hz',
 '92_118distance_mid_MFCC_7',
 '24_42angle_eve_Interquartile range',
 '35_67distance_mid_Median absolute diff',
 '4_31distance_mid_Skewness',
 '4_130angle_eve_MFCC_0',
 '0_55angle_eve_Power bandwidth',
 '111_130distance_mid_Median absolute deviation',
 '3_49angle_mid_Skewness',
 '4_74angle_eve_MFCC_7',
 '117_118angle_aft_Spectral spread',
 '22_39angle_eve_Peak to peak distance',
 '53_117angle_eve_MFCC_5',
 '22_68angle_mid_MFCC_0',
 '0_9distance_aft_MFCC_5',
 '78_82angle_mid_Spectral entropy',
 '95_121distance_mid_ECDF Percentile_0',
 '92_96angle_eve_MFCC_9']

# Read the data again to import data with NaN values

In [33]:
 # Step 3: Use scan_csv and select to read specific columns
df = pl.scan_csv(file_path).select(columns_to_read).collect()

In [34]:
dataset = df.to_pandas()

In [35]:
group = dataset['patient']
groups = group
del dataset['patient']
y = dataset['diagnosis']
del dataset['diagnosis']
records  = dataset['record']
del dataset['record']
X = dataset.copy()

In [36]:
patients_pandas_encoded = pd.get_dummies(group, columns=['patient'], drop_first=False)
patients_pandas_encoded

,P08,P10,P12,P13,P14,P15,P16,P17,P18,P19,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [37]:
X_new = X[col]

In [38]:
patients_pandas_encoded

,P08,P10,P12,P13,P14,P15,P16,P17,P18,P19,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [39]:
X_new2 = pd.concat([X_new, patients_pandas_encoded], axis=1)

In [40]:
X_new2

,115_124angle_mid_Root mean square,23_58angle_eve_LPCC_6,14_82angle_mor_Mean absolute diff,16_32distance_aft_Interquartile range,89_99distance_mid_Wavelet variance_4.17Hz,103_109angle_mid_MFCC_6,15_113angle_eve_MFCC_0,107_117distance_mid_ECDF Percentile_1,107_109angle_eve_Spectral roll-on,14_78angle_mor_Wavelet entropy,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,0.799061,0.547888,0.140407,0.248338,0.001430,-32.270011,-8.506768,0.095242,0.133359,2.112047,...,False,False,False,False,False,False,False,False,False,False
1,0.805598,0.330272,0.206613,0.462673,0.000817,60.100474,-9.942865,0.094939,0.221566,2.134689,...,False,False,False,False,False,False,False,False,False,False
2,0.877206,0.355458,0.493341,0.150280,0.001581,0.964868,-18.733969,0.128673,0.315457,2.171846,...,False,False,False,False,False,False,False,False,False,False
3,0.911890,0.402899,NaN,0.258733,0.001716,26.350711,-12.901433,0.092525,0.000000,NaN,...,False,False,False,False,False,False,False,False,False,False
4,0.899741,0.045994,0.592048,0.238226,0.003014,45.764440,-23.261897,0.130291,0.444444,2.153781,...,False,False,False,False,False,False,False,False,False,False
5,1.064670,0.043891,0.540227,0.403640,0.003370,20.210643,-10.349569,0.097255,0.492611,2.156402,...,False,False,False,False,False,False,False,False,False,False
6,1.095154,0.376512,NaN,0.152366,0.000701,67.632682,-4.332810,0.087734,0.061779,NaN,...,False,False,False,False,False,False,False,False,False,False
7,1.001981,0.361152,NaN,NaN,0.001296,64.421615,-5.981129,0.088843,0.000000,NaN,...,False,False,False,False,False,False,False,False,False,False
8,1.024450,0.349777,0.249261,0.247856,0.001089,-49.658188,-10.462858,0.069503,0.050150,2.127610,...,False,False,False,False,False,False,False,False,False,False
9,NaN,0.394027,0.321497,0.143223,NaN,NaN,2.064593,NaN,0.260870,2.093011,...,False,False,False,False,False,False,False,False,False,False
10,0.880157,0.321086,0.467098,0.309357,0.002099,89.830508,-7.533548,0.140802,0.156006,2.140566,...,False,False,False,False,False,False,False,False,False,False
11,1.068593,0.394348,NaN,0.238120,0.000672,67.047876,-0.005159,0.089340,0.239864,NaN,...,False,False,False,False,False,False,False,False,False,False
12,1.039626,0.328707,0.178446,0.209873,0.000893,52.907511,-6.844734,0.093037,0.167150,2.093095,...,False,False,False,False,False,False,False,False,False,False
13,1.014138,0.195874,0.911119,0.220113,0.000766,-12.229299,-26.060457,0.084887,0.213523,2.159376,...,False,False,False,False,False,False,False,False,False,False
14,0.900893,0.117360,0.456404,0.329747,0.002144,3.787973,-23.021024,0.114105,0.306212,2.145159,...,False,False,False,False,False,False,False,False,False,False
15,0.907612,0.280119,0.690929,0.342367,0.002384,18.277266,-20.408375,0.113345,0.355094,2.129101,...,False,False,False,False,False,False,False,False,False,False
16,0.860832,NaN,0.458408,0.329708,0.000479,-22.582685,NaN,0.091790,NaN,2.146662,...,False,False,False,False,False,False,False,False,False,False
17,0.860942,NaN,0.385031,0.297562,0.000928,-0.374956,NaN,0.125526,NaN,2.132970,...,False,False,False,False,False,False,False,False,False,False
18,0.918823,0.325029,0.362711,0.248670,0.001057,41.339322,-56.932462,0.084753,0.099900,2.094059,...,False,False,False,False,False,False,False,False,False,False
19,0.949925,0.488847,0.410877,0.195408,0.001541,30.375659,-7.517608,0.084546,0.000000,2.077945,...,False,False,False,False,False,False,False,False,False,False
20,0.939003,0.422785,0.014492,0.194119,0.001003,74.086106,-8.201538,0.094972,0.073502,1.982039,...,False,False,False,False,False,False,False,False,False,False
21,0.898280,0.253911,0.785377,0.135091,0.000820,-36.495093,-16.135907,0.087939,0.152983,2.159546,...,False,False,False,False,False,False,False,False,False,False
22,1.001632,0.324294,0.221361,0.214141,0.000406,60.769235,-18.604452,0.083799,0.127518,2.069681,...,False,False,False,False,False,False,False,False,False,False
23,0.956102,0.270030,0.320581,0.231446,0.001385,20.845260,-8.151565,0.082102,0.052301,2.130949,...,False,False,False,False,False,False,False,False,False,False
24,0.900785,0.260071,NaN,0.329442,0.000483,31.715290,-16.494398,0.099318,0.197368,NaN,...,False,False,False,False,False,False,False,False,False,False
25,0.877737,0.285840,0.320733,0.371241,0.000549,8.430119,-8.530967,0.103861,0.223104,2.108284,...,False,False,False,False,False,False,False,False,False,False
26,1.018779,NaN,0.535981,0.554327,0.001925,46.711495,NaN,0.079102,NaN,2.101996,...,False,False,False,False,False,False,False,False,False,False
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
28,1.014020,0.290239,NaN,0.254758,0.001276,55.219283,-9.736535,0.107669,0.212831,NaN,...,False,True,False,False,False,False,False,False,False,False
29,0.957086,0.234189,0.147415,0.140721,0.000659,46.023018,-2.489079,0.096432,0.196899,2.089796,...,False,False,True,False,False,False,False,False,False,False
30,0.989190,0.459767,NaN,0.147221,0.000398,24.433558,-0.592890,0.083376,0.000000,NaN,...,False,False,True,False,False,False,False,False,False,False
31,0.918983,0.224063,NaN,0.268839,0.001985,25.797245,-20.582742,0.116053,0.402145,NaN,...,False,False,False,True,False,False,False,False,False,False
32,0.921178,0.185057,0.450366,0.262405,0.002641,9.257543,-29.700706,0.117790,0.401718,2.155095,...,False,False,False,True,False,False,False,False,False,False
33,0.947065,0.489558,0.211945,0.154023,0.000373,6.514935,-4.030782,0.064459,0.000000,2.093708,...,False,False,False,False,True,False,False,False,False,False
34,0.957391,0.470118,NaN,0.144173,0.001414,37.380153,-2.235470,0.082556,0.000000,NaN,...,False,False,False,False,True,False,False,False,False,False
35,1.037233,0.334039,0.356201,0.144315,0.000705,23.487063,-6.124677,0.087307,0.095663,2.095061,...,False,False,False,False,False,True,False,False,False,False
36,0.990237,0.329642,0.204785,0.144431,0.001395,62.006711,-9.765353,0.096618,0.000000,2.079029,...,False,False,False,False,False,True,False,False,False,False
37,0.952037,0.390579,0.260391,0.180400,0.000514,119.851561,-4.693455,0.079695,0.000000,2.005776,...,False,False,False,False,False,False,True,False,False,False
38,1.015734,0.448572,NaN,0.219996,0.000498,12.694281,-19.976191,0.090469,0.019501,NaN,...,False,False,False,False,False,False,False,True,False,False
39,1.041212,0.434557,0.487288,0.194882,0.001598,56.670787,-9.832489,0.088595,0.046286,2.076314,...,False,False,False,False,False,False,False,True,False,False
40,0.954658,0.396614,0.117688,0.153239,0.001937,44.360410,-45.627723,0.090263,0.215856,1.985566,...,False,False,False,False,False,False,False,False,True,False
41,0.955115,0.313667,NaN,0.472375,0.001739,56.849345,-3.664309,0.092088,0.000000,NaN,...,False,False,False,False,False,False,False,False,False,True
42,0.923343,0.462532,0.024631,0.157901,0.001825,49.876910,-4.169357,0.091278,0.080257,1.978126,...,False,False,False,False,False,False,False,False,False,True

# Cross-validation

In [41]:
# configure the cross-validation procedure
#create loocv procedure
cv = LeaveOneOut()
cv_outer = cv.split(X_new2)

In [42]:
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV

# Logistic regression

In [43]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [44]:
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

# For Leave-One-Day-Out Cross-Validation

In [45]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(extra_AU)>1:

        subrecord = extra_AU['subrecord']

        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord)+1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.703407412616921, Precision: 0.5555555555555556, Recall: 0.7627118644067796, F1-score: 0.6428571428571428, Accuracy: 0.7214484679665738, Balanced Accuracy: 0.7319783388423939

# Nested Cross-Validation LR + SMOTE

In [46]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [47]:
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [48]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
    
        subrecord = extra_AU['subrecord']

        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas


        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)

acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7506857022294114, Precision: 0.6198347107438017, Recall: 0.635593220338983, F1-score: 0.6276150627615062, Accuracy: 0.7520891364902507, Balanced Accuracy: 0.7223609255221886

# Nested Cross-Validation k-NN

In [77]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier

In [78]:
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [79]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    extra_AU
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8932414375131865, Precision: 0.9772727272727273, Recall: 0.3644067796610169, F1-score: 0.5308641975308642, Accuracy: 0.7883008356545961, Balanced Accuracy: 0.6801287010338279

# Nested Cross-Validation k-NN + SMOTE

In [52]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier

In [53]:
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')




# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [54]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values



            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8593079682115479, Precision: 0.7865168539325843, Recall: 0.5932203389830508, F1-score: 0.6763285024154589, Accuracy: 0.8133704735376045, Balanced Accuracy: 0.757191082354596

# Nested Cross-Validation SVM

In [55]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np




# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step,
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

In [56]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.6887615162810324, Precision: 0.4772727272727273, Recall: 0.3559322033898305, F1-score: 0.4077669902912622, Accuracy: 0.6601671309192201, Balanced Accuracy: 0.5825304170476123

# Nested Cross-Validation SVM + SMOTE

In [57]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step,
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

In [58]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.6760672339826992, Precision: 0.576271186440678, Recall: 0.576271186440678, F1-score: 0.576271186440678, Accuracy: 0.7214484679665738, Balanced Accuracy: 0.6844011533863141

# Nested Cross-Validation XGBoost

In [59]:
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)

In [60]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [61]:
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from xgboost import XGBClassifier

In [62]:
from xgboost import XGBClassifier

In [63]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [64]:
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE

param_grid = {
    "xgbsclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbsclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbsclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbsclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbsclassifier__scale_pos_weight": [1, ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
model_params = {
    
    # General parameters
    "xgbclassifier__booster": "gbtree", 
    "xgbclassifier__silent": True, 
    "xgbclassifier__n_jobs": -1, 
    
    # Learning task parameters
    "xgbclassifier__objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "xgbclassifier__eval_metric": "error", 
    "xgbclassifier__seed": seed, 
    
    # Tree Booster parameters
    "xgbclassifier__n_estimators": 500, 
    "xgbclassifier__learning_rate": 0.20, 
    "xgbclassifier__gamma": 1.0, 
    "xgbclassifier__max_depth": 10, 
    "xgbclassifier__subsample": 1.0, 
    "xgbclassifier__colsample_bylevel": 1, 
    "xgbclassifier__colsample_bytree": 1.0, 
    "xgbclassifier__min_child_weight": 5
}
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }


param_grid = {
    "xgbclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbclassifier__scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier#
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, xgb.XGBClassifier(**model_params))
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [65]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(extra_AU)>1:

        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices

            search = RandomizedSearchCV(pipe, cv=cv_inner.split(X_train, y_train), random_state=seed, **search_settings, error_score='raise')

            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)

acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
0
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
1
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
2
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
3
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
4
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
5
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
6
7
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
8
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
9
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
10
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
11
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
12
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
13
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
14
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
15
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
16
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
17
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
18
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
19
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
20
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
21
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
22
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
23
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
24
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
25
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
26
27
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
28
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
29
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
30
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
31
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
32
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
33
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
34
35
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
36

# Nested Cross-Validation with XGBoost and SMOTE

In [66]:
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE

param_grid = {
    "xgbsclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbsclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbsclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbsclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbsclassifier__scale_pos_weight": [1, ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
model_params = {
    
    # General parameters
    "xgbclassifier__booster": "gbtree", 
    "xgbclassifier__silent": True, 
    "xgbclassifier__n_jobs": -1, 
    
    # Learning task parameters
    "xgbclassifier__objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "xgbclassifier__eval_metric": "error", 
    "xgbclassifier__seed": seed, 
    
    # Tree Booster parameters
    "xgbclassifier__n_estimators": 500, 
    "xgbclassifier__learning_rate": 0.20, 
    "xgbclassifier__gamma": 1.0, 
    "xgbclassifier__max_depth": 10, 
    "xgbclassifier__subsample": 1.0, 
    "xgbclassifier__colsample_bylevel": 1, 
    "xgbclassifier__colsample_bytree": 1.0, 
    "xgbclassifier__min_child_weight": 5
}
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }


param_grid = {
    "xgbclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbclassifier__scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier#x
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, xgb.XGBClassifier(**model_params))
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [67]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(extra_AU)>1:

        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices

            search = RandomizedSearchCV(pipe, cv=cv_inner.split(X_train, y_train), random_state=seed, **search_settings, error_score='raise')

            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
0
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
1
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
2
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
3
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
4
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
5
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
6
7
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
8
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
9
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
10
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
11
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
12
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
13
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
14
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
15
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
16
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
17
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
18
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
19
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
20
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
21
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
22
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
23
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
24
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
25
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
26
27
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
28
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
29
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
30
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
31
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
32
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
33
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
34
35
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
36

# Nested Cross-Validation with Random Forest

In [68]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [69]:
param_grid = {
    "model__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "model__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "model__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "model__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "model__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "model__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [70]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

pipe = Pipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('scale', StandardScaler()),
    ('model', model)])

In [71]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices
            search = RandomizedSearchCV(pipe, param_distributions = param_grid, cv=cv_inner.split(X_train, y_train), random_state=seed, scoring='roc_auc', n_jobs=-1)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7641184330824954, Precision: 0.6708860759493671, Recall: 0.4491525423728814, F1-score: 0.5380710659898477, Accuracy: 0.7465181058495822, Balanced Accuracy: 0.6706343624727478

# Nested Cross-Validation with Random Forest + SMOTE

In [72]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
from imblearn.pipeline import make_pipeline

In [73]:
model_params = {
    
    "n_estimators": 1,
    "max_depth": 32,  
    "min_samples_split": 0.1,
    "min_samples_leaf": 0.1,
    "max_features": 1,
    "class_weight": 'balanced'
}

param_grid = {
    "randomforestclassifier__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "randomforestclassifier__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "randomforestclassifier__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "randomforestclassifier__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "randomforestclassifier__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "randomforestclassifier__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [74]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])


# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, RandomForestClassifier(**model_params))

In [75]:
pipe

Pipeline(steps=[('simpleimputer', SimpleImputer()), ('smote', SMOTE()),
                ('randomforestclassifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=32,
                                        max_features=1, min_samples_leaf=0.1,
                                        min_samples_split=0.1,
                                        n_estimators=1))])

In [76]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/ff_cross/ff_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            #fill the Nan values

            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            imp.fit(X_train)
            X_test = imp.transform(X_test)


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices
            search = RandomizedSearchCV(pipe, param_distributions = param_grid, cv=cv_inner.split(X_train, y_train), random_state=seed, scoring='roc_auc', n_jobs=-1)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7468000562627469, Precision: 0.6081081081081081, Recall: 0.3813559322033898, F1-score: 0.46875, Accuracy: 0.7158774373259053, Balanced Accuracy: 0.6305119909979604