In [83]:
import pandas as pd
import numpy as np
from os import listdir

In [84]:
import sklearn

In [85]:
# Ignore warnings
import warnings; warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline



from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
from sklearn import svm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

#from skbold.preproc.confounds import ConfoundRegressor
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn import preprocessing
    
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score,confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.impute import SimpleImputer



# Import libraries
import os
import numpy as np
import pandas as pd


from sklearn.feature_selection import RFE
from sklearn.metrics import balanced_accuracy_score

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from sklearn.model_selection import cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import make_scorer
from sklearn.metrics import \
    confusion_matrix, \
    accuracy_score, \
    matthews_corrcoef, \
    precision_score, \
    recall_score, \
    f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import LeaveOneOut


import pymrmr

# Set the random generator seed
seed = 42

# Matplotlib settings
plt.style.use("classic")

# Seaborn settings
sns.set()
sns.set(font_scale=1.0)
sns.set_style({"font.family":"serif", "font.serif":["Times New Roman"]})

# Show seaborn settings
sns.axes_style()

{'axes.facecolor': '#EAEAF2',
 'axes.edgecolor': 'white',
 'axes.grid': True,
 'axes.axisbelow': True,
 'axes.labelcolor': '.15',
 'figure.facecolor': 'white',
 'grid.color': 'white',
 'grid.linestyle': '-',
 'text.color': '.15',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'lines.solid_capstyle': <CapStyle.round: 'round'>,
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'font.family': ['serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'xtick.bottom': False,
 'xtick.top': False,
 'ytick.left': False,
 'ytick.right': False,
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True}

In [86]:
# ------------------------------
# Define the classifier settings
# ------------------------------

model_params = {
    
    # General parameters
    "booster": "gbtree", 
    "silent": True, 
    "n_jobs": -1, 
    
    # Learning task parameters
    "objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "eval_metric": "error", 
    "seed": seed, 
    
    # Tree Booster parameters
    "n_estimators": 500, 
    "learning_rate": 0.20, 
    "gamma": 1.0, 
    "max_depth": 10, 
    "subsample": 1.0, 
    "colsample_bylevel": 1, 
    "colsample_bytree": 1.0, 
    "min_child_weight": 5
}

# ------------------------------------------
# Define the hyper-parameter tuning settings
# ------------------------------------------

param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [1, 3, 5, 6, 7, 9]  # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
#scale_pos_weight = total_negative_examples / total_positive_examples
}

search_settings = {
    "param_distributions": param_grid, 
    "scoring": "balanced_accuracy",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
}

In [87]:
# ---------------------------------
# Define the classification metrics
# ---------------------------------

def sensitivity_score(y_true, y_pred):
    return recall_score(y_true, y_pred)

def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)

In [88]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import os

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

# For models
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# For evaluation
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score
from sklearn.preprocessing import OneHotEncoder

In [89]:
dataset = pd.read_csv('prob_eye_features.csv')

In [90]:
del dataset['Unnamed: 0']
del dataset['index']

In [91]:
del dataset['timestamp_start']
del dataset['timestamp_end']

In [92]:
dataset

,patient,record,diagnosis,lefteye_mid_Absolute energy,lefteye_mid_Area under the curve,lefteye_mid_Autocorrelation,lefteye_mid_Average power,lefteye_mid_Centroid,lefteye_mid_ECDF Percentile Count_0,lefteye_mid_ECDF Percentile Count_1,...,smiling_eve_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1,smiling_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1,smiling_eve_SP_Summaries_welch_rect_centroid,smiling_eve_FC_LocalSimple_mean3_stderr,lefteye_eve_app_ent,righteye_eve_app_ent,smiling_eve_app_ent,lefteye_eve_rsd,righteye_eve_rsd,smiling_eve_rsd
0,P08,0,0,159.815202,1.754196,1.0,77.580195,1.084595,41.0,165.0,...,0.142857,0.775510,0.133456,0.731912,1.109208,1.273205,0.903131,31.248418,34.398221,161.223253
1,P08,1,0,2994.914034,32.251584,3.0,77.608552,19.458168,772.0,3088.0,...,0.291667,0.145833,0.527689,0.941336,0.950498,1.165241,0.939005,30.496000,44.894973,156.000227
2,P10,2,1,934.998350,9.668103,1.0,89.817325,5.051412,208.0,833.0,...,0.333333,0.166667,0.285320,0.769152,0.649302,1.101207,0.211475,29.254278,47.014199,308.947966
3,P10,3,0,796.366897,9.202542,2.0,62.119103,6.491560,256.0,1026.0,...,0.163265,0.877551,0.061359,0.511171,0.966557,1.240839,0.324205,44.624507,58.077534,246.734071
4,P12,4,1,47.911319,0.690634,1.0,31.940879,0.887026,30.0,120.0,...,0.790698,0.860465,0.662680,0.998367,0.938760,0.973181,0.404289,44.966219,47.288089,233.670461
5,P12,5,1,56.150528,0.624009,1.0,66.845867,0.465824,17.0,68.0,...,0.857143,0.738095,0.490874,0.878668,0.843667,0.936040,0.614584,29.475036,30.276012,185.631759
6,P13,6,0,3223.834261,32.655868,1.0,95.238826,16.860041,677.0,2708.0,...,0.244898,0.857143,0.131155,0.653258,0.362176,0.705464,0.296124,16.339966,20.764821,292.398782
7,P13,7,0,239.778514,2.417260,1.0,96.296592,1.257414,50.0,200.0,...,0.853659,0.853659,0.392699,0.868253,0.255308,0.380562,0.414977,19.979949,15.211448,184.687507
8,P14,8,0,125.931396,1.407684,3.0,66.279682,1.000918,38.0,152.0,...,0.306122,0.877551,0.319068,0.859923,1.101882,0.904987,1.084499,42.789612,34.070540,137.389819
9,P15,9,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.326531,0.877551,0.161068,0.711376,1.208809,1.456139,0.330840,46.953204,49.437349,286.834391
10,P15,10,1,148.221916,2.365285,3.0,22.222176,2.763661,133.0,534.0,...,0.326531,0.877551,0.122718,0.585557,1.364536,1.475528,0.383828,59.648103,65.863117,233.048602
11,P16,11,0,5588.553399,62.150725,50.0,68.144780,37.461605,1640.0,6561.0,...,0.320000,0.780000,0.088204,0.595745,0.762125,0.835477,0.332558,30.701462,24.094999,297.095150
12,P16,12,0,5845.796135,62.812529,4.0,78.763085,37.075180,1484.0,5938.0,...,0.380000,0.580000,0.130772,0.669807,0.852456,0.884501,0.405318,29.720287,24.592209,274.993422
13,P17,13,1,615.099315,6.301963,1.0,92.357254,3.364583,133.0,533.0,...,0.270833,0.125000,0.273049,0.844975,1.048595,1.188359,1.156473,37.329703,55.659185,111.339240
14,P18,14,1,1131.708123,13.521887,21.0,49.484395,10.776009,457.0,1830.0,...,0.122449,0.122449,0.072097,0.669549,1.096102,1.123428,0.781109,75.955618,82.369563,141.626699
15,P18,15,1,1050.551582,12.762046,5.0,54.659291,9.218917,384.0,1538.0,...,0.877551,0.306122,0.111981,0.759323,1.076727,1.201481,1.019533,74.765557,69.809124,135.728765
16,P19,16,1,785.233486,8.650786,8.0,66.376457,6.173040,236.0,947.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
17,P19,17,1,166.931668,2.160410,8.0,19.569949,2.463278,170.0,683.0,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
18,P20,18,0,619.511367,6.606506,4.0,79.526491,4.121953,156.0,624.0,...,0.520833,0.125000,0.134990,0.616732,0.964032,1.175585,0.672123,35.691050,50.930992,166.231026
19,P20,19,0,458.245990,5.044652,5.0,66.995028,3.092467,137.0,548.0,...,0.787234,0.872340,0.362019,0.860334,0.934679,1.322405,0.460527,35.978999,60.945181,200.804377
20,P21,20,0,956.519423,11.600969,11.0,48.505042,8.780004,394.0,1578.0,...,0.244898,0.877551,0.055223,0.556824,0.771458,0.770246,0.250172,39.932150,61.830751,294.667954
21,P21,21,1,318.133891,3.996044,24.0,37.560082,3.150870,169.0,678.0,...,0.551020,0.551020,0.064427,0.557014,0.898230,1.002707,0.295885,37.067773,42.618275,264.953752
22,P23,22,0,1557.863100,16.062215,2.0,91.746943,8.165785,339.0,1359.0,...,0.571429,0.469388,0.061359,0.565418,0.538977,1.348448,0.378350,17.078093,33.430416,223.986300
23,P23,23,0,1809.680737,19.678477,2.0,80.897664,10.879167,447.0,1790.0,...,0.122449,0.122449,0.078233,0.665164,1.149385,1.341509,0.559583,31.562084,50.388901,184.683560
24,P24,24,1,6079.611278,64.336221,2.0,81.496130,35.306750,1492.0,5968.0,...,0.300000,0.120000,0.184845,0.776954,0.954803,1.086713,1.102212,33.204104,29.921619,131.767550
25,P24,25,1,2421.853802,25.353976,2.0,82.572581,15.026373,586.0,2347.0,...,0.142857,0.836735,0.225495,0.793708,1.062141,1.140507,1.251668,36.384238,33.841252,109.062406
26,P25,26,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
27,P27,27,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN
28,P28,28,0,745.251631,8.498635,2.0,63.860465,5.823042,233.0,934.0,...,0.183673,0.122449,0.070563,0.645212,1.437934,1.404281,0.486347,60.487154,63.429320,210.896877
29,P29,29,0,1311.915711,17.357964,32.0,26.170272,27.139914,1002.0,4011.0,...,0.591837,0.387755,0.099709,0.639630,1.278772,0.937102,0.195279,96.713766,152.161785,299.925891
30,P29,30,0,347.214901,6.649285,12.0,6.970787,32.507195,996.0,3985.0,...,0.346939,0.122449,0.156466,0.652597,1.470113,0.929280,0.130678,99.186103,162.618464,329.444500
31,P30,31,1,3589.945864,40.884938,2.0,62.433841,28.606658,1150.0,4600.0,...,0.244898,0.122449,0.128087,0.734137,1.297072,1.257440,0.419275,57.650990,88.540594,259.259532
32,P30,32,1,2971.336252,33.418946,1.0,63.735226,24.159334,932.0,3730.0,...,0.244898,0.877551,0.115816,0.657115,1.356120,1.263509,0.527882,61.105682,93.442520,231.886791
33,P31,33,0,281.396085,4.774415,47.0,19.858580,4.522784,283.0,1134.0,...,0.122449,0.142857,0.182544,0.755975,1.539875,1.706212,0.466452,65.649002,62.926655,130.854432
34,P31,34,0,254.325297,3.971961,59.0,24.407418,5.202684,208.0,834.0,...,0.297872,0.148936,0.134990,0.643366,1.401121,0.871966,0.177829,66.772768,102.396749,259.917089
35,P33,35,0,1666.263975,18.846772,1.0,67.296606,13.001308,495.0,1981.0,...,0.142857,0.836735,0.191748,0.769503,0.928077,1.161691,0.546959,34.968676,35.347310,199.313122
36,P33,36,0,1725.591886,19.021559,2.0,70.374873,11.630395,490.0,1962.0,...,0.285714,0.857143,0.480136,0.906507,1.275150,1.207110,0.529577,46.807877,39.978393,210.880136
37,P34,37,0,407.595456,5.665456,5.0,36.457554,4.911636,223.0,895.0,...,0.125000,0.187500,0.576777,0.942715,1.257130,1.057423,0.553584,70.298913,100.433819,171.129060
38,P35,38,0,1822.229000,18.909761,1.0,86.938406,10.296536,419.0,1677.0,...,0.551020,0.346939,0.168738,0.743202,0.883756,1.080286,0.252690,31.043004,31.412967,416.442165
39,P35,39,0,2062.923103,21.886699,4.0,80.551468,12.745451,512.0,2049.0,...,0.326531,0.306122,0.208621,0.753538,0.873255,1.082971,0.251051,32.657172,30.336398,373.262006
40,P36,40,0,2774.319378,29.587614,2.0,82.397368,16.603693,673.0,2694.0,...,0.653061,0.428571,0.332874,0.859071,0.985478,1.172057,1.123381,23.449370,28.764549,141.769747
41,P38,41,0,1751.929408,18.344965,1.0,87.596470,9.836362,400.0,1600.0,...,0.265306,0.877551,0.093573,0.703637,1.010465,1.522383,0.350549,29.838800,57.584418,235.288671
42,P38,42,0,618.188985,6.426493,2.0,89.333668,3.561437,138.0,554.0,...,0.437500,0.479167,0.110447,0.611543,0.989792,1.248439,0.214802,45.346983,55.594797,275.951876

In [93]:
flag = 0 
for i in range(0, 43):
    subdata = pd.read_csv('.\dataset\prob_cross\prob_'+str(i)+'_.csv')
    if len(subdata)>1:
        if flag==0:
            subdata_all = subdata.loc[1:].copy()
            flag = 1
        else:
            subdata_all = pd.concat([subdata_all, subdata.loc[1:]])

In [94]:
del subdata_all['Unnamed: 0']
del subdata_all['type_data']
del subdata_all['subrecord']

In [95]:
dataset = pd.concat([dataset, subdata_all])

In [96]:
group = dataset['patient']

In [97]:
group = dataset['patient']
patients_pandas_encoded = pd.get_dummies(group, columns=['patient'], drop_first=False)

In [98]:
dataset

,patient,record,diagnosis,lefteye_mid_Absolute energy,lefteye_mid_Area under the curve,lefteye_mid_Autocorrelation,lefteye_mid_Average power,lefteye_mid_Centroid,lefteye_mid_ECDF Percentile Count_0,lefteye_mid_ECDF Percentile Count_1,...,smiling_eve_SP_Summaries_welch_rect_centroid,smiling_eve_FC_LocalSimple_mean3_stderr,lefteye_eve_app_ent,righteye_eve_app_ent,smiling_eve_app_ent,lefteye_eve_rsd,righteye_eve_rsd,smiling_eve_rsd,timestamp_start,timestamp_end
0,P08,0,0,159.815202,1.754196,1.0,77.580195,1.084595,41.0,165.0,...,0.133456,0.731912,1.109208,1.273205,0.903131,31.248418,34.398221,161.223253,NaN,NaN
1,P08,1,0,2994.914034,32.251584,3.0,77.608552,19.458168,772.0,3088.0,...,0.527689,0.941336,0.950498,1.165241,0.939005,30.496000,44.894973,156.000227,NaN,NaN
2,P10,2,1,934.998350,9.668103,1.0,89.817325,5.051412,208.0,833.0,...,0.285320,0.769152,0.649302,1.101207,0.211475,29.254278,47.014199,308.947966,NaN,NaN
3,P10,3,0,796.366897,9.202542,2.0,62.119103,6.491560,256.0,1026.0,...,0.061359,0.511171,0.966557,1.240839,0.324205,44.624507,58.077534,246.734071,NaN,NaN
4,P12,4,1,47.911319,0.690634,1.0,31.940879,0.887026,30.0,120.0,...,0.662680,0.998367,0.938760,0.973181,0.404289,44.966219,47.288089,233.670461,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,P38,42,0,8.792124,0.097050,1.0,73.267701,0.068194,2.0,10.0,...,0.478602,0.868234,0.871396,1.043298,0.234889,21.579730,49.996630,279.250456,1.661206e+09,1.661983e+09
3,P38,42,0,6.533883,0.079334,1.0,54.449029,0.051634,2.0,10.0,...,0.122718,0.643346,0.774804,0.765338,0.613899,26.098807,32.764375,99.911777,1.661206e+09,1.661983e+09
4,P38,42,0,8.792124,0.097050,1.0,73.267701,0.068194,2.0,10.0,...,0.165670,0.669523,0.868369,0.958283,0.262414,20.604022,40.146809,265.416473,1.661206e+09,1.661983e+09
5,P38,42,0,12.789357,0.119004,1.0,106.577974,0.059964,2.0,10.0,...,0.159534,0.805297,0.957112,1.011946,0.267087,53.172706,61.109972,232.519461,1.661206e+09,1.661983e+09
6,P38,42,0,167.186108,1.826052,5.0,77.760981,1.039197,43.0,172.0,...,0.165670,0.669523,0.868369,0.958283,0.262414,20.604022,40.146809,265.416473,1.661206e+09,1.661983e+09

In [99]:
del dataset['patient']

In [100]:
dataset = dataset.fillna(dataset.mean())

In [101]:
y = dataset['diagnosis']

In [102]:
records  = dataset['record']

In [103]:
del dataset['record']

In [104]:
X = dataset.copy()

In [105]:
dataset

,diagnosis,lefteye_mid_Absolute energy,lefteye_mid_Area under the curve,lefteye_mid_Autocorrelation,lefteye_mid_Average power,lefteye_mid_Centroid,lefteye_mid_ECDF Percentile Count_0,lefteye_mid_ECDF Percentile Count_1,lefteye_mid_ECDF Percentile_0,lefteye_mid_ECDF Percentile_1,...,smiling_eve_SP_Summaries_welch_rect_centroid,smiling_eve_FC_LocalSimple_mean3_stderr,lefteye_eve_app_ent,righteye_eve_app_ent,smiling_eve_app_ent,lefteye_eve_rsd,righteye_eve_rsd,smiling_eve_rsd,timestamp_start,timestamp_end
0,0,159.815202,1.754196,1.0,77.580195,1.084595,41.0,165.0,0.755065,0.988791,...,0.133456,0.731912,1.109208,1.273205,0.903131,31.248418,34.398221,161.223253,1.659630e+09,1.661055e+09
1,0,2994.914034,32.251584,3.0,77.608552,19.458168,772.0,3088.0,0.733824,0.991869,...,0.527689,0.941336,0.950498,1.165241,0.939005,30.496000,44.894973,156.000227,1.659630e+09,1.661055e+09
2,1,934.998350,9.668103,1.0,89.817325,5.051412,208.0,833.0,0.951033,0.997039,...,0.285320,0.769152,0.649302,1.101207,0.211475,29.254278,47.014199,308.947966,1.659630e+09,1.661055e+09
3,0,796.366897,9.202542,2.0,62.119103,6.491560,256.0,1026.0,0.326910,0.987720,...,0.061359,0.511171,0.966557,1.240839,0.324205,44.624507,58.077534,246.734071,1.659630e+09,1.661055e+09
4,1,47.911319,0.690634,1.0,31.940879,0.887026,30.0,120.0,0.146387,0.768462,...,0.662680,0.998367,0.938760,0.973181,0.404289,44.966219,47.288089,233.670461,1.659630e+09,1.661055e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,0,8.792124,0.097050,1.0,73.267701,0.068194,2.0,10.0,0.486996,0.950315,...,0.478602,0.868234,0.871396,1.043298,0.234889,21.579730,49.996630,279.250456,1.661206e+09,1.661983e+09
3,0,6.533883,0.079334,1.0,54.449029,0.051634,2.0,10.0,0.279111,0.899735,...,0.122718,0.643346,0.774804,0.765338,0.613899,26.098807,32.764375,99.911777,1.661206e+09,1.661983e+09
4,0,8.792124,0.097050,1.0,73.267701,0.068194,2.0,10.0,0.486996,0.950315,...,0.165670,0.669523,0.868369,0.958283,0.262414,20.604022,40.146809,265.416473,1.661206e+09,1.661983e+09
5,0,12.789357,0.119004,1.0,106.577974,0.059964,2.0,10.0,0.986606,0.994761,...,0.159534,0.805297,0.957112,1.011946,0.267087,53.172706,61.109972,232.519461,1.661206e+09,1.661983e+09
6,0,167.186108,1.826052,5.0,77.760981,1.039197,43.0,172.0,0.763449,0.987175,...,0.165670,0.669523,0.868369,0.958283,0.262414,20.604022,40.146809,265.416473,1.661206e+09,1.661983e+09

# Feature selection 2

In [106]:
from pyHSICLasso import HSICLasso

In [107]:
del X['diagnosis']

In [108]:
#Initialize HSICLasso
hsic_lasso = HSICLasso()

# Load data
hsic_lasso.input(np.array(X), np.array(y), featname=X.columns)

True

In [109]:
hsic_lasso.classification(50)

Block HSIC Lasso B = 20.
M set to 3.
Using Gaussian kernel for the features, Delta kernel for the outcomes.

True

In [110]:
valuable_features_list = hsic_lasso.get_features()

In [111]:
col =  valuable_features_list

In [114]:
col = ['righteye_eve_Wavelet variance_2.78Hz',
 'smiling_mor_MFCC_6',
 'lefteye_mid_Wavelet variance_25.0Hz',
 'lefteye_mid_Wavelet variance_8.33Hz',
 'smiling_eve_Mean absolute diff',
 'lefteye_mor_MFCC_11',
 'lefteye_mor_Wavelet energy_8.33Hz',
 'smiling_eve_Interquartile range',
 'smiling_mid_ECDF Percentile_1',
 'righteye_aft_MFCC_10',
 'righteye_eve_Wavelet variance_5.0Hz',
 'smiling_mid_Wavelet variance_8.33Hz',
 'lefteye_mid_Zero crossing rate',
 'smiling_eve_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1',
 'righteye_mor_MFCC_10',
 'lefteye_aft_MFCC_4',
 'righteye_aft_PD_PeriodicityWang_th0_01',
 'smiling_eve_Wavelet variance_8.33Hz',
 'lefteye_aft_FC_LocalSimple_mean1_tauresrat',
 'lefteye_mid_rsd',
 'smiling_aft_Mean absolute diff',
 'righteye_aft_Wavelet variance_2.78Hz',
 'smiling_aft_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1',
 'righteye_aft_MFCC_8',
 'smiling_aft_Entropy',
 'smiling_mor_Centroid',
 'righteye_aft_MFCC_1',
 'lefteye_mor_Mean diff',
 'smiling_mid_CO_FirstMin_ac',
 'smiling_mid_Zero crossing rate',
 'smiling_eve_Wavelet variance_12.5Hz',
 'smiling_mor_Autocorrelation',
 'lefteye_eve_Wavelet variance_8.33Hz',
 'smiling_eve_ECDF Percentile_1',
 'lefteye_mor_Wavelet standard deviation_8.33Hz',
 'righteye_mid_Wavelet energy_3.12Hz',
 'smiling_mid_Interquartile range',
 'lefteye_aft_Variance',
 'smiling_aft_Wavelet entropy',
 'lefteye_mid_Wavelet variance_5.0Hz',
 'righteye_eve_Power bandwidth',
 'smiling_eve_Average power',
 'righteye_eve_MFCC_8',
 'smiling_mid_SB_BinaryStats_diff_longstretch0',
 'lefteye_aft_Standard deviation',
 'lefteye_mid_DN_OutlierInclude_n_001_mdrmd',
 'righteye_mor_Variance',
 'lefteye_mid_Interquartile range',
 'smiling_aft_DN_HistogramMode_5',
 'righteye_aft_MD_hrv_classic_pnn40']

# Read the data again to import data with NaN values

In [115]:
dataset = pd.read_csv('prob_eye_features.csv')
del dataset['Unnamed: 0']
del dataset['index']
group = dataset['patient']
groups = group
del dataset['patient']
y = dataset['diagnosis']
del dataset['diagnosis']
records  = dataset['record']
del dataset['record']
X = dataset.copy()

In [116]:
patients_pandas_encoded = pd.get_dummies(group, columns=['patient'], drop_first=False)
patients_pandas_encoded

,P08,P10,P12,P13,P14,P15,P16,P17,P18,P19,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [117]:
X_new = X[col]

In [118]:
patients_pandas_encoded

,P08,P10,P12,P13,P14,P15,P16,P17,P18,P19,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [119]:
X_new2 = pd.concat([X_new, patients_pandas_encoded], axis=1)

In [120]:
X_new2

,righteye_eve_Wavelet variance_2.78Hz,smiling_mor_MFCC_6,lefteye_mid_Wavelet variance_25.0Hz,lefteye_mid_Wavelet variance_8.33Hz,smiling_eve_Mean absolute diff,lefteye_mor_MFCC_11,lefteye_mor_Wavelet energy_8.33Hz,smiling_eve_Interquartile range,smiling_mid_ECDF Percentile_1,righteye_aft_MFCC_10,...,P27,P28,P29,P30,P31,P33,P34,P35,P36,P38
0,0.180836,17.397419,0.037474,0.091848,0.045827,76.296057,0.270495,0.042540,0.108066,51.392610,...,False,False,False,False,False,False,False,False,False,False
1,0.307664,24.720626,0.039164,0.092656,0.049046,117.519711,0.253023,0.045286,0.198921,133.410548,...,False,False,False,False,False,False,False,False,False,False
2,0.311214,NaN,0.023752,0.047104,0.014013,NaN,NaN,0.009503,0.067954,51.854271,...,False,False,False,False,False,False,False,False,False,False
3,0.249249,NaN,0.053234,0.118933,0.029694,NaN,NaN,0.019399,0.052268,25.703759,...,False,False,False,False,False,False,False,False,False,False
4,0.460429,128.715319,0.085218,0.094118,0.052096,175.546101,0.297566,0.018578,0.686507,128.591013,...,False,False,False,False,False,False,False,False,False,False
5,0.181255,99.340222,0.082379,0.169605,0.077577,128.350499,0.356250,0.054460,0.137512,128.356761,...,False,False,False,False,False,False,False,False,False,False
6,0.054660,NaN,0.017654,0.021409,0.019808,NaN,NaN,0.012580,0.026149,74.106212,...,False,False,False,False,False,False,False,False,False,False
7,0.219882,NaN,0.015859,0.047571,0.020791,NaN,NaN,0.015917,0.011907,NaN,...,False,False,False,False,False,False,False,False,False,False
8,0.271935,39.998555,0.044505,0.257689,0.105646,51.359312,0.320533,0.144817,0.017575,82.457134,...,False,False,False,False,False,False,False,False,False,False
9,0.202201,-5.299011,NaN,NaN,0.034528,119.190389,0.246350,0.012580,NaN,72.203781,...,False,False,False,False,False,False,False,False,False,False
10,0.365694,119.706828,0.047495,0.143782,0.040068,166.660381,0.272589,0.018247,0.016065,114.960057,...,False,False,False,False,False,False,False,False,False,False
11,0.121418,NaN,0.034900,0.084860,0.025048,NaN,NaN,0.009580,0.017575,22.905229,...,False,False,False,False,False,False,False,False,False,False
12,0.137669,78.891436,0.031097,0.083777,0.026250,114.970800,0.297345,0.011491,0.026149,111.026030,...,False,False,False,False,False,False,False,False,False,False
13,0.217498,-43.651115,0.022801,0.027965,0.127031,53.217873,0.262531,0.281669,0.410341,91.150345,...,False,False,False,False,False,False,False,False,False,False
14,0.440472,68.734447,0.044829,0.108140,0.061004,87.521322,0.328685,0.078965,0.396167,103.135622,...,False,False,False,False,False,False,False,False,False,False
15,0.368874,80.471102,0.049157,0.109257,0.098269,144.939400,0.348926,0.172771,0.327356,111.096560,...,False,False,False,False,False,False,False,False,False,False
16,NaN,76.095343,0.059671,0.106227,NaN,145.327108,0.280099,NaN,0.142290,162.514099,...,False,False,False,False,False,False,False,False,False,False
17,NaN,82.725406,0.051990,0.111598,NaN,163.972395,0.225708,NaN,0.055681,100.682231,...,False,False,False,False,False,False,False,False,False,False
18,0.197373,47.971298,0.037159,0.079879,0.060728,-25.376984,0.316812,0.103836,0.142290,156.452215,...,False,False,False,False,False,False,False,False,False,False
19,0.212070,38.924262,0.062771,0.109687,0.044046,82.238172,0.278752,0.024012,0.137512,83.266163,...,False,False,False,False,False,False,False,False,False,False
20,0.162348,21.790730,0.047697,0.111262,0.027728,50.705250,0.248074,0.007249,0.469853,117.985672,...,False,False,False,False,False,False,False,False,False,False
21,0.291396,8.378444,0.039347,0.091062,0.033259,82.906716,0.330553,0.011491,0.539508,154.550124,...,False,False,False,False,False,False,False,False,False,False
22,0.163229,-16.589053,0.011690,0.023662,0.029366,49.407121,0.174317,0.018357,0.052268,122.371774,...,False,False,False,False,False,False,False,False,False,False
23,0.214289,31.974531,0.019863,0.043794,0.039857,83.098954,0.274333,0.055953,0.083873,77.367349,...,False,False,False,False,False,False,False,False,False,False
24,0.187044,NaN,0.037601,0.081135,0.069890,NaN,NaN,0.167319,0.052268,111.768017,...,False,False,False,False,False,False,False,False,False,False
25,0.247851,173.214888,0.049334,0.108518,0.071278,98.470460,0.330915,0.198646,0.031306,58.411041,...,False,False,False,False,False,False,False,False,False,False
26,NaN,19.211217,NaN,NaN,NaN,66.105859,0.296907,NaN,NaN,81.972622,...,False,False,False,False,False,False,False,False,False,False
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
28,0.298503,-143.888212,0.067502,0.101079,0.042436,-147.194756,0.488209,0.018357,0.032083,60.586082,...,False,True,False,False,False,False,False,False,False,False
29,0.252951,-31.463276,0.051440,0.100833,0.014843,27.346987,0.276192,0.010810,0.029784,72.632841,...,False,False,True,False,False,False,False,False,False,False
30,0.129735,-53.781408,0.018507,0.050492,0.011006,79.129345,0.316938,0.010311,0.031306,128.236362,...,False,False,True,False,False,False,False,False,False,False
31,0.434150,-19.809836,0.068983,0.139053,0.038667,141.873166,0.406603,0.015667,0.065936,92.966748,...,False,False,False,True,False,False,False,False,False,False
32,0.421458,19.726657,0.070088,0.136866,0.044120,67.762916,0.364535,0.020880,0.065936,49.136993,...,False,False,False,True,False,False,False,False,False,False
33,0.090810,24.087913,0.022291,0.056606,0.010136,50.413499,0.252506,0.010084,0.065936,100.045698,...,False,False,False,False,True,False,False,False,False,False
34,0.210986,71.138900,0.027237,0.058060,0.018299,101.453529,0.344803,0.009805,0.105115,NaN,...,False,False,False,False,True,False,False,False,False,False
35,0.147239,NaN,0.058943,0.099949,0.034116,NaN,NaN,0.019899,0.046645,75.199452,...,False,False,False,False,False,True,False,False,False,False
36,0.131687,NaN,0.053804,0.093907,0.036928,NaN,NaN,0.018376,0.055681,67.330289,...,False,False,False,False,False,True,False,False,False,False
37,0.412457,1.549149,0.050452,0.117235,0.026363,5.138031,0.291136,0.016732,0.083873,-6.350867,...,False,False,False,False,False,False,True,False,False,False
38,0.179651,NaN,0.033794,0.059639,0.010141,NaN,NaN,0.004003,0.016065,92.510040,...,False,False,False,False,False,False,False,True,False,False
39,0.134221,NaN,0.036334,0.066259,0.018250,NaN,NaN,0.005432,0.016065,18.123916,...,False,False,False,False,False,False,False,True,False,False
40,0.156082,28.873431,0.028934,0.061750,0.065238,39.785824,0.287944,0.084464,0.128848,72.876851,...,False,False,False,False,False,False,False,False,True,False
41,0.245249,NaN,0.022880,0.042605,0.030144,NaN,NaN,0.018078,0.105115,68.636353,...,False,False,False,False,False,False,False,False,False,True
42,0.346024,-42.853728,0.016264,0.039929,0.027772,-12.262319,0.184303,0.009503,0.358736,25.142796,...,False,False,False,False,False,False,False,False,False,True

# Cross-validation

In [121]:
# configure the cross-validation procedure
#create loocv procedure
cv = LeaveOneOut()
cv_outer = cv.split(X_new2)

In [122]:
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV

# Logistic regression

In [123]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [124]:
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

# For Leave-One-Day-Out Cross-Validation

In [125]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)
    
    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8070891061256066, Precision: 0.639344262295082, Recall: 0.6610169491525424, F1-score: 0.65, Accuracy: 0.766016713091922, Balanced Accuracy: 0.7392221675223293

# Nested Cross-Validation LR + SMOTE

In [126]:
from sklearn import linear_model

param_grid = [
    {
        'model__C': np.logspace(0, 4, num=10),
        'model__penalty': ['l1', 'l2'],
        'model__solver': ['liblinear', 'saga']
        
    }]

model = linear_model.LogisticRegression()

In [127]:
# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [128]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8125219776355581, Precision: 0.6608695652173913, Recall: 0.6440677966101694, F1-score: 0.6523605150214592, Accuracy: 0.7743732590529248, Balanced Accuracy: 0.7411210352345453

# Nested Cross-Validation k-NN

In [129]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier

In [130]:
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [131]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8391764540403686, Precision: 0.7204301075268817, Recall: 0.5677966101694916, F1-score: 0.6350710900473934, Accuracy: 0.7855153203342619, Balanced Accuracy: 0.7299563963710529

# Nested Cross-Validation k-NN + SMOTE

In [132]:
param_grid = [
    {
        'model__n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        'model__weights': ['uniform', 'distance'],
        'model__p': [1, 2, 3, 4, 5]
        
    }]


distributions_knn = dict(n_neighbors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], weights = ['uniform', 'distance'], p = [1, 2, 3, 4, 5])

# Create the classifier

In [133]:
from sklearn import neighbors, datasets



model = neighbors.KNeighborsClassifier(n_neighbors=4, weights='uniform')




# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step
    ('model', model)  # Model with probability=True
])

In [134]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0



            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)
    
    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.7234861804627611, Precision: 0.3771626297577855, Recall: 0.923728813559322, F1-score: 0.5356265356265356, Accuracy: 0.4735376044568245, Balanced Accuracy: 0.5884204233771714

# Nested Cross-Validation SVM

In [135]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np




# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('sca', StandardScaler()),  # Preprocessing step,
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])
# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

In [136]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)
    
    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8245129755960335, Precision: 0.6770833333333334, Recall: 0.5508474576271186, F1-score: 0.6074766355140186, Accuracy: 0.766016713091922, Balanced Accuracy: 0.7111083761164638

# Nested Cross-Validation SVM + SMOTE

In [137]:
from sklearn.datasets import make_classification
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
import numpy as np



# Define pipeline with SMOTE
pipe = ImbPipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('over', SMOTE()),
    ('sca', StandardScaler()),  # Preprocessing step,
    ('clf', SVC(kernel='rbf', random_state=100, probability=True))  # Model with probability=True
])

# Define model and parameter grid
param_grid = [
    {
        'clf__kernel': ['linear', 'rbf', 'poly'],
        'clf__gamma': [0.1, 1, 10, 100],
        'clf__C': [0.1, 1, 10, 100, 1000],
        'clf__degree': [0, 1, 2, 3, 4, 5, 6]
        
    
        
    }]

In [138]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    if len(extra_AU)>1:
 
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(1, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # define the model

            # define search
            search = GridSearchCV(pipe, param_grid, scoring='roc_auc', cv=cv_inner, refit=True)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.8129087840213798, Precision: 0.6605504587155964, Recall: 0.6101694915254238, F1-score: 0.6343612334801761, Accuracy: 0.7688022284122563, Balanced Accuracy: 0.7283212602855335

# Nested Cross-Validation XGBoost

In [139]:
ratio_scaler = (len(y) - np.sum(y))/np.sum(y)

In [140]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "estimators": [50, 100, 200],

    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [141]:
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, RandomizedSearchCV
from xgboost import XGBClassifier

In [142]:
from xgboost import XGBClassifier

In [143]:
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [144]:
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE

param_grid = {
    "xgbsclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbsclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbsclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbsclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbsclassifier__scale_pos_weight": [1, ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
model_params = {
    
    # General parameters
    "xgbclassifier__booster": "gbtree", 
    "xgbclassifier__silent": True, 
    "xgbclassifier__n_jobs": -1, 
    
    # Learning task parameters
    "xgbclassifier__objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "xgbclassifier__eval_metric": "error", 
    "xgbclassifier__seed": seed, 
    
    # Tree Booster parameters
    "xgbclassifier__n_estimators": 500, 
    "xgbclassifier__learning_rate": 0.20, 
    "xgbclassifier__gamma": 1.0, 
    "xgbclassifier__max_depth": 10, 
    "xgbclassifier__subsample": 1.0, 
    "xgbclassifier__colsample_bylevel": 1, 
    "xgbclassifier__colsample_bytree": 1.0, 
    "xgbclassifier__min_child_weight": 5
}
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }


param_grid = {
    "xgbclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbclassifier__scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier#
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, xgb.XGBClassifier(**model_params))
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [145]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices

            search = RandomizedSearchCV(pipe, cv=cv_inner.split(X_train, y_train), random_state=seed, **search_settings, error_score='raise')

            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
0
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
1
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
2
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
3
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
4
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
5
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
6
7
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
8
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
9
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
10
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
11
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
12
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
13
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
14
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
15
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
16
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
17
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
18
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
19
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
20
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
21
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
22
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
23
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
24
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
25
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
26
27
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
28
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
29
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
30
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
31
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
32
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
33
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
34
35
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
36

# Nested Cross-Validation with XGBoost and SMOTE

In [146]:
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE

param_grid = {
    "xgbsclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbsclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbsclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbsclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbsclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbsclassifier__scale_pos_weight": [1, ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
model_params = {
    
    # General parameters
    "xgbclassifier__booster": "gbtree", 
    "xgbclassifier__silent": True, 
    "xgbclassifier__n_jobs": -1, 
    
    # Learning task parameters
    "xgbclassifier__objective": "binary:logistic",  # https://xgboost.readthedocs.io/en/latest/parameter.html
    "xgbclassifier__eval_metric": "error", 
    "xgbclassifier__seed": seed, 
    
    # Tree Booster parameters
    "xgbclassifier__n_estimators": 500, 
    "xgbclassifier__learning_rate": 0.20, 
    "xgbclassifier__gamma": 1.0, 
    "xgbclassifier__max_depth": 10, 
    "xgbclassifier__subsample": 1.0, 
    "xgbclassifier__colsample_bylevel": 1, 
    "xgbclassifier__colsample_bytree": 1.0, 
    "xgbclassifier__min_child_weight": 5
}
param_grid = {
    "learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "max_depth": [6, 8, 10, 12, 15],  
    "subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }


param_grid = {
    "xgbclassifier__learning_rate": [0.001, 0.01, 0.1, 0.2, 0.3], 
    "xgbclassifier__gamma": [0, 0.10, 0.15, 0.25, 0.5], 
    "xgbclassifier__max_depth": [6, 8, 10, 12, 15],  
    "xgbclassifier__subsample": [0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bylevel": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__colsample_bytree": [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 
    "xgbclassifier__min_child_weight": [0.5, 1.0, 3.0, 5.0, 7.0, 10.0], 
    "xgbclassifier__scale_pos_weight": [ratio_scaler]
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }
    
search_settings = {
    "param_distributions": param_grid, 
    "scoring": "roc_auc",  # https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    "n_jobs": -1, 
    "n_iter": 500, 
    "verbose": 1
    }

print("Hyper-parameters tuning:")

# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, xgb.XGBClassifier(**model_params))
    
model = xgb.XGBClassifier(**model_params)

Hyper-parameters tuning:

In [147]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0

            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices

            search = RandomizedSearchCV(pipe, cv=cv_inner.split(X_train, y_train), random_state=seed, **search_settings, error_score='raise')

            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}')

Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
0
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
1
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
2
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
3
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
4
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
5
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
6
7
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
8
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
9
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
10
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
11
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
12
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
13
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
14
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
15
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
16
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
17
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
18
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
19
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
20
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
21
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
22
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
23
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
24
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
25
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
26
27
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
28
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
29
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
30
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
31
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
32
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
33
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
34
35
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
Fitting 3 folds for each of 500 candidates, totalling 1500 fits
36

In [148]:
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

AUC: 0.7027568746044025, Precision: 0.5166666666666667, Recall: 0.5254237288135594, F1-score: 0.5210084033613446, Accuracy: 0.6824512534818942, Balanced Accuracy: 0.6423799141993107

# Nested Cross-Validation with Random Forest

In [149]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [150]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

pipe = Pipeline([
    ('imp', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('scale', StandardScaler()),
    ('model', model)])

In [151]:
param_grid = {
    "model__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "model__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "model__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "model__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "model__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "model__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [152]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    
    if len(extra_AU)>1:
        subrecord = extra_AU['subrecord']

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices
            search = RandomizedSearchCV(pipe, param_distributions = param_grid, cv=cv_inner.split(X_train, y_train), random_state=seed, scoring='roc_auc', n_jobs=-1)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.5942576833813912, Precision: 0.38181818181818183, Recall: 0.17796610169491525, F1-score: 0.24277456647398846, Accuracy: 0.6350974930362117, Balanced Accuracy: 0.5184436317603207

# Random Forest with SMOTE

In [153]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
from imblearn.pipeline import make_pipeline

In [154]:
model_params = {
    
    "n_estimators": 1,
    "max_depth": 32,  
    "min_samples_split": 0.1,
    "min_samples_leaf": 0.1,
    "max_features": 1,
    "class_weight": 'balanced'
}

param_grid = {
    "randomforestclassifier__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "randomforestclassifier__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "randomforestclassifier__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "randomforestclassifier__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "randomforestclassifier__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "randomforestclassifier__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [155]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])


# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, RandomForestClassifier(**model_params))

In [156]:
model_params = {
    
    "n_estimators": 1,
    "max_depth": 32,  
    "min_samples_split": 0.1,
    "min_samples_leaf": 0.1,
    "max_features": 1,
    "class_weight": 'balanced'
}

param_grid = {
    "randomforestclassifier__n_estimators": [1, 2, 4, 8, 16, 32, 64, 100, 200], 
    "randomforestclassifier__max_depth": [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],  
    "randomforestclassifier__min_samples_split": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.], 
    "randomforestclassifier__min_samples_leaf": [0.1, 0.2, 0.3, 0.4, 0.5], 
    "randomforestclassifier__max_features": [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
    "randomforestclassifier__class_weight": ['balanced', None] 
        # https://machinelearningmastery.com/xgboost-for-imbalanced-classification/
    #scale_pos_weight = total_negative_examples / total_positive_examples
    }

In [157]:
distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])
model=rf

distributions_rf = dict(n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200], max_depth = np.linspace(1, 32, 32, endpoint=True).astype(int), min_samples_split = np.linspace(0.1, 1.0, 10, endpoint=True), min_samples_leaf = np.linspace(0.1, 0.5, 5, endpoint=True), max_features = list(range(1,100)), class_weight=['balanced'])


# Create the classifier#
over = SMOTE()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

pipe =  make_pipeline(imp, over, RandomForestClassifier(**model_params))

In [158]:
i= 0
# enumerate splits
y_true_all = []
y_pred_all = []
y_pred_proba_all = []
for train_ix, test_ix in cv.split(X_new2):
    # split data
    X_train0 = X_new2.loc[train_ix, :]
    y_train0 = y.loc[train_ix] 
    # configure the cross-validation procedure
    # configure the cross-validation procedure
    
    record = i
    #Read the extra data

    extra_AU = pd.read_csv('./dataset/prob_cross/prob_'+str(i)+'_.csv')
    if len(extra_AU)>1:
        
        subrecord = extra_AU['subrecord']
        type_datas = ['test'] + ['test', 'train']*max(extra_AU['subrecord'])
        extra_AU['type_data'] = type_datas

        type_data = extra_AU['type_data']

        #Create extra dummies files:
        data_dummies_extra = pd.DataFrame(columns=patients_pandas_encoded.columns)

        for subsample in range(0, len(extra_AU)):
            data_dummies_extra.loc[subsample] = [False]*len(patients_pandas_encoded.columns)
        data_dummies_extra[extra_AU['patient'].loc[0]] = True

        extra_AU2 = pd.concat([extra_AU[col], data_dummies_extra, extra_AU['subrecord'], extra_AU['type_data'], extra_AU['diagnosis']], axis=1)

        for sub_record in range(1, max(subrecord) +1):
            extra_AU3 = extra_AU2[extra_AU['subrecord']==sub_record]
            extra_test_AU = extra_AU3[extra_AU3['type_data']=='test']
            y_test = extra_test_AU['diagnosis']
            del extra_test_AU['subrecord']
            del extra_test_AU['type_data']
            del extra_test_AU['diagnosis']
            X_test = extra_test_AU 
            extra_train_AU = extra_AU3[extra_AU3['type_data']=='train']

            #Add extra train values
            if (len(extra_train_AU))>0:
                y_train = pd.concat([y_train0, extra_train_AU['diagnosis']], axis=0)
                del extra_train_AU['subrecord']
                del extra_train_AU['type_data']
                del extra_train_AU['diagnosis']
                X_train = pd.concat([X_train0, extra_train_AU], axis=0)
            else:
                X_train = X_train0
                y_train = y_train0


            cv_inner = StratifiedKFold(n_splits=3, random_state=seed, shuffle=True)
            # Employ the hyper-parameter tuning
            # Get the cross-validation indices
            search = RandomizedSearchCV(pipe, param_distributions = param_grid, cv=cv_inner.split(X_train, y_train), random_state=seed, scoring='roc_auc', n_jobs=-1)
            # execute search
            result = search.fit(X_train, y_train)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            # evaluate model on the hold out dataset
            # Predict on the test data
            y_pred = best_model.predict(X_test)
            y_pred_proba = best_model.predict_proba(X_test)[:, 1]  # Probabilities for AUC

            # Collect predictions and true labels
            y_true_all.extend(y_test)
            y_pred_all.extend(y_pred)
            y_pred_proba_all.extend(y_pred_proba)

    print(i)
    i+=1

# Compute metrics
auc_score = roc_auc_score(y_true_all, y_pred_proba_all)
precision = precision_score(y_true_all, y_pred_all)
recall = recall_score(y_true_all, y_pred_all)
f1 = f1_score(y_true_all, y_pred_all)
acc = accuracy_score(y_true_all, y_pred_all)
balanced_acc = balanced_accuracy_score(y_true_all, y_pred_all)

print(f'AUC: {auc_score}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Accuracy: {acc}, Balanced Accuracy: {balanced_acc}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
AUC: 0.6129650467684085, Precision: 0.48314606741573035, Recall: 0.3644067796610169, F1-score: 0.41545893719806765, Accuracy: 0.6629526462395543, Balanced Accuracy: 0.5867677051832055